### ISSUE TITLE
problem on remember login

### ISSUE THREAD

**Issue by italoc** [benedmunds/CodeIgniter-Ion-Auth#1001]
i have a problem with remember login, the cookie always expire when 'sess_expiration' is exceeded and the users need to be relogged,  i need that user is always remember if i check REMEMBER LOGIN, and is loggeout when close the browser if REMEMBER LOGIN is not checked
i'm using C.I. 3.1.2 and latest version of ion_auth, with older version of C.I. 2.2.4 all work great but not with latest version

this is my setting

`$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'aaw_ci_session';
$config['sess_expiration'] = 2592000;
$config['sess_save_path'] = 'ci_sessions_test';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;`

`$config['remember_users']             = TRUE;               
$config['user_expire']                = 0;                  
$config['user_extend_on_login']       = TRUE;            
$config['track_login_attempts']       = TRUE;          
$config['track_login_ip_address']     = TRUE;           
$config['maximum_login_attempts']     = 3;                
$config['lockout_time']               = 600;            
$config['forgot_password_expiration'] = 0;`

can you help me?

**Comment by avenirer** [comment]
Did you try  ```$config['sess_expiration'] = 0```?

**Comment by italoc** [comment]
yes if i set ` $config['sess_expiration'] = 0` login is never remember every time i need to login

**Comment by avenirer** [comment]
Can you show us the login controller?

**Comment by italoc** [comment]
it's the standard login function, untouched from latest version of ion_auth

`	
public function login()
	{
		$this->data['title'] = $this->lang->line('login_heading');
		//validate form input
		$this->form_validation->set_rules('identity', str_replace(':', '', $this->lang->line('login_identity_label')), 'required');
		$this->form_validation->set_rules('password', str_replace(':', '', $this->lang->line('login_password_label')), 'required');

		if ($this->form_validation->run() == true)
		{
			// check to see if the user is logging in
			// check for "remember me"
			$remember = (bool) $this->input->post('remember');
                        
			if ($this->ion_auth->login($this->input->post('identity'), $this->input->post('password'), $remember))
			{
				//if the login is successful
				//redirect them back to the home page
				$this->session->set_flashdata('message', $this->ion_auth->messages());
				redirect('/', 'refresh');
			}
			else
			{
				// if the login was un-successful
				// redirect them back to the login page
				$this->session->set_flashdata('message', $this->ion_auth->errors());
				redirect('auth/login', 'refresh'); // use redirects instead of loading views for compatibility with MY_Controller libraries
			}
		}
		else
		{
			// the user is not logging in so display the login page
			// set the flash data error message if there is one
			$this->data['message'] = (validation_errors()) ? validation_errors() : $this->session->flashdata('message');

			$this->data['identity'] = array('name' => 'identity',
				'id'    => 'identity',
				'type'  => 'text',
				'value' => $this->form_validation->set_value('identity'),
			);
			$this->data['password'] = array('name' => 'password',
				'id'   => 'password',
				'type' => 'password',
			);
                        
			$this->_render_page('auth/login', $this->data);
		}
	}`

**Comment by avenirer** [comment]
It seems that you need to change this: ```$config['user_expire'] = 0``` because if set to zero, the cookie will last only until the browser is closed.

**Comment by avenirer** [comment]
OK... Let us analyse this again... You want users to be logged in until the browser window is closed. You've set the session expiration to be 2592000 seconds (30 days...) And you're complaining that after 30 days (with the browser opened) the users are logged out and need to login again? Do I understand this correctly?

**Comment by italoc** [comment]
No the correct analysis is the following:

i need that when the user  check "REMEMBER LOGIN", the user is always loggedin (2592000 seconds is a temporary trick) and when the user don't check REMEMBER LOGIN the session expire when browser is closed...

whit C.I. 2.2.4 my configuration works great

**Comment by avenirer** [comment]
Then also set this to 2592000: ```$config['user_expire'] = 2592000```

**Comment by italoc** [comment]
with this setting
`$config['user_expire'] = 2592000;
$config['sess_expiration'] = 2592000;`

the user il always logged in, with or without REMEMBER ME

with this setting

`$config['user_expire'] = 2592000;
$config['sess_expiration'] = 0;`

the user is always logged out when the browsers is closed

**Comment by italoc** [comment]
i have reset the cookie from all my browser and now with this setting
`$config['user_expire'] = 2592000;
$config['sess_expiration'] = 0;`

seems to be ok, but now i have a question, with user_expire = 2592000 means that every month the user need to be logged in? or if the user don't login between 1 month is logged out?

**Comment by avenirer** [comment]
it means that every 30 days from last login he needs to log in again.

**Comment by italoc** [comment]
now after clean all cookie from my browser with this configuration 

`$config['user_expire'] = 0; 
$config['sess_expiration'] = 0;`

seems to work correclty

**Comment by italoc** [comment]
the problem is not solved, today after 1 day, the session was lost and i need to relogin

**Comment by italoc** [comment]
after 1 day (not after 24 hours but the next solar day) the cookie always lost sessione with this
`$config['user_expire'] = 2592000; $config['sess_expiration'] = 0;`

and this:

`$config['user_expire'] = 0; $config['sess_expiration'] = 0;`

congiguration, you know why? there is a way to solve the problem?

**Comment by avenirer** [comment]
so... the cookie still exists after 24 hours?

**Comment by italoc** [comment]
is the cookie exist, but the login was lost when solar day change...

**Comment by avenirer** [comment]
please do try that pull request and verify if it works or not

**Comment by italoc** [comment]
for me the identiy column is the "username" and not the email, i can test your mon in the next few days... but i hope to test in late evening...

**Comment by italoc** [comment]
i'm trying your patch url_decode() does not exits, urldecode() exist

i'm trying and i hope that works

**Comment by italoc** [comment]
your patch don't work, i have tested this configuration on this weekend and the session was lost every 2-4 hours of inactivity not the next solar days, if i have some times i try to debug your library...

**Comment by italoc** [comment]
after some time i hope to have finaly solved the problem, and i find  problem in your autentication system. 

now if you have more devices (desktop, smartphone, tablet) that need to be always logged in it is impossibile witouth a little trick. in ion_auth_model.php in "remember_user" you need to modify 1 line of code

`$salt = $this->salt();`

in 

`$salt = $this->db->get_where($this->tables['users'], array('id' => $id))->first_row()->remember_code;

if ($salt == '') $salt = $this->salt();`

in this way if you login with REMEMBER FUNCTION from difference device you obtain always the same salt and session works great, please if my mod is ok for you update source code

**Comment by avenirer** [comment]
You can't be remembered on more than one device. This would turn into no security at all. I don't think the problem is there. Anyway, this is not my authentication system. I only wanted to help. I am sorry, but it seems I don't have the time to take a deeper look (and to be honest, I never used the "remember me" because I think this doesn't help keeping everything secure).

**Comment by italoc** [comment]
i think that can be an option in configuration file, if the user prefer to be logged out when another do a login from another device

**Comment by benedmunds** [comment]
@italoc Ion Auth doesn't currently support remember me from multiple devices.  I'm not against the idea but it would take another table to store the tokens and relate them back to users.  If you want to submit a PR I'll consider it, but you'll need to figure out a way to do it without breaking backwards compatibility.
