### ISSUE TITLE
Gmail SMTP email_activation and forget password email  not working in ion auth 

### ISSUE THREAD

**Issue by jimit-hothi** [benedmunds/CodeIgniter-Ion-Auth#1003]
Hello,

Gmail SMTP not working in ion auth i can getting this error 

> A PHP Error was encountered
> 
> Severity: Warning
> 
> Message: fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known
> 
> Filename: libraries/Email.php
> 
> Line Number: 2014
> 
> Backtrace:
> 
> File: /opt/lampp/htdocs/Project/application/libraries/Ion_auth.php
> Line: 372
> Function: send
> 
> File: /opt/lampp/htdocs/Project/application/controllers/Auth.php
> Line: 463
> Function: register
> 
> File: /opt/lampp/htdocs/Project/index.php
> Line: 315
> Function: require_once
> A PHP Error was encountered
> 
> Severity: Warning
> 
> Message: fsockopen(): unable to connect to mail.example.com:465 (php_network_getaddresses: getaddrinfo failed: Name or service not known)
> 
> Filename: libraries/Email.php
> 
> Line Number: 2014
> 
> Backtrace:
> 
> File: /opt/lampp/htdocs/Project/application/libraries/Ion_auth.php
> Line: 372
> Function: send
> 
> File: /opt/lampp/htdocs/Project/application/controllers/Auth.php
> Line: 463
> Function: register
> 
> File: /opt/lampp/htdocs/Project/index.php
> Line: 315
> Function: require_once
> 

My Config Below

> $config['use_ci_email'] = TRUE; // Send Email using the builtin CI email class, if false it will return the code and the identity
> $config['email_config'] = array(
>     'mailtype' => 'html',
>     'protocol' => 'smtp',
>     'smtp_host' => 'mail.example.com',
>     'smtp_user' => 'XXXXXX@gmail.com', // actual values different
>     'smtp_pass' => 'XXXXXXXX',
>     'smtp_port' => '465'
> );
> 

> $config['site_title']                 = "Example.com";    
> $config['admin_email']                = "admin@example.com";
> $config['default_group']              = 'members';      
> $config['admin_group']                = 'admin';          
> $config['identity']                   = 'email';          
> $config['min_password_length']        = 8;                 
> $config['max_password_length']        = 20;           
> $config['email_activation']           = TRUE;            
> $config['manual_activation']          = FALSE;     
> $config['remember_users']             = TRUE;     
> $config['user_expire']                = 60;            
> $config['user_extend_on_login']       = FALSE;    
> $config['track_login_attempts']       = TRUE;        
> $config['track_login_ip_address']     = FALSE;    
> $config['maximum_login_attempts']     = 1;        
> $config['lockout_time']               = 60;            
> $config['forgot_password_expiration'] = 0;      

and also email libraries load

what wrong with me ??

i can not figure out error 
please help me 

Thanks

**Comment by avenirer** [comment]
Well... smtp host is mail.example.com?

**Comment by jimit-hothi** [comment]
no bro i used gmail smtp used  and his host used 


ssl://smtp.gmail.com

**Comment by xemuj** [comment]
did you load email library on Auth controller?
