### ISSUE TITLE
If deleting a user fails, the $this->ion_auth->messages() does not contain the error message

### ISSUE THREAD

**Issue by dgvirtual** [benedmunds/CodeIgniter-Ion-Auth#1005]
I have a constraint added to my users table, which prevents deleting a user when there are entries created by that user. It means that deleting users fails from time to time. However, the system fails to catch the error message, and the $this->ion_auth->messages() does not print out anything.

`var_dump($this->ion_auth->messages()); `

produces

`string(0) ""`

There must  be some error in Ion_auth-model.php ...     
I am using the latest version (2) of this file.

**Comment by benedmunds** [comment]
Looks like the code is setup to return FALSE if the user deletion doesnt affect any rows

```

		// if user does not exist in database then it returns FALSE else removes the user from groups
		if ($this->db->affected_rows() <= 0)
		{
		    return FALSE;
		}
```

**Comment by benedmunds** [comment]
@dgvirtual try the hotfix here and tell me if it fixes the problem: https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/1006

**Comment by dgvirtual** [comment]
Hi Ben, thank you a lot. I commented out those five lines of code, but it did not influence the problem. Do I understand the intention behind the code right, when I think, that after a failed delete $this->ion_auth->messages() should contain the contents of $lang['delete_unsuccessful'] string?

**Comment by benedmunds** [comment]
@dgvirtual $this->ion_auth->messages()  wont contain it since it's an error, you'd need to get it from $this->ion_auth->errors()

**Comment by dgvirtual** [comment]
Oh, $this->ion_auth->errors() does print the $lang['delete_unsuccessful'] string. But only with your quickfix in place. So, I think the problem is solved with your patch. Thank you!

**Comment by benedmunds** [comment]
Ok perfect, I'll merge it in then.  Thanks!
