### ISSUE TITLE
Regstering works, login does not.

### ISSUE THREAD

**Issue by dmonizer** [benedmunds/CodeIgniter-Ion-Auth#1007]
Dear sir,

I have traced the "fault" down to:
ion_auth_model.php, hash_password_db() function  where 
$hash_password_db = $query->row(); returns correct hash, but then

if ($this->bcrypt->verify($password,$hash_password_db->password))

returns false due to  hash difference as $password is cryptedg once more with bcrypt.

in config/ion_auth.php i have bcrypt set, as per recommendation:

$config['hash_method']    = 'bcrypt';	// sha1 or bcrypt, bcrypt is STRONGLY recommended
$config['default_rounds'] = 8;		// This does not apply if random_rounds is set to true
$config['random_rounds']  = FALSE;
$config['min_rounds']     = 5;
$config['max_rounds']     = 9;
$config['salt_prefix']    = version_compare(PHP_VERSION, '5.3.7', '<') ? '$2a$' : '$2y$';

Have I misunderstood something or is there some mistake/bug there?

thank you,
Erik

**Comment by benedmunds** [comment]
What php version are you running? and can youverify that you have bcrypt support?

**Comment by dmonizer** [comment]
$ php -v
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )

password_hash('erik', PASSWORD_DEFAULT):
$2y$10$7m4L8NOOTBQtd0WhKYiMcOJ0otN3wQahcsGh4KRSn86BwGC2rw3om 

$options ( [cost] => 11 )
password_hash('erik', PASSWORD_BCRYPT, $options):
 $2y$11$kfl2bXaqaP8ZeG9osHJRpOGtyi9KmoZ5X0J1PECtAmdfnjH2drqUq

**Comment by benedmunds** [comment]
@dmonizer hmm ok good.  Can you expand on what you mean by "returns false due to hash difference as $password is cryptedg once more with bcrypt"

**Comment by benedmunds** [comment]
Also can you echo what you get for $password and $hash_password_db->password before they are passed to $this->bcrypt->verify()

**Comment by dmonizer** [comment]
added log_message's as follows in Ion_auth_model.php:
 public function hash_password_db($id, $password, $use_sha1_override=FALSE) 

	log_message('error', '$password: '.print_r($password,true));
	$hash_password_db = $query->row();
	log_message('error', '$hash_password_db'.print_r($hash_password_db,true));

and in Bcrypt.php,   public function verify($input, $existingHash):

	$hash = crypt($input, $existingHash);
	log_message('error', "ERIK: verify() input: $input existingHash: $existingHash hash: $hash");

Result:

	$password: 12qwerty
	$hash_password_db stdClass Object
	(
	    [password] => $2y$08$0Cts7CtvlpRMHgzi2kOGEOa3jnkKpdgbNLVluGOqaNf0tF75ds5qS
	    [salt] => 
	)

	verify() input: 12qwerty existingHash: $2y$08$0Cts7CtvlpRMHgzi2kOGEOa3jnkKpdgbNLVluGOqaNf0tF75ds5qS hash: $2y$08$0Cts7CtvlpRMHgzi2kOGEOLo/ylNvR/wCZPYGEiNwuUIkhSuiuLrW


and by that "returns false..." i meant something that I just now realized was my error :)

Just in case i registered new user and tried to log in with that as well. 

	ERROR - 2016-12-16 13:19:59 --> verify() input: 12345678 existingHash: $2y$08$eY7OA3MHYinMi2usq6k1SOVVvi0enrjyoDkPUU7/NNMPQLzYtSvJ. hash: $2y$08$eY7OA3MHYinMi2usq6k1SOCtxAaT/LsdZcrkPgqNHLyqUQNQ1wbC6

users table has this currently:
+-----------------+--------------------------------------------------------------+
| email           | password                                                     |
+-----------------+--------------------------------------------------------------+
| admin@admin.com | $2a$07$SeBknntpZror9uyftVopmu61qg0ms8Qv1yV6FG.kQOSM.9QhmTo36 |
| erik@2.ee    | $2y$08$0Cts7CtvlpRMHgzi2kOGEOa3jnkKpdgbNLVluGOqaNf0tF75ds5qS |
| 1@2.ee          | $2y$08$eY7OA3MHYinMi2usq6k1SOVVvi0enrjyoDkPUU7/NNMPQLzYtSvJ. |
+-----------------+--------------------------------------------------------------+

**Comment by benedmunds** [comment]
Add debug code to the verify() method in Bcrypt.php as well: https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/libraries/Bcrypt.php#L39

It looks like maybe something is happening with the salts...

**Comment by dmonizer** [comment]
this was from verify() method: 

	input: 12qwerty 
	existingHash: $2y$08$0Cts7CtvlpRMHgzi2kOGEOa3jnkKpdgbNLVluGOqaNf0tF75ds5qS 
	hash: $2y$08$0Cts7CtvlpRMHgzi2kOGEOLo/ylNvR/wCZPYGEiNwuUIkhSuiuLrW



and just in case, config/ion_auth.php has 
$config['salt_length'] = 22;
$config['store_salt']  = FALSE;

**Comment by benedmunds** [comment]
@dmonizer actually can you post you're entire config/ion_auth.php file? Then hopefully I'll be able to reproduce the test case locally.

**Comment by dmonizer** [comment]
here it is. removed all comments.
formatting is awful here - look here instead: http://pastebin.com/sGt0Rv2M

**Comment by benedmunds** [comment]
What commit hash are you on? Are you using HybridAuth?

**Comment by dmonizer** [comment]
sorry, can you clarify what "commit hash" is? :)

I do have hybridauth installed in the CI from your composer repo - but i have not managed to make it work yet :)

**Comment by benedmunds** [comment]
You'd have the commit hash if you pulled the code directly from Github.  

The version with HybridAuth is pretty old.  I don't have a composer repo for this, do you mean the Spark repo?

Either way, I'd recommend you try using the newest version from https://github.com/benedmunds/CodeIgniter-Ion-Auth/archive/2.zip and see what happens.
