### ISSUE TITLE
Changing new password template after reset password

### ISSUE THREAD

**Issue by pudyasto** [benedmunds/CodeIgniter-Ion-Auth#1008]
Hey sir, I've successfully using reset password and using method forgotten_password_complete.
my question :
how to change new password with some numbers

like :
Your password has been reset to: Yp9p68377WPUFv3xa1oClu

![2016-12-14 1](https://cloud.githubusercontent.com/assets/7855552/21188471/2052acce-c24e-11e6-995c-68ef394300a2.png)

Thanks a lot ...

**Comment by lloricode** [comment]
> how to change new password with some numbers

i dont understand

**Comment by benedmunds** [comment]
You'd need to generate the password yourself and then call update() with it
