### ISSUE TITLE
infoMessage vs Errors?

### ISSUE THREAD

**Issue by blaasvaer** [benedmunds/CodeIgniter-Ion-Auth#1010]
How do I distinguish between info messages and errors in ion auth?

All I can find is id="infoMessage" ... I'd like to differentiate between info and actual errors.

Now in the library I can see that errors are handled, just not clear how this bleeds through to the view ... ?

**Comment by benedmunds** [comment]
Feel free to modify the views as needed to suit your needs. Those are just example meant for you to modify.
