### ISSUE TITLE
Get user ID checking email

### ISSUE THREAD

**Issue by federicovilla** [benedmunds/CodeIgniter-Ion-Auth#1014]
I'm wondering how I could retrieve the already user registered ID checking if the email is already in the Database.
Thanks

**Comment by benedmunds** [comment]
Sorry but I dont understand the question.  Can you elaborate?

**Comment by federicovilla** [comment]
Hi Ben, thanks a lot for feedback an support.
About my question, I mean:
if I use the following code nd providing an ID I get the user data including email
`$user = $this->ion_auth->user()->row();`

Right now I have to check if an email address is registered and, if so, get the user data and ID. Just to avoid to write a custom function.

Using the function check_email() I just get a boolean TRUE or FALSE.

Thanks again for help

**Comment by benedmunds** [comment]
I think I see what you mean.  You can query by the email with:

   $email = 'theUsersEmail@domain.com';
   $user = $this->ion_auth->where('email', $email)->user()->row();

**Comment by federicovilla** [comment]
Thanks for feedback Ben.
I tried that query but got a NULL value. Of course I'm sure about email in users table

**Comment by benedmunds** [comment]
YEa I see the problem, try this instead:

    $email = 'theUsersEmail@domain.com';
    $user = $this->ion_auth->where('email', $email)->users()->row();

**Comment by federicovilla** [comment]
You are the man Ben! It works perfect! Thanks a lot for invaluable help.

**Comment by benedmunds** [comment]
No problem! Glad to help!

**Comment by devbikram** [comment]
`$user = $this->ion_auth->where('email', $email)->user()->row();`

But the query return is wrong.
`SELECT `users`.*, `users`.`id` as `id`, `users`.`id` as `user_id` FROM `users` WHERE `email` = 'admin@admin.com' AND `users`.`id` IS NULL ORDER BY `users`.`id` DESC LIMIT 1`

Why it adds ``AND `users`.`id` IS NULL``
