### ISSUE TITLE
Retrieve group name

### ISSUE THREAD

**Issue by federicovilla** [benedmunds/CodeIgniter-Ion-Auth#1015]
I got in trouble trying to get name and description for a specific group.
Here you are what I am using:

` $group = $this->ion_auth->group($group_id);
  $this->data['group_description'] = $group->description;`

The error I get is:
`Message:  Undefined property: Users::$description`

Thanks for any feedback

**Comment by benedmunds** [comment]
What is in the $group variable/object?

**Comment by benedmunds** [comment]
you can var_dump() it to see

**Comment by federicovilla** [comment]
Hi Ben, thanks a lot for feedback and for your great script.
About var_dump(), even if I pass the group ID I get an object with all the data related to the users in the specified group

**Comment by federicovilla** [comment]
Fixed, I had to use:
`$this->ion_auth->group($group_id)->row();`
