### ISSUE TITLE
Using more then one Reset Password Email/URL

### ISSUE THREAD

**Issue by federicovilla** [benedmunds/CodeIgniter-Ion-Auth#1018]
Hello,
in my web site I have a user registration area and an Admin Area, both have their own login form with Reset password function.
I'd like to send different email template for Users and Admin reset password function with their own correct controller URL in email.
Right now, both get the same email with the reset link pointing to the user controller.
It seems that the forgotten password method use the same email template and URL
`$forgotten = $this->ion_auth->forgotten_password($identity->{$this->config->item('identity', 'ion_auth')});` 

Thanks a lot for any help

**Comment by benedmunds** [comment]
Hey,

Feel free to modify the controller and views to suit your needs.  The ones included here are just examples to get you started using the library.
