### ISSUE TITLE
Auth.php | Trying to get property of non-object

### ISSUE THREAD

**Issue by phuze** [benedmunds/CodeIgniter-Ion-Auth#1019]
I noticed while logging out, that an error would on occasion very quickly appear. Its virtually unnoticeable on my desktop computer, but easily seen using a mobile phone (just do to a slower connection). As such, I was able to quickly grab a screen shot.

The error:

> A PHP error was encountered
> Severity: Notice
> Message: Trying to get property of non-object
> Filename: controllers/Auth.php
> Line Number: 150
> Backtrace:
>      File: /var/www/application/controllers/Auth.php
>      Line: 150
>      Function: _error_handler
>      File: /var/www/html/index.php
>      Line: 315
>      Function: require_once

In my case, line 150 of **Auth.php** was actually just a comment line which is odd (im guessing my IDE line numbering is different or something). Immediately below the comment line:

`$logout = $this->ion_auth->logout();`

I'm not entirely sure what's triggering this error, has anyone seen this previously?

**Comment by benedmunds** [comment]
Can you post the code you see on line 150? Cause Im not seeing anything similar.

**Comment by phuze** [comment]
Line 150 in my **Auth.php** file is a comment line. I can't get the code to post correctly, so these images will have to suffice.

![screen shot 2017-01-17 at 7 49 29 pm](https://cloud.githubusercontent.com/assets/9218035/22046417/7531ade8-dcee-11e6-96eb-5402a88edb4d.png)

![screen shot 2017-01-17 at 7 50 45 pm](https://cloud.githubusercontent.com/assets/9218035/22046420/7947ec58-dcee-11e6-8874-f3da53f1a811.png)

**Comment by phuze** [comment]
I have been able to successfully re-create the error by logging in and opening an additional tab (chrome). Log out in one tab, then logout in the other. This error will appear.

I have also been able to identify that the issue is with the **update_prev_login** function I use to implement 'real' last login times.

This is **not** an issue with Ion Auth.

Thanks.
