### ISSUE TITLE
Can't log in after upgrading PHP, CI, Ion_Auth

### ISSUE THREAD

**Issue by jgalak** [benedmunds/CodeIgniter-Ion-Auth#1020]
I am trying to revive an old project and running into a brick wall.  The project was running fine, login was working, all was good.  This was under PHP 5.2, CI 2.2.6, and an older Ion_Auth (not sure of the version).

I upgraded to PHP 5.6, CI 3.1.3 and current version of Ion_Auth.  Now I cannot log in.  I don't get any error, just "Invalid password".  

Nothing in the CI logs, the sessions file has the session with the text "Incorrect Login" in it.

Any idea what aspect of this upgrade could have broken the log in?

Thanks.

**Comment by benedmunds** [comment]
Post your old ion_auth.php config file and your new one.  It's probably that the password hashing algo has changed.

**Comment by jgalak** [comment]
Old: https://www.dropbox.com/s/glhu97rh2k6ufhp/ion_auth-old.php?dl=0
New: https://www.dropbox.com/s/u6orlxaalq8usct/ion_auth.php?dl=0

I tried playing with the salt prefix (hence the commented out line) but no luck.

Let me know if the dropbox links aren't convenient, I'll use some other method.

**Comment by benedmunds** [comment]
Looks like it might (hopefully) be salt_length:

Old:
```
$config['salt_length'] = 10;
$config['store_salt']  = FALSE;
```

New:
```
$config['salt_length'] = 22;
$config['store_salt']  = FALSE;
```

**Comment by jgalak** [comment]
Missed that.

Unfortunately, that didn't fix the problem.  

Is there a way to reset the password hash manually, through a DB edit?  (I can't use the reset pwd function as email isn't set up on this server)  That way I can update to brypt and a longer salt?

**Comment by benedmunds** [comment]
No but you could write a script that calls the change password method on a user.
