### ISSUE TITLE
Logged user previous login date

### ISSUE THREAD

**Issue by federicovilla** [benedmunds/CodeIgniter-Ion-Auth#1026]
Let's say that I log in and I need to know when was my previous log in date ... is there a way to achieve that? For what I know the last login field in DB is updated as soon as I'm logged in so I don't know when I logged previously.
Thanks for any feedback

**Comment by avenirer** [comment]
You can use the "update_last_login" event (hook) which is triggered before updating the last_login field.

**Comment by federicovilla** [comment]
Thanks a lot Adrian...really missed the hook! Additional, I've just now realized that Ion Auth creates a session after a person was logged in successfully. Other session variables created by the login() method are: identity, username, user_id, and old_last_login.
Maybe old_last_login could come in handy?
