### ISSUE TITLE
forgot password not working 

### ISSUE THREAD

**Issue by vinodkumar899** [benedmunds/CodeIgniter-Ion-Auth#1032]
I have set the email configs but i am getting error is **Unable to Reset Password**
$config['use_ci_email'] = TRUE; // Send Email using the builtin CI email class, if false it will return the code and the identity
$config['email_config'] =  array(
'protocol' => 'smtp',
'smtp_host' => 'ssl://smtp.gmail.com',
'smtp_timeout'=>30,
'smtp_port' => 587,
'smtp_user' => 'xxxx@gmail.com',
'smtp_pass' => 'xxxx',
'charset'=>'utf-8',
'mailtype' => 'html',
'newline'=>'\r\n'
);
what i did wrong  i could not find the solution please provide the solution

**Comment by lloricode** [comment]
did you run a website in live server?

**Comment by vinodkumar899** [comment]
No sir , i have run in my local pc

**Comment by lloricode** [comment]
you need to run that in live server ,

i also used this repo ,then run in live server

my repo
https://github.com/lloricode/ci-capstone
my live server.
http://ci-capstone.lloricmayugagarcia.com/


by the way, later i will commit for forgot password, . to see a sample :)

**Comment by vinodkumar899** [comment]
Actually I am using ION AUTH API in this api forgot password not working

**Comment by avenirer** [comment]
what do you mean by "I am using ION AUTH API"? Also, the fact that the error says "Unable to Reset Password" means that it has nothing to do with the email settings. How are you resseting the password? In what controller?

**Comment by avenirer** [comment]
Hello, @vinodrightpath the way you've set up the configuration for gmail is wrong. This is not a problem with the library.
