### ISSUE TITLE
Suggest: on csrf

### ISSUE THREAD

**Issue by lloricode** [benedmunds/CodeIgniter-Ion-Auth#1034]
hmm I just see that CI has own csrf protection

**config.php line 450**
```
$config['csrf_protection'] = TRUE;  //<======================
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;   //<<==========================
$config['csrf_exclude_uris'] = array();
```

so just set this and no need to create that for ion_auth.

after set that, you will need to use `form_open();` to automatically create a `csrf`

hmm, it is this ok?

by the way thanks :+1:

**Comment by benedmunds** [comment]
Yea that's fine, I originally made these examples before CI had CSRF protection built in

**Comment by lloricode** [comment]
ah ok ok . thanks
