### ISSUE TITLE
question: How to register an admin?

### ISSUE THREAD

**Issue by pedroadame** [benedmunds/CodeIgniter-Ion-Auth#1037]
I.e have the user in admin_users table via ion_auth->register() as the group is set as user_group and the user saved in "users"

**Comment by benedmunds** [comment]
Assuming you figured this out?

**Comment by pedroadame** [comment]
Yup, was an issue related to ci_bootstrap_3 as it provides "admin_users", not Ion Auth

**Comment by benedmunds** [comment]
Ok cool
