### ISSUE TITLE
e-mail activation mail bounces

### ISSUE THREAD

**Issue by salihkulangara** [benedmunds/CodeIgniter-Ion-Auth#1038]
Hi, I had some issues with activation through email, now it's working for some extend, here is the previous [issue](https://github.com/benedmunds/CodeIgniter-Ion-Auth/issues/1024
) 
I am using the bare config, library, controller and model files given in the repository, Once I got the mail without any issue.
Now, the registration happens and getting a message like Activation Email Sent. Please check your inbox or spam, I can see the user in inactive form, But not getting email, when I check the mail id, that I have given in admin_email section in config file, there is a mail delivery failed mail, I have given a Gmail account, so I got in admin_email like this
![1](https://cloud.githubusercontent.com/assets/6852780/22832993/3766f2b6-efd6-11e6-9de9-fe3fcbce4c6a.jpg)

What will be the reason for this, I changed to some other server, so there everything is working fine, mail not bouncing but there the email subject getting some weird format like below
![2](https://cloud.githubusercontent.com/assets/6852780/22833244/3508115c-efd7-11e6-94d1-c94c1705022e.jpg)

any idea about this issue

**Comment by benedmunds** [comment]
What are you using as an email provider/smtp?  and are you sure the recipient address is valid?

**Comment by salihkulangara** [comment]
```
$config['email_activation']           = TRUE;             
$config['manual_activation']          = FALSE;
```    

and

```
$config['use_ci_email'] = TRUE; 
$config['email_config'] = array(
        'mailtype'  => 'html'
);
```

The Recipient email is correct. I am using ci email, I dont want to use SMTP, I dont have any email.php file in config folder, Is there any config I want to do regarding ci email, any where?

**Comment by salihkulangara** [comment]
Sorry, I think this is something to do with my Server, even the test code bouncing

```
<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Email extends CI_Controller {
 
 function __construct(){

  parent::__construct();
  //load the  library
  $this->load->library('email');
 }

 function send_mail(){
 
  $this->email->from('salih@gmail.com', 'Salih');
  $this->email->to('tomail@gmail.com');
  
  $this->email->subject('mail send demonstration');
  $this->email->message('this is testing');
  
  $this->email->send();
  
  echo $this->email->print_debugger();
 }
}
```

[even print_debugger() not giving any result?? ]

I created a test file out side codeigniter and use  mail();, it works, but codeigniter mail bounces, I dont know what is happening, do you have any Idea, what can I do??

As I told, in the other server it works, and when I change the config code a little bit, as I got from SO, like this, 

```
$config['email_config'] = array(
        'protocol'=> 'mail', 'mailtype' => 'html', 'charset' =>'utf-8' 
);
```
now the Subject part also works fine.

thank you.

**Comment by benedmunds** [comment]
Do you have a config/email.php file?

If not then you'll need to udpate the config for email within the Ion Auth config.

**Comment by salihkulangara** [comment]
these are the config I am using:
```
$config['email_config'] = array(
        'useragent'=>'CodeIgniter','protocol'=> 'mail', 'mailtype' => 'html', 'charset' =>'utf-8'
);
```
is there anything else I want to change, I dont have a config/email.php file. [Not using SMTP]

**Comment by benedmunds** [comment]
Maybe try smtp?

**Comment by salihkulangara** [comment]
thanks @benedmunds, as I told earlier, the issue was with the Hosting Provider, I have contacted them. I have to use SMTP, they provided the details, now issue is fixed.

**Comment by benedmunds** [comment]
Ok great, thanks!
