### ISSUE TITLE
Error when using like-method on model

### ISSUE THREAD

**Issue by tookig** [benedmunds/CodeIgniter-Ion-Auth#1039]
The method `like `in `ion_auth_model `seems to be using a format for the like-array that is not supported by CodeIgniter:
```
$like = array($like => array(
      'value'    => $value,
     'position' => $position
));
```
I can't find anything in the CI docs about adding the position when using an array with `like`. 
Probably easiest just to remove the position functionality:

```
	public function like($like, $value = NULL)
	{
		$this->trigger_events('like');

                if (!is_array($like)) {
                     $like = array($like => $value);
                }

		array_push($this->_ion_like, $like);

		return $this;
	}
```

Otherwise the array needs to be mapped to single like-calls whenever it is used.

**Comment by benedmunds** [comment]
What version of ion auth are you using?

I just checked the v3 code and it looks like you're right.  Can you send a PR for this change?

**Comment by benedmunds** [comment]
For reference: https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/DB_query_builder.php#L955
