### ISSUE TITLE
In live server auth shows 404 error

### ISSUE THREAD

**Issue by vinodkumar899** [benedmunds/CodeIgniter-Ion-Auth#1040]
I am using codeigniter 3 vesrion in my localhost ion auth is working in live server it shows page not found 

In localhost
url : localhost/foldername/auth/login
it is working fine 
In LIve Server
url: http://XXX.com/auth/login
it shows 404 error

**Comment by avenirer** [comment]
not an Ion_auth issue.

**Comment by lloricode** [comment]
http://stackoverflow.com/questions/28709185/codeigniter-404-page-not-found-on-live-server

maybe your file/controller class names/ should me capitalize .

**Comment by benedmunds** [comment]
Closing since this isn't an Ion Auth issue. I'd recommend posting on the CI forums.

**Comment by vinodkumar899** [comment]
I got the solution .i have used hmvc in codeigniter. Module name in capital letter it be made small the it is working
