### ISSUE TITLE
Can we have two default groups in config/ion_auth.php ?

### ISSUE THREAD

**Issue by namanbansal45** [benedmunds/CodeIgniter-Ion-Auth#1043]
Not sure but curious to know if we can have two default groups in config/ion_auth.php.
while user is signing up or in case of user creation user must be assigned with two groups by default.

**Comment by benedmunds** [comment]
No, that's not currently supported.

**Comment by namanbansal45** [comment]
So, if I need to assign two groups for a user while signing up, is it fine to edit in ion_auth file (passing n no. of groups id and disabling default group in ion_auth) or should I write separate code in my own controller?

**Comment by benedmunds** [comment]
You can edit the controller to do that.  You shouldnt edit the core library or model file but feel free to edit the controller as needed.

**Comment by namanbansal45** [comment]
Thanks!
