### ISSUE TITLE
User Table needs one more column "modified_date"

### ISSUE THREAD

**Issue by iEdzar** [benedmunds/CodeIgniter-Ion-Auth#1044]
We used this library and it's great but I encountered a problem. In our table, we listed the user base on the column "created_on." This is good if there wont be update/edit. In our case we have an update function and so it would be more appropriate to see first which entry was modified and so, in my opinion, it would be helpful if we will add another  column which is "modified_on" or "modified date."

**Comment by avenirer** [comment]
you can do this either by using the "post_update_user_successful" hook, or by doing an update on the table inside the controller after a user updates the data.

**Comment by iEdzar** [comment]
thank you for the response sir. im quite new here so  would it be possible if you would clarify it more about "by doing an update on the table inside the controller after a user updates the data."?

**Comment by benedmunds** [comment]
@iEdzar here's a good tutorial on using hooks with Ion Auth: http://codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth

If you wanted to just do it with the controller, you should modify the controller to do what you need without changing the library or model files.  The controller is simply an example of how to use Ion Auth so feel free to modify as needed.
