### ISSUE TITLE
hi!, can i create some additional function?...

### ISSUE THREAD

**Issue by lloricode** [benedmunds/CodeIgniter-Ion-Auth#1047]
@benedmunds @avenirer 

.... that a parameter is a ID or NAME [maybe array] of group or groups, then return all users that has a groups?, 

or maybe is there a available function? hmmm i cant find in documenttaion and also code inside

**Comment by lloricode** [comment]
i think i found :|

```
	/**
	 * users
	 *
	 * @return object Users
	 * @author Ben Edmunds
	 **/
	public function users($groups = NULL)
	{
		$this->trigger_events('users');

```

so no need to create, its been already have :+1:

**Comment by avenirer** [comment]
@lloricode in here you have (almost) everything: http://benedmunds.com/ion_auth/

**Comment by lloricode** [comment]
thanks @avenirer :100:
