### ISSUE TITLE
Using order_by causes unknown column error

### ISSUE THREAD

**Issue by jamieburchell** [benedmunds/CodeIgniter-Ion-Auth#1051]
`$users = $this->ion_auth->users()->order_by('modified_date', 'desc')->result();`

Then:

`$this->ion_auth->register($email, $password, $email, $data, $groups);`

Causes:

```
Error Number: 1054
Unknown column 'modified_date' in 'order clause'
SELECT *
FROM `groups`
WHERE `groups`.`id` = 1
ORDER BY `modified_date` DESC
 LIMIT 1
Filename: models/Ion_auth_model.php
Line Number: 1504
```

**Comment by benedmunds** [comment]
This is really weird...  Try running 

     $this->db->_reset_select()


between the two calls, not saying this is the final solution by any means, but I want to know if it fixes it.

Also, what version of CI are you running?

**Comment by jamieburchell** [comment]
`Fatal error: Call to protected method CI_DB_query_builder::_reset_select()`

CI 3, I was updating the library to the 2.6 tag, but notice the version in the library comments is 2.5.2. The 2.5.2 tag looks again different from the library code in the 2.5.2 version I upgraded from, so I have no idea what version it was, only that this didn't happen then.

**Comment by benedmunds** [comment]
@jamieburchell can you try upgrading Ion Auth to the most recent code in the "2" branch here on Github?

**Comment by jamieburchell** [comment]
Doesn't seem to happen in the most recent code in the "2" branch

**Comment by benedmunds** [comment]
Awesome.  Closing since this seems to be resolved.  Feel free to re-open if needed.
