### ISSUE TITLE
Function mcrypt_get_iv_size() is deprecated

### ISSUE THREAD

**Issue by Th3AL0** [benedmunds/CodeIgniter-Ion-Auth#1052]
Hello Guys, I'm getting this error in the forgot_password. Thanks in advance!

![error](https://cloud.githubusercontent.com/assets/5881465/23300462/f5063016-fa85-11e6-9280-24123f12e1dc.PNG)

**Comment by AlexandreLogist** [comment]
@avenirer @benedmunds  Thanks !

**Comment by Th3AL0** [comment]
Thanks for solving this issue!

**Comment by amitamie-com** [comment]
Hello Guys I was getting same above error message but by updating the code which was suggested from @avenirer is solved.
But still I am facing some issues and I am getting below error.

> A PHP Error was encountered
> Severity: 8192
> Message: Function mcrypt_get_iv_size() is deprecated
> Filename: libraries/Encrypt.php
> Line Number: 337
> 
> A PHP Error was encountered
> Severity: 8192
> Message: Function mcrypt_decrypt() is deprecated
> Filename: libraries/Encrypt.php
> Line Number: 346

Please help ! Thanks in Advance !!!

**Comment by benedmunds** [comment]
@amitamie-com is this a duplicate of https://github.com/benedmunds/CodeIgniter-Ion-Auth/issues/1076#issuecomment-297697292 ?

**Comment by amitamie-com** [comment]
**@benedmunds**  Sorry for duplicate post , actually I thought two comments at two different places are better than one , **but guys replied so fast** , for that thank you so much , and in future I will not do any duplicate comment.

**Comment by benedmunds** [comment]
Ok cool, take care!

**Comment by julio899** [comment]
i can solve using the new library encryption recommend.
example:
`
// #Encrypt

        $this->load->library('encryption');
        $to_encrypt="some value";
        $this->encryption->initialize(
                array(
                        'cipher' => 'aes-256',
                        'mode' => 'ctr',
                        'key' => $this->config->config['encryption_key']
                )
        );
        echo $this->encryption->encrypt($to_encrypt);
`
