### ISSUE TITLE
forgot password issue

### ISSUE THREAD

**Issue by vinodkumar899** [benedmunds/CodeIgniter-Ion-Auth#1062]
I have setting the these configurations in ion auth config file but i am getting error is fsockopen error. I have used liveserver
$config['email_activation']           = TRUE;    
$config['use_ci_email'] = TRUE;
$config['email_config'] = array(
	
	'protocol' => 'smtp',
	'smtp_host' => 'ssl://smtp.gmail.com',
	'smtp_timeout'=>30,
	'smtp_port' => 587,
	'smtp_user' => 'xxxx@gmail.com',
	'smtp_pass' => 'xxxx',
	'charset'=>'utf-8',
	'mailtype' => 'html',
	'newline'=>'\r\n'
);

**Comment by avenirer** [comment]
Not an Ion Auth issue...

**Comment by benedmunds** [comment]
Hey @vinodrightpath 

This isn't an Ion Auth issue.  It's either related to your CodeIgnier email config or your PHP server setup.  I'd recommend doing some research on StackOverflow and troubleshooting.

You can try starting with these:

http://stackoverflow.com/questions/1555145/sending-email-with-gmail-smtp-with-codeigniter-email-library

http://stackoverflow.com/questions/38417920/unable-to-send-email-using-smtp-gmail-config-in-codeigniter-3

http://stackoverflow.com/questions/25305417/how-to-solve-warning-fsockopen-unable-to-connect
