### ISSUE TITLE
How to Integrate Ion-Auth with Native Android Apps

### ISSUE THREAD

**Issue by 1345121** [benedmunds/CodeIgniter-Ion-Auth#1068]
Hi edmunds, I hope all is well with you on there 😺 

It's my first time i use your libs, hope i can get clear explanations. :neckbeard: 

I use ci v3.1.2 with hmvc, all it's work because i use `ci_bootstrap_3` some core template included your libs (if it's fine here, i will included it link in my next reply maybe you wanna check), Anyway, i try to create new `modules > android > controllers > Api.php` this my codes

```php

//Api.php

<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
class Api extends MY_Controller
{
    public function __construct()
    {
        parent::__construct();
        //$this->load->model('Api_m');
        $this->load->library('ion_auth');
    }

    public function index()
    {
        echo 'Android API v1.0';
    }

    public function login()
    {
        $username = $this->input->post('username');
        $password = $this->input->post('password');
        //$result = $this->ion_auth->login($username, $password);
        //$result = $this->Api_m->login($username,$password);
      //  echo json_encode($result);

      $result = $this->ion_auth->login($username, $password, FALSE);
                echo json_encode($result);
    }

```

i wanna use that for implement to my android apps as API, but when i test it on postman it's always return false, no other files on my android modules just `controllers > Api.php` and `models > api_m.php` i used models earlier for try to connect with it but i cant, imho all of that's because i send non encrypted password string, and well how i can handle this probs?

if thats solve, i wanna know as deep (i mean like session expire time, multi login user, or maybe you have an important poin to who's works with it on API development). 🚀 

Thanks in advance!

**Comment by benedmunds** [comment]
You'll need to follow a few more troubleshooting steps, for starters:

Try echoing the username and password vars.

Check for any php errors in your logs.

See what $this->ion_auth->errors() returns.

**Comment by 1345121** [comment]
Thanks for quick reply ben,

i had echoing my password it result not encrypted password, and when i try echo `$this->ion_auth->errors()` its return `<p>Incorrect Login<\/p>` what should i do next, hope you can guide me over there.

**Comment by benedmunds** [comment]
For one, you should return that error to your API consumer if the result of login is false.

Are you trying with the default admin login? Does it work with the example controller?

**Comment by 1345121** [comment]
thanks a lot ben, now all it's working well after checking back example code, btw how about timing session expired and multi user? is it will probs? i mean can i setting my custom function login on controller to trigger session never expired for my android apps, or maybe is there an another way to handle it?

**Comment by benedmunds** [comment]
You can't directly store a session via an API like you do the browser. You'll need to implement authentication and state management.

I'd recommend you check out this book to get you on the right track: https://leanpub.com/build-apis-you-wont-hate

**Comment by 1345121** [comment]
Nice! had been cleared overhere, Thanks Ben! 😸 

Notes:
my problem's before is because i used hmvc and i forgot to put ion_auth.php on my new module, so it just work on my other modules where it included ion_uth.php in config folder.
