### ISSUE TITLE
hook in construct

### ISSUE THREAD

**Issue by lloricode** [benedmunds/CodeIgniter-Ion-Auth#1073]
hi @benedmunds !

i just want to add hook in `__construct()` in `Ion_auth`

but I notice that load first the library before we can call `trigger_hook`,

##
when i set_hook for `library_constructor`, it not call because it will load first the library.
then cannot call again my set hook

my plan is call it in model, but you said is do not call directly a function using ion_auth_model

is there other way to call it?

thanks to all sir in response :)

**Comment by benedmunds** [comment]
Here is a good tutorial on how to use them: http://codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth

Let me know if you have any questions after going through that.  Thanks!

**Comment by lloricode** [comment]
@benedmunds thanks :)
