### ISSUE TITLE
step verification user with email

### ISSUE THREAD

**Issue by sidiqnugraha** [benedmunds/CodeIgniter-Ion-Auth#1074]
iam new in CI and i try library ion auth , please help to verfication user steps ion auth 
THANKS

**Comment by benedmunds** [comment]
Hey,

The example controller and views are included to get you started.  Sounds like you may want to invest some time in learning more about CI in general and then post specific questions on StackOverflow or the CI forums.  GitHub issues are meant to house actual bugs.  

Thanks!
