### ISSUE TITLE
Function mcrypt_get_iv_size() is deprecated

### ISSUE THREAD

**Issue by amitamie-com** [benedmunds/CodeIgniter-Ion-Auth#1076]
Hello Guys I am getting getting below error message.

> A PHP Error was encountered
> Severity: 8192
> Message: Function mcrypt_get_iv_size() is deprecated
> Filename: libraries/Encrypt.php
> Line Number: 337
> 
> A PHP Error was encountered
> Severity: 8192
> Message: Function mcrypt_decrypt() is deprecated
> Filename: libraries/Encrypt.php
> Line Number: 346

 Please help ! Thanks in Advance !!!

**Comment by avenirer** [comment]
As I remember, this was fixed in pr #1054. Make sure you also have latest version of ion_auth.

**Comment by amitamie-com** [comment]
First of all thanks for answering for my query .
As I know I have updated **ion_auth_model.php** with the fix which you have provided .

By the way can you please tell me which are those files which I have to replace with the latest ones.

Note: My current version  PHP is 7.1.1

**Comment by benedmunds** [comment]
To do a full update replace:

libraries/BCrypt.php
libraries/Ion_auth.php
models/Ion_auth_model.php

**Comment by lloricode** [comment]
@amitamie-com 

include also a language folder

`language/`

because message value is in there

**Comment by amitamie-com** [comment]
**@benedmunds @avenirer @lloricode**  
Thank you guys for your valuable suggestions and comments :-)
