### ISSUE TITLE
When remember me not checked 

### ISSUE THREAD

**Issue by Brhmts** [benedmunds/CodeIgniter-Ion-Auth#1080]
Hi , I am new with CI 
At localhost 
When "remember me" not checked, Just redirecting to the URL and Cookies just get the 'name' property

When "remember me" is checked , All works well, Cookies get all properties  'name', 'identity', 'remember_code' 

Is it a bug or i miss something?

**Comment by benedmunds** [comment]
What version of CI are you using?

What hash of Ion Auth,  have you tried updating to latest?

And lastly, post both your CI config and Ion Auth config please.

**Comment by Brhmts** [comment]
CI version 3.1.3 ,  I am using latest version for Ion Auth too , yesterday updated.  I added 2 files like this ,hope they are ok .

https://gist.github.com/Brhmts/5d4efa3ac5146eb25147235b4fcf942f

**Comment by avenirer** [comment]
@Brhmts can you try this version https://github.com/benedmunds/CodeIgniter-Ion-Auth/tree/6733651c7f52338a9427104ade814d9377d7affe and tell us if it is working?

**Comment by Brhmts** [comment]
@avenirer I did , result is still same

**Comment by benedmunds** [comment]
This might be a long shot but can you try with CI 3.1.4?  This is an odd issue...

**Comment by Brhmts** [comment]
Hi again , yes it works well with CI 3.1.4 . I used @avenirer 's version

**Comment by avenirer** [comment]
What avenirer's version? Now you should try it with the latest version of ion auth, and tell us if it works, please.

**Comment by Brhmts** [comment]
I meant , i  used the link which you sent ,  Just tried with latest version with Ion Auth ,
It works well  , Thanks lots , I will go on with CI 3.1.4

**Comment by benedmunds** [comment]
Awesome, thanks!
