### ISSUE TITLE
why don't have auth

### ISSUE THREAD

**Issue by wzq232** [benedmunds/CodeIgniter-Ion-Auth#1081]
why don't have auth

**Comment by avenirer** [comment]
Well... this is a good question...

**Comment by benedmunds** [comment]
You'll need to be quite a bit more descriptive of the issue if you'd like help

**Comment by wzq232** [comment]
you code have group，but don't have group auth。
意思就是代码中有用户组，但用户组没有限制他们的权限。现在只是一个用户表和用户组表对应的扩展〜〜

**Comment by lloricode** [comment]
@qiang5062250 you can, by just create a new `group` in your application.

```php
// pass the right arguments and it's done
$group = $this->ion_auth->create_group('new_test_group', 'This is a test description');

if(!$group)
{
       $view_errors = $this->ion_auth->messages();
{
else
{
      $new_group_id = $group;
     // do more cool stuff
{
```

here's a link: [http://benedmunds.com/ion_auth/#create_group](http://benedmunds.com/ion_auth/#create_group)

**Comment by wzq232** [comment]
why not add rbac or oauth

**Comment by avenirer** [comment]
You can have whatever you want. For this you have hooks. But this is not a forum...

**Comment by wzq232** [comment]
Thank you
