### ISSUE TITLE
Add role organization

### ISSUE THREAD

**Issue by Afdhal-Mahdi** [benedmunds/CodeIgniter-Ion-Auth#1083]
How to add field to group or new table, to get organization id

**Comment by benedmunds** [comment]
Implementation will change a bit based on how you want to use it but in general you'll add the field and then use hooks to modify the behavior where needed.  Here's a good tutorial on hooks:

http://codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth

**Comment by deenjustin** [comment]
How can make user permission?

**Comment by benedmunds** [comment]
You can use groups to control permissions.
