### ISSUE TITLE
Error when create user

### ISSUE THREAD

**Issue by daytch** [benedmunds/CodeIgniter-Ion-Auth#1085]
Hi...
i get this error when create user.
user is created in table users but not in users_groups, help me please

A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: models/Ion_auth_model.php

Line Number: 934

Backtrace:

File: C:\xampp\htdocs\xxx\application\third_party\ion_auth\models\Ion_auth_model.php
Line: 934
Function: _error_handler

File: C:\xampp\htdocs\xxx\application\third_party\ion_auth\libraries\Ion_auth.php
Line: 305
Function: register

File: C:\xampp\htdocs\xxx\application\controllers\User.php
Line: 186
Function: register

File: C:\xampp\htdocs\xxx\index.php
Line: 315
Function: require_once

**Comment by avenirer** [comment]
Did you read about how to install the library? Because I don't remember mentioning about installing as third party...

**Comment by lloricode** [comment]
@avenirer here the [commit](https://github.com/benedmunds/CodeIgniter-Ion-Auth/commit/463b94a7740fdf340ef0ef61a95ab8c065d7c4f0) of @benedmunds about `loading third party`.

**Comment by benedmunds** [comment]
You need to add the package path as well:

$this->load->add_package_path(APPPATH.'third_party/ion_auth/');


See this issue for more details: https://github.com/benedmunds/CodeIgniter-Ion-Auth/issues/1055

**Comment by daytch** [comment]
solved, thanks all.
my mistake in function register, i throw string in $group not array(). 
$this->ion_auth->register($username, $password, $email, $additional_data, $group)

**Comment by benedmunds** [comment]
Ok awesome!
