### ISSUE TITLE
Reset-password link giving 404 error -

### ISSUE THREAD

**Issue by sinisnair** [benedmunds/CodeIgniter-Ion-Auth#1088]

**Comment by benedmunds** [comment]
Have you changed the controller?
Are you using mod_rewrite?

**Comment by sinisnair** [comment]
Previously` link has given to auth/reset_password. 
``<?php` echo sprintf(lang('email forgot_password subheading'), anchor('auth/reset_password/'. $forgotten_password_code, lang('email_forgot_password_link')));?>`

I changed it to controller. Now it is working. Thanks for the help

**Comment by benedmunds** [comment]
No problem!
