### ISSUE TITLE
Retaining field values after captcha mismatch

### ISSUE THREAD

**Issue by sinisnair** [benedmunds/CodeIgniter-Ion-Auth#1090]
After captcha mismatch, how to fill/retain the values of a registration page?
Controller code is 
```
if (!$captcha_text_matched) {
                $this->session->set_flashdata(
                        'register_message', 'The entered text is not matched.'
                );
                redirect(base_url('user/register'));
            }
```

**Comment by benedmunds** [comment]
Closing this issue since it's not directly related to an Ion Auth bug.

I'd recommend you ask questions like this on the CI Forums or StackOverflow.  A good place to start though would be using flashdata to save the values before the redirect and then refilling from that if needed.
