### ISSUE TITLE
Timestamp should be taken into account when getting attempts number

### ISSUE THREAD

**Issue by Indigo744** [benedmunds/CodeIgniter-Ion-Auth#1094]
Dear dev,

The `get_attempts_num()` function of Ion_auth_model retrieve all attempts for a specific identity.
I expected this function to actually retrieve the number of attempts from the last `lockout_time` seconds.

It makes sense, my clients actually expect that if they wait enough time (i.e. the `lockout_time` config value), they will have all their "try" back (i.e. the `maximum_login_attempts` config value).

So may I suggest to only retrieve attempts made in the last `lockout_time` seconds?
I understand this behavior is maybe not for everyone, so maybe this can be configurable?

What are your thoughts on this?

Thanks.
Regards.

**Comment by Indigo744** [comment]
After some digging, I saw this was (partially) discussed in #859.

**Comment by benedmunds** [comment]
If you want to send a PR to make that configurable I'll consider it but not sure how I feel about that.  The point of this feature is to prevent brute forcing and more you do to slow down logins the better for that.  I would think that after X tries a user really should just do the forgot your password workflow rather than attempting a dozen passwords.

You could always do a hook to call clear_login_attempts for your specific app implementation.

**Comment by Indigo744** [comment]
I see what you mean.

However, speaking of `clear_login_attempts()` function, it has an interesting behavior.
It will clear all login attempts related to a specific identity (and IP address is option is set), **AND** it will clear _all other expired login attempts_.

This means, if I use `clear_login_attempts()` for user A (either using a hook, or naturally because he successfully logged in), and user B was locked-out and was trying one login at a time, user B will be able to suddenly try multiple times again.
I'm not sure I'm explaining it well, but do you see what I mean?

**Comment by benedmunds** [comment]
Yea I see what you mean there.  Reviewing this PR I'm tending to agree with your thoughts here.  It's a lot simpler and more consistent.  I'll merge it in.  Thanks!

**Comment by benedmunds** [comment]
Merged #1095

Thanks again!

**Comment by Indigo744** [comment]
Waaaaait the PR wasn't actually directly related to this issue XD
The PR is only for having a consistent check behavior.

Here, I'm just talking about whether the `get_last_attempt_time()` function should also check the timestamp field...

**Comment by benedmunds** [comment]
My bad!  I saw you had updated get_last_attempt_time.  Reopening :D

**Comment by Indigo744** [comment]
Maybe I should have waited before submitting this PR. But it was an inconsistencies and I thought I didn't need to open a new issue, just to submit a PR.

For the issue of this thread, would you like I made it configurable or not?

**Comment by benedmunds** [comment]
Ok so on the time.  I'm kind of torn.  If people use decent numbers for time and attempts num I think it's fine but I don't want to make it too insecure.

How about this:
 * Make your idea the default (only) behavior
 * Add a comment to lockout_time in the config that it's recommend that it not be set lower than 60

That way we at least encourage a secure practice yet it does behave intuitively for locked out users.


Thoughts?

**Comment by Indigo744** [comment]
It is always good to encourage people to have more security in their app.
60 (1 minute) seems like a good minimum value (however, the default value at 600 - 10 mins - should stay as it is even more secure, and usual).

Also, maybe we should update the `clear_login_attempts()` function to no longer purge old attempts.
As a matter of facts, since it expects an identity, a dev should expect this function to only act on attempts from this specific identity.
I am not afraid of cluttering the table, because any successful login attempts will remove all attempts for an identity.
For other remaining attempts, we could simply add a `purge_old_login_attempts()` function for this action. The dev will then be in charge of calling this once in a while.

**Comment by Indigo744** [comment]
Also, why is the option `track_login_attempts` set to FALSE by default?
It would be more secure to set to TRUE by default, to encourage people to use it, isn't it?

**Comment by benedmunds** [comment]
Agreed, leave the default at 600.

I agree as well, clear_login_attempts should only affect the identity it is called on.

I'm really not sure a purge_old_login_attempts is even needed, since a successful login will clear for any user.

Maybe also clear attempts after max attempts * 2 or something like that so a DOS attack doesnt fill the database of attempts for a specific user?

and finally, I'm OK with making track_login_attempts default to TRUE.  Truthfully, I don't remember why it was false by default.  Likely it was added and wanted to maintain BC functionality for upgrading users.

**Comment by Indigo744** [comment]
Well, sometimes an attempts looks like "address@yaho.com", which means the user has only forgot one 'o' in Yahoo. Next try, he will put "address@yahoo.com" and log in. However, the attempt regarding "address@yaho.com" will never be purged... So maybe the dev needs a function to be able to purge these bad values once in a while...

**Comment by Indigo744** [comment]
Well, after some thought, maybe we should kept `clear_login_attempts()` as is, i.e. with the purging of old and obsolete value. To keep the same behavior as before.
However, the `$expire_period` value is set by default to 86400 seconds, which is 24h.
We should make this value depends on the `lockout_time` config value. Maybe `lockout_time * 2` for instance.
That way, if a dev set the `lockout_time` to a week (for security reason), attempts will not be removed automatically by the default value after 24h.

What do you think?

**Comment by benedmunds** [comment]
I like this plan.  Definitely agree with lockout_time * 2

**Comment by Indigo744** [comment]
I think this thread can be closed now :) time to start a new one! Yiaie ^^
