### ISSUE TITLE
Get Login attempts information for other users

### ISSUE THREAD

**Issue by Indigo744** [benedmunds/CodeIgniter-Ion-Auth#1098]
Hello,

First of all, this is _not_ related to the current PR (just to be sure ^^).

So, let's me explain some context.
In an application I am currently developing, the administrators have access to all users information in the backend.
Among these information, I want the administrators to be able to see if a user has made some unsuccessful login attempts: how many, if they are locked, and the ability to remove this lock.

Now all can be done using the following functions:
 - `get_attempts_num($identity)`
 - `is_max_login_attempts_exceeded($identity)`
 - `get_last_attempt_time($identity)`
 - `clear_login_attempts($identity)`

As you can see, all these functions accept the identity as a parameter. So I should be able to use it for a specific user.
However there is an issue. If the `track_login_ip_address` configuration value is set to TRUE (as in my configuration), all these functions will then use the _current_ IP Address as a filter.
This is hardcoded. So I sadly cannot use these function as is.

I have thought of several approach:
 1. _No update of library_: make wrapper functions to set `track_login_ip_address` to FALSE before calling these functions, and then set it back to TRUE.
 2. _No update of library_: rewrite these functions as needed in another app model.
 3. _Update the library_: add a public `$ip_address` attribute to the class, initialized to the current IP. 
 4. _Update the library_: add a new `$ip_address` parameter for each of these functions. Default behavior would be to use the current IP to keep compatibility.

I have a preference for the last approach, which seems to be the cleanest (and may benefit others who may want to do the same).

What do you think?

**Comment by benedmunds** [comment]
I prefer option 4 and would be happy to merge that in.  I like passing arguments in when possible.

**Comment by Indigo744** [comment]
I guess I can close this now :) thanks.

**Comment by benedmunds** [comment]
Thanks again!!!
