### ISSUE TITLE
List active user sessions / logged in users

### ISSUE THREAD

**Issue by simsyau** [benedmunds/CodeIgniter-Ion-Auth#1101]
Hi guys,

Possible feature request?

Is there anyway to get a list of active user sessions or logged in users?

Looking through the documentation, the model and DB schema it appears there isn't a function that does this or a table that contains the details of active sessions? or is there?

cheers,

Andrew

**Comment by benedmunds** [comment]
There's no good way to do this easily.  The way I've recommended in the past for people to handle this is to use DB sessions in CodeIgniter and use the sessions table to mine the data you need.

Sorry, this isn't something I'd want to complicate the library with adding.
