### ISSUE TITLE
Date And Time Error On Integration of Ion-Auth 

### ISSUE THREAD

**Issue by Johnnydoncom** [benedmunds/CodeIgniter-Ion-Auth#1105]
Actually, I've been working with Ion Auth for awhile now with no issue on other hosting companies. When I upload my project on Ipage.com, I kept seeing this error message:

A PHP Error was encountered

Severity: Warning

Message: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.

Filename: libraries/Email.php

Line Number: 979

Backtrace:

File: /hermes/bosnaweb07a/b1404/ipg.dynown/application/libraries/Ion_auth.php
Line: 60
Function: library

File: /hermes/bosnaweb07a/b1404/ipg.dynown/index.php
Line: 315
Function: require_once

Please I need your help in fixing this.
Thanks in anticipation

**Comment by benedmunds** [comment]
This is a PHP config issue.  To fix it, either set a date.timezone in your php.ini (http://php.net/manual/en/datetime.configuration.php) or manually call date_default_timezone_set() (http://php.net/manual/en/function.date-default-timezone-set.php) in your app.  I usually just call that function in my index.php.
