### ISSUE TITLE
Temporarily Locked Out. Try again later.

### ISSUE THREAD

**Issue by blaasvaer** [benedmunds/CodeIgniter-Ion-Auth#1107]
I keep getting this ... and cannot get past the login screen. What am I missing?

Had it working, but updated to the latest version, now this.

**Comment by benedmunds** [comment]
Can you post your Ion Auth config please.

Also do you get it after failed login attempts?

**Comment by blaasvaer** [comment]
OK, just scrapped the tables in the DB, and ran the SQL again. All is good. Thanks.

**Comment by benedmunds** [comment]
ok good 👍
