### ISSUE TITLE
can i use multiple identity for login ?

### ISSUE THREAD

**Issue by cdmathukiya** [benedmunds/CodeIgniter-Ion-Auth#1108]
i have requirement to login using any of this field either **email** OR **username** OR **mobile number** 
it is directly possible in ion-auth ? if yes then how?
i am currently using codeigniter CodeIgniter-3.1.5 with PHP 7.1.1
please help me.
Thank you in advance

**Comment by lloricode** [comment]
Here's the [config](https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/config/ion_auth.php#L89). :)

but multiple? maybe cannot.

**Comment by cdmathukiya** [comment]
Thanks,
but,that's i know about select one identity.
but i want to check either email or username  or mobile number.
so, i need to check multiple identity column with or condition

**Comment by lloricode** [comment]
I think, that is currently not supported,
maybe we can suggest for this in PR,

just wait for the owner of repo's answer.

**Comment by avenirer** [comment]
I guess you can check the type of input (if number, that means telephone number, if with @ and valid email, that means email address, else means username.

After the script decided what to work to, you can dynamically change the config value for identity and then try to login the user...

**Comment by lloricode** [comment]
great @avenirer ,

@cdmathukiya you can use `$this->trigger_events('pre_login');` hook
to dynamically change the identity before validate input from user to database

[here](https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/models/Ion_auth_model.php#L965) the execution

**Comment by benedmunds** [comment]
This isn't currently supported and not something I'm really up for supporting with the standard library.  It would add a lot of complexity that most users simply dont need.

That being said, you could use a hook to check the type or just loop through each option and dynamically change the identity then try a login as explained above.

**Comment by cdmathukiya** [comment]
Thanks for help me.
finally i found the solution for that issue.
just put the or_where in ion_auth_model query in login function like this..
```
$query = $this->db->select($this->identity_column . ', email, id, password, active, last_login')
		->where($this->identity_column, $identity)
		->or_where('username', $identity)
		->or_where('mobile', $identity)
		->limit(1)->order_by('id', 'desc')
		->get($this->tables['users']); 
```

it is work for me.

**Comment by benedmunds** [comment]
That'll work, just note thats its not very flexible and will stop you from being able to upgrade the library in the future.

**Comment by lloricode** [comment]
@cdmathukiya just don't modify the library, just use hooks,

here's the [link](http://benedmunds.com/ion_auth/#set_hook)

**Comment by benedmunds** [comment]
Jeff Madsen has a really good tutorial on using hooks as well, I definitely recommend using them instead.

 http://codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth

**Comment by lloricode** [comment]
```php
if ($this->form_validation->run() == true)
		{
			// Put here, because no need this in outside the process,
			// Here is only has POST
			$this->ion_auth->set_hook('pre_login','check_identity_event',$this,'_check_identity',array());

			// check to see if the user is logging in
			// check for "remember me"
			$remember = (bool) $this->input->post('remember');

			if ($this->ion_auth->login($this->input->post('identity'), $this->input->post('password'), $remember))
			{
```

```php
	public function _check_identity()
	{
		// No need to execute this if has no POST request.
		if(!$this->input->post())
		{
			// just show 404 like other not exist really exist.
			show_404();
		}

		// Just store the user input.
		$identity = 	$this->input->post('identity',TRUE);

		// Set Null
		$column_table = NULL;

		// Use this for email
		$this->load->library('form_validation');


		// Username
		if(preg_match('/^[a-zA-Z0-9]+[_.-]{0,1}[a-zA-Z0-9]+$/m',$identity))
		{
			$column_table = 'username';
		}

		// Email
		// we can use build in ci validation
		elseif($this->form_validation->valid_email($identity))
		{
			$column_table = 'email';
		}


		// Phone
		// SAMPLE EXACT FORMAT  
		// 1234 5678

		// Then make sure this coulum in your table is unique also
		elseif(preg_match('/^\d{4}[ ]\d{4}$/',$identity))// modify this if you want other format
		{
			$column_table = 'phone';
		}

		
		// If there has any of the three, then override this, 
		// ELSE default value by ion_auth model will be use
		if(!is_null($column_table))
		{
			$this->ion_auth_model->identity_column = $column_table;
		}

	}
```


@cdmathukiya you can use my [branch](https://github.com/lloricode/CodeIgniter-Ion-Auth/tree/multi-identity)

**Comment by benedmunds** [comment]
@lloricode 👏
