### ISSUE TITLE
How to send Post activation Email

### ISSUE THREAD

**Issue by arunkp** [benedmunds/CodeIgniter-Ion-Auth#1109]
Hi,

is there a way to send a welcome email post activation?
I wold ideally want to create welcome.tpl.php and store it under auth/email/ and would like to trigger it when activate() is successful.

**Comment by benedmunds** [comment]
You can use a post_activate hook to accomplish this.

The docs for hooks are here:
http://benedmunds.com/ion_auth/#set_hook

And Jeff Madsen has a good tutorial here:
http://codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth
