### ISSUE TITLE
New password doesn't get sent

### ISSUE THREAD

**Issue by josemilioz** [benedmunds/CodeIgniter-Ion-Auth#1110]
I guess it is because function forgotten_password_complete never gets called in the Auth controller when resetting the password.

Also found out that many model functions have the same name in the library. Doesn't this rewrites the aliases behavior in some way? Why not try to separate the names for certain functions in order to keep it neater (if that's a word hehe).

Greetings.

**Comment by benedmunds** [comment]
reset_password is what is used to completed the process in the controller.

All of the methods are called against the library.  If the library has the method it will be used, if it doesn't the method is called against the model by the library.  Note the __call method here: https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/libraries/Ion_auth.php#L90

**Comment by josemilioz** [comment]
Correct Ben. I've seen that. Then the right thing to do is to move the logic of the email-sending into that function. Or call the forgotten_password_complete in the controller before you kill the password recovery code.

**Comment by benedmunds** [comment]
It's left that way to keep BC and give developers more flexibility.  

In general you want to let the user set the password and not email them a password.

Feel free to correct me if I'm not following your issue correctly.

**Comment by josemilioz** [comment]
Ok, sorry for the inconvenience. Didn't know it was that way on purpose. Thank you Ben for the input on it. Cheers mate.

**Comment by benedmunds** [comment]
No problem!  👍
