### ISSUE TITLE
Force Login

### ISSUE THREAD

**Issue by celianvdb** [benedmunds/CodeIgniter-Ion-Auth#1111]
Hey,
I want to add Oauth2 support on my website but i need a function to force login after to authentification from Oauth2. There is a way to do that actually or i can send a pull request ?

**Comment by benedmunds** [comment]
There's a social branch that has some support for logging in to other services via OAuth.  It's not officially maintained by me but even if you can't use it directly hopefully it'll help:

https://github.com/benedmunds/CodeIgniter-Ion-Auth/tree/social
