### ISSUE TITLE
How to get "$this->ion_auth->logged_in()" in views of  other controllers

### ISSUE THREAD

**Issue by andreyka26-git** [benedmunds/CodeIgniter-Ion-Auth#1113]
I  copy the files from  package to the corresponding folder in  application folder, and include the library in MY_Controller ($this->load->library('ion_auth')). But i dont know how to check in other controllers if user was  authorization or not? So i dont know when i must to display button link logout, and when -  login. Please help me! Sorry for my English.... i am from Ukraine..

**Comment by avenirer** [comment]
if($this->ion_auth->logged_in()) {
  echo "logout button";
}

**Comment by andreyka26-git** [comment]
thank))

**Comment by benedmunds** [comment]
Closing since this seems to be resolved.  Feel free to reopen if the problem persists.
