### ISSUE TITLE
Add singular table and column names

### ISSUE THREAD

**Issue by odahcam** [benedmunds/CodeIgniter-Ion-Auth#1114]
Well, why? Just read:

- https://softwareengineering.stackexchange.com/a/341327/250744
- http://www.wilsonmar.com/sql_adventureworks.htm
- https://stackoverflow.com/questions/7662/database-table-and-column-naming-conventions

Singular or plural names should be an option, as it depends on your religion. 😄

**Comment by benedmunds** [comment]
Nah I'm good. I see no reason to change a library that's been stable for years due to some people's preferences.  It's just words.

Feel free to fork and offer a branch with different options if you want :shrug:

**Comment by odahcam** [comment]
Actually this issue is focused in adding a `.sql` file, but, avoiding unnecessary words, this lib can be more flexible. 

**E.g.:** mapping the table and column names used by the lib properly in config file should do the trick.

The config file already has something like this, but it looks a little confusing and incomplete.
