### ISSUE TITLE
Multiple login session

### ISSUE THREAD

**Issue by maneeshms** [benedmunds/CodeIgniter-Ion-Auth#1115]
Is there anyway to use multiple login sessions using ion auth? I mean Eg : I logged in as as admin and I want to login as user in the next tab and the sessions should not mix up...

**Comment by avenirer** [comment]
Why not use two different browsers?

**Comment by lloricode** [comment]
@maneeshms  did you mean `http://127.0.0.1:8000/` and `http://127.0.0.1:8000/admin` ?

**Comment by maneeshms** [comment]
@avenirer  In some situation we have to maintain different sessions. It would be great if we do it... google allowing multiple sessions on same browser... Something like that

**Comment by maneeshms** [comment]
@lloricode Yes.

**Comment by benedmunds** [comment]
Sorry this isn't something we can support easily with the core library.  If you want to make a fork that does this I'll be happy to link anyone in the future that needs this to it.
