### ISSUE TITLE
Forgot Password Complete not send email

### ISSUE THREAD

**Issue by wayahnawe** [benedmunds/CodeIgniter-Ion-Auth#1117]
Hi All, 
forgot password can send email but after i reset my password, forgot password complete not sending email. it just send my back to login page. 
How i complete this?

**Comment by benedmunds** [comment]
The default work flow is just to get the one email, then reset your password, then login with the new password.

**Comment by wayahnawe** [comment]
So its means that function forgotten_password_complete($code) will not send email confirmation?

**Comment by benedmunds** [comment]
forgotten_password_complete should send an email if use_ci_email = false in your config.

forgotten_password_complete isn't called in the example controller anymore though.  Did you update your controller to call it?

**Comment by wayahnawe** [comment]
Yes i did, cause when i set use_ci_email =false i can't recieve forgot pasword  confirmation.

**Comment by benedmunds** [comment]
Can you post your controller please.

Also might be worth through in debug code in the library to see if the email library is returning an error.

**Comment by wayahnawe** [comment]
its looks like because i'm running on xampp for dev and linux for production. function forgot_password_complete($code) is running well when on linux enviroment after i set use_ci_email = false and i config email library  for builtin CI.

**Comment by benedmunds** [comment]
Ok cool, thanks!
