### ISSUE TITLE
Set Expire Time For Activation Code

### ISSUE THREAD

**Issue by wayahnawe** [benedmunds/CodeIgniter-Ion-Auth#1119]
Hi, 

I want to set expire time for activation code, so if user on certain time not activate the code will expire. Can we do that?

Rengga Patria

**Comment by benedmunds** [comment]
There's no way to do that right now.  You'd probably have to add a hook for it.  Here's a good article on hooks: http://codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth
