### ISSUE TITLE
Get inactive users

### ISSUE THREAD

**Issue by abdhannan** [benedmunds/CodeIgniter-Ion-Auth#1121]
How can we get all inactive user ?I know to get all users, we can use
`$this->ion_auth->users()->result();`
But, I want to filter to retrieve only inactive users

**Comment by benedmunds** [comment]
Should be able to do something like:

$this->ion_auth->where('users.active', 0)->users()->result();

**Comment by abdhannan** [comment]
Thank you so much, Benedmunds.
Great library, great work, i really appreciated

**Comment by benedmunds** [comment]
Thanks!
