### ISSUE TITLE
Forgotton password length

### ISSUE THREAD

**Issue by raptor00** [benedmunds/CodeIgniter-Ion-Auth#1122]
Hello,
There is no error but it sends the new forgotton password with 22 character length to email. are there any adjustment for this length. it is too long i think. I didnt change the main codes.  I think new forgotton password create code doesnt take care the max length password variable in config.

As i see, new pass is created by code 
$password = $this->salt(); 
in function forgotten_password_complete() in Ion_auth_model.php

why the salt code used for new password. in salt code there is a limit 16 char but it doesnt limit i think.

the last code i used is that i copy from help :

	public function reset_password($code)
		{
			$reset = $this->ion_auth->forgotten_password_complete($code);

			if ($reset) {  //if the reset worked then send them to the login page
				$this->session->set_flashdata('message', $this->ion_auth->messages());
				redirect(base_url_lang()."uyegiris", 'refresh');
			}
			else { //if the reset didnt work then send them back to the forgot password page
				$this->session->set_flashdata('message', $this->ion_auth->errors());
				redirect("uye/sifremiunuttum", 'refresh');
			}
		}

Config:

$config['hash_method']    = 'bcrypt';	// sha1 or bcrypt, bcrypt is STRONGLY recommended
$config['default_rounds'] = 8;		// This does not apply if random_rounds is set to true
$config['random_rounds']  = FALSE;
$config['min_rounds']     = 5;
$config['max_rounds']     = 9;
$config['salt_prefix']    = version_compare(PHP_VERSION, '5.3.7', '<') ? '$2a$' : '$2y$';

$config['site_title']                 = "Emlak";       // Site Title, example.com
$config['admin_email']                = ""; // Admin Email, admin@example.com
$config['default_group']              = 'members';           // Default group, use name
$config['admin_group']                = 'admin';             // Default administrators group, use name
$config['identity']                   = 'email';             // You can use any unique column in your table as identity column. The values in this column, alongside password, will be used for login purposes
$config['min_password_length']        = 8;                   // Minimum Required Length of Password
$config['max_password_length']        = 16;                  // Maximum Allowed Length of Password
$config['email_activation']           = TRUE;               // Email Activation for registration
$config['manual_activation']          = FALSE;               // Manual Activation for registration
$config['remember_users']             = TRUE;                // Allow users to be remembered and enable auto-login
$config['user_expire']                = 86500;               // How long to remember the user (seconds). Set to zero for no expiration
$config['user_extend_on_login']       = FALSE;               // Extend the users cookies every time they auto-login
$config['track_login_attempts']       = TRUE;                // Track the number of failed login attempts for each user or ip.
$config['track_login_ip_address']     = TRUE;                // Track login attempts by IP Address, if FALSE will track based on identity. (Default: TRUE)
$config['maximum_login_attempts']     = 5;                   // The maximum number of failed login attempts.
$config['lockout_time']               = 600;                 /* The number of seconds to lockout an account due to exceeded attempts
							        You should not use a value below 60 (1 minute) */
$config['forgot_password_expiration'] = 0;                   // The number of milliseconds after which a forgot password request will expire. If set to 0, forgot password requests will not expire.
$config['recheck_timer']              = 0;                   /* The number of seconds after which the session is checked again against database to see if the user still exists and is active.
							           Leave 0 if you don't want session recheck. if you really think you need to recheck the session against database, we would
								   recommend a higher value, as this would affect performance */
								

$config['remember_cookie_name'] = 'remember_code';
$config['identity_cookie_name'] = 'identity';

$config['use_ci_email'] = TRUE; // Send Email using the builtin CI email class, if false it will return the code and the identity
$config['email_config'] = array(
	'mailtype' => 'html',
);

$config['email_templates'] = 'auth/email/';

$config['email_activate'] = 'activate.tpl.php';

$config['email_forgot_password'] = 'forgot_password.tpl.php';

$config['email_forgot_password_complete'] = 'new_password.tpl.php';

$config['salt_length'] = 22;
$config['store_salt']  = FALSE;

$config['delimiters_source']       = 'config'; 	// "config" = use the settings defined here, "form_validation" = use the settings defined in CI's form validation library
$config['message_start_delimiter'] = '<p>'; 	// Message start delimiter
$config['message_end_delimiter']   = '</p>'; 	// Message end delimiter
$config['error_start_delimiter']   = '<p>';		// Error message start delimiter
$config['error_end_delimiter']     = '</p>';	// Error message end delimiter

**Comment by benedmunds** [comment]
The database password field should be a varchar(255) so this shouldnt matter.  Are you seeing any issues?

**Comment by raptor00** [comment]
The only issue is that customers maybe have difficulty to use long password although they may use once. This length may be better if it is adjustable so I can make another function for just random password instead of salt function. So using salt doesnt have a special meaning right ? If so i will change it.

**Comment by benedmunds** [comment]
They will probably just copy and paste right?  But yea, you could make this configurable.  You could just update it to pass the length to the salt method to get the size you prefer.

I'm going to go ahead and close this since it's not a core library issue.  Thanks!
