### ISSUE TITLE
How i am can make this in twig?

### ISSUE THREAD

**Issue by rekbx** [benedmunds/CodeIgniter-Ion-Auth#1124]
Hello, how can I recreate this code on twig?
` <?php echo form_hidden(array('id'=>$user->id)); ?>`
That's what I did, but it does not work
`  {{ form_hidden(array('id'=>user.id)) }}`

**Comment by benedmunds** [comment]
Hey,

I don't use twig but I don't think you can call the function directly without registering them somehow.  form_hidden is a CI form helper function.  I'd recommend you ask this on either the CI forums or StackOverflow.

Also, issues in GH here are really meant to be for bugs in the core library so I'm closing this issue.

**Comment by TomZdulski** [comment]
A bit late, but to let you know how:
This can be done easly with Twig macro that emulates CI's form helper function, no need to register custom functions.

in file macro.twig :
{% macro hidden(data) %}
    {% if data is iterable %}
            {% for key, val in data %}
                \<input name="{{key}}" value="{{val}}" type="hidden"/>
            {% endfor %}
    {% endif %}
{% endmacro %}

in file template.twig :
{% import 'macro.twig' as form %}
{{ form.hidden(data) }}

and send data = array('id'=>$user->id) from controller to twig as template variable
(this can do as many html inputs as data's array elements an once ;) )

I got basic CI's form_open/close and inputs equivalent macros written, so if you need it , just let me know.

**Comment by benedmunds** [comment]
Awesome, thanks for sharing!
