### ISSUE TITLE
Activate Function

### ISSUE THREAD

**Issue by blalan** [benedmunds/CodeIgniter-Ion-Auth#1125]
Looking through the example Auth controller, I see an activate function, and the the call to the library line 345`$activation = $this->ion_auth->activate($id, $code);`
However, tracing it, I don't see that function in the the library. It does show up in the model line 452. It that how it should be or is the code in the wrong spot?

**Comment by benedmunds** [comment]
The library uses magic method to call the methods in the model if it doesn't exist in the controller.  It allows you to just call everything through the library.

**Comment by blalan** [comment]
That does sound like magic. Awesome thanks!

**Comment by dacalvi** [comment]
That kind of magic is not the best for the ones that read the code.
