### ISSUE TITLE
Create a user session (login) without password

### ISSUE THREAD

**Issue by CodeBrauer** [benedmunds/CodeIgniter-Ion-Auth#1126]
I'm currently working with [hybridauth](http://hybridauth.github.io/hybridauth/) and I'm also using ion_auth for basic email/password register/login.

How can I login a user that has a connected social account. I'm getting a unique token from facebook/twitter to identify the user and create a session - but how can I create a ion_auth-login-session?

The `login()` method only works if I pass the users password. Any ideas, without hacking actually the ion_auth library?

**Comment by benedmunds** [comment]
Hey,

There's a community supported branch with hybridauth integration so I'd recommend you start there:  https://github.com/benedmunds/CodeIgniter-Ion-Auth/tree/social

It's probably a bit out of date, so even if you roll you're own it should be good inspiration.  Also, it'd be awesome if you could contribute any updates back to this branch.
