### ISSUE TITLE
[Question] Where is the $this->ion_auth->where() function

### ISSUE THREAD

**Issue by khalid-mahmood** [benedmunds/CodeIgniter-Ion-Auth#1127]
Where is the $this->ion_auth->where() function i want to make custom changes in logic.?
Can you help me please

**Comment by khalid-mahmood** [comment]
how can i add or_where() like where() ?

**Comment by benedmunds** [comment]
The where clauses are defined in each function that uses them in the model, here's an example for the users() function:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/models/Ion_auth_model.php#L1436

If you want an or_where the best solution is to add a hook for "extra_where" that calls $ci->db->or_where().  Jeff Madsen has a good tutorial on hooks here: http://codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth
