### ISSUE TITLE
Checking logged_in and in_group function

### ISSUE THREAD

**Issue by wendaliu** [benedmunds/CodeIgniter-Ion-Auth#1129]
So in my controller I use this check:

> if ( !$this->ion_auth->logged_in() || !$this->ion_auth->in_group('admin') )
> 		{
> 			if ( $redirect_url==NULL )
> 				$redirect_url = site_url('user/login');> 			
> 			redirect($redirect_url);
> 		}

So logic is if user not logged in and user is not in a certain group they will be redirected.

However when I test this, it seems that the user is redirected anyway, even when they are logged in and do belong in the specified user group.

I'm not sure whether its a logic error or a syntax error, or if its an issue with the ion_auth functions.

Any help is appreciated.

**Comment by benedmunds** [comment]
We'll have to troubleshoot a bit.

Post a db query of your user record, their users_groups record, and their groups records.

Then login via the frontend and post the output of $this->ion_auth->logged_in() and the output of $this->ion_auth->in_group('admin').

**Comment by wendaliu** [comment]
Well OK so I already did some troubleshooting:

Here's the user groups as array:

> Array ( [0] => stdClass Object ( [id] => 1 [name] => admin [description] => Administrator ) [1] => stdClass Object ( [id] => 2 [name] => members [description] => General User ) )

Just the basic default, admin and member groups.

Here's the logged in user array(class object):

> stdClass Object ( [id] => 1 [ip_address] => 127.0.0.1 [username] => administrator [password] => *somepasswordstringhere* [salt] => [email] => admin@admin.com [activation_code] => [forgotten_password_code] => [forgotten_password_time] => [remember_code] => qsY8W7O2eZeH8U3wUX1QGu [created_on] => 1268889823 [last_login] => 1503788389 [active] => 1 [first_name] => Admin [last_name] => istrator [company] => ADMIN [phone] => 0 [user_id] => 1 )

Again default admin user from clean ion auth install.

Also, when testing I echoed the results of ion_auth->logged_in and ion_auth->in_group('admin') and they both echoed out as "1", which i assume means boolean true.

**Comment by wendaliu** [comment]
Also, actually it seems that when I check remember me on login, the above function works as intended and does not redirect me. Not sure what that implies about the login and remember function.

**Comment by benedmunds** [comment]
Hmm so both of the checks in 

    if ( !$this->ion_auth->logged_in() || !$this->ion_auth->in_group('admin') )

Return true yet it's still getting inside the if block?

Maybe try making those explicit?

        if ( $this->ion_auth->logged_in() === FALSE || $this->ion_auth->in_group('admin') === FALSE )

What version of PHP are you running?  Also try in a different browser.

**Comment by wendaliu** [comment]
Ok I will give those a try, and with a different browser.

**Comment by wendaliu** [comment]
Ok after updating the code with the `=== FALSE ` method, nothing has changed. Also nothing changes on a different web browser(I usually use Chrome, so I tried on Microsoft Edge). Still redirects me to login page when I'm logged in and also have admin group, but again after logging out and then logging in with "remember me" checked, the code functions as intended and I am not redirected.

This really confuses me 😭

**Comment by benedmunds** [comment]
That's weird.  The fact that remember me fixes me makes it seem like a session issue.

What version of PHP are you on?

Also, what version of CodeIgniter?

**Comment by wendaliu** [comment]
I believe my host is running PHP 7.0 and I am currently using CI 3.1.5.

**Comment by benedmunds** [comment]
I'm not sure what to tell you actually.  My next step in troubleshooting would be to start dropping code in the library to make sure it's setting the CI session data.  Make sure there's a redirect/refresh after login and before this code runs (so the session can update).  Then maybe try updating CI to the edge stable? https://github.com/bcit-ci/CodeIgniter/tree/3.1-stable

**Comment by wendaliu** [comment]
Actually, you are right it is a session issue. It seems I had accidentally set 2 different session names.

I'm so sorry for wasting your time on this issue, when it wasn't an issue regarding ion_auth.
Hope you'll forgive me 😢

**Comment by benedmunds** [comment]
Oh awesome, glad you found it!  🎉
