### ISSUE TITLE
Implementing this in AJAX!?

### ISSUE THREAD

**Issue by blaasvaer** [benedmunds/CodeIgniter-Ion-Auth#1134]
Hi, I'm seriously having trouble implementing this in an AJAX kind of way. Are there any examples of how to do this?

I've tried wrapping stuff in things like:

```
if(!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') { ...
```
Is this doable at all?

**Comment by benedmunds** [comment]
Is what doable exactly?  I'll need a more detailed example.  

I've used Ion Auth with many sites using ajax with no issues.  Any issues usually come from CodeIgniter's session implementation.  Note that early CI 3.x versions had a known session bug that's since been fixed as well.

**Comment by blaasvaer** [comment]
Yeah, seems I'd modified the file with the above HTTP_X wrapper to fix some other issues ... just had to wrap my head around modifying the edit_user view properly, and only return the form ... thanks.

**Comment by benedmunds** [comment]
Awesome!  Take care
