### ISSUE TITLE
Prevent total page reload when submitting edit_user form via AJAX?

### ISSUE THREAD

**Issue by blaasvaer** [benedmunds/CodeIgniter-Ion-Auth#1135]
How do I prevent a complete page reload when submitting the edit_user form?

I'm doing this:
```
$('body').on('submit', 'form#update_user', function ( e ) {
	e.preventDefault();

	let user_id = $(this).closest('tr').data('user_id'),
		form_data = $(this).serialize();
	$.ajax({
		type: 'POST',
		url: base_url + 'auth/edit_user/' + user_id,
		data: form_data
	}).done(function ( response ) {
	}).fail(function ( err ) {
	});
```

**Comment by benedmunds** [comment]
Add an onclick function that prevents default or returns false to the submit button.   Pretty sure you can do it via jquery as well somehow.

BTW this really isn't the place to ask for help with Javascript, it's meant for errors with the library itself so I'm closing this.  I'd recommend asking questions like that on StackOverflow or some jQuery related forum.

**Comment by blaasvaer** [comment]
Fair enough, but I was just wondering. I've modified the Auth.php controller so heavily now to get around redirect() vs load->view(), that It'd be nearly impossible to update it ... should I ever need to. Is that to be expected, or should it have been written in a more overriding possible manner (or am I just getting it wrong)?

**Comment by benedmunds** [comment]
Nah, the controller and view are just examples for using the library so future upgrades you can just drop in the library and model files.

**Comment by blaasvaer** [comment]
So I guess the redirect() is the issue I'm having (page reload) with the response redirecting and not passing me the markup as a response via AJAX, right?

**Comment by benedmunds** [comment]
Yea probably, if your page is actually redirecting though it's probably the JS cause even if the response was a redirect the JS shouldnt change the page location there.
