### ISSUE TITLE
Confirm email change?

### ISSUE THREAD

**Issue by gienq** [benedmunds/CodeIgniter-Ion-Auth#1141]
Hi,
I have
`$identity = 'nickname'`
as identity column in database, but I store users' emails too. I am not sure, but I couldn't find in Ion auth change_email() method with a feature to confirm change of email. Am I right?
Thanks for the responses.

**Comment by benedmunds** [comment]
You'd need to write your own controller/view code for the confirmation. You can update the email with update()
