### ISSUE TITLE
Does Ion Auth support Multi Authentication ?

### ISSUE THREAD

**Issue by peterson-umoke** [benedmunds/CodeIgniter-Ion-Auth#1142]
Good day, Please i intend to use this library for a very large project... but i would like to know if i can check against multiple tables, in order words, say i am designing an e-commerce system, all admins have different levels, that requires a role authentication system, but the customers and the admins cannot share the same table structure, as such they need their own authentication procedures for the login, logout, register, please does your library support multi-authentication?

**Comment by benedmunds** [comment]
No it doesn’t support this out of the box

-Ben Edmunds
706.289.4115
ben.edmunds@gmail.com

**Comment by peterson-umoke** [comment]
please do you have any ideas as to how i can implement this requirement using this library or any library at all ?

**Comment by benedmunds** [comment]
You could dynamically change the config to use a different table name. You might need to utilize hooks for it as well.

See http://codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth for details on how hooks work with Ion Auth.

-Ben Edmunds
706.289.4115
ben.edmunds@gmail.com

**Comment by peterson-umoke** [comment]
God bless you sir. Thanks so much

**Comment by benedmunds** [comment]
No problem! Make sure to post back once you determine a solution, I’m sure it’ll help someone else in the future.

-Ben Edmunds
706.289.4115
ben.edmunds@gmail.com

**Comment by peterson-umoke** [comment]
Definitely..  will do!

**Comment by benedmunds** [comment]
Closing for now.  Hope to see a solution soon!
