### ISSUE TITLE
error_csrf in edit user form when call Ajax function

### ISSUE THREAD

**Issue by immodor** [benedmunds/CodeIgniter-Ion-Auth#1143]
I have erreur_csrf in edit user form when call function Ajax drop down for Country State & City.
I have the same error with

$config['csrf_protection'] = FALSE;

And

$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array('dashboard/get_city/.*+','dashboard/get_city/[0-9]+');

Can you help me on that?
Thank you.

**Comment by benedmunds** [comment]
What’s the error?

**Comment by immodor** [comment]
When i submit the form of edit user i have this error  "This form post did not pass our security checks." but only when i change drop-down of country who it call an ajax function {dashboard/get_city/[0-9]+} to update a drop-down of list of city,
and when i don't change de drop-down of country and they are not a call to this ajax function, the submit form is ok, and the user information are update

Thank you for you help.

**Comment by avenirer** [comment]
I don't think this is related to Ion Auth... Most likely this is happening because your csrf inside the session changes the moment you do a query for the city, and your csrf inside the main form stays the same.

**Comment by benedmunds** [comment]
@immodor agreed with @avenirer this doesnt look to be related to Ion Auth.  You'll need to change the way you're handling the CSRF tokens.  There are some ideas on StackOverflow, here's what I found from a quick google search:

https://stackoverflow.com/questions/7348383/codeigniter-ajax-csrf-problem


The gist of what you'll need to do is return a new CSRF token with the AJAX request and update the token in your form to the new one.

**Comment by immodor** [comment]
@benedmunds  why you closed this issue without having a solution to this problem !!!!!

I knew it was an error due to ajax and csrf when regenerating request for city of country.
I'm looking good in google but no response to this problem, 

I thought to find a solution here

I have the same error with
$config['csrf_protection'] = FALSE;
And
$config['csrf_protection'] = TRUE;

Thank you for your help.

**Comment by benedmunds** [comment]
I closed the issue because this is for tracking issue with the Ion Auth library.  Not for providing CodeIgniter support.

I gave you some things to try above but I'd recommend you post on the CI forums or StackOverflow if you can't work out a solution from here.

**Comment by immodor** [comment]
@avenirer I totally agree with you, but the solution is what?
I use your tutorial in your site to develop my project, but here I'm in a dead end for 3 days,
can you help me,
Thank you.

**Comment by immodor** [comment]
@benedmunds Is there a way to disable [csrf-protection] in ion_auth ? just to continue developing  my project, and see later the solution to this problem.
Thank you.

**Comment by benedmunds** [comment]
First you’d need to determine if it’s the CI wide CSRF or the one from the example Ion Auth controller. If it’s from the Ion Auth one just remove the code from the controller. If it’s the CodeIgniter one you’ll need to reference their docs but I think that config flag you referenced above is it.

**Comment by immodor** [comment]
It's from the Ion Auth, i will remove the code from the controller, and see if de problem persist, 
Thank you.
From CI i have put :
$config['csrf_protection'] = FALSE;

**Comment by immodor** [comment]
@benedmunds Thank you for your help.
I have change the code of CSRF from the controller :

if ($this->_valid_csrf_nonce() === FALSE || $id != $this->input->post('id')) {
                show_error($this->lang->line('error_csrf'));

to this one 

if ($id != $this->input->post('id')) {
                show_error($this->lang->line('error_csrf'));

and From CI config i have put :
$config['csrf_protection'] = TRUE;

Now it's OK 👍

**Comment by benedmunds** [comment]
Awesome 👍
