### ISSUE TITLE
Count users in groups

### ISSUE THREAD

**Issue by federicovilla** [benedmunds/CodeIgniter-Ion-Auth#1145]
Not an issue, just wondering if there is a way to count users in each group using $this->ion_auth->groups()->result()
Thanks

**Comment by benedmunds** [comment]
I don’t think there’s a good way via the API but a query like this should do it:

Select count(*) as count, group_id from users_groups group by group_id

**Comment by federicovilla** [comment]
Thanks a lot Ben
