### ISSUE TITLE
The second time I update user – Error: This form post did not pass our security checks.

### ISSUE THREAD

**Issue by sabsaxo** [benedmunds/CodeIgniter-Ion-Auth#1147]
I edit a user via AJAX by POSTing the form (to 'auth/edit_user/') and reinject the returned for again.

But the second time I edit the user, the server responds with an error:

`This form post did not pass our security checks.`

I can see that the hidden field with the secret name attribute get updated with the returned form.

Now, how do I make sure that nothing breaks, when I POST the form again (and again, and again if needed)?

**Comment by benedmunds** [comment]
Here's a recent discussion of this issue:

https://github.com/benedmunds/CodeIgniter-Ion-Auth/issues/1143

Hopefully it helps.

**Comment by benedmunds** [comment]
Closing since the answer should be in the above post.  Feel free to reopen or ping me if it doesn't.  Take care!

**Comment by blaasvaer** [comment]
Comment out these lines in Auth.php:

```
if ( ( $this->_valid_csrf_nonce() === FALSE || $id != $this->input->post('id') ) ) {
	show_error($this->lang->line('error_csrf'));
}
```

And enable CSRF protection in application/config/config.php:

From:
`$config['csrf_protection'] = FALSE;`

To:
`$config['csrf_protection'] = TRUE;`

*Not absolutely sure this is the 'right' way (if such exist), but it works ...*
