### ISSUE TITLE
I can edit Users as non admin?

### ISSUE THREAD

**Issue by blaasvaer** [benedmunds/CodeIgniter-Ion-Auth#1150]
It seems I can edit Users even though I'm not logged in as an admin – or am I doing something wrong (is this by design)?

I've created two users who are in different groups; admin_group is set to be 'admin' in the config.

I also have a plain 'user' group. Now when I log in as a plain user, I can still do edit_user stuff?

I think there's 'something' wrong with this line of code:

```
if ( ! $this->ion_auth->logged_in() || ( ! $this->ion_auth->is_admin() && !( $this->ion_auth->user()->row()->id == $id ) ) ) {
```
Or am I reading this wrong?

**Comment by benedmunds** [comment]
Really the controller is yours to make do whatever you want.  It's just there as an example of how to use the library.  The library itself doesn't stop you from letting non-admin users edit.

The above logic should stop users that aren't admins from editing any users except themselves.

**Comment by blaasvaer** [comment]
OK, just had the wrong impression then, thanks.
