### ISSUE TITLE
Test email activation?

### ISSUE THREAD

**Issue by gegere** [benedmunds/CodeIgniter-Ion-Auth#1162]
Does this still need to be tested? I have the ability to test this completely over the weekend and would like to give feedback / updates if needed.

https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/14b2d2c58adf883ed584afbd56f2cd296d2a5742/libraries/Ion_auth.php#L306

**Comment by benedmunds** [comment]
Ah thanks but it’s been tested and looks like I forgot to remove this comment
