### ISSUE TITLE
While resetting Password or change Password, user should not use previous password

### ISSUE THREAD

**Issue by Premgupta01** [benedmunds/CodeIgniter-Ion-Auth#1164]
while I was working on My CI Project for client my QA suggested that User shouldn't be able to use the previous password while resetting or Change password

I have tried to fix this and also added it to my Project, If you allow me to add this So I would like to help for the same

**Comment by gegere** [comment]
I'd suggest creating a pull request with the updates. This way the code and permissions of the repo can be maintained properly.
