### ISSUE TITLE
Bcrypt lib used when password_hash exists since PHP 5.5.0

### ISSUE THREAD

**Issue by To-mos** [benedmunds/CodeIgniter-Ion-Auth#1169]
Out of curiosity is there a specific reason this package is using a dedicated Bcrypt lib utilizing `crypt` and `hash_equals` supporting PHP 5.6.0 when `password_hash` and  `password_verify` have existed since 5.5.0 and up and do basically the same thing. Is one better than the other?

**Comment by benedmunds** [comment]
This was implemented before password_hash() or password_verify() were added.  Which also gives us support for back to PHP 5.3 I believe (I'd have to run some tests to be sure of that).

Also it's worth noting, password_hash() is just a wrapper around crypt() so we aren't losing anything by using crypt directly.  See notes near the top of this page http://php.net/manual/en/function.crypt.php

**Comment by bkader** [comment]
Even inside system/core/ there a compatibility file named password I guess.

**Comment by benedmunds** [comment]
Good point, I'm not against using those functions if someone wants to refactor it (as long as it keeps backwards compatibility).  I don't think there's much to gain there but it would simplify things.
