### ISSUE TITLE
Forgotten password link in email

### ISSUE THREAD

**Issue by federicovilla** [benedmunds/CodeIgniter-Ion-Auth#1170]
Sorry for the dumb question...but I'm not able to figure out how to set the "Reset your password" link in email received by the user in case of forgotten password.
The forgot_password method in Auth controller uses the following line:
```
$forgotten = $this->ion_auth->forgotten_password($identity->{$this->config->item('identity', 'ion_auth')});
```
to send the email but I cannot find a way to set the email url, this points to auth/reset_password method, but in my server I set up a different one.
If I'm not wrong there is no config entry for this in configuration file.
Thanks

**Comment by federicovilla** [comment]
Silly me! It was in template email!!

**Comment by benedmunds** [comment]
No worries, glad you found it :D
