### ISSUE TITLE
Ion Auth and AJAX Datatables

### ISSUE THREAD

**Issue by federicovilla** [benedmunds/CodeIgniter-Ion-Auth#1172]
Working with AJAX Datatables and Codeigniter I'm in the need to draw a users table but I'm not able to figure out how to set some data required by Datatables.
In details I need to perform some search in Ion Auth users using limit, start, column, direction (ASC-DESC) and search field (search filed could be username, first name, last name or usermail )
About limit and start I found a previous thread so now I know I could use limit and offset in Ion Auth, like:
`$rows = $this->ion_auth->limit($limit)->offset($start)->users()->result();`

Any help about column, direction and search data?
Thanks a lot

**Comment by benedmunds** [comment]
For the order you can use

    $this->ion_auth->order_by($column, $direction)

https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/models/Ion_auth_model.php#L1420



For the columns you can select with

    $this->ion_auth->select($columns)

https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/models/Ion_auth_model.php#L1405
