### ISSUE TITLE
Lang file

### ISSUE THREAD

**Issue by federicovilla** [benedmunds/CodeIgniter-Ion-Auth#1173]
I realized that in language folder there are two files: ion_auth_lang.php and auth_lang.php: I'm wondering what's the purpose of having two files...do I need to load both in my controllers?
Since in the italian file there are lots of untranslated sentences...can I submit a correct italian version?

**Comment by benedmunds** [comment]
The ion Auth Lang file is for the core library messages.

The Auth Lang file is for the example messages.

I’d really appreciate a PR with updated translations.

**Comment by federicovilla** [comment]
Thanks a lot for your time and invaluable support
