### ISSUE TITLE
Bcrypt not works at PHP7.0+

### ISSUE THREAD

**Issue by jjur** [benedmunds/CodeIgniter-Ion-Auth#1176]
I have upgraded server to PHP7.1 and cannot sign in. I tied also 7.0 and 7.2. All versions with the same error.

> A PHP Error was encountered
> Severity: 8192
> Message: crypt(): Supplied salt is not valid for DES. Possible bug in provided salt format.
> Filename: libraries/Bcrypt.php
> Line Number: 40
> Backtrace:
> File: /nfsmnt/hosting2_2/8/4/845faa92-38a1-46de-8cc0-83667e6a48b7/labak.net/web/application/libraries/Bcrypt.php
> Line: 40
> Function: crypt 
> File: /nfsmnt/hosting2_2/8/4/845faa92-38a1-46de-8cc0-83667e6a48b7/labak.net/web/application/models/Ion_auth_model.php
> Line: 320
> Function: verify 
> File: /nfsmnt/hosting2_2/8/4/845faa92-38a1-46de-8cc0-83667e6a48b7/labak.net/web/application/models/Ion_auth_model.php
> Line: 1005
> Function: hash_password_db 
> File: /nfsmnt/hosting2_2/8/4/845faa92-38a1-46de-8cc0-83667e6a48b7/labak.net/web/application/libraries/Ion_auth.php
> Line: 104
> Function: login 
> File: /nfsmnt/hosting2_2/8/4/845faa92-38a1-46de-8cc0-83667e6a48b7/labak.net/web/application/controllers/System.php
> Line: 85
> Function: __call 
> File: /nfsmnt/hosting2_2/8/4/845faa92-38a1-46de-8cc0-83667e6a48b7/labak.net/web/index.php
> Line: 315
> Function: require_once `

**Comment by benedmunds** [comment]
If you generate a new password does it work?

**Comment by just-vicu** [comment]
Hey benedmuds,

maybe you should remove Bcrypt library and use native password_hash function instead?

**Comment by benedmunds** [comment]
Yea it's probably worth it, at least for the needs rehash functionality.

Anyone want to take a crack at a PR for it?

**Comment by franksierra** [comment]
I'm just implementing ion_auth in a project i am working on and notice the use of the Bcrypt library. Then came here to se if it was any reason to use it instead of the native function.
I will be pushing a PR when i'm done.

**Comment by benedmunds** [comment]
I lay out the reasons here: https://github.com/benedmunds/CodeIgniter-Ion-Auth/issues/1169

To recap with a couple clarifications:
This was implemented before password_hash() or password_verify() were added to PHP. Which also gives us support for back to PHP 5.3 I believe (I'd have to run some tests to be sure of that).

Also it's worth noting, password_hash() is just a wrapper around crypt() so we aren't losing anything by using crypt directly (which is what the current BCrypt lib does). See notes near the top of this page http://php.net/manual/en/function.crypt.php

**Comment by benedmunds** [comment]
That being said.  At this point I'm not against using the password hash functions (and maybe backfilling with https://github.com/ircmaxell/password_compat).

**Comment by xie-yang** [comment]
Hello 
Thank you for your wonderful library in advance.
I have a question about library working.
Code flow like this.
After user login in login page, I check usergroup and redirect to 3 kinds of contents.
			if ($this->ion_auth->login($this->input->post('identity'), $this->input->post('password'), $remember))
			{
				$this->session->set_flashdata('message', $this->ion_auth->messages());
                $user_groups = $this->ion_auth->get_users_groups()->result();
                $grpname = $user_groups[0]->name;
                if( $grpname == 'admin' ) {
                    redirect(base_url('index.php/admin'), 'refresh');
                } else if($grpname == 'buyer') {
                    redirect(base_url('index.php/buyer'), 'refresh');
                } else {
                    redirect(base_url('index.php/supplier'), 'refresh');
                }
			}
I logged in as buyer and I checked if it is redirected to 'index.php/buyer' correctly.
In redirected page, I check again if user is logged in.
Here is an error.
User just logged in and redirect but 
        if (!$this->ion_auth->logged_in())
        {
            redirect(base_url('index.php/auth/login'), 'refresh');
        } else {
            $this->load->view('buyer_interest');
        }
this codes goes to login page.
More wired thing is it works correctly on my local sever but it shows error on my remote server.
I cant find what is error.
Hope your kind reply.

Thank you.

**Comment by benedmunds** [comment]
Maybe some type of session/cookie issue?  If you write your own troubleshooting code to set data in the session is it there after the redirect?

**Comment by xie-yang** [comment]
Thank you for your reply.
I havent write any own session setting code.
I'm using your login function and only add redirect code.

**Comment by benedmunds** [comment]
Right, so try that and see what happens as a means of troubleshooting.

**Comment by xie-yang** [comment]
This is whole login function
`	public function login()
	{
		$this->data['title'] = $this->lang->line('login_heading');

		// validate form input
		$this->form_validation->set_rules('identity', str_replace(':', '', $this->lang->line('login_identity_label')), 'required');
		$this->form_validation->set_rules('password', str_replace(':', '', $this->lang->line('login_password_label')), 'required');

		if ($this->form_validation->run() === TRUE)
		{
			// check to see if the user is logging in
			// check for "remember me"
			$remember = (bool)$this->input->post('remember');

			if ($this->ion_auth->login($this->input->post('identity'), $this->input->post('password'), $remember))
			{
				$this->session->set_flashdata('message', $this->ion_auth->messages());
                $user_groups = $this->ion_auth->get_users_groups()->result();
                $grpname = $user_groups[0]->name;
                if( $grpname == 'admin' ) {
                    redirect(base_url('index.php/admin'), 'refresh');
                } else if($grpname == 'buyer') {
                    redirect(base_url('index.php/buyer'), 'refresh');
                } else {
                    redirect(base_url('index.php/supplier'), 'refresh');
                }
			}
			else
			{
				// if the login was un-successful
				// redirect them back to the login page
				$this->session->set_flashdata('message', $this->ion_auth->errors());
                $this->load->view('auth/login', array('message'=>'Input email and password','identity'=>'identity','password'=>'password'));
			}
		}
		else
		{
			// the user is not logging in so display the login page
			// set the flash data error message if there is one
			$this->data['message'] = (validation_errors()) ? validation_errors() : $this->session->flashdata('message');

			$this->data['identity'] = array('name' => 'identity',
				'id' => 'identity',
				'type' => 'text',
				'value' => $this->form_validation->set_value('identity'),
			);
			$this->data['password'] = array('name' => 'password',
				'id' => 'password',
				'type' => 'password',
			);

			$this->_render_page('auth/login', $this->data);
		}
	}
`
And this is other controller
`    public function index()
    {
        if (!$this->ion_auth->logged_in())
        {
            redirect(base_url('index.php/auth/login'), 'refresh');
        } else {
            $this->load->view('buyer_interest');
        }
    }
`
Why its not working only on remote server?

**Comment by benedmunds** [comment]
I don't know.  You're going to have to spend some time to troubleshoot this.  I'd recommend starting with looking for a session / cookie issue.

**Comment by xie-yang** [comment]
Ok.
Thank you for your time.

**Comment by Salman937** [comment]
Hi every one,

I am facing a problem when login. I am not logging to dashboard when both email and password are correct. I checked everything but all are ok when I remove from Ion_auth_model.php. when i print_r($password) it show nothing.
 if ($password === TRUE)
 {
 }

it's now logging where is the problem can anyone help me out.

**Comment by ariandi22** [comment]
Excuse me, is this github or stackoverflow? Oooh my goodness, That's right, this is Github. Thank you.

**Comment by deevannaveed** [comment]
@benedmunds I have two implementations of Ion_auth, one for admin and one for front-end, now I want the admin to be able to change user's passwords so I am generating passwords for the users using `$this->ion_auth->hash_password("testtest");` but with this password I am not able to login as user, can you tell me what can be the problem or how can I do that? Thanks.

**Comment by benedmunds** [comment]
@deevannaveed do your configs match?  and can you post the parts of your config that are relevant to hashing?

**Comment by deevannaveed** [comment]
@benedmunds  thanks for your reply, following is the config and in both configs its the same.

`$config['hash_method']    = 'bcrypt';	// sha1 or bcrypt, bcrypt is STRONGLY recommended
$config['default_rounds'] = 8;			// This does not apply if random_rounds is set to true
$config['random_rounds']  = FALSE;
$config['min_rounds']     = 5;
$config['max_rounds']     = 9;
$config['salt_prefix']    = version_compare(PHP_VERSION, '5.3.7', '<') ? '$2a$' : '$2y$';`

**Comment by deevannaveed** [comment]
@benedmunds I used it like this `$this->ion_auth->hash_password("testtest", null);` and now it worked, which means that its taking the `null` salt from the database and using that as well even if  `$config['store_salt']  = FALSE;`.

**Comment by deevannaveed** [comment]
@benedmunds the problem was here at my side. Sorry!

**Comment by benedmunds** [comment]
No worries, take care!

**Comment by ghost** [comment]
Was this ever tackled for us PHP 7 users?

**Comment by benedmunds** [comment]
@CryptoCurrencyFreak what problem are you facing with PHP 7?

**Comment by Indigo744** [comment]
Just to chime in: it works perfectly fine for PHP 7.0 and 7.1. i've been using it without issue.

**Comment by lalithsagar03** [comment]
crypt(): Supplied salt is not valid for DES. Possible bug in provided salt format. can anyone help me to resolve the issue?

**Comment by Indigo744** [comment]
Please drop IonAuth 2 and upgrade to IonAuth 3.

**Comment by lalithsagar03** [comment]
yeah,ok
