### ISSUE TITLE
forgotten_password fails on call to affected_rows

### ISSUE THREAD

**Issue by VikR0001** [benedmunds/CodeIgniter-Ion-Auth#1178]
On my CI 3 installation, in ion_auth_model, function forgotten_password:

`$return = $this->db->affected_rows() == 1;`

...always returns false, because affected_rows()  always returns -1, even when the sql query is successful.

**Comment by benedmunds** [comment]
Sounds like a possible CodeIgniter issue.  I'd recommend posting on their forums along with your database info, server info, and steps to reproduce.

**Comment by VikR0001** [comment]
Okay, thanks.
