### ISSUE TITLE
forgotten_password_check

### ISSUE THREAD

**Issue by araujo0205** [benedmunds/CodeIgniter-Ion-Auth#1180]
I have seen in the sample code and there is a forgot_password_check () function to check the key sent in the email. But in the documentation of the site http://benedmunds.com/ion_auth/ does not have this function.

**Comment by benedmunds** [comment]
Thanks!  I just pushed an update to the docs for this

**Comment by araujo0205** [comment]
Thanks

**Comment by simmonspaul** [comment]
I see the call from Auth.php...
		$user = $this->ion_auth->forgotten_password_check($code);
but not the actual function in ion_auth_model ? ie. public function forgotten_password_check($code)

Am I following correctly?

**Comment by simmonspaul** [comment]
sorry found it, right where it was supposed to be in Ion_auth. thanks.
