### ISSUE TITLE
How To get User id After Registration ? 

### ISSUE THREAD

**Issue by romandahidayat** [benedmunds/CodeIgniter-Ion-Auth#1181]
Hello Im was read documentation but im not found the way, how to get user id after registration , where i can get user id after registration . thanks.

**Comment by benedmunds** [comment]
The register() method returns the user's ID if successful, it returns false if its not.

**Comment by romandahidayat** [comment]
```
if ($this->form_validation->run() == true && $this->ion_auth->register($identity, $password, $email, $additional_data)) {
            var_dump( $this->ion_auth->register($identity, $password, $email, $additional_data));
        }

```
$id= $this->ion_auth->register($identity, $password, $email, $additional_data);
					 if ($id) {
					 	var_dump($id);
					 }

i was try but return is blank sir ?

**Comment by benedmunds** [comment]
in the above you'd be registering the same user twice so the second will fail

**Comment by romandahidayat** [comment]
thanks sir @benedmunds ill try again sir, dont close this thread before...

**Comment by cnamex** [comment]
You can try this.: **data['id'] have the id**



```
if ($this->form_validation->run() === TRUE) {
                $data = $this->ion_auth->register($identity, $password, $email,$additional_data);
                if ($data) {
                var_dump(data['id']);
                 }
}
```

**Comment by romandahidayat** [comment]
this is a example register function result is Blank
```
if ($this->form_validation->run() == true && $this->ion_auth->register($identity, $password, $email, $additional_data)) {
            var_dump( $this->ion_auth->register($identity, $password, $email, $additional_data));
        }

```
but if code like this Result Is last **User ID** 
```
if ($this->form_validation->run() == true ) {
$id =$this->ion_auth->register($identity, $password, $email, $additional_data)
            var_dump($id); 
        }
```
@benedmunds  thanks a lot sir...
@cnamex nice one...

problem solved....
