### ISSUE TITLE
Ion_auth: Cannot call constructor

### ISSUE THREAD

**Issue by PedroRuiz** [benedmunds/CodeIgniter-Ion-Auth#1182]
Dear:
This is the situation:

**In controllers/Auth.php**:
`<?php defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Class Auth
 * @property Ion_auth|Ion_auth_model $ion_auth        The ION Auth spark
 * @property CI_Form_validation      $form_validation The form validation library
 */
class Auth extends CI_Controller
{

	public function __construct()
	{
		parent::__construct();
		$this->load->database();
		
		/*//
		* I did declared in autoload.php
		* 2018-01-26
		*/
		//$this->load->add_package_path(APPPATH.'third_party/ion_auth/');

		$this->load->library(array('ion_auth', 'form_validation'));
		$this->load->helper(array('url', 'language'));

		$this->form_validation->set_error_delimiters($this->config->item('error_start_delimiter', 'ion_auth'), $this->config->item('error_end_delimiter', 'ion_auth'));

		$this->lang->load('auth');
	}`

**In config/autoload.php**
`/*
| -------------------------------------------------------------------
|  Auto-load Packages
| -------------------------------------------------------------------
| Prototype:
|
|  $autoload['packages'] = array(APPPATH.'third_party', '/usr/local/shared');
|
*/
$autoload['packages'] = array(APPPATH.'third_party/ion_auth/');

/*
| -------------------------------------------------------------------
|  Auto-load Libraries
| -------------------------------------------------------------------
| These are the classes located in system/libraries/ or your
| application/libraries/ directory, with the addition of the
| 'database' library, which is somewhat of a special case.
|
| Prototype:
|
|	$autoload['libraries'] = array('database', 'email', 'session');
|
| You can also supply an alternative library name to be assigned
| in the controller:
|
|	$autoload['libraries'] = array('user_agent' => 'ua');
*/
$autoload['libraries'] = array('database','session','email','migration');`

In config/migration.php
`/*
|--------------------------------------------------------------------------
| Migration Type
|--------------------------------------------------------------------------
|
| Migration file names may be based on a sequential identifier or on
| a timestamp. Options are:
|
|   'sequential' = Sequential migration naming (001_add_blog.php)
|   'timestamp'  = Timestamp migration naming (20121031104401_add_blog.php)
|                  Use timestamp format YYYYMMDDHHIISS.
|
| Note: If this configuration value is missing the Migration library
|       defaults to 'sequential' for backward compatibility with CI2.
|
*/
$config['migration_type'] = 'sequential';

/*
|--------------------------------------------------------------------------
| Migrations table
|--------------------------------------------------------------------------
|
| This is the name of the table that will store the current migrations state.
| When migrations runs it will store in a database table which migration
| level the system is at. It then compares the migration level in this
| table to the $config['migration_version'] if they are not the same it
| will migrate up. This must be set.
|
*/
$config['migration_table'] = 'migrations';

/*
|--------------------------------------------------------------------------
| Auto Migrate To Latest
|--------------------------------------------------------------------------
|
| If this is set to TRUE when you load the migrations class and have
| $config['migration_enabled'] set to TRUE the system will auto migrate
| to your latest migration (whatever $config['migration_version'] is
| set to). This way you do not have to call migrations anywhere else
| in your code to have the latest migration.
|
*/
$config['migration_auto_latest'] = TRUE;`

Then, I get:

![captura de pantalla de 2018-01-26 14-40-39](https://user-images.githubusercontent.com/6648808/35442336-34a10c62-02a7-11e8-9623-74e6d7c2c0a7.png)

The database is created, and migration is all Ok.

Best regards
Pedro

**Comment by benedmunds** [comment]
What version PHP and CI are you running?

Please make sure Ion Auth is updated to the latest version in GH.

If you load the package in the controller instead of autoloading do you get the same results?

**Comment by avenirer** [comment]
I don't know if here is the problem (I never used a library as third party...), but shouldn't this: ``$autoload['packages'] = array(APPPATH.'third_party/ion_auth/');`` be ``$autoload['packages'] = array(APPPATH.'third_party/ion_auth');``

**Comment by PedroRuiz** [comment]
PHP Version 7.0.27
and
 CodeIgniter Version 3.2.0-dev

**Comment by benedmunds** [comment]
Are you using the latest Ion Auth from Github?

If you load the package in the controller instead of autoloading do you get the same results?

**Comment by PedroRuiz** [comment]
Yes, I got the same.

**Comment by benedmunds** [comment]
I'd recommend falling back to the last stable version of CI (3.1.0-stable).  There's an issue with develop, it doesnt have the constructor method defined for CI_Model.  I've commented on the related issue here: https://github.com/bcit-ci/CodeIgniter/issues/5332

**Comment by PedroRuiz** [comment]
avenirer, Same result :-(

**Comment by avenirer** [comment]
Yes, @benedmunds is right. You should get a stable version of CI and not the dev branch. 3.1.7 seems ok.

**Comment by benedmunds** [comment]
@PedroRuiz the 2 branch has been updated to support CI 3.2.x after discussions with Narf.  The CI_Model change was intentional on his side so updating Ion Auth to be compatible.

**Comment by PedroRuiz** [comment]
Thanks a lot @benedmunds !!!

I prefer a nephritic colic to not knowing why an error occurs. Thanks too to all people whom did help me!

**Comment by PedroRuiz** [comment]
All go fine! @benedmunds
