### ISSUE TITLE
Converting an existing user table to $config['store_salt']  = TRUE;

### ISSUE THREAD

**Issue by hquadrat** [benedmunds/CodeIgniter-Ion-Auth#1186]
Hello,

I have an exisiting user table with some 260 entries. I now changed the configuration to $config['store_salt']  = TRUE; due to reasons ;-) .

- if I set the password for an exisiting user, no salt is generated or stored (field content for salt column is NULL and stays NULL). The password hash is changed but the user **can not** log in.
- if I create a new user, a salt is generated and the password hash is stored; the user **can** log in.

What could be the recommended way the get salts generated for the exisiting users and afterwards set their passwords (to a default)? Some 'write yourself a batch' or any idea?

Rgds,

Henning

**Comment by benedmunds** [comment]
What hashing algo are you using?  Salts should only be stored in the separate field for SHA1 and that's really not recommended anyway.  BCrypt stores the salt as well but stores it in the password field.

**Comment by hquadrat** [comment]
We use SHA1 indeed, maybe we can switch to BCrypt; I'll discuss with the colleagues. Meanwhile I'll figure out how to handle that with a little script. Thanks, Ben!
