### ISSUE TITLE
Is it possible to create sub-groups?

### ISSUE THREAD

**Issue by dlzi** [benedmunds/CodeIgniter-Ion-Auth#1225]
I'm wondering if it's possible to great users sub-groups or anything similar. 

I found this answer [https://stackoverflow.com/questions/14953219/how-to-create-sub-groups-in-ion-auth-codeigniter](https://stackoverflow.com/questions/14953219/how-to-create-sub-groups-in-ion-auth-codeigniter) but I don't think it would apply for my case. I still think that I need to have separete accounts, but under one main account.

**Comment by benedmunds** [comment]
Sounds like you might want full ACL.  There's a user made package for that here: https://github.com/weblogics/Codeigniter-Ion-Auth-ACL

Fair warning though, I've never used this package.
