### ISSUE TITLE
Unused properties 

### ISSUE THREAD

**Issue by ghost** [benedmunds/CodeIgniter-Ion-Auth#1230]
I noticed that Ion Auth library and model have a few declared properties that aren't used anywhere in the code. Like:

    protected $status;
    public $_extra_set = [];
    public $new_password;

Is there are reason for that or is it just my weak OOP understanding?

**Comment by benedmunds** [comment]
Good catch, I don’t believe these are used anymore either.  Want to make a PR removing them?

**Comment by dlzi** [comment]
I cannot promise anything soon, but I'll try. Thank you.

**Comment by benedmunds** [comment]
Closing due to age, we'll make sure to take care of this with v4.  Thanks!
