### ISSUE TITLE
Message: Authentication failed! Google returned an error: access_denied in hybridauth

### ISSUE THREAD

**Issue by cdmathukiya** [benedmunds/CodeIgniter-Ion-Auth#1231]
when i am trying to login in google and i am giving permission then it's login and working fine.

![](https://i.stack.imgur.com/E37Lj.png)

But, i am click on cancel button on permission popup it will give error like 

![](https://i.stack.imgur.com/zbE8V.png)

**Comment by benedmunds** [comment]
@cdmathukiya are you on the "social" branch?  are you still seeing this issue?

**Comment by benedmunds** [comment]
Closing due to age, tag me if this is a still an issue and I'll reopen.

**Comment by cdmathukiya** [comment]
hello @benedmunds ,
yes, still getting this issue

**Comment by benedmunds** [comment]
@cdmathukiya reopening, can you answer the above questions please.

**Comment by benedmunds** [comment]
Closing due to age, @cdmathukiya when you get time to help I'll be happy to reopen.  Thanks!
