### ISSUE TITLE
Ion Auth session with Redis

### ISSUE THREAD

**Issue by romandahidayat** [benedmunds/CodeIgniter-Ion-Auth#1232]
Hello ben,  iwant to little ask how to integrated ion auth session to redis im using predis library..
thanks..little comment cant be help..

**Comment by aphofstede** [comment]
@romandahidayat Have you tried to set `sess_driver` to `redis`? Do you run in to Ion auth related issues then?

**Comment by romandahidayat** [comment]
@aphofstede im no yet tried to sess_driver to redis,btw any some example for this case?

**Comment by benedmunds** [comment]
Closing due to age, this is really a question for the CodeIgniter forums since it's not Ion Auth specific.  Hope you got it sorted though :D
