### ISSUE TITLE
Windows local machine directory separator

### ISSUE THREAD

**Issue by bedrijfsportaal** [benedmunds/CodeIgniter-Ion-Auth#1234]
Goodmorning,

I'm using ion_auth for the very first time, must say it's awesome with enough features buildin. The only issue i'm currently facing is the directory separator, it's not responding to / but only on \\.

Can easly fix this by adding `DIRECTORY_SEPARATOR` instead of hard-coded, don't know if it's overrided when updated so i can start all over again?

**CodeIgniter Ion Auth default**
`$this->_render_page('auth/index', $this->data);`

**My current fix (works)**
`$this->_render_page('auth' . DIRECTORY_SEPARATOR . 'index', $this->data);`

Should this be updated as by request on this repository or will this be added, don't know if it's by default on server settings or only when activated.

Thanks in Advance!

**Comment by benedmunds** [comment]
Are you on Windows?

**Comment by bedrijfsportaal** [comment]
Correct, working on my local machine with MAMP PRO before pushing this to a web-server.

**Comment by benedmunds** [comment]
Ah that makes sense.  Would you be interested in submitting a PR for these changes?

**Comment by bedrijfsportaal** [comment]
Shure no problem at all, will do this in a few seconds!
