### ISSUE TITLE
Login with Google

### ISSUE THREAD

**Issue by hugomiura** [benedmunds/CodeIgniter-Ion-Auth#1240]
Does anyone has a login with Google example with Ion Auh?

**Comment by benedmunds** [comment]
I don't off hand.  Looks like HybridAuth works with Google: https://hybridauth.github.io/providers.html

You can use the (not officially supported) social branch of Ion Auth to get started with HybridAuth integration: https://github.com/benedmunds/CodeIgniter-Ion-Auth/tree/social
