### ISSUE TITLE
Pagination data users_groups ?

### ISSUE THREAD

**Issue by merakinoya** [benedmunds/CodeIgniter-Ion-Auth#1242]
Dear, Ben
I want to display data between tables users with tabels groups with pagination underneath how to do?
I implement it with tables of users as "lowongan" and tables groups as "industri" ?

the code model like this

`public function fetch_jobs($limit, $start)
		{
			$this->db->limit($limit, $start);
			$this->db->select('l.*');
			$this->db->select('i.*');
			$this->db->from('lowongan_industri AS li');
			$this->db->join('lowongan AS l', 'l.id = li.lowongan_id');
			$this->db->join('industri AS i', 'i.id = li.industri_id');
			
			$query = $this->db->group_by('li.id')->order_by('l.created_on', 'desc')->get();
			
			if ($query->num_rows() > 0)
			{
				foreach ($query->result() as $row)
				{
					$data[] = $row;
				}
				return $data;
			}
			return FALSE;
		}`

**Comment by benedmunds** [comment]
Ion Auth has limit and offset methods so you can use something like this:

    $this->ion_auth->limit(100)->offset(100)->users();

**Comment by merakinoya** [comment]
It just for users tables ? How if to users tables and groups tables ?

Like this what you mean?

`$this->data['users'] = $this->job_industry->limit(100)->offset(100)->users()->result();
foreach ($this->data['users'] as $k => $user)
{
$this->data['users'][$k]->groups = $this->job_industry->get_users_groups($user->id)->result();
}`

**Comment by benedmunds** [comment]
Yes something similar to that should work, assuming job_industry is what you have the ion_auth library loaded as.

Limit and Offset work for group listing as well:
    `$this->ion_auth->limit(100)->offset(100)->groups()->result()`

**Comment by merakinoya** [comment]
Oh ok thankyou mas Ben, solved from [https://github.com/benedmunds/CodeIgniter-Ion-Auth/issues/347](url)

**Comment by merakinoya** [comment]
Dear ben, i'm sorry ask again,

How to get user data from goup member ?
if i have SQL like this ?
`SELECT g.group_name, GROUP_CONCAT(u.fullname) 
FROM group g
JOIN user_group ug ON g.id = ug.id
JOIN user u ON ug.user_id = u.id
WHERE g.id`

**Comment by benedmunds** [comment]
You want to retrieve it via SQL or via the Ion Auth lib?

**Comment by merakinoya** [comment]
retrive via ion auth library. so when I select a member group it appears a list of user data that has a member group, i was try like this 
`public function get_catagories_users($id=FALSE)
{
	$this->trigger_events('get_users_catagory');
	//$id || $id = $this->session->userdata('lowongan_id');
	return $this->db->select($this->tables['katagori']. '.name,' .$this->tables['katagori']. '.description,'.$this->tables['lowongan'].'.name')
	->from($this->tables['katagori'])
	->join($this->tables['lowongan_katagori'], $this->tables['katagori'].'.id'.'='.$this->tables['lowongan_katagori']. '.' .$this->join['katagori'])
	->join($this->tables['lowongan'], $this->tables['lowongan_katagori'].'.'.$this->join['lowongan'].'='.$this->tables['lowongan'].'.id')
	->where($this->tables['katagori'], $id)
	->get($this->tables['lowongan']);
}`

katagori table as groups tables, and lowongan table as users table, i hope you can help me

**Comment by benedmunds** [comment]
You can get the users groups with:

    $this->ion_auth->get_users_groups($user_id)

**Comment by merakinoya** [comment]
the script try in controller ? 
what is $user_id ? how to get it ?

**Comment by enlivenapp** [comment]
$this->ion_auth->get_user_id();

**Comment by merakinoya** [comment]
Your mean is 
`$id = (int) $id;`
`$user_id = $this->ion_auth->user($id);`
`$this->data['group'] = $this->ion_auth->get_users_groups($user_id);`
?

**Comment by enlivenapp** [comment]
OK,  I'll just do this all at once.  There's a couple ways to get info on an user.

So, for a logged in user:

    if ($this->ion_auth->logged_in())
    {
      // the user is logged in
      $user_id = $this->ion_auth->get_user_id();
      $this->data['group'] = $this->ion_auth->get_users_groups($user_id);

        // or if you're interested in a one-liner of hard to read:
       $this->data['group'] = $this->ion_auth->get_users_groups($this->ion_auth->get_user_id());
    }
    else
    {
       // user is not logged in
     }

If you're trying to pull info on a specific user, like inside an admin panel:

    $id = (int) $id;  // user id you want
    $user_id = $this->ion_auth->user($id);  // you should check there's an actual ID, since this will return your id if $id isn't set, and that could be issues if you're, say, deleting.
    $this->data['group'] = $this->ion_auth->get_users_groups($user_id);

    // or again, the harder to read way
    $id = (int) $id;  // user id you want
    $this->data['group'] = $this->ion_auth->get_users_groups($this->ion_auth->user($id));

**Comment by benedmunds** [comment]
Closing due to age, tag me if this is a still an issue and I'll reopen.
