### ISSUE TITLE
Activation email failed !

### ISSUE THREAD

**Issue by merakinoya** [benedmunds/CodeIgniter-Ion-Auth#1245]
Dear ben, 

i have problem to send email activation for a new user when Project to hosting

`A PHP Error was encountered
Severity: Warning

Message: mail() has been disabled for security reasons

Filename: libraries/Email.php

Line Number: 1894

Backtrace:

File: /home/cirw4317/public_html/test/application/libraries/Ion_auth.php
Line: 377
Function: send

File: /home/cirw4317/public_html/test/application/controllers/Auth.php
Line: 124
Function: register

File: /home/cirw4317/public_html/test/index.php
Line: 315
Function: require_once`

MY ion_auth config  

`$config['email_activation']           = TRUE;               // Email Activation for registration
$config['manual_activation']          = FALSE;               // Manual Activation for registration
$config['remember_users']             = TRUE;                // Allow users to be remembered and enable auto-login
$config['user_expire']                = 86040;               // How long to remember the user (seconds). Set to zero for no expiration
$config['user_extend_on_login']       = TRUE;               // Extend the users cookies every time they auto-login
$config['track_login_attempts']       = TRUE;                // Track the number of failed login attempts for each user or ip.
$config['track_login_ip_address']     = TRUE;   

$config['use_ci_email'] = TRUE; // Send Email using the builtin CI email class, if false it will return the code and the identity
$config['email_config'] = array(
	'mailtype' => 'html',`

**Comment by benedmunds** [comment]
Looks like your server doesnt support mail.  That's not an Ion Auth issue, it's a CI config / server config issue.  I'd recommend using a third party email service (like sendgrid or a similar service).
