### ISSUE TITLE
How to send activation mail after sign up in ion auth. 

### ISSUE THREAD

**Issue by anand1100** [benedmunds/CodeIgniter-Ion-Auth#1246]
$config['email_activation']           = TRUE;  

$config['email_config'] = array(
    'mailtype' => 'html',
    'protocol' => 'smtp',
    'smtp_host' => 'just49.justhost.com',
    'smtp_user' => 'anand@xxxxx.com', // actual values different
    'smtp_pass' => 'xxxxxxx',
    'smtp_port' => '26'
);

here how i setup my config but not getting any mail. please help me to fix this

**Comment by benedmunds** [comment]
Hey @anand1100 

Make sure use_ci_email is set to true in your Ion Auth config as well.

If that doesn't fix it this likely isn't an Ion Auth issue at all. It's probably related to your email config. I'd recommend doing some research on StackOverflow and troubleshooting.

You can try starting with these:

http://stackoverflow.com/questions/1555145/sending-email-with-gmail-smtp-with-codeigniter-email-library

http://stackoverflow.com/questions/38417920/unable-to-send-email-using-smtp-gmail-config-in-codeigniter-3


You may also want to try creating your own controller and method that send an email and use it to verify/troubleshoot your email config.

**Comment by anand1100** [comment]
it's not working. use_ci_email  if true then its unable to send mail showing message.

**Comment by benedmunds** [comment]
are you getting any errors from CIs email class? You can use the print_debugger method to troubleshoot that https://codeigniter.com/user_guide/libraries/email.html?highlight=email#class-reference

**Comment by anand1100** [comment]
user_ci_email i checked true so its showing unable to send email and im using ion_AUTH LIBRARY that time also not able to send email activation key

**Comment by benedmunds** [comment]
If you dump or log the email classes print_debugger output after the email send fails what do you get?

**Comment by anand1100** [comment]
Its showing this error im stuck here. please help me sir to fix this 


im getting unable to send the activation Email

**Comment by bvrignaud** [comment]
I think the message is clear :
line 136 : replace TURE with TRUE

**Comment by anand1100** [comment]
That i have changed sir but still i'm getting 
error unable to send activation email
![1](https://user-images.githubusercontent.com/22708423/41350805-f52ce5a4-6f31-11e8-966a-166cf7658d81.PNG)
![2](https://user-images.githubusercontent.com/22708423/41350858-1f965622-6f32-11e8-9c14-ce44f8dee10c.PNG)
![3](https://user-images.githubusercontent.com/22708423/41350892-38109640-6f32-11e8-8bf1-4d9b7fc72d64.PNG)

**Comment by bvrignaud** [comment]
Have you try to send an email with CodeIgniter ?
https://www.codeigniter.com/user_guide/libraries/email.html

**Comment by anand1100** [comment]
yes i have tried through codeigniter php mailer and its works.

**Comment by bvrignaud** [comment]
What have you in your log ?

**Comment by anand1100** [comment]
simply i download ion_auth and  i just simply enable email_activation but its not showing error its showing unable to send activation mail. 
$config['use_ci_email'] = TRUE;
$config['email_activation']           = TRUE; 
$config['email_config'] = array(
	'mailtype' => 'html',
    'protocol' => 'smtp',
    'smtp_host' => 'just49.justhost.com',
    'SMTPSecure'=>	'tls',
    'smtp_port' => '26',
    'SMTPAuth'  =>	'TRUE',
    'smtp_user' => '############', // actual values different
    'smtp_pass' => '****************',
    'charset' => 'utf-8',
    'newline' => '\r\n',
);

**Comment by bvrignaud** [comment]
in application/config.php, set log_thresold at least 1
```php
$config['log_threshold'] = 1;
```

And now you can read your log at application/logs/

**Comment by anand1100** [comment]
Still having same issue sir .  still showing unable to send mail .

**Comment by bvrignaud** [comment]
Can we read your logs please ?

**Comment by anand1100** [comment]
Thanks sir i have fixed that problem through PHPMailer .

**Comment by doudouPremium** [comment]
hi @anand1100, 
can you help me with how to use PHPMailer to solve the probleme ?
thank you!
