### ISSUE TITLE
Unable to email the Reset Password link

### ISSUE THREAD

**Issue by Tibokool** [benedmunds/CodeIgniter-Ion-Auth#1247]
Hello.
I know a lot of issue spoke about this subject, i read a lot of topic about this and try a lot of modification but its dont work.. I want to send email with the server method.

I create the file "email.php" inside the folder applications/config

`<?php
	defined('BASEPATH') OR exit('No direct script access allowed');

	$config['useragent'] = 'CodeIgniter';
	$config['protocol'] = 'sendmail';
	$config['mailpath'] = '/usr/sbin/sendmail';
	$config['wordwrap'] = TRUE;
	$config['wrapchars'] = 76;
	$config['mailtype'] = 'html';
	$config['charset'] = 'utf-8';
	$config['validate'] = FALSE;
	$config['priority'] = 3;
	$config['crlf'] = "\r\n";
	$config['newline'] = "\r\n";
	$config['bcc_batch_mode'] = FALSE;
	$config['bcc_batch_size'] = 200;`

I create a function to send mail. I load the library _($this->load->library('email');)_ and the function work great. But, when i try to reset password with ionAuth, i have the error "Unable to email the Reset Password link".

Inside the ion auth config, i have:
`$config['use_ci_email'] = TRUE;
$config['email_config'] = 'file';`

(i try with $config['email_config'] = array('mailtype' => 'html'); and its dont work too. 

Thanks..

**Comment by bvrignaud** [comment]
Where is your config/ion_auth.php file ?

It must be in application/config/ion_auth.php

If you put it in the third party folder, that doesn't work.

**Comment by Tibokool** [comment]
Hello. Thanks for your reply @bvrignaud 

My ion Auth configuration file is in:
`application/config/ion_auth.php`
and my email file is in:
`application/config/email.php`

**Comment by bvrignaud** [comment]
And what have you in your log file ?

**Comment by Tibokool** [comment]
`$config['log_threshold'] = 4;`
return me:

`.......
INFO - 2018-06-20 16:02:41 --> Session: Class initialized using 'files' driver.
INFO - 2018-06-20 16:02:41 --> Helper loaded: date_helper
INFO - 2018-06-20 16:02:41 --> Database Driver Class Initialized
INFO - 2018-06-20 16:02:41 --> Model "Ion_auth_model" initialized
INFO - 2018-06-20 16:02:41 --> Helper loaded: form_helper
INFO - 2018-06-20 16:02:41 --> Form Validation Class Initialized
INFO - 2018-06-20 16:02:41 --> Language file loaded: language/english/auth_lang.php
INFO - 2018-06-20 16:02:41 --> File loaded: /home/www/client/ecume/dev/ionauth/application/views/auth/forgot_password.php
INFO - 2018-06-20 16:02:41 --> Final output sent to browser
DEBUG - 2018-06-20 16:02:41 --> Total execution time: 0.0324`

**Comment by bvrignaud** [comment]
Can you try this at Ion_auth.php l173:
```php
$this->email->send(FALSE);
log_message('debug', $this->email->print_debugger());
```

**Comment by benedmunds** [comment]
@Tibokool also in addition to what @bvrignaud posted above.   Just as a test, try setting email_config to match your email.php config:

```
$config['use_ci_email'] = TRUE; 
$config['email_config'] = array(
  'useragent' => 'CodeIgniter',
  'protocol' => 'sendmail',
  'mailpath' => '/usr/sbin/sendmail',
  'wordwrap' => TRUE,
  'wrapchars' => 76,
  'mailtype' => 'html',
  'charset' => 'utf-8',
  'validate' => FALSE,
  'priority' => 3,
  'crlf' => "\r\n",
  'newline' => "\r\n",
  'bcc_batch_mode' => FALSE,
  'bcc_batch_size' => 200
);
```

**Comment by Tibokool** [comment]
@bvrignaud Its return me:
**Error 1:**
`Severity: Notice
Message: Undefined property: CI_Loader::$email
Filename: config/ion_auth.php
Line Number: 173`

**Error2:**
`Severity: Warning
Message: Cannot modify header information - headers already sent by (output started at /home/www/client/ecume/dev/ionauth/system/core/Exceptions.php:271)
Filename: core/Common.php
Line Number: 570`

**Error3:**
`Type: Error
Message: Call to a member function send() on null
Filename: /home/www/client/ecume/dev/ionauth/application/config/ion_auth.php
Line Number: 173`

**Comment by Tibokool** [comment]
@benedmunds Hi. I already try this solution, i find it on another issue but it dont work too for me....

**Comment by benedmunds** [comment]
@Tibokool can you move that logging code from @bvrignaud to the libraries/ion_auth.php file, instead of the config/ion_auth.php file.

**Comment by bvrignaud** [comment]
@Tibokool you haven't make the change in the good place. It's for libraries/Ion_auth.php
Can you try this at libraries/Ion_auth.php l173:
change :
```php
$this->email->send();
```
by
```php
$this->email->send(FALSE);
log_message('debug', $this->email->print_debugger());
```

**Comment by Tibokool** [comment]
Oh... sorry..
I put this on line 173 (in the librairie file):
`else
   {
      $this->email->send(FALSE);
         log_message('debug', $this->email->print_debugger());
}`

and its return me nothing, always Unable to email the Reset Password link.. 
Its strange, i remove the `$this->set_error('forgot_password_unsuccessful');`

**Comment by bvrignaud** [comment]
Of course it return notthing look in your log file

**Comment by Tibokool** [comment]
This if my full log file:
`INFO - 2018-06-20 16:27:24 --> Config Class Initialized
INFO - 2018-06-20 16:27:24 --> Hooks Class Initialized
DEBUG - 2018-06-20 16:27:24 --> UTF-8 Support Enabled
INFO - 2018-06-20 16:27:24 --> Utf8 Class Initialized
INFO - 2018-06-20 16:27:24 --> URI Class Initialized
INFO - 2018-06-20 16:27:24 --> Router Class Initialized
INFO - 2018-06-20 16:27:24 --> Output Class Initialized
INFO - 2018-06-20 16:27:24 --> Security Class Initialized
DEBUG - 2018-06-20 16:27:24 --> Global POST, GET and COOKIE data sanitized
INFO - 2018-06-20 16:27:24 --> Input Class Initialized
INFO - 2018-06-20 16:27:24 --> Language Class Initialized
INFO - 2018-06-20 16:27:24 --> Loader Class Initialized
INFO - 2018-06-20 16:27:24 --> Controller Class Initialized
INFO - 2018-06-20 16:27:24 --> Database Driver Class Initialized
DEBUG - 2018-06-20 16:27:24 --> Config file loaded: /home/www/client/ecume/dev/ionauth/application/config/ion_auth.php
INFO - 2018-06-20 16:27:24 --> Email Class Initialized
INFO - 2018-06-20 16:27:24 --> Language file loaded: language/english/ion_auth_lang.php
INFO - 2018-06-20 16:27:24 --> Helper loaded: cookie_helper
INFO - 2018-06-20 16:27:24 --> Helper loaded: language_helper
INFO - 2018-06-20 16:27:24 --> Helper loaded: url_helper
DEBUG - 2018-06-20 16:27:24 --> Session: "sess_save_path" is empty; using "session.save_path" value from php.ini.
INFO - 2018-06-20 16:27:24 --> Session: Class initialized using 'files' driver.
INFO - 2018-06-20 16:27:24 --> Helper loaded: date_helper
INFO - 2018-06-20 16:27:24 --> Database Driver Class Initialized
INFO - 2018-06-20 16:27:24 --> Model "Ion_auth_model" initialized
INFO - 2018-06-20 16:27:24 --> Helper loaded: form_helper
INFO - 2018-06-20 16:27:24 --> Form Validation Class Initialized
INFO - 2018-06-20 16:27:24 --> Language file loaded: language/english/auth_lang.php
INFO - 2018-06-20 16:27:24 --> Language file loaded: language/english/form_validation_lang.php
INFO - 2018-06-20 16:27:25 --> Config Class Initialized
INFO - 2018-06-20 16:27:25 --> Hooks Class Initialized
DEBUG - 2018-06-20 16:27:25 --> UTF-8 Support Enabled
INFO - 2018-06-20 16:27:25 --> Utf8 Class Initialized
INFO - 2018-06-20 16:27:25 --> URI Class Initialized
INFO - 2018-06-20 16:27:25 --> Router Class Initialized
INFO - 2018-06-20 16:27:25 --> Output Class Initialized
INFO - 2018-06-20 16:27:25 --> Security Class Initialized
DEBUG - 2018-06-20 16:27:25 --> Global POST, GET and COOKIE data sanitized
INFO - 2018-06-20 16:27:25 --> Input Class Initialized
INFO - 2018-06-20 16:27:25 --> Language Class Initialized
INFO - 2018-06-20 16:27:25 --> Loader Class Initialized
INFO - 2018-06-20 16:27:25 --> Controller Class Initialized
INFO - 2018-06-20 16:27:25 --> Database Driver Class Initialized
DEBUG - 2018-06-20 16:27:25 --> Config file loaded: /home/www/client/ecume/dev/ionauth/application/config/ion_auth.php
INFO - 2018-06-20 16:27:25 --> Email Class Initialized
INFO - 2018-06-20 16:27:25 --> Language file loaded: language/english/ion_auth_lang.php
INFO - 2018-06-20 16:27:25 --> Helper loaded: cookie_helper
INFO - 2018-06-20 16:27:25 --> Helper loaded: language_helper
INFO - 2018-06-20 16:27:25 --> Helper loaded: url_helper
DEBUG - 2018-06-20 16:27:25 --> Session: "sess_save_path" is empty; using "session.save_path" value from php.ini.
INFO - 2018-06-20 16:27:25 --> Session: Class initialized using 'files' driver.
INFO - 2018-06-20 16:27:25 --> Helper loaded: date_helper
INFO - 2018-06-20 16:27:25 --> Database Driver Class Initialized
INFO - 2018-06-20 16:27:25 --> Model "Ion_auth_model" initialized
INFO - 2018-06-20 16:27:25 --> Helper loaded: form_helper
INFO - 2018-06-20 16:27:25 --> Form Validation Class Initialized
INFO - 2018-06-20 16:27:25 --> Language file loaded: language/english/auth_lang.php
INFO - 2018-06-20 16:27:25 --> File loaded: /home/www/client/ecume/dev/ionauth/application/views/auth/forgot_password.php
INFO - 2018-06-20 16:27:25 --> Final output sent to browser
DEBUG - 2018-06-20 16:27:25 --> Total execution time: 0.0324
`

**Comment by bvrignaud** [comment]
@Tibokool No idea ...
CodeIgniter Version ?
Ion-Auth version ?

**Comment by Tibokool** [comment]
Last version of codeigniter & Ion Auth, i download it 2 hours ago. I want to try before build project with Ion Auth and its the only problem i find.. Thanks for your time @bvrignaud. Hope someone else find solution ^^

**Comment by benedmunds** [comment]
Which branch did you download? 2?

**Comment by Tibokool** [comment]
@benedmunds Yes, on the branch n°2 _(Codeigniter version: 3.1.9)_

**Comment by benedmunds** [comment]
@Tibokool can you post your libraries/ion_auth.php - lines 165 - 175

**Comment by Tibokool** [comment]
**Librairies/ion_auth.php (line 166 to 175):** 165 is blank line for me 
`
					if ($this->email->send())
					{
						$this->set_message('forgot_password_successful');
						return TRUE;
					}
					else
					{
						$this->set_error('forgot_password_unsuccessful');
						return FALSE;
					}`

Its very strange, i touch to 0 file. Only the config file..

**Comment by benedmunds** [comment]
Update it to the following please, and post the output:

```
if ($this->email->send())
					{
						$this->set_message('forgot_password_successful');
						return TRUE;
					}
					else
					{
var_dump($this->email->print_debugger());exit;
						$this->set_error('forgot_password_unsuccessful');
						return FALSE;
					}
```

**Comment by Tibokool** [comment]
No error was display, and the log file was the same of my reply before..

**Comment by benedmunds** [comment]
Ah, it might be an issue with the user lookup and not the email then.

Can you make sure https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/libraries/Ion_auth.php#L145 is passing this if check

**Comment by benedmunds** [comment]
To expand on this, you can add the following var_dumps to help determine where this is failing exactly, my guess is something wrong with the identity you're passing:

```
  public function forgotten_password($identity)
  {
    if ($this->ion_auth_model->forgotten_password($identity))
    {
      // Get user information
      $identifier = $this->ion_auth_model->identity_column; // use model identity column, so it can be overridden in a controller
      $user = $this->where($identifier, $identity)->where('active', 1)->users()->row();
      if ($user)
      {
        $data = array(
          'identity' => $user->{$this->config->item('identity', 'ion_auth')},
          'forgotten_password_code' => $user->forgotten_password_code
        );
        if (!$this->config->item('use_ci_email', 'ion_auth'))
        {
          $this->set_message('forgot_password_successful');
          return $data;
        }
        else
        {
          $message = $this->load->view($this->config->item('email_templates', 'ion_auth') . $this->config->item('email_forgot_password', 'ion_auth'), $data, TRUE);
          $this->email->clear();
          $this->email->from($this->config->item('admin_email', 'ion_auth'), $this->config->item('site_title', 'ion_auth'));
          $this->email->to($user->email);
          $this->email->subject($this->config->item('site_title', 'ion_auth') . ' - ' . $this->lang->line('email_forgotten_password_subject'));
          $this->email->message($message);
          if ($this->email->send())
          {
            $this->set_message('forgot_password_successful');
            return TRUE;
          }
          else
          {
            var_dump('email sending failed');
            var_dump($this->email->print_debugger());
            exit;
            $this->set_error('forgot_password_unsuccessful');
            return FALSE;
          }
        }
      }
      else
      {
        var_dump('user query failed');exit;
        $this->set_error('forgot_password_unsuccessful');
        return FALSE;
      }
    }
    else
    {
      var_dump('ion_auth_model->forgotten_password() failed');exit;
      $this->set_error('forgot_password_unsuccessful');
      return FALSE;
    }
  }
```

**Comment by Tibokool** [comment]
Hi back.
I try your code and he return me this:

`string(17) "user query failed"`

**Comment by benedmunds** [comment]
Run a SQL query for select(*) from users where {identity}={identity} and post the results, specifically looking for if both the user identity is correct and if they are active.

**Comment by Tibokool** [comment]
Sorry but i dont know this kind of sql query ? He return me an error ?
`#1064 - Erreur de syntaxe près de '*) from users where {identity}={identity} LIMIT 0, 25' à la ligne 1`

**Comment by benedmunds** [comment]
The {identity} pieces were just placeholders, you’ll need to insert those.  The idea is to run a similar query to what Ion Auth is running.

**Comment by Tibokool** [comment]
Oh.... oh no.... 
The user was not active............ I'm so ashamed...
Sorry for all the time I wasted on you...
I think you need to add custom error if user reset password and i not active for all the assh**** like me 🤐

**Comment by benedmunds** [comment]
No problem!  Just glad we figured it out.  I'm going to close this issue, take care!
