### ISSUE TITLE
Create auth hierarchy

### ISSUE THREAD

**Issue by Tibokool** [benedmunds/CodeIgniter-Ion-Auth#1248]
Hello everybody,

On my project, i want to create a hierarchy with your library. I want to know, for you, the easiest way to do  this. For example, the administrator can create / edit / remove "Moderator". The Moderator can create / edit / remove his own team of "Employees".

So, i create my 3 group inside the codeigniter project. Now:
1 - Where can i change the default group relative to the login user ? I find inside config but i want to add conditions. (If login user is moderator, profil created is Employees for example)

Thanks for your help! 😋

**Comment by benedmunds** [comment]
You can pass the groups to register() to use instead of the default group:
http://benedmunds.com/ion_auth/#register

**Comment by Tibokool** [comment]
Thanks ! Just another question. In your librairie, the session data was include ? Whis informations of logg user?

**Comment by benedmunds** [comment]
The session contains the following:

```
		    'identity'             => $user->{$this->identity_column},
		    $this->identity_column => $user->{$this->identity_column},
		    'email'                => $user->email,
		    'user_id'              => $user->id, //everyone likes to overwrite id so we'll use user_id
		    'old_last_login'       => $user->last_login,
		    'last_check'           => time(),
```

You can reference the code at https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/models/Ion_auth_model.php#L2009
