### ISSUE TITLE
I am struggling with is_unique validation

### ISSUE THREAD

**Issue by Namennaj** [benedmunds/CodeIgniter-Ion-Auth#1249]
I am trying to create a new user group.  Here is a snippet of my code:

`$this->load->library('form_validation');
    $this->form_validation->set_rules('group_name','Group name','trim|required|is_unique[groups.name]');
    $this->form_validation->set_rules('group_description','Group description','trim|required');`

The problem is I keep getting this error message:  The Group name field must contain a unique value.
This should not be the case.  It is a fresh install and I only have the two default user groups in there.

When I remove the 'is_unique[groups.name]' part, everything is working fine.

Do you have any suggestions of what can be wrong?

Thanks

**Comment by benedmunds** [comment]
Are you certain that the name you're entering is unique?

**Comment by Namennaj** [comment]
@benedmunds, Yes I am sure.  The existing groups are "admin" and "members".  I am trying to create a group with the name "test".

**Comment by Namennaj** [comment]
I should mention that I have used this code with a previous version of Codeigniter and it worked for that project.  However, I cannot get it to work now.

**Comment by benedmunds** [comment]
Which version of CI are you on now? Maybe there's an issue with it.  I'd recommend upgrading to the latest and checking docs/issues on their project to see.

Worst case is you could write your own callback validation that checks it.

**Comment by benedmunds** [comment]
Maybe also check these to see if any solve your problem: https://github.com/bcit-ci/CodeIgniter/issues?q=is%3Aissue+is_unique+is%3Aclosed

**Comment by Namennaj** [comment]
I tried both 3.1.8 and 3.1.9 now.  Both have the exact same issue.  I am using the steps in this tutorial:  https://avenir.ro/create-cms-using-codeigniter-3/.   I have now built 6 iterations today and they all have this issue.  However, the project I did in 2017 with CI works perfectly.  It's really baffling.

**Comment by Namennaj** [comment]
The working version is 3.1.5.  I am going to try that version next and see if that makes a difference.

**Comment by Namennaj** [comment]
I tried with 3.1.5 with no luck.  I also tried reinstalling wamp.

**Comment by Namennaj** [comment]
@benedmunds it's working now.  I used an old version of Ion Auth (Version: 2.5.2).  It worked on a previous project and when I tried those files it did the trick.
