### ISSUE TITLE
Latest stable release?

### ISSUE THREAD

**Issue by tantrus332** [benedmunds/CodeIgniter-Ion-Auth#1251]
Which branch is the last stable version?

- The online documentation (http://benedmunds.com/ion_auth/) says that, download: http://github.com/benedmunds/CodeIgniter-Ion-Auth/zipball/2 (2016-06-18, without table meta)
- After downloading, the offline documentation says that http://github.com/benedmunds/CodeIgniter-Ion-Auth/zipball/master (2016-06-18, with table meta)
- In releases version 2.6.0 - 2014 year (without table meta)

Where should I download to get the latest stable release?

**Comment by benedmunds** [comment]
The 2 branch is the latest, so http://github.com/benedmunds/CodeIgniter-Ion-Auth/zipball/2  is correct.

I'll fix the offline docs, thanks for pointing that out!
