### ISSUE TITLE
Folder-Repo Structure-Configuration Suggestion

### ISSUE THREAD

**Issue by rondemena** [benedmunds/CodeIgniter-Ion-Auth#1252]
While working on integrating this code with a project, I realized I didnt want to host, or try and view your userguide from the host I was working on.  It may be ideal to present your code online from here by simply changing the userguide directory to docs and enabling the GitHub Pages for your documentation link.

**Comment by benedmunds** [comment]
Hey, the docs are available online at http://benedmunds.com/ion_auth/
