### ISSUE TITLE
Please help with HMVC setup

### ISSUE THREAD

**Issue by buddyy93** [benedmunds/CodeIgniter-Ion-Auth#1254]
i've tried so many attempts but still not working please someone help me with the setup.

Message: Undefined property: stdClass::$data

Filename: drivers/Session_database_driver.php

Line Number: 184

Backtrace:

File: E:\MyServer\simawa\application\third_party\MX\Loader.php
Line: 177
Function: _ci_load_library

File: E:\MyServer\simawa\application\third_party\MX\Loader.php
Line: 196
Function: library

File: E:\MyServer\simawa\application\third_party\MX\Loader.php
Line: 157
Function: libraries

File: E:\MyServer\simawa\application\third_party\MX\Loader.php
Line: 64
Function: initialize

File: E:\MyServer\simawa\application\third_party\MX\Base.php
Line: 55
Function: __construct

File: E:\MyServer\simawa\application\third_party\MX\Base.php
Line: 60
Function: __construct

Message: session_start(): Failed to read session data: user (path: C:\xampp\tmp)

Filename: Session/Session.php

Line Number: 143

Backtrace:

File: E:\MyServer\simawa\application\third_party\MX\Loader.php
Line: 177
Function: _ci_load_library

File: E:\MyServer\simawa\application\third_party\MX\Loader.php
Line: 196
Function: library

File: E:\MyServer\simawa\application\third_party\MX\Loader.php
Line: 157
Function: libraries

File: E:\MyServer\simawa\application\third_party\MX\Loader.php
Line: 64
Function: initialize

File: E:\MyServer\simawa\application\third_party\MX\Base.php
Line: 55
Function: __construct

File: E:\MyServer\simawa\application\third_party\MX\Base.php
Line: 60
Function: __construct

File: E:\MyServer\simawa\application\third_party\MX\Controller.php
Line: 4
Function: require

File: E:\MyServer\simawa\application\third_party\MX\Modules.php
Line: 123
Function: include_once

i keep getting that kinda errors, and i think there are others as well, thank you in advance

**Comment by benedmunds** [comment]
Hey,

I dont personally use HMVC but a few issues have been posted about it in the past so hopefully you can find something there that helps, see:

https://github.com/benedmunds/CodeIgniter-Ion-Auth/issues/257
https://github.com/benedmunds/CodeIgniter-Ion-Auth/issues/1139
https://github.com/AXeL-dev/CodeIgniter-Ion-Auth-HMVC

**Comment by buddyy93** [comment]
@benedmunds hi thank you for the response.
after several attempts and following the repository i finally made it work, for some reasons there's problem in my system folder which is in the root project, so i replace it with a brand new one and it worked like a charm, thank you

**Comment by benedmunds** [comment]
Great to hear!
