### ISSUE TITLE
Can't make a NULL column unique during v2 -> v3 SQL Server migration

### ISSUE THREAD

**Issue by TylerVigario** [benedmunds/CodeIgniter-Ion-Auth#1255]
**I get this error (excluded other 2):**

`Error in query (3621): The CREATE UNIQUE INDEX statement terminated because a duplicate key was found for the object name 'dbo.users' and the index name 'uc_activation_selector'. The duplicate key value is (<NULL>).
Could not create constraint or index. See previous errors.
The statement has been terminated.`

**from these last 3 commands:**

```
ALTER TABLE users
  ADD CONSTRAINT uc_activation_selector
    UNIQUE (activation_selector);

ALTER TABLE users
  ADD CONSTRAINT uc_remember_selector
    UNIQUE (remember_selector);

ALTER TABLE users
  ADD CONSTRAINT uc_forgotten_password_selector
    UNIQUE (forgotten_password_selector);
```

**This worked for me:**

> Pretty sure you can't do that, as it violates the purpose of uniques.
– https://stackoverflow.com/questions/191421/how-to-create-a-unique-index-on-a-null-column

`CREATE UNIQUE INDEX uc_activation_selector on users (activation_selector) where activation_selector is not null`

**Comment by benedmunds** [comment]
Hey,

Where did these constraints originally come from?  I don't see them in the SQL file here: https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/sql/ion_auth.mssql.sql

**Comment by TylerVigario** [comment]
Sorry, maybe this is an incorrect spot for this error.

However, it came from the v3 branch – https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/sql/migrating_from_ionauth2/migrate.mssql.sql

**Comment by benedmunds** [comment]
Ah sorry, my bad. I didn't follow.

@Indigo744 can you take a look at this?

**Comment by Indigo744** [comment]
@benedmunds Sorry I actually didn't see you notification.

Indeed, I made an error in the TSQL syntax. In MySQL, you can add unique on column with NULL. In TSQL, you should do as proposed by @MeekLogic 

I'll create a PR.

**Comment by benedmunds** [comment]
Closing since the PR has been merged.
