### ISSUE TITLE
password function to encrypt my password

### ISSUE THREAD

**Issue by mraheelkhan** [benedmunds/CodeIgniter-Ion-Auth#1256]
hello. 
I am new to CI and Ion Auth, thank you for such great lib. 
I just want to insert users by my own methods with custom fields, but I don't know how to encrypt the password so that password can work on login as well. 
Can you please suggest me what to do? or which password function can I use?

Let's suppose, I have received the below password from the user.

```
$password = $this->input->post("password");
// $password = "12345678";
```
How to encrypt it? 

Thank You

NOTE: I don't know where to ask this question that's why I placed it as an issue.

**Comment by bvrignaud** [comment]
Hello,

I think the best way is to use the **register()** methode.
Uou can also use the **hash_password()** methode.

`

**Comment by mraheelkhan** [comment]
like
`$password = hash_password($password);`

but doesn't work for me. :-(

**Comment by bvrignaud** [comment]
No, not like that.
It must me something like this :
```php
$this->ion_auth_model->hash_password(....)
```
Take a look to the source code of Ion_auth_model.php

I really think that `$this->ion_auth->register()` is a better way.

**Comment by mraheelkhan** [comment]
Okay thank you will check that. 
secondly i need to know that i want to show the user profile data from "users" table after the sucessful login. 
can you please tell me how to do that?

i tried 

```
$this->load->library('session');

If($this->ion_auth->logged_in()){

$data['name'] = $this->session->userdata('first_name');
$data['name'] = $this->session->first_name;
$data['name'] = $_SESSION['first_name'];
}
```
but unfortunately, none of them is working for me. 
I just want to show the User First, name and last name on the profile view(dashbaord) to the user who is logged in.

**Comment by mraheelkhan** [comment]
this is my controller code. 

```
public function dashboard_student()
	{
		if ( !$this->ion_auth->logged_in() ) {
			// redirect them to the login page
			redirect( 'auth/login', 'refresh' );
		}
		if ( $this->ion_auth->in_group( "teacher" ) ) {
			$this->load->view( "unauth" );
		} else {
			// $data['name'] = $this->session->userdata('first_name');
			// $data['name'] = $this->session->first_name;
			// $this->load->library('session');
			$data = $this->session->userdata('first_name');
			echo var_dump($data);
			$this->load->view( 'dashboard_student', $data );
		}
	}
```

**Comment by bvrignaud** [comment]
Please, read the doc : http://benedmunds.com/ion_auth/
`$this->ion_auth->user()->row();`

**Comment by mraheelkhan** [comment]
Oo, Allah, 
That's Love, how can I miss it? 
Ion_Auth saved my complete BS Degree. 
ThankYou for such great script. 
Love From Pakistan <3
