### ISSUE TITLE
Unable to load the requested file: login_view.php

### ISSUE THREAD

**Issue by fliant** [benedmunds/CodeIgniter-Ion-Auth#1257]
i am new to codeigniter and as i tryied  out my code i met this error message 
some one help me out 

An Error Was Encountered
Unable to load the requested file: login_view.php

**Comment by benedmunds** [comment]
Hey @fliant 

This is a place meant for posting bugs with the library itself.  I'd recommend asking for help on the CodeIgniter forums (https://forum.codeigniter.com/) or on StackOverflow (https://stackoverflow.com/).

When you do post there, make sure to include additional information on what you've tried so far and examples of your code.
