### ISSUE TITLE
Ion_auth_model not reusing the default database connection

### ISSUE THREAD

**Issue by marios88** [benedmunds/CodeIgniter-Ion-Auth#1258]
I don't know if this is a bug or a feature!
CI : 3.1.9
Ion_auth : 3 & 2

Applies to the following code segment

```
/models/Ion_auth_model.php

protected $db;
.
.
.
$this->db = $this->load->database($this->config->item('database_group_name', 'ion_auth'), TRUE, TRUE);
```
If `database_group_name` is empty or `default` shouldn’t it recycle the same connection?

relevant commits https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/1194/commits/2f6c6eb9a508e99af5ba768488043bd30a076583 and merge https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/1194

**Comment by benedmunds** [comment]
If it's empty CI should load the default, afaik CI will recycle automatically if it already exists.  Are you seeing a second DB connection being opened?

**Comment by marios88** [comment]
Using PDO, testing with following code seems to open a new connection

```
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class MY_Controller extends CI_Controller {

    protected $data = array();
    private function show_conns(){
        $plist = $this->db->query('show full processlist')->result_array();
        foreach ($plist as $k => $v){
            echo '('. $k .')' . $v['State'] .' : ' .$v['Info'].PHP_EOL;
        }
        echo '***********'.PHP_EOL;
    }
    function __construct() {
        parent::__construct();
        $this->show_conns();
        $this->load->library('ion_auth');
        $this->show_conns();    
    }
}
```
outputs
```
(0)init : show full processlist
***********
(0)init : show full processlist
(1) : 
***********
```

Did a little bit more digging as the results seem counter-intuitive and couldn’t find any documentation, it seems like if you set `return = TRUE`  you get a new connection no matter what

see https://github.com/bcit-ci/CodeIgniter/blob/7269d8376151afe58dc23956693bf12ec48bc45d/system/core/Loader.php#L377

Doing this, throws a database error
```
for($i=0;$i<1000;$i++) {
            ${'testconn'.$i} = $this->load->database('', TRUE, TRUE);
            $this->show_conns();
}
```

so i guess this is the expected behaviour and unrelated to ion_auth, if you agree feel free to close this

**Comment by benedmunds** [comment]
I guess we could change the way we call this based on if the value is empty.

@Indigo744 do you want to comment on this since it references your PR?

**Comment by Indigo744** [comment]
Thanks for the ping @benedmunds 

The issue, as I understand it, is that another connection is always used for IonAuth calls, even with default group naming. Looking back at the PR and the commits, I can't understand why I didn't see it sooner 😦 

The thing is, CodeIgniter Database library is made in a way that it is complicated to have multiple DB opened at the same time.

If you do 
```php
$this->load->database('a_group');
```
It will replace any active connection, and other libraries and models will be in disarray.

If you do
```php
$DB = $this->load->database('a_group', TRUE);
```
It will open a new connection, even if a connection already exists for this very group.

There isn't a way to say _"Give me a connection to this group if you have one, open if not"_

Anyway, for OP case, when using default (i.e. empty) group name, we could simply avoid overwriting the `$db` member and keep the default active connection (like before).

If a group name is set, we sadly cannot know if a connection is already opened to this group, and thus we need to load the database. We _could_ provide a constructor where the user can supply a DB parameter, but I don't know if it's worth it.

**Comment by benedmunds** [comment]
I like the idea of reusing if its default and doing a new connection (no injection) if its a non-default group name.  Nice balance between performance and complexity.

**Comment by Indigo744** [comment]
Alright then, I'll submit a PR on 2 and 3 branches.
