### ISSUE TITLE
is there a way I can utilize this for an acl? 

### ISSUE THREAD

**Issue by ramsesrom** [benedmunds/CodeIgniter-Ion-Auth#1259]
is there a way I can utilize this for an acl ? like per group or per person allowed access and restriction access?

**Comment by ramsesrom** [comment]
another thing, would it hurt if I change the user id to a random number not just auto increment from the table?

**Comment by benedmunds** [comment]
Steve Goodwin has an ACL project here https://github.com/weblogics/Codeigniter-Ion-Auth-ACL/blob/master/README.md

I haven’t used it myself though.


On user id, it shouldn’t cause any issues with Ion Auth, it relies on the DB for that.
