### ISSUE TITLE
It's asking for drive permssion each and every time while login

### ISSUE THREAD

**Issue by dipalinigade26** [benedmunds/CodeIgniter-Ion-Auth#1260]
Hello i am having application where i can login using google. its working fine for me when i click on login it visited gmail login page where i can put gmail id and password it ask for drive permission then it redirect back to my application, after completing my work i logout from application, after some time if i click on login application not visited gmail page directly get login with previous detail. If i put this line
Hide   Copy Code
$client->setApprovalPrompt('force');
application ask mi to select email id and again drive allow window is their. but i want application to ask permission each and every time to select gmail id and not for google drive even if their is only one account login on gmail

The code 
	$client->setClientId($client_id);
		$client->setClientSecret($client_secret);
		$client->setRedirectUri($redirect_uri);
		$client->setAccessType('offline');
		$client->setApprovalPrompt('force');
		$client->addScope("https://www.googleapis.com/auth/userinfo.email");
		$client->addScope("https://www.googleapis.com/auth/drive.file");

**Comment by benedmunds** [comment]
Which branch of Ion Auth are you using?

**Comment by dipalinigade26** [comment]
sorry but i'm not getting what means the branch?

**Comment by benedmunds** [comment]
Which branch of the Ion Auth repo are you using? (2/3/social/etc)

**Comment by dipalinigade26** [comment]
Using Oauth 2

**Comment by benedmunds** [comment]
So you have coded your own custom solution to integrate Ion Auth with Google via Oauth2?

**Comment by dipalinigade26** [comment]
i have used the hybrid auth library for that....

**Comment by benedmunds** [comment]
Sorry for the basic questions but I'm trying to make sure we're on the same page.  Are you using Hybrid Auth via custom code you've written or are you using the "social" branch of Ion Auth?

**Comment by dipalinigade26** [comment]
I have not change  any code.....

**Comment by benedmunds** [comment]
Right, but Ion Auth doesn't support Hybrid Auth by default in the 2/3 branches.  So I'm trying to figure out where your issue might be coming from.

Can you post more example code.

**Comment by benedmunds** [comment]
Closing due to age, tag me if this is a still an issue and I'll reopen.
