### ISSUE TITLE
Non Object property 

### ISSUE THREAD

**Issue by adipatiarya** [benedmunds/CodeIgniter-Ion-Auth#1264]
204 : $forgotten = $this->ion_auth->forgotten_password($identity->{$this->config->item('identity', 'ion_auth')});

Error when email is not active
div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Trying to get property of non-object</p>
<p>Filename: api/Auth.php</p>
<p>Line Number: 204</p>

	<p>Backtrace:</p>
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gretonge/public_html/application/controllers/api/Auth.php<br />
			Line: 204<br />
			Function: _error_handler			</p>

		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gretonge/public_html/application/libraries/REST_Controller.php<br />
			Line: 743<br />
			Function: call_user_func_array			</p>

		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gretonge/public_html/index.php<br />
			Line: 315<br />
			Function: require_once			</p>

		
	

</div>{"status":false,"message":"No record of that email address.Unable to email the Reset Password link"}

**Comment by benedmunds** [comment]
Post the entire forgot_password method from your controller please.

Also what changes have you made to the example code?

**Comment by benedmunds** [comment]
Closing due to age, tag me if this is a still an issue and I'll reopen.
