### ISSUE TITLE
how to allow user to only edit his branch

### ISSUE THREAD

**Issue by almiali** [benedmunds/CodeIgniter-Ion-Auth#1265]
Hi 

I have more than one branch 

how I can make a user for each branch, I mean that I should choose the branch id for a specific user and allow him to edit his branch only

thank you

**Comment by benedmunds** [comment]
Sorry but you’ll need to give me more details.  What is s branch in your use case?

Example code is also appreciated.

Ion Auth doesn’t have an ACL built in, there is a user supported package you could try for that here https://github.com/weblogics/Codeigniter-Ion-Auth-ACL

**Comment by almiali** [comment]
I trying to allow each user to manage his branch 

so I should assign the Branch ID to the user then he can manage his branch without access to other branches 

I do not have the code, but that is the Idea .
we have a restaurant with three branches 
1-there is 3 branches each branch has ID
2- user I will allow to manage Branch one only, user 2 allows to manage branch 2 and etc...

now I can only allow the user to manage all branches by calling that method 

		if(!$this->ion_auth->checkuser_privilage($this->privilage))
		{	
			$this->session->set_flashdata('message', $this->ion_auth->errors());
			redirect('admin/dashboard', 'refresh');
		}
I hope that you underand what I means .

thank you

**Comment by benedmunds** [comment]
That should work fine. It could be as simple as something like:
```
if($user->id !== $branch->id)
	{	
		$this->session->set_flashdata('message', $this->ion_auth->errors());
		redirect('admin/dashboard', 'refresh');
	}
```

**Comment by almiali** [comment]
thank you  a lot, your hint help me a lot

Thank you
