### ISSUE TITLE
Possible "remember me" issue

### ISSUE THREAD

**Issue by marios88** [benedmunds/CodeIgniter-Ion-Auth#1269]
Please bear with me as i have not yet fully debugged this, and i might be wrong

Use case: One user logins from multiple devices with the same credentials using "remember me"
```
( Login1 ) 00:00 Account1 / on PC -> login with "remember me"
( Login2 ) 00:05 Account1 / on Mobile -> login with "remember me"
```

from 
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/4a007e65cd6da0f14e68421ef91e20445e44a211/models/Ion_auth_model.php#L2102

the "remember me" hash goes on the database, so after the second login,
only the remember me code from "Login2" is available

Shouldn't all the relevant data be stored in the session?

**Comment by benedmunds** [comment]
This is correct.  It's a limitation of the implementation that I'm fine with.  In order to support multiple computers you'd need an additional table that tracks remember codes.
