### ISSUE TITLE
User edit their own information 

### ISSUE THREAD

**Issue by felisane123** [benedmunds/CodeIgniter-Ion-Auth#1272]
Hello I want to know if its possible to allow users to edit their own information and how ? Best regards !

**Comment by benedmunds** [comment]
Yes you can.  You'll need to modify the example controller/views to suit your needs.

**Comment by felisane123** [comment]
I have been trying but till now I couldn't figure out how to do it exactly would be very helpful if you give me a light. Thanks

**Comment by benedmunds** [comment]
Post a couple examples of the code you tried and the results you got. We can help suggest paths to take.

I’d start with copying the admin edit functionality and removing the admin group requirement

**Comment by felisane123** [comment]
Thank you I'll try and let you know the result

**Comment by bvrignaud** [comment]
This my template :
The controller :
[Profil.php.zip](https://github.com/benedmunds/CodeIgniter-Ion-Auth/files/2436922/Profil.php.zip)
The view :
[edit_profil.php.zip](https://github.com/benedmunds/CodeIgniter-Ion-Auth/files/2436923/edit_profil.php.zip)

**Comment by felisane123** [comment]
Thank you soo much benedmunds and bvrignaud.
