### ISSUE TITLE
[v3] sending emails is replacing chars by '='

### ISSUE THREAD

**Issue by phalox** [benedmunds/CodeIgniter-Ion-Auth#1279]
Heya,

I don't think this is an ion auth issue, but might be caused by a badly configured mail class... I just didn't see any instructions on how to fix it or how to properly configure the email library (I followed the config from the repo)

It seems to be related to the line-length which should not be more than 76 chars (74 + \r\n), also documented here: https://stackoverflow.com/questions/14916834/codeigniter-html-email-changing-characters

It's impacting the activation mail sent by the library, because the URL gets quite long.

What's the best way to fix this?

Edit:
Environment = WAMP server, using Test Mail Server tool. php5. Emails are supposed to be HTML

**Comment by benedmunds** [comment]
This shouldnt matter for HTML emails right?  As far as I understand it, the 78 character limit is a suggestion for display, and the activation code URL isn't displayed in the HTML email, it's behind an <a href.

**Comment by phalox** [comment]
That's exactly how it's configured...

```
/*
 | -------------------------------------------------------------------------
 | Email options.
 | -------------------------------------------------------------------------
 | email_config:
 | 	  'file' = Use the default CI config or use from a config file
 | 	  array  = Manually set your email config settings
 */
$config['use_ci_email'] = TRUE; // Send Email using the builtin CI email class, if false it will return the code and the identity
$config['email_config'] = [
	'mailtype' => 'html',
];
```

To hack things and make it work, I've added:

`$this->email->set_crlf( "\r\n" );`

in libraries/ion_auth.php/ around line 300 (mail sending code)

This seems to fix things...
Email stuff is so fragile, incredible what backwards compatibility causes in complexity!

**Comment by benedmunds** [comment]
What if you set the crlf setting in the email_config instead?

**Comment by phalox** [comment]
Done, works.

I'll need to test this on my production environment and see if I can also
reproduce this issue...

I'm too unfamiliar with potential email issues...

**Comment by benedmunds** [comment]
Ok awesome

**Comment by benedmunds** [comment]
Closing this for now, @phalox tag me if you have any further issues here and I'll reopen.
