### ISSUE TITLE
Redirect call uses refresh

### ISSUE THREAD

**Issue by marios88** [benedmunds/CodeIgniter-Ion-Auth#1280]
CI : **3.1.9**
Ion_auth : **3** & **2**

`redirect()` calls use the "refresh" option in order to avoid stale content

In my opinion this partially solves the problem and does not account for the following cases
- Possible stale content on browser back-forward
- it causes a flash of "white page" during the redirects

A solution to both problems could be to output no-cache headers in the controller constructor and use "auto" redirects

Thank you for your time!

**Comment by benedmunds** [comment]
In general my opinion is that it's not an Ion Auth issue to handle all the edge cases that come up in app development like this.  The example controller is just an example of how to use the library, it's not meant to be used as your application.

If you want to submit a PR for the example code for this I'd merge it though as it does seem to be a tricky issue for many.

**Comment by marios88** [comment]
I see you point and agree, the controllers are per use case
