### ISSUE TITLE
MySQL collation

### ISSUE THREAD

**Issue by federicovilla** [benedmunds/CodeIgniter-Ion-Auth#1284]
Not an issue but just a doubt: right now the sql files create utf8_general_ci tables. Can I edit this to utf8mb4_unicode_ci? 
Thanks

**Comment by marios88** [comment]
If i recall correctly, i changed the tables and fields after the initial setup to mb4 with no problems on MariaDB 10.x

**Comment by benedmunds** [comment]
I've never tried it but not aware of anything that would cause issues there.

**Comment by benedmunds** [comment]
Closing, lmk if you hit any issues here and we can reopen.
