### ISSUE TITLE
set_flashdata does not work after libraries/ion_auth.php logout() method if used with CI3 and PHP5

### ISSUE THREAD

**Issue by dgvirtual** [benedmunds/CodeIgniter-Ion-Auth#1285]
I have noticed that if I set flashdata this way in my controller:

	public function logout()
	{
		$this->ion_auth->logout();
		$this->session->set_flashdata('message', $this->ion_auth->messages());
		redirect('user/login', 'refresh');
	}

The flashdata (indicating successful logout) does not get displayed on the user/login page. 

I have traced the problem to this check in libraries/ion_auth.php, line 433:

			if (version_compare(PHP_VERSION, '7.0.0') >= 0)
			{
				session_start();
			}

if I change php version indicated on line 433 to match the one I am using, the flashdata starts working.

**Comment by benedmunds** [comment]
Which exact php version are you on?

**Comment by dgvirtual** [comment]
Yeh, did not specify that: the ones I tested on were 5.6.15, 5.6.37 and some other version in the 5.6.* range.

**Comment by benedmunds** [comment]
Interesting, anyone else seeing an issue with this on PHP 5.x?

**Comment by dgvirtual** [comment]
I have found a thread https://stackoverflow.com/q/42124509/9663356 suggesting various workarounds for (I think) the same problem.

**Comment by abilb** [comment]
From Codeigniter's documentation

[Session Library](https://www.codeigniter.com/user_guide/libraries/sessions.html) -> [Destroying a Session](https://www.codeigniter.com/user_guide/libraries/sessions.html#destroying-a-session)

> This must be the last session-related operation that you do during the same request. All session data (**including flashdata and tempdata**) will be destroyed permanently and functions will be unusable during the same request after you destroy the session.

**Comment by benedmunds** [comment]
Might be better for Ion Auth to overwrite the values it uses rather than destroying the whole session.  I worry about what userland implementations this could break though and wouldnt want to inadvertently open a security hole in users apps if they relying on the destroy action.

**Comment by benedmunds** [comment]
Anyone think this is worth implementing?  

Also anyone want to submit a PR for it or should I?

**Comment by dgvirtual** [comment]
What would be wrong about simply lowering the required PHP version to php5 for session_start() to be executed?

**Comment by benedmunds** [comment]
@dgvirtual that wouldnt fix it would it? Unless we add a redirect as well...

**Comment by dgvirtual** [comment]
@benedmunds , I do have a redirect in my logout function, but that is what is usually done after logout. As far as displaying flashdata display is concerned, it starts to work for me when I set something like

      if (version_compare(PHP_VERSION, '5.6.0') >= 0)

on line 433 (which means the session_start() gets executed). 

My logout function is standard: 

	public function logout()
	{
		if ($this->ion_auth->logged_in()) 
			{
				$this->ion_auth->logout();
				$this->session->set_flashdata('message', $this->ion_auth->messages());
			}
		redirect('user/login', 'refresh');
	}

**Comment by benedmunds** [comment]
I think you're right and we should be safe doing this for all CI3 instances.  Just pushed this, give it a try please https://github.com/benedmunds/CodeIgniter-Ion-Auth/commit/bb8f867a34b02af1dde7889f43fcf1835819ca95

**Comment by benedmunds** [comment]
@dgvirtual ^

**Comment by dgvirtual** [comment]
@benedmunds , this change is ok, works for me now, thank you.

**Comment by dgvirtual** [comment]
@benedmunds, just a short unrelated query that you can delete: on your webpage http://benedmunds.com/ion_auth/ you seem to still recommend version 2 of Ion Auth. Should it be replaced with version 3 for the purposes of CI3 applications?

**Comment by benedmunds** [comment]
@dgvirtual thanks for the heads up, it's been updated now
