### ISSUE TITLE
Consider to migrate to CI4

### ISSUE THREAD

**Issue by tpw1314** [benedmunds/CodeIgniter-Ion-Auth#1286]
I just want to know if any of you especially Bend plan to upgrade/migrate to CodeIgniter 4 ?
I am interested to contribute. So if no one intends to do that I will create one prototype and post the repo here.

**Comment by bvrignaud** [comment]
Hello, as you can see, I have worked on it :

- https://github.com/benedmunds/CodeIgniter-Ion-Auth/issues/1270

- https://github.com/benedmunds/CodeIgniter-Ion-Auth/tree/4

- https://github.com/bvrignaud/CodeIgniter-Ion-Auth/tree/4

It's steel in progress.

Your help is welcome.

**Comment by tpw1314** [comment]
Glad to hear that. But I see some files are few days outdated as compared to CI4 master. I will fork out from CI4 and amend according to Ion-Auth.

The question is, should I follow branch 3 or branch 2 ?? Which is more up-to-date in terms of feature and stability ?

**Comment by bvrignaud** [comment]
Be careful, actually all the woks are on my repo : https://github.com/bvrignaud/CodeIgniter-Ion-Auth/tree/4 . No merges have been done yet.
I used the branch 3 to start the 4 one.

**Comment by bvrignaud** [comment]
https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/1273

The branch 4 is up to date with the 3 one.

**Comment by benedmunds** [comment]
Closing since this us being worked under #1273
