### ISSUE TITLE
Capitalize the first letter of folder name + file name

### ISSUE THREAD

**Issue by tpw1314** [benedmunds/CodeIgniter-Ion-Auth#1287]
In CI4, the first letter of all folders' name in 'application' are capitalized (as well as /config file). Would not it be better if Ion-Auth 4 follows the same approach to match CI4 ?

I have tried to changed mine in local repo but github wont recognize it as changes.
![image](https://user-images.githubusercontent.com/20537849/48691398-6a7b5e00-ec0d-11e8-88e5-5b6391d4373c.png)

**Comment by bvrignaud** [comment]
This branch is WIP.
Look at 
IonAuth4 still follows the same approach to CI4.
Have a look to :
- https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/1273
- https://github.com/bvrignaud/CodeIgniter-Ion-Auth/tree/4

**Comment by benedmunds** [comment]
Closing since this is handled in the upcoming version from @bvrignaud
