### ISSUE TITLE
Session inactivity

### ISSUE THREAD

**Issue by geoffcording** [benedmunds/CodeIgniter-Ion-Auth#1288]
I am running ion_auth 2.5.2 I have seen several references to 'sess_expiration' but cannot find it anywhere. Is it implemented in a version later than my own? I also cannot find any reference on this (http://benedmunds.com/ion_auth/) page.
What I would like to do is set an inactivity time which, when expired, triggers an event that allows me to refresh the user's page back to a nominated page and issue a message stating they have been logged out due to inactivity. I assume I would also need to invoke a function to tell ion_auth that activity is occurring rather than assume there will be a call to ion_auth based upon what the user is actually doing. The effect should be ... user does nothing, inactivity event triggered, set message, force new page. As it stands, the user is unaware of the expiry until they force interaction with the server, which I find irritating.
Any suggestions, examples would be appreciated.
Thanks
Geoff

**Comment by benedmunds** [comment]
Hey,

The session expiration is a CI config setting: https://www.codeigniter.com/user_guide/libraries/sessions.html#session-preferences

There are a few ways you could do what you want, it would probably be a custom implementation.  You could have a session variable that store a last activity timestamp, if the timestamp is over X old then redirect them to your new error page and force a log out.

**Comment by geoffcording** [comment]
Thank you.
I think the issue was (for me) that the sess_** values to be defined in config.php are described under the session library documentation pages whereas I was looking for them in the ion_auth pages where config options are described. There was nothing that suggested to me that there were other values described elsewhere. This was reinforced by the absence of any sess_*** values in the supplied config file, nor could I find any reference in the ion_auth controller code. You may wish to consider adding some sort of reference to any additional config values in the primary config documentation or at least a comment in the supplied config.php file. With your timestamp suggestion, that would still require the user to send a page back to the server in order to check for timeout. Could your hook mechanism be used in any way? I guess the question depends upon whether your session expiry is implemented via a timer pop event or a test every time ion_auth is invoked.
Again thanks
Geoff

**Comment by benedmunds** [comment]
Great suggestion on the documentation update, reopening this until I make that.

In order to alert the user without a new activity being required you’d need to use JavaScript. Maybe long poll against an endpoint that tells you if you still have an active session, then redirect if you don’t.
