### ISSUE TITLE
        $this->load->library('ion_auth');

### ISSUE THREAD

**Issue by ct0182** [benedmunds/CodeIgniter-Ion-Auth#1312]
My apologies if this is not a bug, I am unable to "secure" a page by loading  $this->load->library('ion_auth');  yet ion_auth is installed.
 
**Which branch are you using?**
3
**What commit hash are you on?**
 c90d9e9

**Describe the bug**
Severity: Notice
Message: Undefined property: Home::$db
Filename: models/Ion_auth_model.php

**To Reproduce**
Add "        $this->load->library('ion_auth');        " to a public function within a controller.

e.g
class Home extends CI_Controller {

	public function index()
	{
        $this->load->library('ion_auth');        
}
}

**Comment by benedmunds** [comment]
You'll need to have a DB connection setup and loaded in CI before you load Ion Auth.

**Comment by benedmunds** [comment]
Closing.  @ctaylor-c172 please tag me if this is still an issue and I'll reopen it.
