### ISSUE TITLE
Update Group Documentation

### ISSUE THREAD

**Issue by walknight** [benedmunds/CodeIgniter-Ion-Auth#1313]
Hello, i dont know if this is a bugs or not

I ussed ion auth brach 3 and when i look at the Update Groups Function in documentation, in there say that to use that function is :

```
// source these things from anywhere you like (eg., a form)
        $group_id = 2;
        $group_name = 'test_group_changed_name';
        $group_description = 'I changed the name yay';

        // pass the right arguments and it's done
        $group_update = $this->ion_auth->update_group($group_id, $group_name, $group_description);
```

but when i try to update some group, the group description not change. And then i see the ion_auth_model.php, and search update_group function. In there function describe this :

`public function update_group($group_id = FALSE, $group_name = FALSE, $additional_data = [])`

and i think this is miss group_description variable so the group description not change.

But i figuring out to change that group description so i put group_description value and field name to array and put in to additional_data variable :

`$additional_data = array('description'=>'some description change');`

and then my group description change.

I think you should change the documentation how to used update_group method. :)

**Comment by benedmunds** [comment]
Thanks!  This has been fixed with https://github.com/benedmunds/CodeIgniter-Ion-Auth/commit/c5aa0a9b30c91674c3af9bbca3aa91d38d67ee2c
