### ISSUE TITLE
Login destination

### ISSUE THREAD

**Issue by seven0sam** [benedmunds/CodeIgniter-Ion-Auth#1318]
Hello,

I can't find anything related to login destination in the docs. Suppose I opened the products sections of my website while not logged in, so ion_auth will redirect me to auth/login. But after successful login, it should send me back to where I came from (products section). Does this make sense? 

Thanks.

**Comment by benedmunds** [comment]
Hey, the Ion auth library is agnostic about this. Feel free to change the example controller to redirect to whatever you need after login.
