### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by spitfire64** [benedmunds/CodeIgniter-Ion-Auth#1325]
I try to login with "admin@admin.com/password". When I submit, I get redirected back to the login page. However, I can see an error message for like 0.1 sec before the redirect.

If I halt (exit) the script Auth.php on line 78 (just before the redirect back to auth/login), the error is caught:
```
A PHP Error was encountered
Severity: Warning

Message: password_hash(): Invalid bcrypt cost parameter specified: 0

Filename: models/Ion_auth_model.php

Line Number: 281

Backtrace:

File: C:\xampp\htdocs\ci3ia3\application\models\Ion_auth_model.php
Line: 281
Function: password_hash

File: C:\xampp\htdocs\ci3ia3\application\models\Ion_auth_model.php
Line: 952
Function: hash_password

File: C:\xampp\htdocs\ci3ia3\application\libraries\Ion_auth.php
Line: 113
Function: login

File: C:\xampp\htdocs\ci3ia3\application\controllers\Auth.php
Line: 66
Function: __call

File: C:\xampp\htdocs\ci3ia3\index.php
Line: 315
Function: require_once
```

**Comment by benedmunds** [comment]
What version of PHP are you using?

**Comment by spitfire64** [comment]
Sorry for the missing info.
CI 3.1.9
PHP 7.1.7

**Comment by benedmunds** [comment]
@spitfire64 Thanks!  Post your Ion Auth config please

**Comment by spitfire64** [comment]
For some reason, the password was deleted from admin in my database. I put it back it and now it works again. Probably some issue on my side. Thanks.
