### ISSUE TITLE
 Thread Modes Error Unable to De-Activate Account when registering a new user

### ISSUE THREAD

**Issue by enfrte** [benedmunds/CodeIgniter-Ion-Auth#1326]
After updating to Ion-Auth 3, I'm getting the error `Unable to De-Activate Account` when trying to register a new user. 

Here is the code I'm calling. 

    $user_id = $this->ion_auth->register($username, $password, $email, $additional_data, $group_ids);    
    // $user_id returns false when doing a var_dump

    // update the user requirements
    if($user_id !== FALSE) {
      $this->session->set_flashdata('message',$this->ion_auth->messages()); // message confirming user was created 
      $this->requirements_model->update_user_requirements($this->input->post('requirements'), $user_id);
    } 
    else {
	  $this->session->set_flashdata('message', $this->ion_auth->errors());
    } 

Before I last updated (which was about two years ago) everything was working fine. I'm using email as the identity and I've followed the update guide in github. 

What is causing that error? The message doesn't seem to be relevant. There are no users in the database with the email I'm trying to register. Thanks. 

### More info 

CI version 3.1.8

Php version:  7.2.15

	<?php
	/**
	 * Name:    Ion Auth
	 * Author:  Ben Edmunds
	 *           ben.edmunds@gmail.com
	 *           @benedmunds
	 *
	 * Added Awesomeness: Phil Sturgeon
	 *
	 * Created:  10.01.2009
	 *
	 * Description:  Modified auth system based on redux_auth with extensive customization. This is basically what Redux Auth 2 should be.
	 * Original Author name has been kept but that does not mean that the method has not been modified.
	 *
	 * Requirements: PHP5.6 or above
	 *
	 * @package    CodeIgniter-Ion-Auth
	 * @author     Ben Edmunds
	 * @link       http://github.com/benedmunds/CodeIgniter-Ion-Auth
	 * @filesource
	 */
	defined('BASEPATH') OR exit('No direct script access allowed');

	/*
	 | -------------------------------------------------------------------------
	 | Database group name option.
	 | -------------------------------------------------------------------------
	 | Allows to select a specific group for the database connection
	 |
	 | Default is empty: uses default group defined in CI's configuration
	 | (see application/config/database.php, $active_group variable)
	 */
	$config['database_group_name'] = '';

	/*
	| -------------------------------------------------------------------------
	| Tables.
	| -------------------------------------------------------------------------
	| Database table names.
	*/
	$config['tables']['users']           = 'users';
	$config['tables']['groups']          = 'groups';
	$config['tables']['users_groups']    = 'users_groups';
	$config['tables']['login_attempts']  = 'login_attempts';

	/*
	 | Users table column and Group table column you want to join WITH.
	 |
	 | Joins from users.id
	 | Joins from groups.id
	 */
	$config['join']['users']  = 'user_id';
	$config['join']['groups'] = 'group_id';

	/*
	 | -------------------------------------------------------------------------
	 | Hash Method (bcrypt or argon2)
	 | -------------------------------------------------------------------------
	 | Bcrypt is available in PHP 5.3+
	 | Argon2 is available in PHP 7.2
	 |
	 | Argon2 is recommended by expert (it is actually the winner of the Password Hashing Competition
	 | for more information see https://password-hashing.net). So if you can (PHP 7.2), go for it.
	 |
	 | Bcrypt specific:
	 | 		bcrypt_default_cost settings:  This defines how strong the encryption will be.
	 | 		However, higher the cost, longer it will take to hash (CPU usage) So adjust
	 | 		this based on your server hardware.
	 |
	 | 		You can (and should!) benchmark your server. This can be done easily with this little script:
	 | 		https://gist.github.com/Indigo744/24062e07477e937a279bc97b378c3402
	 |
	 | 		With bcrypt, an example hash of "password" is:
	 | 		$2y$08$200Z6ZZbp3RAEXoaWcMA6uJOFicwNZaqk4oDhqTUiFXFe63MG.Daa
	 |
	 |		A specific parameter bcrypt_admin_cost is available for user in admin group.
	 |		It is recommended to have a stronger hashing for administrators.
	 |
	 | Argon2 specific:
	 | 		argon2_default_params settings:  This is an array containing the options for the Argon2 algorithm.
	 | 		You can define 3 differents keys:
	 | 			memory_cost (default 4096 kB)
	 |				Maximum memory (in kBytes) that may be used to compute the Argon2 hash
	 |				The spec recommends setting the memory cost to a power of 2.
	 | 			time_cost (default 2)
	 |				Number of iterations (used to tune the running time independently of the memory size).
									This defines how strong the encryption will be.
	 | 			threads (default 2)
	 |				Number of threads to use for computing the Argon2 hash
	 |				The spec recommends setting the number of threads to a power of 2.
	 |
	 | 		You can (and should!) benchmark your server. This can be done easily with this little script:
	 | 		https://gist.github.com/Indigo744/e92356282eb808b94d08d9cc6e37884c
	 |
	 | 		With argon2, an example hash of "password" is:
	 | 		$argon2i$v=19$m=1024,t=2,p=2$VEFSSU4wSzh3cllVdE1JZQ$PDeks/7JoKekQrJa9HlfkXIk8dAeZXOzUxLBwNFbZ44
	 |
	 |		A specific parameter argon2_admin_params is available for user in admin group.
	 |		It is recommended to have a stronger hashing for administrators.
	 |
	 | For more information, check the password_hash function help: http://php.net/manual/en/function.password-hash.php
	 |
	 */
	$config['hash_method']				= 'bcrypt';	// bcrypt or argon2
	$config['bcrypt_default_cost']		= 10;		// Set cost according to your server benchmark - but no lower than 10 (default PHP value)
	$config['bcrypt_admin_cost']		= 12;		// Cost for user in admin group
	$config['argon2_default_params']	= [
		'memory_cost'	=> 1 << 12,	// 4MB
		'time_cost'		=> 2,
		'threads'		=> 2
	];
	$config['argon2_admin_params']		= [
		'memory_cost'	=> 1 << 14,	// 16MB
		'time_cost'		=> 4,
		'threads'		=> 2
	];

	/*
	 | -------------------------------------------------------------------------
	 | Authentication options.
	 | -------------------------------------------------------------------------
	 | maximum_login_attempts: 	This maximum is not enforced by the library, but is used by
	 | 							is_max_login_attempts_exceeded().
	 | 							The controller should check this function and act appropriately.
	 | 							If this variable set to 0, there is no maximum.
	 | min_password_length:		This minimum is not enforced directly by the library.
	 | 							The controller should define a validation rule to enforce it.
	 | 							See the Auth controller for an example implementation.
	 |
	 | The library will fail for empty password or password size above 4096 bytes.
	 | This is an arbitrary (long) value to protect against DOS attack.
	 */
	$config['site_title']                 = "Example.com";       // Site Title, example.com
	$config['admin_email']                = "admin@example.com"; // Admin Email, admin@example.com
	$config['default_group']              = 'members';           // Default group, use name
	$config['admin_group']                = 'admin';             // Default administrators group, use name
	$config['identity']                   = 'email';             /* You can use any unique column in your table as identity column.
																		The values in this column, alongside password, will be used for login purposes
																		IMPORTANT: If you are changing it from the default (email),
																					 update the UNIQUE constraint in your DB */
	$config['min_password_length']        = 8;                   // Minimum Required Length of Password (not enforced by lib - see note above)
	$config['email_activation']           = TRUE;               // Email Activation for registration
	$config['manual_activation']          = FALSE;               // Manual Activation for registration
	$config['remember_users']             = TRUE;                // Allow users to be remembered and enable auto-login
	$config['user_expire']                = 86500;               // How long to remember the user (seconds). Set to zero for no expiration - see sess_expiration in CodeIgniter Session Config for session expiration
	$config['user_extend_on_login']       = FALSE;               // Extend the users cookies every time they auto-login
	$config['track_login_attempts']       = TRUE;                // Track the number of failed login attempts for each user or ip.
	$config['track_login_ip_address']     = TRUE;                // Track login attempts by IP Address, if FALSE will track based on identity. (Default: TRUE)
	$config['maximum_login_attempts']     = 5;                   // The maximum number of failed login attempts.
	$config['lockout_time']               = 300;                 /* The number of seconds to lockout an account due to exceeded attempts
																	You should not use a value below 60 (1 minute) */
	$config['forgot_password_expiration'] = 0;                /* The number of seconds after which a forgot password request will expire. If set to 0, forgot password requests will not expire.
																						30 minutes to 1 hour are good values (enough for a user to receive the email and reset its password)
																						You should not set a value too high, as it would be a security issue! */
	$config['recheck_timer']              = 0;                   /* The number of seconds after which the session is checked again against database to see if the user still exists and is active.
																	Leave 0 if you don't want session recheck. if you really think you need to recheck the session against database, we would
																	recommend a higher value, as this would affect performance */

	/*
	 | -------------------------------------------------------------------------
	 | Cookie options.
	 | -------------------------------------------------------------------------
	 | remember_cookie_name Default: remember_code
	 */
	$config['remember_cookie_name'] = 'remember_code';

	/*
	 | -------------------------------------------------------------------------
	 | Email options.
	 | -------------------------------------------------------------------------
	 | email_config:
	 | 	  'file' = Use the default CI config or use from a config file
	 | 	  array  = Manually set your email config settings
	 */
	$config['use_ci_email'] = TRUE; // Send Email using the builtin CI email class, if false it will return the code and the identity
	$config['email_config'] = [
		'mailtype' => 'html',
	];

	/*
	 | -------------------------------------------------------------------------
	 | Email templates.
	 | -------------------------------------------------------------------------
	 | Folder where email templates are stored.
	 | Default: auth/
	 */
	$config['email_templates'] = 'admin/email/';

	/*
	 | -------------------------------------------------------------------------
	 | Activate Account Email Template
	 | -------------------------------------------------------------------------
	 | Default: activate.tpl.php
	 */
	$config['email_activate'] = 'activate.tpl.php';

	/*
	 | -------------------------------------------------------------------------
	 | Forgot Password Email Template
	 | -------------------------------------------------------------------------
	 | Default: forgot_password.tpl.php
	 */
	$config['email_forgot_password'] = 'forgot_password.tpl.php';

	/*
	 | -------------------------------------------------------------------------
	 | Message Delimiters.
	 | -------------------------------------------------------------------------
	 */
	$config['delimiters_source']       = 'config'; 	// "config" = use the settings defined here, "form_validation" = use the settings defined in CI's form validation library
	$config['message_start_delimiter'] = '<div class="alert alert-success">'; // Message start delimiter
	$config['message_end_delimiter']   = '</div>'; // Message end delimiter
	$config['error_start_delimiter']   = '<div class="alert alert-danger">'; // Error message start delimiter
	$config['error_end_delimiter']     = '</div>'; // Error message end delimiter

**Comment by benedmunds** [comment]
Try it with $config['email_activation']=FALSE and see what happens

**Comment by enfrte** [comment]
Hi, Thanks for replying. 

Yes, it worked. The user is created and no activation email is sent. Is it a problem with the email settings? This would be strange because the email settings are identical to the old version, which currently work.

**Comment by benedmunds** [comment]
Could be the email... try adding troubleshooting code through the library and model register methods to narrow down where it’s failing from exactly

**Comment by enfrte** [comment]
I stepped through the register function in ion_auth_model.php and everything looked fine. It then passed me to the register function in  ion_auth.php where it assigned false to `$deactivate = $this->ion_auth_model->deactivate($id);` ($id == 70, $email_activation == true). 

Back in the deactivate function in ion_auth_model.php, we seem to have all the data for `$this->db->update($this->tables['users'], $data, ['id' => $id]);` but `$return = $this->db->affected_rows() == 1;` returns false `$this->set_error('deactivate_unsuccessful');` is called, and we are back to the register function in  ion_auth.php.

After evaluating false when tested here

	if (!$deactivate)
	{
		$this->set_error('deactivate_unsuccessful');
		$this->ion_auth_model->trigger_events(['post_account_creation', 'post_account_creation_unsuccessful']);
		return FALSE;
	}

I'm returned to my controller where $user_id returns false. I'm not really sure why it fails to insert into the database.

**Comment by benedmunds** [comment]
Var Dump $data and $id there.

Also do a select * from users where id=70, directly against the DB and post the results please.

**Comment by enfrte** [comment]
```
C:\xampp\htdocs\aikataulu_local\application\models\Ion_auth_model.php:485:
array (size=3)
  
'activation_selector' => string '67e9d6534f32e1428c02' (length=20)
  
'activation_code' => string '$2y$10$09.gjCnAZW1JLgSWvsQ5.usTBwns/KIUS5UmhvBeeZaURugbi/Lb6' (length=60)
  
'active' => int 0

C:\xampp\htdocs\aikataulu_local\application\models\Ion_auth_model.php:485:int 73
```

and 

`select * from users where id=70`

Returned nothing.

**Comment by benedmunds** [comment]
Interesting, didn’t the earlier post say the ID was 70? Maybe something deleted it?

**Comment by enfrte** [comment]
Yes, it is. Every time I run it and it fails, it uses up a PK ID, even though it doesn't register the user row. I wasn't sure if it was standard MySQL behaviour, but now you mention it, it doesn't really make much sense. 

I'll look into if something maybe deleting it, but I can't really think of anything I've made that would do that.

**Comment by benedmunds** [comment]
Definitely seems like it’s failing at the db level then. See if you can add more logging, or bump up the CI error log reporting, to narrow down on which query is failing and why. Probably do data doesn’t match what the DB expects.

**Comment by benedmunds** [comment]
Closing due to time elapsed since the last response.  Please submit a new ticket if this is still an issue.
