### ISSUE TITLE
Access Login Page when Logged

### ISSUE THREAD

**Issue by sunuazizrahayu** [benedmunds/CodeIgniter-Ion-Auth#1329]
**Which branch are you using?**
3

**What commit hash are you on?**
Attempt updating to the latest commit on your branch.

**What CodeIgniter version are you using?**
v3

**What PHP version are you using?**
PHP 7.2

**Post your Ion Auth config below**
```
default config of branch 3
```

**Describe the bug**
i can access login page when i was logged. i think that we cant access login page when we're logged in.

**To Reproduce**

**Expected behavior**
i hope you add some protection to prevent login page when you're logged in, forgot password too.

**Comment by benedmunds** [comment]
Hey, this isn’t an error per se but you can change this.  The controller and views here are just examples of how to use the library, feel free to change them to match your needs.

I usually allow users to access the login page if logged in, in case they want to login as a different user. You could instead redirect them somewhere else or log them out.
