### ISSUE TITLE
Branch 4 will not install with composer

### ISSUE THREAD

**Issue by pkMyt1** [benedmunds/CodeIgniter-Ion-Auth#1336]
When attempting to install with composer I get this error:
PS C:\Users\g2che\OneDrive\htdocs\TriLIMS> composer require benedmunds/CodeIgniter-Ion-Auth:4.0.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for benedmunds/codeigniter-ion-auth 4.0.0 -> satisfiable by benedmunds/codeigniter-ion-auth[4.0.0].
    - benedmunds/codeigniter-ion-auth 4.0.0 requires codeigniter4/framework develop-dev -> no matching package found.

I think the problem is this line in your composer.jason file:
      "codeigniter4/framework": "develop-dev"

It should be:
    "codeigniter4/framework": "dev-master"

**Comment by benedmunds** [comment]
Hey I updated the instructions this morning actually, did you run the add repo command first?

**Comment by pkMyt1** [comment]
Yes.  I think the CI folks may have made a name change

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by benedmunds** [comment]
Ah gotcha, @bvrignaud think we should use master or develop here?  Master is more stable but fairly out of date atm.

**Comment by pkMyt1** [comment]
Good question. I have been working with the dev branch

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by eyounelson** [comment]
Hi  @benedmunds  I have a fairly similar issue. The message from composer:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for benedmunds/codeigniter-ion-auth 4.0.0 -> satisfiable by benedmunds/codeigniter-ion-auth[4.0.0].
    - benedmunds/codeigniter-ion-auth 4.0.0 requires codeigniter4/framework develop-dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```
I'm working with CI appstarter beta.1

**Comment by benedmunds** [comment]
Updated CI dependency to dev-master for now

**Comment by benedmunds** [comment]
@dot-brainy can you try again please

**Comment by eyounelson** [comment]
I was not able to get it to work. Composer returned the same error.
I cloned the git repo instead

It is probably an issue from my PC, because even `composer update` on any project returns some kind of error.

**Comment by benedmunds** [comment]
Ah I see, Codeigniter dropped the "4" from their composer package name.  Just pushed a fix.

**Comment by pkMyt1** [comment]
Still no joy, same error.  When I install Codeigniter4 with Composer I get this in my .jason file:
    "require": {
        "php": ">=7.2",
        "codeigniter4/codeigniter4": "dev-master",

So I think your original name was fine.  I don't know Composer well but where ever it is pulling this line from is likely the problem:
 - benedmunds/codeigniter-ion-auth 4.0.0 requires codeigniter4/framework develop-dev -> no matching package found.

**Comment by benedmunds** [comment]
@pkMyt1 can you make sure you're on the newest code?  The require was changed to ""codeigniter/framework": "dev-master"" so you shouldnt see codeigniter4 in that error.

**Comment by pkMyt1** [comment]
@benedmunds.  I did a fresh install of both the Codeigniter4/appstarter and Codedigniter4/devstarter.  Both give the identical error when attempting to install Ion Auth 4 with Composer.

**Comment by benedmunds** [comment]
Hmm looks like the appstarter is using:
```
"codeigniter4/framework": "^4@alpha"
```
and devstarter is using:
```
"codeigniter4/codeigniter4": "dev-master"
```

@pkMyt1 do both of these install fine for you?

**Comment by pkMyt1** [comment]
Yep.  Both install and both give me the welcome page

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by benedmunds** [comment]
@pkMyt1 ok cool, I just pushed a change for Ion Auth to match devstarter.  Lmk if that works for you as well please.  Thanks!

**Comment by pkMyt1** [comment]
@benedmunds I need to offer my sincere apologizes.   I forked your repo so I could try some different configs in the composer.json file.  It looks like my changes got pushed through to your repo.  I did not think that was possible.  I will remove my fork now.

**Comment by benedmunds** [comment]
@pkMyt1 hey, I'm not seeing any changes, it probably pushed changes to your fork

**Comment by pkMyt1** [comment]
I think I need to get a good sleep and then look at this again.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gesmit** [comment]
Can't install using composer on rc1 ( "codeigniter4/framework": "^4@rc" )

**Comment by benedmunds** [comment]
@gesmit doesn't look like CI has an RC branch/tag so I guess you'll need the full tag.  Try this:

```
"codeigniter4/framework": "v4.0.0-rc.1"
````

**Comment by barentshavet** [comment]
I have the same issues as above.

What is the solution on this?

**Comment by benedmunds** [comment]
@sigveringseth what issue are you seeing exactly?

**Comment by nachoaguirre** [comment]
hi! got the same problem...
 
my json:
"require": {
        "php": ">=7.2",
        "codeigniter4/framework": "^4@rc"
    },

"repositories": {
        "ionAuth": {
            "type": "vcs",
            "url": "git@github.com:benedmunds/CodeIgniter-Ion-Auth.git"
        }
    }
-----------------

my terminal output:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for benedmunds/codeigniter-ion-auth 4.x-dev -> satisfiable by benedmunds/codeigniter-ion-auth[4.x-dev].
    - benedmunds/codeigniter-ion-auth 4.x-dev requires codeigniter4/framework dev-master -> satisfiable by codeigniter4/framework[dev-master] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.



thanks!

**Comment by benedmunds** [comment]
What minimum stability are you using?

**Comment by nachoaguirre** [comment]
@benedmunds im using dev.
im using the appstarter repo with codeigniter 4 (clean installation)...

this is my entire composer .json:

{
    "name": "codeigniter4/appstarter",
    "type": "project",
    "description": "CodeIgniter4 starter app",
    "homepage": "https://codeigniter.com",
    "license": "MIT",
    "require": {
        "php": ">=7.2",
        "codeigniter4/framework": "^4@rc"
    },
    "require-dev": {
        "mikey179/vfsstream": "1.6.*",
        "phpunit/phpunit": "^7.0"
    },
    "scripts": {
        "post-update-cmd": [
            "@composer dump-autoload"
        ]
    },
    "support": {
        "forum": "http://forum.codeigniter.com/",
        "source": "https://github.com/codeigniter4/CodeIgniter4",
        "slack": "https://codeigniterchat.slack.com"
    },
    "minimum-stability": "dev",
    "repositories": {
        "ionAuth": {
            "type": "vcs",
            "url": "git@github.com:benedmunds/CodeIgniter-Ion-Auth.git"
        }
    }
}

**Comment by bvrignaud** [comment]
Hell, I think we have to remove the '"codeigniter4/framework": "^4@rc"' line for now.
We will re-add it later when CI4 will be ready.

**Comment by benedmunds** [comment]
Yea fair point.  Removed it.
