### ISSUE TITLE
Vulnerability : Fail to invalidate session on Password Reset

### ISSUE THREAD

**Issue by amchicas** [benedmunds/CodeIgniter-Ion-Auth#1340]
Hello there, 
I observed that when we change password from password reset form one browser
in place of session Expire from other browser its just update password from
other browser and the old session got updated without being logout
It allows one account to be used with two sessions (different browsers) initiating with two different passwords at the same time.
any advice?

**Comment by benedmunds** [comment]
There's not a great way to do this in realtime without a performance decrease.  The simplest way to do this, off the top of my head, is to store the password hash in the session and check that against the database with a hook in logged_in().  

Anyone else feel free to chime in if you've done this before and have a good solution?

**Comment by amchicas** [comment]
I am using the table ci_sessions in the database to save sessions, so I am thinking to add a user_id column and when it is used the reset_password function delete all sessions with the same user_id.

**Comment by afagard** [comment]
Whether or not you change the password, if the session is valid and hasn't been invalidated you'll still have access in the browsers where the sessions aren't expired. To me I don't find it much of a security risk. Google and Facebook allow multiple sessions on different devices. Although having 1 allowable session per user is an interesting thought - I think in the end it would be more trouble than it is worth.

**Comment by benedmunds** [comment]
I agree with @afagard and this is why we've never tried to implement this.  I've done plenty of HIPAA safe and apps for large security focused enterprises with this not being an issue.

Not saying there's never a reason for this but I would recommend pushing back on why you're being asked to do this before throwing a lot of time in to it.

**Comment by benedmunds** [comment]
Closing due to time elapsed since the last response.  Please submit a new ticket if this is still an issue.
