### ISSUE TITLE
Database needs to be explicitly loaded before using Ion Auth3?

### ISSUE THREAD

**Issue by romant-1** [benedmunds/CodeIgniter-Ion-Auth#1346]
Hi,
I just tried to switch from Ion Auth2 to Ion Auth3 and it looks like the database needs to be loaded first now before loading Ion Auth. If I don't load the database first I get the error message

```
<p>Severity: Notice</p>
<p>Message:  Undefined property: MyAwesomeController ::$db</p>
<p>Filename: models/Ion_auth_model.php</p>
<p>Line Number: 212</p>
```
Here is the controller:
```
class MyAwesomeController extends CI_Controller {

    public function __construct() {
        parent::__construct();
        $this->load->add_package_path(APPPATH.'third_party/ion_auth/'); // fails in Ion Auth3
        $this->load->library('ion_auth');
         .....
    }
}
.....
```
It wasn't needed to load the database first and the above code worked fine in Ion Auth2. Has this behavior been introduced deliberately?
Thanks

**Comment by benedmunds** [comment]
I don’t believe this has changed between 2 and 3. The example controller for both branches loads the DB before losing Ion Auth.  Can you pinpoint a difference?

**Comment by romant-1** [comment]
Of course it has changed. I'm not talking about the example Auth.php controller - the db has been loaded there first since ever.

I'm talking about the Ion Auth library code itself. With Ion Auth 2 I didn't have to load DB first, with Ion Auth 3 I have to otherwise I get the error mentioned above.

I can see that the Ion_auth_model.php file used to load the DB first but then this has changed - see the commit [here](https://github.com/benedmunds/CodeIgniter-Ion-Auth/commit/2f6c6eb9a508e99af5ba768488043bd30a076583#diff-6c07b5299da915667ed377b3f9b8adb4
).

If you look at [the latest version](https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/models/Ion_auth_model.php) of the Ion_auth_model.php file you will notice that this has changed even more since then and the DB is loaded only under certain conditions. Line 212 apparently expects the DB to be already loaded - which in my case fails as Ion Auth 2 didn't have this requirement.

As long as this is the intended behavior and not a bug or regression I'm happy, I would just expect a warning that Ion Auth 3 requires the DB to be loaded first before it can be used.

Or maybe we can put it in such a way that it has been always a requirement to load the DB first considering the code in the example Auth.php file and it was just a lucky coincidence that in Ion Auth 2 the DB didn't have to be loaded first.

**Comment by benedmunds** [comment]
Hey sorry, didn't mean to imply that you were incorrect, just asking for help pinpointing this.  It's been years since I wrote/merged this code so don't remember off the top of my head.

I agree with you that if it's an intended effect it should be documented but I need to try to narrow down the change so I can review git history on it.

It looks like the db loading in the model is the same across the 2 and 3 branches, unless there's an older version of the 2 branch that loaded differently, which is very possible.  Does this match what you're seeing:

2 branch -
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/models/Ion_auth_model.php#L185

3 branch - 
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/models/Ion_auth_model.php#L206

**Comment by benedmunds** [comment]
My bet is that 2 used to always load it, conditional loading was added to 3, then backported to 2.  Still investigating..

```
git branch -r --contains=2f6c6eb9a508e99af5ba768488043bd30a076583
  origin/2
  origin/3
  origin/4
  origin/feature/06142018_fixed_issue_with_mysql_in_group_type_checking
  origin/hotfix/session_regena_after_destroy
```

Ok yea, looks like this is what changed it, and it wasn't changed strictly on purpose:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/commit/c34c939a26f2b9b003c49ad0ce8f6bc673faacf0

**Comment by benedmunds** [comment]
@romant-1 I pushed a potential fix for this, can you confirm if it resolves this for you?  https://github.com/benedmunds/CodeIgniter-Ion-Auth/commit/33b797876fb1a96eadef1565f3d259acac012352

**Comment by romant-1** [comment]
Yes, this fixes the issue, thanks. 
But hey Ben, don't let me push you fix something that maybe doesn't need to be fixed. If it makes more sense to you to expect that the database has been already loaded then leave it that way and just document it. That would be apparently fine too as otherwise someone would have already complained about this issue but I'm the first one long time after the code has been released so it's probably not a big deal. I'll leave the decision with you.

Thanks for looking into this and sorry for being unnecessarily too direct.

**Comment by benedmunds** [comment]
Oh no worries, this was an unexpected side affect so should be fixed.  It doesn't hurt anything to load the DB twice anyway since CI will return the existing DB if it exists.

Thanks for reporting and testing it!  Take care!

**Comment by marios88** [comment]
@benedmunds 
Sorry for the late reply, please have a look at #1258 as this seems to revert it

**Comment by benedmunds** [comment]
@marios88 oh thanks for pointing this out!  I completely forgot about this issue...

@romant-1 ok looks like I spoke too soon.  I'm going to revert this change and go with a documentation change instead.  Forgot that CI doesn't reuse connections if they are returned...
