### ISSUE TITLE
Empty message call returns error

### ISSUE THREAD

**Issue by pkMyt1** [benedmunds/CodeIgniter-Ion-Auth#1347]
**Which branch are you using?**
Branch 4

**What commit hash are you on?**
Attempt updating to the latest commit on your branch.

**What CodeIgniter version are you using?**
v4

**What PHP version are you using?**
PHP 7.2

**Post your Ion Auth config below**
```
Config goes here
```

**Describe the bug**
If a call is made to set an ionAuth message and the message doesn't exist an empty string is returned throwing an error.  Granted this should not happen in your controller but could if someone is integrating your code into their project. The error is from ionAuthModel line 2392

	public function messages(): array
	{
		if (empty($this->messages))
		{
			return '';
		}

Any reason not to return a [] instead?  As far as I can tell it does not break anything.

**To Reproduce**
This is a simple method to reproduce it.  
print_r($this->session->setFlashdata('message', $this->ionAuth->messages()));

Return value of IonAuth\Models\IonAuthModel::messages() must be of the type array, string returned

**Expected behavior**
Return an empty message array not a string.

**Comment by benedmunds** [comment]
Are you on the latest version of the 4 branch?  Cause the return type for the messages method is set to string here:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/4/Models/IonAuthModel.php#L2387

**Comment by pkMyt1** [comment]
Yep, on latest version.  I found that block of code.   I wanted to know if there was any reason not to return an empty array instead of an empty string.  The empty string throws an error while the empty array does not.  I tested it and if appears to work with the empty array

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by benedmunds** [comment]
messages() should always return a string, even if it's an empty string.  If you want an array back you can use messagesArray() instead.

Here's a link to it:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/4/Models/IonAuthModel.php#L2410

I'm not sure how the code you posted has an array return type though, cause that doesn't match the codebase.  Can you double check that you're on the latest commit.

**Comment by pkMyt1** [comment]
Not a bug, just my addled brain.  I couldn't figure out how to get your message view into my templates so I had changed that to return an array that I can display.  I forgot to document it.

In case I haven't mentioned it, this is an awesome security framework you developed.  I have used it in the past for a LIMS for academic research labs.  I am working on a new version now.  Just a bit rusty with PHP

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by benedmunds** [comment]
No worries!  Definitely keep us informed about your experience using v4, it’s still very new code so any feedback is helpful.
