### ISSUE TITLE
Activation email with sprintf(): Too few arguments

### ISSUE THREAD

**Issue by strzala-dj** [benedmunds/CodeIgniter-Ion-Auth#1351]
CI v3, PHP v7

I have configured email activation and the email I receive contains errors below.
What might be wrong? I havn't change anything there.

```
A PHP Error was encountered

Severity: Warning

Message: sprintf(): Too few arguments

Filename: helpers/MY_language_helper.php

Line Number: 64

Backtrace:

File: /home/users/arrows/public_html/test4climbing/fuel/modules/fuel/helpers/MY_language_helper.php
Line: 64
Function: sprintf

File: /home/users/arrows/public_html/test4climbing/fuel/application/views/auth/email/activate.tpl.php
Line: 3
Function: lang

File: /home/users/arrows/public_html/test4climbing/fuel/modules/fuel/core/Loader.php
Line: 396
Function: include

File: /home/users/arrows/public_html/test4climbing/fuel/modules/fuel/core/Loader.php
Line: 323
Function: _ci_load

File: /home/users/arrows/public_html/test4climbing/fuel/application/libraries/Ion_auth.php
Line: 300
Function: view

File: /home/users/arrows/public_html/test4climbing/fuel/application/controllers/Auth.php
Line: 509
Function: register

File: /home/users/arrows/public_html/test4climbing/index.php
Line: 364
Function: require_once
```
```
A PHP Error was encountered

Severity: Warning

Message: sprintf(): Too few arguments

Filename: helpers/MY_language_helper.php

Line Number: 64

Backtrace:

File: /home/users/arrows/public_html/test4climbing/fuel/modules/fuel/helpers/MY_language_helper.php
Line: 64
Function: sprintf

File: /home/users/arrows/public_html/test4climbing/fuel/application/views/auth/email/activate.tpl.php
Line: 4
Function: lang

File: /home/users/arrows/public_html/test4climbing/fuel/modules/fuel/core/Loader.php
Line: 396
Function: include

File: /home/users/arrows/public_html/test4climbing/fuel/modules/fuel/core/Loader.php
Line: 323
Function: _ci_load

File: /home/users/arrows/public_html/test4climbing/fuel/application/libraries/Ion_auth.php
Line: 300
Function: view

File: /home/users/arrows/public_html/test4climbing/fuel/application/controllers/Auth.php
Line: 509
Function: register

File: /home/users/arrows/public_html/test4climbing/index.php
Line: 364
Function: require_once
```

**Comment by benedmunds** [comment]
Looks like maybe the lang file is missing.  What language are you using?

**Comment by strzala-dj** [comment]
I'm using English. Language files are untouched in the language folder.
I have Ion Auth installed into FuelCMS. I'm using it from the Fuel's advanced module and everything works fine, except the content of the email. I have tried with copying language files into my module's language folder, but this didn't work.
How to check where lang() function is looking for the language file?

**Comment by benedmunds** [comment]
Add a log or var_dump of the $data array around here to see what variables are passed in to the view:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/libraries/Ion_auth.php#L290

**Comment by strzala-dj** [comment]
```
array(4) {
	["identity"]=> string(18) "email1@testing.com" 
	["id"]=> string(2) "32" 
	["email"]=> string(18) "email1@testing.com" 
	["activation"]=> string(61) "a0a6c23b0f00aed48552.73d8bd9335e0cf39cd87ef0ea56198c676084a86"
}
```

**Comment by benedmunds** [comment]
Hmm ok so it has data, definitely seems like the Lang isn’t loading.

In this view, or in the controller, dump the lang() calls here and see what’s returning: https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/255c3dac483d57f9caf0946b8d9cfbbc57ffdfff/views/auth/email/activate.tpl.php#L3

**Comment by strzala-dj** [comment]
I have found the reason and solution.
In FuelCMS the `lang()` overwrites the CodeIgniter `lang()` function to provide the added benefits of passing arguments to your language files (uses `sprintf()` function). So f.ex. line 3 should looks like this:
`<h1><?php echo lang('email_activate_heading', $identity);?></h1>`

I have made several tests to check lang files and functions operating with activate.tpl.php as:
```
echo lang('email_activation_subject').'<br/>';	// taken from ion_auth_lang.php
echo lang('login_subheading').'<br/>';			// taken from auth_lang.php
var_dump(lang('login_subheading'));				// taken from auth_lang.php
echo '<br/>';
echo '$identity: '.lang('email_activate_heading', $identity).'<br/>';
echo 'anchor: '.lang('email_activate_subheading', anchor('auth/activate/'. $id .'/'. $activation, lang('email_activate_link'))).'<br/>';
echo '<br/>';
var_dump(lang('email_activate_heading'));
var_dump(lang('email_activate_subheading'));
```
and I received an email with:

Account Activation
Please login with your email and password below.
string(48) "Please login with your email and password below."
$identity: Activate account for email1@testing.com
anchor: Please click this link to Activate Your Account.

```
A PHP Error was encountered

Severity: Warning

Message: sprintf(): Too few arguments

Filename: helpers/MY_language_helper.php

Line Number: 64

Backtrace:

File: /home/users/arrows/public_html/test4climbing/fuel/modules/fuel/helpers/MY_language_helper.php
Line: 64
Function: sprintf

File: /home/users/arrows/public_html/test4climbing/fuel/application/views/auth/email/activate.tpl.php
Line: 9
Function: lang

File: /home/users/arrows/public_html/test4climbing/fuel/modules/fuel/core/Loader.php
Line: 396
Function: include

File: /home/users/arrows/public_html/test4climbing/fuel/modules/fuel/core/Loader.php
Line: 323
Function: _ci_load

File: /home/users/arrows/public_html/test4climbing/fuel/application/libraries/Ion_auth.php
Line: 300
Function: view

File: /home/users/arrows/public_html/test4climbing/fuel/application/controllers/Auth.php
Line: 510
Function: register

File: /home/users/arrows/public_html/test4climbing/index.php
Line: 364
Function: require_once
```
bool(false)
```
A PHP Error was encountered

Severity: Warning

Message: sprintf(): Too few arguments

Filename: helpers/MY_language_helper.php

Line Number: 64

Backtrace:

File: /home/users/arrows/public_html/test4climbing/fuel/modules/fuel/helpers/MY_language_helper.php
Line: 64
Function: sprintf

File: /home/users/arrows/public_html/test4climbing/fuel/application/views/auth/email/activate.tpl.php
Line: 10
Function: lang

File: /home/users/arrows/public_html/test4climbing/fuel/modules/fuel/core/Loader.php
Line: 396
Function: include

File: /home/users/arrows/public_html/test4climbing/fuel/modules/fuel/core/Loader.php
Line: 323
Function: _ci_load

File: /home/users/arrows/public_html/test4climbing/fuel/application/libraries/Ion_auth.php
Line: 300
Function: view

File: /home/users/arrows/public_html/test4climbing/fuel/application/controllers/Auth.php
Line: 510
Function: register

File: /home/users/arrows/public_html/test4climbing/index.php
Line: 364
Function: require_once
```
bool(false)

**Comment by benedmunds** [comment]
Can you post your english lang files?  This is odd..

**Comment by strzala-dj** [comment]
Here you go.
This Ion Auth's files are inside FuelCMS lang folder (../public_html/site_main_folder/fuel/application/language/english):
[lang_files.zip](https://github.com/benedmunds/CodeIgniter-Ion-Auth/files/3170384/lang_files.zip)
This one is my site's file inside advanced module lang folder (../public_html/site_main_folder/fuel/modules/advanced_module/language/english):
[assessments_lang.zip](https://github.com/benedmunds/CodeIgniter-Ion-Auth/files/3170390/assessments_lang.zip)

**Comment by benedmunds** [comment]
@strzala-dj oh I completely missed your note before about Fuel overriding the lang function!  Ok that definitely makes sense now.  Thanks for this.  I'm going to repost it below before closing for any future users to easily reference:

**Solution:**
In **FuelCMS** the lang() overwrites the CodeIgniter lang() function to provide the added benefits of passing arguments to your language files (uses sprintf() function). So f.ex. line 3 should looks like this:
<h1><?php echo lang('email_activate_heading', $identity);?></h1>
