### ISSUE TITLE
Will ion auth work for php 7+ ?  library is not loading $this->load->library('ion_auth')

### ISSUE THREAD

**Issue by imtiaz2564** [benedmunds/CodeIgniter-Ion-Auth#1352]
**This Github Issue section is meant to track bugs with the library itself**
Please post generic support issues to the CodeIgniter forums or StackOverflow.

**Comment by benedmunds** [comment]
Yea it works, what PHP and CodeIgniter versions are you running?

**Comment by imtiaz2564** [comment]
PHP 7.2  and CI 3.1, getting following error while loading the library in controller 
A PHP Error was encountered
Severity: Notice

Message: Undefined property: Master::$db

Filename: models/Ion_auth_model.php

Line Number: 212

**Comment by benedmunds** [comment]
Make sure you’re loading the database before loading Ion Auth

**Comment by ronaldaraujo** [comment]
Hello.

Running the application in PHP 7.3 the `logged_in()` method always returns NULL even if the login is correctly performed.

```
/**
 * logged_in
 *
 * @return bool
 * @author Mathew
 **/
public function logged_in()
{
	$this->ion_auth_model->trigger_events('logged_in');
	return (bool) $this->session->userdata('identity');
}
```

It is as if the application is no longer defined as the identity variable in:

```
/**
 * set_session
 *
 * @return bool
 * @author jrmadsen67
 **/
public function set_session($user)
{
	$this->trigger_events('pre_set_session');

	$session_data = array(
	    'identity'  => $user->{$this->identity_column},
	    $this->identity_column => $user->{$this->identity_column},
	    'email' => $user->email,
	    'user_id' => $user->id, //everyone likes to overwrite id so we'll use user_id
	    'old_last_login' => $user->last_login
	);

	$this->session->set_userdata($session_data);
	$this->trigger_events('post_set_session');
	return TRUE;
}
```

I need help resolving this. Thank you very much.

**Comment by benedmunds** [comment]
@ronaldaraujo what version of CI are you using?

Also can you post your Ion Auth and CI configs

**Comment by ronaldaraujo** [comment]
@benedmunds, these are my versions:

CI_VERSION: 3.1.0
Ion Auth: 2.5.2

**Comment by benedmunds** [comment]
@ronaldaraujo is it possible for you to upgrade to Ion Auth 3? v2 is pretty old at this point

**Comment by ronaldaraujo** [comment]
Okay. I'll update.

**Comment by ronaldaraujo** [comment]
@benedmunds 

Unfortunately I did not succeed. I did the following:

1. Executed the migration file (migrate.postgre.sql);
2. I copied the contents of the config/ion_auth.php file keeping my existing values settings;
3. I copied the contents of the libraries/Ion_auth;
4. I copied the contents of the models/Ion_auth_model;

Did I forget something?

To contextualize.

After login, I send the user to Home using the method `redirect('home', 'refresh')`.

My controller Home extends from MY_Controller. Just like all the others ...

In MY_Controller I perform a simple check. Look.

```
class MY_Controller extends CI_Controller 
{
    public function __construct()
    {
        parent::__construct();

        if (!$this->ion_auth->logged_in())
            redirect('auth');
     }
}
```

**Comment by benedmunds** [comment]
Are things working in general after the upgrade?  Here are the full upgrade instructions (just in case): https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/UPGRADING.md#upgrading-from-ion-auth-2

Post your CI and Ion Auth configs, this seems like a session issue.  Might be worth upgrading to the latest version of CI 3, there have been a few session related bugs in the past but I don't remember the exact versions.

**Comment by ronaldaraujo** [comment]
@benedmunds, your suggestion to update CodeIgniter worked. Thank you very much.

**Comment by benedmunds** [comment]
Awesome, glad to hear that!
