### ISSUE TITLE
" Remember me "   Security .. ?!

### ISSUE THREAD

**Issue by milad86** [benedmunds/CodeIgniter-Ion-Auth#1353]
Hello ,
first of all, thanks for your great job.

a question please..
how would the Remember me work ? with SESSIONS? Cookies ?? what kind of info is stored client side ? what encryption is used for that ?
how safe is it regarding storing user's log in credentials on client side ??

**Comment by milad86** [comment]
> 
> 
> Hello ,
> first of all, thanks for your great job.
> 
> My CI version is 3.1.10 / ion_auth ver. 3
> My problem is Remember me is always working as if it is true.
> user always remains logged in.
> 

  $this->ion_auth->logged_in()   it always returns true .. even if browser is closed

**Comment by benedmunds** [comment]
It uses a combination of a client side cookie and a hash in the user table.  You can find the code here:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/models/Ion_auth_model.php#L1995
