### ISSUE TITLE
Is it support for multiple user auth ?

### ISSUE THREAD

**Issue by ErwinSavedTest** [benedmunds/CodeIgniter-Ion-Auth#1355]
how do I log in with different accounts with different routes ? there is only one methd is_admin() how make new one ?

**Comment by benedmunds** [comment]
The in_group() method allows you to check other groups:

http://benedmunds.com/ion_auth/#in_group

**Comment by ErwinSavedTest** [comment]
Thank you so much for your help. You are a great person

**Comment by benedmunds** [comment]
:) thanks! Take care!
