### ISSUE TITLE
reset password page has errors when key is incorrect (doesn't fail gracefully)

### ISSUE THREAD

**Issue by afagard** [benedmunds/CodeIgniter-Ion-Auth#1357]
After updating to the latest version I noticed that the reset password page no longer works properly when the key provided is incorrect. Test key = 123123 e.g. /auth/reset_password/123123

We now fail with `Trying to get property 'selector' of non-object` and `Trying to get property 'validator' of non-object`

The issue is that:

```
		$token = $this->_retrieve_selector_validator_couple($user_code);

		// Retrieve the user according to this selector
		$user = $this->where('forgotten_password_selector', $token->selector)->users()->row();
```

doesn't check if the `$token` is false before accessing the `selector`.

This is an easy fix, but I'm not sure if this issue pervades elsewhere where `_retrieve_selector_validator_couple` is used.

fix:

```
$token = $this->_retrieve_selector_validator_couple($user_code);

if ($token === FALSE) {
    return FALSE;
}
```

update: issue appears to be isolated. the other usage checks if it is false.

**Comment by benedmunds** [comment]
Thanks for reporting this!  Interested in submitting a PR? If not I can throw it in a commit.

**Comment by afagard** [comment]
My knowledge of git is limited to downloading unfortunately. I really need to learn more about pull requests and such but I code more as a hobby.
