### ISSUE TITLE
strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

### ISSUE THREAD

**Issue by Measne** [benedmunds/CodeIgniter-Ion-Auth#1358]
**Which branch are you using?**
2/3/4 (branch used should match CodeIgniter version)

**What commit hash are you on?**
Attempt updating to the latest commit on your branch.

**What CodeIgniter version are you using?**
v2/v3/v4

**What PHP version are you using?**
PHP 5.4/5.6/5.7/7.0/etc

**Post your Ion Auth config below**
```
Config goes here
```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Comment by benedmunds** [comment]
Looks like the needles we're using are strings.  So this shouldn't cause any issues.

Am I missing something here?

**Comment by Measne** [comment]
Filename: MX/Router.php

Line Number: 239

Backtrace:

File: C:\xamppx\htdocs\wedian\application\third_party\MX\Router.php
Line: 239
Function: strpos

File: C:\xamppx\htdocs\wedian\application\third_party\MX\Router.php
Line: 72
Function: set_class

File: C:\xamppx\htdocs\wedian\index.php
Line: 315
Function: require_once

**Comment by benedmunds** [comment]
Those files aren't a part of Ion Auth.  Maybe you meant to report this to CodeIgniter?  Closing issue for now.
