### ISSUE TITLE
it is possible to register user without login in ion auth latest and CI 3.1.10

### ISSUE THREAD

**Issue by AlokInsan** [benedmunds/CodeIgniter-Ion-Auth#1359]
**it is possible to register user without login in ion auth latest and CI 3.1.10**
Creating user without login auth/create_user function throwback to login page.
But i have to do this....Please help me sir.

**Comment by benedmunds** [comment]
Feel free to change the controller to match your needs.  It’s just there as a starting place for your business logic.

**Comment by AlokInsan** [comment]
ok sir, but  it works after hiding first if condition in create_user function.
     public function create_user()
	{
		$this->data['title'] = $this->lang->line('create_user_heading');

         /*   if (!$this->ion_auth->logged_in() || !$this->ion_auth->is_admin())
		{ 
			redirect('auth', 'refresh');
		}    */
          ...
          .....
          ....
       }

**Comment by benedmunds** [comment]
Yea that change is fine.  In the example controller only admins are allowed to create users.  This change would be it publicly available. Which is fine if that’s how your app needs to work.

Take care!

**Comment by AlokInsan** [comment]
Ok Thanks a lot sir....
