### ISSUE TITLE
Old users not able to login after migrating the ion-auth to latest version.

### ISSUE THREAD

**Issue by sanjay7m** [benedmunds/CodeIgniter-Ion-Auth#1360]
Hi @benedmunds
I have a problem or question i have migrated the codeginiter and ion-auth to the latest version . The old version was using th sha1 . Now the problem is after upgrading the old users in the system are not able to login. But if i register a new user that is able to login. Do i need to add some logic to migrate old users or it should be automatic. As suggested in the upgrading.md file "However, fear not! The transition should actually be pretty smooth for you and your users.
After upgrading to Ion Auth 3, any user logging in your application will be migrated to the
new hashing method. This is completely transparent."

**Comment by benedmunds** [comment]
Hey,

There is logic to check for SHA1 passwords on login and if they are correct to upgrade the hash and login the user.

You may need to troubleshoot a bit to identify the issue.  Can you post your old and new Ion Auth config files please.

FYI here is the SHA1 upgrade logic:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/models/Ion_auth_model.php#L332

https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/models/Ion_auth_model.php#L2731

**Comment by sanjay7m** [comment]
Hi sir this is the old one 
===============================================================================]
	$config['tables']['groups']          = 'groups';
	$config['tables']['users']           = 'users';
	$config['tables']['users_groups']    = 'users_groups';
	$config['tables']['login_attempts']  = 'login_attempts';
	$config['tables']['entity_types']    = 'entity_types';

    /**
	 * Hash Method  (sha1 or bcrypt)
	 *
	 * Bcrypt is available in PHP 5.3+
	 *
	 * IMPORTANT: Based on the recommendation by many professionals, it is highly recommended to use
	 * 		    bcrypt instead of sha1.
	 *
	 *
	 * NOTE: 	If you use bcrypt you will need to increase your password column character limit
	 * 		    to (80)
	 *
	 * Below there is "default_rounds" setting.  This defines how strong the encryption will be,
	 * but remember the more rounds you set the longer it will take to hash (CPU usage) So adjust
	 * this based on your server hardware.
	 * 
	 * If you are using Bcrypt the Admin password field also needs to be changed in order login as admin:
	 * $2a$07$SeBknntpZror9uyftVopmu61qg0ms8Qv1yV6FG.kQOSM.9QhmTo36
	 * 		    
	 */
	
	$config['hash_method'] = 'sha1';		// IMPORTANT: Make sure this is set to either sha1 or bcrypt 
	
	/**
	 * Default rounds used for Bcrypt only 
	 */
	$config['default_rounds'] = 8;		// This does not apply if random_rounds is set to true
	
	/**
	 *
	 * Random Rounds encrypts each new user's password using random rounds
	 * 
	 *
	 * Becareful how high you set max_rounds, I would do your own testing on how long it takes
	 * to encrypt with x rounds.
	 *
	 */	
	$config['random_rounds'] = false;
	$config['min_rounds'] = 5;
	$config['max_rounds'] = 9;
	

	
	/**
	 * Site Title, example.com
	 */
	$config['site_title']		   = "GIVINGtrax";
	
	/**
	 * Admin Email, admin@example.com
	 */
	$config['admin_email']		   = "founders@givingtrax.com";
	
	/**
	 * Default group, use name
	 */
	$config['default_group']       = 'members';
	
	/**
	 * Default administrators group, use name
	 */
	$config['admin_group']         = 'sysadmin';
	 
	/**
	 * Users table column and Group table column you want to join WITH.
	 * Joins from users.id
	 * Joins from groups.id
	 **/
	$config['join']['users']       = 'user_id';
	$config['join']['groups']      = 'group_id';
	
	/**
	 * A database column which is used to
	 * login with.
	 **/
	$config['identity']            = 'email';
		 
	/**
	 * Minimum Required Length of Password
	 **/
	$config['min_password_length'] = 8;
	
	/**
	 * Maximum Allowed Length of Password
	 **/
	$config['max_password_length'] = 20;

	/**
	 * Email Activation for registration
	 **/
	$config['email_activation']    = false;

	/**
	 * Manual Activation for registration
	 **/
	$config['manual_activation']    = false;
	
	/**
	 * Allow users to be remembered and enable auto-login
	 **/
	$config['remember_users']      = true;
	
	/**
	 * How long to remember the user (seconds)
	 **/
	$config['user_expire']         = 86500;
	
	/**
	 * Extend the users cookies everytime they auto-login
	 **/
	$config['user_extend_on_login'] = false;

	/**
	 * Send Email using the builtin CI email class
	 * if false it will return the code and the identity
	 **/
	$config['use_ci_email']= true;

	/**
	 * Email config - 
	 * 	'file' = use the default CI config or use from a config file
	 * 	array = manually set your email config settings
	 **/
	$config['email_config']         = array(
		'mailtype' => 'html',
	);
	
	/**
	 * Folder where email templates are stored.
     * Default : auth/
	 **/
	$config['email_templates']     = 'auth/email/';
	
	/**
	 * Activate Account Email Template
     * Default : activate.tpl.php
	 **/
	$config['email_activate']   = 'activate.tpl.php';
	
	/**
	 * Forgot Password Email Template
     * Default : forgot_password.tpl.php
	 **/
	$config['email_forgot_password']   = 'forgot_password.tpl.php';

	/**
	 * Forgot Password Complete Email Template
     * Default : new_password.tpl.php
	 **/
	$config['email_forgot_password_complete']   = 'new_password.tpl.php';
	
	/**
	 * Salt Length
	 **/
	$config['salt_length'] = 10;

	/**
	 * Should the salt be stored in the database?
	 * This will change your password encryption algorithm, 
	 * default password, 'password', changes to 
	 * fbaa5e216d163a02ae630ab1a43372635dd374c0 with default salt.
	 **/
	$config['store_salt'] = false;
	
	/**
	 * The number of seconds after which a forgot password request will
	 * expire. If set to 0, forgot password requests will not expire.
	 **/
	$config['forgot_password_expiration'] = 0;
	
	/**
	 * Track the number of failed login attempts for each user or ip. 
	 **/
	$config['track_login_attempts'] = true;

	/**
	 * Set the maximum number of failed login attempts.
	 * This maximum is not enforced by the library, but is 
	 * used by $this->ion_auth->is_max_login_attempts_exceeded().
	 * The controller should check this function and act
	 * appropriately. If this variable set to 0, there is no maximum.
	 **/
	$config['maximum_login_attempts'] = 3;
	
	/**
	 * Message Start Delimiter
	 **/
	$config['message_start_delimiter'] = '';
	
	/**
	 * Message End Delimiter
	 **/
	$config['message_end_delimiter'] = '';
	
	/**
	 * Error Start Delimiter
	 **/
	$config['error_start_delimiter'] = '';
	
	/**
	 * Error End Delimiter
	 **/
	$config['error_end_delimiter'] = '';
	$config['password_exp_time'] = 30;

**Comment by sanjay7m** [comment]
$config['database_group_name'] = '';

/*
| -------------------------------------------------------------------------
| Tables.
| -------------------------------------------------------------------------
| Database table names.
*/
$config['tables']['users']           = 'users';
$config['tables']['groups']          = 'groups';
$config['tables']['users_groups']    = 'users_groups';
$config['tables']['login_attempts']  = 'login_attempts';
$config['tables']['entity_types']    = 'entity_types';
/*
 | Users table column and Group table column you want to join WITH.
 |
 | Joins from users.id
 | Joins from groups.id
 */
$config['join']['users']  = 'user_id';
$config['join']['groups'] = 'group_id';
$config['hash_method']				= 'bcrypt';	// bcrypt or argon2
$config['bcrypt_default_cost']		= 10;		// Set cost according to your server benchmark - but no lower than 10 (default PHP value)
$config['bcrypt_admin_cost']		= 12;		// Cost for user in admin group
$config['argon2_default_params']	= [
	'memory_cost'	=> 1 << 12,	// 4MB
	'time_cost'		=> 2,
	'threads'		=> 2
];
$config['argon2_admin_params']		= [
	'memory_cost'	=> 1 << 14,	// 16MB
	'time_cost'		=> 4,
	'threads'		=> 2
];
$config['site_title']                 = "ssss";       // Site Title, example.com
$config['admin_email']                = "sss@givingtrax.com"; // Admin Email, admin@example.com
$config['default_group']              = 'members';           // Default group, use name
$config['admin_group']                = 'admin';             // Default administrators group, use name
$config['identity']                   = 'email';             /* You can use any unique column in your table as identity column.
															    The values in this column, alongside password, will be used for login purposes
															    IMPORTANT: If you are changing it from the default (email),
															    		   update the UNIQUE constraint in your DB */
$config['min_password_length']        = 8;                   // Minimum Required Length of Password (not enforced by lib - see note above)
$config['email_activation']           = FALSE;               // Email Activation for registration
$config['manual_activation']          = FALSE;               // Manual Activation for registration
$config['remember_users']             = TRUE;                // Allow users to be remembered and enable auto-login
$config['user_expire']                = 86500;               // How long to remember the user (seconds). Set to zero for no expiration - see sess_expiration in CodeIgniter Session Config for session expiration
$config['user_extend_on_login']       = FALSE;               // Extend the users cookies every time they auto-login
$config['track_login_attempts']       = TRUE;                // Track the number of failed login attempts for each user or ip.
$config['track_login_ip_address']     = TRUE;                // Track login attempts by IP Address, if FALSE will track based on identity. (Default: TRUE)
$config['maximum_login_attempts']     = 3;                   // The maximum number of failed login attempts.
$config['lockout_time']               = 600;                 /* The number of seconds to lockout an account due to exceeded attempts
																You should not use a value below 60 (1 minute) */
$config['forgot_password_expiration'] = 1800;                /* The number of seconds after which a forgot password request will expire. If set to 0, forgot password requests will not expire.
                   												30 minutes to 1 hour are good values (enough for a user to receive the email and reset its password)
                   												You should not set a value too high, as it would be a security issue! */
$config['recheck_timer']              = 0;  
/*
 | -------------------------------------------------------------------------
 | Cookie options.
 | -------------------------------------------------------------------------
 | remember_cookie_name Default: remember_code
 */
$config['remember_cookie_name'] = 'remember_code';

/*
 | -------------------------------------------------------------------------
 | Email options.
 | -------------------------------------------------------------------------
 | email_config:
 | 	  'file' = Use the default CI config or use from a config file
 | 	  array  = Manually set your email config settings
 */
$config['use_ci_email'] = TRUE; // Send Email using the builtin CI email class, if false it will return the code and the identity
$config['email_config'] = [
	'mailtype' => 'html',
];

/*
 | -------------------------------------------------------------------------
 | Email templates.
 | -------------------------------------------------------------------------
 | Folder where email templates are stored.
 | Default: auth/
 */
$config['email_templates'] = 'auth/email/';

/*
 | -------------------------------------------------------------------------
 | Activate Account Email Template
 | -------------------------------------------------------------------------
 | Default: activate.tpl.php
 */
$config['email_activate'] = 'activate.tpl.php';

/*
 | -------------------------------------------------------------------------
 | Forgot Password Email Template
 | -------------------------------------------------------------------------
 | Default: forgot_password.tpl.php
 */
$config['email_forgot_password'] = 'forgot_password.tpl.php';

/*
 | -------------------------------------------------------------------------
 | Message Delimiters.
 | -------------------------------------------------------------------------
 */
$config['delimiters_source']       = 'config'; 	// "config" = use the settings defined here, "form_validation" = use the settings defined in CI's form validation library
$config['message_start_delimiter'] = '<p>'; 	// Message start delimiter
$config['message_end_delimiter']   = '</p>'; 	// Message end delimiter
$config['error_start_delimiter']   = '<p>';		// Error message start delimiter
$config['error_end_delimiter']     = '</p>';	// Error message end delimiter

**Comment by benedmunds** [comment]
Please add the following to your new config and try again:

```
$config['salt_length'] = 10;
$config['store_salt'] = false;
```

**Comment by sanjay7m** [comment]
It worked . Thanks sir.

**Comment by benedmunds** [comment]
Awesome! Take care!
