### ISSUE TITLE
How can i identify two unique column?

### ISSUE THREAD

**Issue by fdemir** [benedmunds/CodeIgniter-Ion-Auth#1361]
I want to identify two unique identity column like username and email. I set username as a unique. But i want to set also email. I cant identify two unique column.

**Comment by benedmunds** [comment]
Are you trying to enforce this in sql or what have you tried so far?

**Comment by fdemir** [comment]
So i want to get errors from ion auth. Like "this username already used" and "this email already used".  Both of email and username. But i can in this ion auth only i can set one unique column.

**Comment by benedmunds** [comment]
The best way to do that would be adding form validation for is_unique to both.  Here's an example of that for email (you can do it to both fields):

https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/controllers/Auth.php#L480

**Comment by fdemir** [comment]
Thx @benedmunds
