### ISSUE TITLE
Model: time() => now() ?

### ISSUE THREAD

**Issue by EzraZebra** [benedmunds/CodeIgniter-Ion-Auth#1362]
In Ion Auth 3, the model uses PHP's native `time()` and not CI3's `now()`.  
Changing it would probably improve compatibility for those who have changed 'time_reference' in CI3's config and are using the Date Helper.  
The date helper is already being loaded in the Ion Auth model anyway.

**Comment by benedmunds** [comment]
I'm not against this change, although I haven't seen any other reports of it causing issues so likely a low priority.

Want to submit a PR for it?

**Comment by EzraZebra** [comment]
Sure, I'll submit it in a minute.

**Comment by EzraZebra** [comment]
On second thought, time() is timezone independant, whereas now() is not.  
Changing it may cause unexpected results if the user isn't aware that now() is being used?

**Comment by benedmunds** [comment]
Closing this since I don't believe it's an issue.  Feel free to open a new ticket if you'd like to kickstart a new discussion on this.
