### ISSUE TITLE
Message: Class 'CodeIgniter\Controller' not found

### ISSUE THREAD

**Issue by ct0182** [benedmunds/CodeIgniter-Ion-Auth#1364]
I've had a go installing IonAuth 4.0.3 with CI 3.1.10.
Are the two versions compatible? 

It's installed into the 3rd party setup as set out within installing.md. It is also being autoloaded within the autoload.php file.

I get the following error.

```
Message: Class 'CodeIgniter\Controller' not found
Filename: directory_structure\Auth.php
```

**Comment by ct0182** [comment]
I'm assuming V2.6.0 works with CI V3 and V4 only works with CI V4?

**Comment by benedmunds** [comment]
Correct. V2 of Ion Auth is meant to go with v2 of CI, same with v3 for CI3 and v4 for CI4.

I’d recommend using the latest commit from the associated branch instead of the tags, they get outdated quickly.
