### ISSUE TITLE
Error in query (1215): Cannot add foreign key constraint 

### ISSUE THREAD

**Issue by vladimirhacker** [benedmunds/CodeIgniter-Ion-Auth#1371]
**Which branch are you using?**
2/3/4 (branch used should match CodeIgniter version)
3

**What commit hash are you on?**
Attempt updating to the latest commit on your branch.

**What CodeIgniter version are you using?**
v2/v3/v4
3
**What PHP version are you using?**
PHP 5.4/5.6/5.7/7.0/etc
 [not important]
```

**Post your Ion Auth config below**
```
Config goes here [not important]
```

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

Can't execute ion_auth.sql on ,y latest Debian Maria DB, it produces:
Error in query (1215): Cannot add foreign key constraint

**Comment by benedmunds** [comment]
Please try running the SQL commands one at a time and let me know which one is triggering this error.

**Comment by benedmunds** [comment]
Closing due to time elapsed since the last response.  Please submit a new ticket if this is still an issue.
