### ISSUE TITLE
My web Admin Pannel not login in Codeigniter 

### ISSUE THREAD

**Issue by vasiyanigm** [benedmunds/CodeIgniter-Ion-Auth#1374]
My web Admin Pannel not login in Codeignite, How to solve this Problem ?

**Comment by benedmunds** [comment]
I'll need more information.

Are you using Ion Auth?  What errors/issues are you getting?

**Comment by benedmunds** [comment]
Closing due to time elapsed since the last response.  Please submit a new ticket if this is still an issue.
