### ISSUE TITLE
Forgot_Password link is showing error

### ISSUE THREAD

**Issue by gpdas1** [benedmunds/CodeIgniter-Ion-Auth#1375]
**This Github Issue section is meant to track bugs with the library itself**
Please post generic support issues to the CodeIgniter forums or StackOverflow.
Recently I changed my Ubuntu 16.04 server from one machine to another. Then Forgot Password link is showing error.
![emailError](https://user-images.githubusercontent.com/4804013/65613779-221e9080-dfd4-11e9-8b96-4d5c4950ac49.PNG)
![emailError](https://user-images.githubusercontent.com/4804013/65613889-5003d500-dfd4-11e9-9291-93884e174bc2.PNG)

**Comment by benedmunds** [comment]
This isn't an Ion Auth issue.  It's an issue with your email setup.

My guess would be that either your Google SMTP needs a different setting or your server doesn't support the SSL that Google requires.
