### ISSUE TITLE
What is the algorithm for changing password directly in phpmyadmin?

### ISSUE THREAD

**Issue by blaasvaer** [benedmunds/CodeIgniter-Ion-Auth#1376]
I'm repairing and old CI app ... and need to recover (change) the password directly in the DB to get access to the system again. Now WHAT is the default algorithm I should select for storing a new password?

**Comment by benedmunds** [comment]
You cant do it directly in the DB since it's BCrypt by default.  Either copy the default password from https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/sql/ion_auth.sql#L63 or generate a new password hash via the library and manually update the DB.
