### ISSUE TITLE
Switch ashing method from bcrypt to Argon2

### ISSUE THREAD

**Issue by federicovilla** [benedmunds/CodeIgniter-Ion-Auth#1377]
First of all sorry if this isn't the correct section to post my question.
Since I have updated my PHP server to 7.2 I'd like to switch the Ion Auth ashing method from the actual bcrypt to Argon2; I'm wondering if I could get in trouble with the already registered users since their passwords are ashed using bcrypt.
Thanks a lot for any help

**Comment by benedmunds** [comment]
This shouldn't cause any issues.  What will happen is that as users with the old hash login they'll be rehashed and saved as Argon2.

**Comment by benedmunds** [comment]
Do let me know if you run into any issues though!  I haven't used Argon2 yet myself.
