### ISSUE TITLE
Implementing with Google Authenticator PHP

### ISSUE THREAD

**Issue by oasin** [benedmunds/CodeIgniter-Ion-Auth#1378]
How can i make use of the Google Authenticator library with IonAuth?

Few steps and methods can help..

**Comment by marios88** [comment]
I used https://github.com/Spomky-Labs/otphp
then you can use any compatible app to generate one time passwords

Implementation depends on what you want to accomplish , but the necessary
steps are
Generate & Store OTP generator string in DB
Present the user with the QR code

When you want (e.g. login, delete account ) check against it to authenticate

**Comment by oasin** [comment]
Did you try with ionAuth?
 how? because am new to it an example please

**Comment by marios88** [comment]
Cant provide a working example but the following code will give you the gist

```php
$this->load->library('otp');
$user2FA = $this->otp->user_has_2FA($supposed_user->id);
if($this->globalconf->get('otp_enforce_otp_only_logins') || !empty($user2FA)){
    //validate OTP CODE!
    $otp = OTPHP\Factory::loadFromProvisioningUri($user2FA);
    if(!$otp->verify($this->input->post('otp'),($this->globalconf->get('otp_period'))) && !$otp->verify($this->input->post('otp'), $this->globalconf->get('otp_period') - $this->globalconf->get('otp_seconds_leeway'))){
        redirect('login');
    }
}

...
rest of login controller
```
`otp` is a simple wrapper library for `otphp`
I chose to do 2FA auth before checking for password

**Comment by oasin** [comment]
Thanks anyway but still didn't get it done

**Comment by benedmunds** [comment]
Closing due to time elapsed since the last response.  You may get better support on StackOverflow since this isn't an issue with Ion Auth itself.
