### ISSUE TITLE
library function register() works but create_user() does not work

### ISSUE THREAD

**Issue by rupinderDev** [benedmunds/CodeIgniter-Ion-Auth#1381]
I am using 
CodeIgniter-Ion-Auth  - **branch 3**

**commit hash** - latest commit

**CodeIgniter version** - codeigniter 3.1.11

**PHP version** - PHP 7.2

**Description of bug**
library function create_user() does not work 

An uncaught Exception was encountered
Type: Exception
Message: Undefined method Ion_auth::create_user() called

**Expected behavior**
Should work like register()

**Comment by benedmunds** [comment]
Thanks for the PR!
