### ISSUE TITLE
sess_expiration not working in CI with ionAuth 

### ISSUE THREAD

**Issue by kloj** [benedmunds/CodeIgniter-Ion-Auth#1383]
**This Github Issue section is meant to track bugs with the library itself**
Please post generic support issues to the CodeIgniter forums or StackOverflow.

a CI app having ionAuth implemented is not working with session expire function

application\config\config.php
$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 300;
$config['sess_save_path'] = 'ci_sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 120;
$config['sess_regenerate_destroy'] = FALSE;

application\config\ion_auth.php
$config['user_expire']                = 300;               // How long to remember the user (seconds). Set to zero for no expiration

even the web page is left idle for hours,, still the session is not expired

whereas another CI app without ionAuth is working perfectly with session expire,,,

so please help  to fix this issue
thanks

**Comment by benedmunds** [comment]
Are you using the remember me functionality?

**Comment by kloj** [comment]
> 
> 
> Are you using the remember me functionality?

No, not using Remember Me Function

**Comment by kloj** [comment]
though Remember Me, explicit function of Login Page is not enabled,,
but ,, in application/config/ion_auth.php 

$config['remember_users']             = TRUE;                // Allow users to be remembered and enable auto-login

just this parameter is set TRUE,, let me try it by FALSE.

**Comment by kloj** [comment]
even setting $config['remember_users'] = FALSE; 
still the session not expired in 2 hours,  while expiration time is set to 300 in both in config.php and config/ion_auth.php

**Comment by benedmunds** [comment]
Try a lower user_expire in the Ion Auth config

**Comment by kloj** [comment]
> 
> 
> Try a lower user_expire in the Ion Auth config

set to 150,   still not worked

if you plz give a look to one of controllers construct

class Invoices extends MY_Controller
{
    /**
     * Invoices constructor.
     */
    public function __construct ()
    {
        parent::__construct ();
        // Load Invoices Model
        $this->load->model ( 'invoices_model' );
        // Load Billers Model
        $this->load->model ( 'biller_model' );
        // Load Payments Model
        $this->load->model ( 'payments_model' );
        // Load Form Validation Library
        $this->load->library ( 'form_validation' );
        // Load Ion Auth Library
        $this->load->library ( 'ion_auth' );
        // Load Helper Language
        $this->load->helper('language');
        // Load Helper Date Format
        $this->load->helper('date_format');
        // Check user is logged in ?
        if ( !$this->ion_auth->logged_in () ) {
            if ($this->input->is_ajax_request()) {
                $next_link = urlencode("/invoices");
                $result = array("status"=>"redirect", "message"=>site_url("auth/login?next=$next_link"));
                die(json_encode($result));
            }else{
                $next_link = urlencode(substr("$_SERVER[REQUEST_URI]", stripos("$_SERVER[REQUEST_URI]", "index.php")+9));
                redirect("auth/login?next=$next_link");
            }
        }
    }

**Comment by benedmunds** [comment]
This controller seems fine.  I'm running out of ideas.  Maybe try a lower sess_time_to_update, this should be lower than the expiration time you want.

**Comment by benedmunds** [comment]
Closing due to time elapsed since the last response.  Please submit a new ticket if this is still an issue.
