### ISSUE TITLE
Ion_auth controller error : Unable to load the requested file 

### ISSUE THREAD

**Issue by ezxcess** [benedmunds/CodeIgniter-Ion-Auth#1387]
I have a very weird error where it only occurs on my server running Ubuntu but working fine on my local dev running on WAMPserver on Windows 10. FYI, I am running CodeIgniter 3 with WireDesignz HMVC extension.

In all my other module's controllers, which reside in its own folders, eg. modules/cases/controllers/, modules/providers/controllers/, etc... Let me show you my folder and file structure

Example Structure
- modules/

  - auth/
    - controllers/
      - Auth.php
    - views/
      - auth/
        - footer.php
        - header.php
        - login.php

  - cases/
    - controllers/
      - My_cases.php
    - views/
      - private_cases/
        - private_cases_view.php
      - public_cases/
        - public_cases_view.php

In the controller My_cases.php, I am able to load a view file by simply calling:
  `$this->load->view('private_cases/private_cases_view')`

However, in the Auth controller, Auth.php, if I did the same, ie.
  `$this->load->view('auth/login')`
I will get the following error:

> An Error Was Encountered
Unable to load the requested file: auth/login.php

What is even weirder is that it works fine on my local dev environment but I get that error in the remote Ubuntu server. Currently, the only workaround is to add a slash as follows:
  `$this->load->view('/auth/login')`

This have fixed my issue but I wanted to know WHY is it happening? I have done everything exactly as what I did to the other modules, ie cases/ such as setting up routing in config/routes.php but for the life of me, I still don't know why Auth.php is not able to load without the starting slash/.

Hopefully you can help me understand. Thanks.

**Comment by benedmunds** [comment]
I'm not sure since I don't use HMVC.  You may get more help on the CI forums, might be worth cross posting there.

**Comment by benedmunds** [comment]
Closing due to age and the fact that this isn't an Ion Auth specific issue.
