### ISSUE TITLE
How can i disable debug mode?

### ISSUE THREAD

**Issue by metabinaryio** [benedmunds/CodeIgniter-Ion-Auth#1388]
Hi,

I want to disable debug mode, but it doesn't work. How do I do this for Ion auth? Since I am developing a public project, I will show an error page when customer open a link that is not valid. But there are hundreds of warnings. This is the smallest example! There's so much more.

Thanks for your help.

**Comment by benedmunds** [comment]
Ion auth doesn’t set debug mode.  That’ll be in either your CI setup or your PHP ini.
