### ISSUE TITLE
Double use esc function with form_input

### ISSUE THREAD

**Issue by MashinaMashina** [benedmunds/CodeIgniter-Ion-Auth#1393]
**Describe the bug**
Code:
```php
// In controller
$this->data['identity'] = [
	'name'  => 'identity',
	'id'    => 'identity',
	'type'  => 'text',
	'value' => set_value('identity'),
];

// In view
echo form_input($identity);
```

1. Enter \<h1>Hello\</h1> to field and submit.
2. In input you see "\&lt\;h1\&gt\;Hello\&lt\;/h1\&gt\;" instead your value
3. If you again submit, you see "\&amp\;lt\;h1\&amp\;gt\;Hello\&amp\;lt\;/h1\&amp\;gt;"
4. After you can see "&amp;amp;amp;amp;lt;h1&amp;amp;amp;amp;gt;Hello&amp;amp;amp;amp;lt;/h1&amp;amp;amp;amp;gt;" and etc

Such behavior because CI4 use esc() in set_value() and in form_input.

In controller must replace set_value('...'), to  set_value('...', '', false), because using escape again in form_input

**Comment by benedmunds** [comment]
Good catch!  Can you submit a PR for this?

**Comment by MashinaMashina** [comment]
> Good catch! Can you submit a PR for this?

What is PR?

**Comment by benedmunds** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by MashinaMashina** [comment]
> https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

I have only IonAuth with
1. Multi user auth (you can login in one account in miltiple devices).
2. Fixed ->numRows() (replace example "if ($user = $query->getRow())" ...) (https://forum.codeigniter.com/thread-71713-post-357749.html)
3. Added functions getUserdata() and setLoggedUser()
4. Replaced
$this->db->delete($this->tables['users'], ['id' => $id]);
to
$this->db->table($this->tables['users'])->delete(['id' => $id]);
https://codeigniter4.github.io/userguide/database/query_builder.html#deleting-data

5. Redirect locations after register and after login in config
6. Edit set_value(). Fix double escaping

But it isnt universal and need to modify a lot. I modified only the functions I need. Tables I write in code and etc

**Comment by benedmunds** [comment]
I’m not sure I follow. Is this more than just the controller change to set_value?

**Comment by MashinaMashina** [comment]
I made a big update for myself

**Comment by benedmunds** [comment]
You can make the PR in a separate repo or branch, then just apply this once fix, so your other changes won’t be in the PR.

**Comment by benedmunds** [comment]
Closing. Definitely encourage that PR submission when you have time.  Thanks!
