### ISSUE TITLE
Security Error

### ISSUE THREAD

**Issue by gpdas1** [benedmunds/CodeIgniter-Ion-Auth#1395]
Hi Ben
While trying to change 'password' or any other fields of 'users' table, the following error comes.  
"This form post did not pass our security checks"
Your guidance please.

![IonAuthSecurity](https://user-images.githubusercontent.com/4804013/71358232-57745380-25ae-11ea-94da-c159df1e42fe.JPG)

**This Github Issue section is meant to track bugs with the library itself**
Please post generic support issues to the CodeIgniter forums or StackOverflow.

**Comment by benedmunds** [comment]
That’s a CSRF error most likely.  Are you using the Ion Auth CSRF from the example controller or the CodeIgniter CSRF?

**Comment by gpdas1** [comment]
I am using CodeIgniter CSRF.

**Comment by benedmunds** [comment]
Are you using the example forms as is or have you made changes?  Have multiple forms on the same page or using javascript to submit?

**Comment by benedmunds** [comment]
Closing due to time elapsed since the last response.  Please submit a new ticket if this is still an issue.
