### ISSUE TITLE
How to NOT Expire Session

### ISSUE THREAD

**Issue by Andrewsuares** [benedmunds/CodeIgniter-Ion-Auth#1399]
Hello,

Is it possible to disable the session timeout? I want to be logged in permanently on multiple devices.  For some reason I keep getting logged out on Firefox on Android. I can login fine. I've set the remember option to enabled. And I've made the changes below.

$config['recheck_timer']              = 0;
$config['user_expire']                = 0;

		/*$recheck = $this->ion_auth_model->recheck_session();

		// auto-login the user if they are remembered
		if (!$recheck && get_cookie($this->config->item('remember_cookie_name', 'ion_auth')))
		{
			$recheck = $this->ion_auth_model->login_remembered_user();
		}*/

**Comment by benedmunds** [comment]
If you set $recheck to false on that first line and leave the IF block in place it should always log you back in.  I think...

**Comment by benedmunds** [comment]
Any update on this?

**Comment by Andrewsuares** [comment]
Hello,

Doesn't seem to have logged out yet.

**Comment by benedmunds** [comment]
Awesome!  I'll go ahead and close the ticket.  Feel free to open a new one if an issue pops up.

**Comment by Andrewsuares** [comment]
Hello Ben,

I've experienced a logout today. Is there anything in these functions that would create the logout?

		$recheck = FALSE;

		// auto-login the user if they are remembered
		if (!$recheck && get_cookie($this->config->item('remember_cookie_name', 'ion_auth')))
		{
			$recheck = $this->ion_auth_model->login_remembered_user();
		}

		$recheck = $this->ion_auth_model->login_remembered_user();
		return $recheck;

Thanks

**Comment by benedmunds** [comment]
Looks fine.  Makes me wonder if anything happened to the cookie data in the browser.

**Comment by Andrewsuares** [comment]
Does Ion Auth modify the cookie on subsequent logins after it is set?

**Comment by benedmunds** [comment]
Yea it does:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/models/Ion_auth_model.php#L2057

Might be worth trying to comment out:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/models/Ion_auth_model.php#L2074

or moving that delete_cookie call to before:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/models/Ion_auth_model.php#L2064

I wonder if there's some type of session data race condition in play here...

**Comment by Andrewsuares** [comment]
Ok, lets start over again.

Here's the modified logged_in function. 

public function logged_in()
{
	$this->ion_auth_model->trigger_events('logged_in');

	// Login remember is forced.
	$recheck = $this->ion_auth_model->login_remembered_user();
	return $recheck;
}

And here's where I see the 'You are not authorized' error. This bit is used in the controller of my control panel. This says that if(!$this->ion_auth->in_group($group)) {
is false, then show the error. 

// Check group
$group = 'admin';
if(!$this->ion_auth->in_group($group)) {
	echo 'You are not authorized!';
	exit();
}

Now here's what happens:
1) On my phone, I am logged in to the control panel BUT I dont visit the control panel for many days. When I visit, the above error shows.
2) On my laptop, I visit the CP everyday and it does'nt show the error.

IS the cookie based on time extensions? Is the cookie deleted if the session has expired?

I see the expire for the remember_code COOKIE as Expires:"Wed, 09 Feb 2022 11:23:09 GMT"

Line 2074. I have this commented out already.
// delete_cookie($this->config->item('remember_cookie_name', 'ion_auth'));
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/models/Ion_auth_model.php#L2074

**Comment by benedmunds** [comment]
Are you logging in to the same account on phone and web?  Only one remember code is supported at a time, could that be the issue here?

**Comment by Andrewsuares** [comment]
Yes. I am logging in with the same account on both devices. I have another account that 5 people use. So we need one account to be used by multiple people for sure. How does it know that another device has logged in? Can we disable that?

**Comment by benedmunds** [comment]
Sorry for not catching this earlier, this makes a lot more sense now.

The remember code is stored in the user table so there is only one at a time.  If you wanted to remember multiple users you’d need to extend this functionality to use a table for remember codes and then store N codes per user.

**Comment by Andrewsuares** [comment]
I've built cookie based auth in some projects by:

1) Creating the cookie after the user logs in correctly.
2) On subsequent logins, the user ID from the cookie is checked against the db. If the user has been deleted, the cookie is deleted and the user is logged out.

Where do I make the change so that the db lookup for remember user is disabled. Instead, I can add the lookup to see if the user exists or not.

**Comment by benedmunds** [comment]
You'd need to change the login_remembered_user(https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/models/Ion_auth_model.php#L2039) and remember_user(https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/models/Ion_auth_model.php#L1982) and clear_remember_code(https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/models/Ion_auth_model.php#L531) methods to use a sub table instead of storing the codes in the users table.

**Comment by Andrewsuares** [comment]
Thanks for your help. This query was the problem. I've added an ELSE to return TRUE always. 
		$this->trigger_events('extra_where');
		$query = $this->db->select($this->identity_column . ', id, email, remember_code, last_login')
						  ->where('remember_selector', $token->selector)
						  ->where('active', 1)
						  ->limit(1)
						  ->get($this->tables['users']);


The next change was to set $selector as a static value. So on every login, anything to do with user auth does not change. To force a logout, I have to just disable the user.

Thanks!

**Comment by benedmunds** [comment]
Ah awesome, glad that you figured out a workaround!  Do make sure that this doesn’t allow users to login by creating the cookie with fake values though, it seems like this would bypass password checking...

**Comment by Andrewsuares** [comment]
Hello Ben, I'm currently checking the username. Should I check the password also by storing its md5 value in a new field in the table and the cookie? And then compare the two values on subsequent logins?

**Comment by benedmunds** [comment]
It’s definitely safer to check a hash, you could just store the password hash in the cookie and then compare that.  That would allow you to have multiple browsers use remember me.

but will be a huge security concern if the hashing algo is ever broken one day. Because the hashes will be visible in the browser.

The best option really is to have a new table of remember codes, that way you could kill sessions by deleting the entries if needed in the future.

**Comment by Andrewsuares** [comment]
>>The best option really is to have a new table of remember codes, that way you could kill sessions by deleting the entries if needed in the future.

The remember code is also stored in a cookie. Cracking a hash of a password and cracking a remember code. Isis'nt this the same? The attacker would still gain access?

**Comment by benedmunds** [comment]
Cracking the hash is the same but there are a couple advantages to remember hashes:

1. exposing passwords is much worse than exposing a random hash
2. hashes are easier to upgrade the algo for, you just delete the hashes and have subsequent logins create new hashes on an updated algo

If this is some type of internal site or intranet I would just store the password hash in the cookie.  If this is a public site then I recommend using remember hashes.
