### ISSUE TITLE
How to use custom library send email function in Ion Auth

### ISSUE THREAD

**Issue by petershok** [benedmunds/CodeIgniter-Ion-Auth#1402]
I want to use Amazon SDK API instead of SMTP I have created Amazon Access Key and Amazon Secret Key and implemented in my project to send email. It is working fine.  For this I have created a custom library for CodeIgniter by following the documentation given at URL: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-sdk-php.html 

Now when I reached the page where the user does signup, I found that for Sign In and Sign Up website using Ion Auth.  How I can tell Ion Auth to send email using my custom library function instead of using CodeIgniter send mail using SMTP.

**Comment by benedmunds** [comment]
For CI3 you could write a MY_Email class that overrides this functionality to wrap Amazon sending.  

For CI4 you should be able to inject an email class that implements the send method to call Amazon.
