### ISSUE TITLE
Change password not working v4

### ISSUE THREAD

**Issue by Daniel-Monroy** [benedmunds/CodeIgniter-Ion-Auth#1403]
# Hotifx 

## In the branch ci4, the method change_password is not working. This generates by the new structure of CI4

file Controller/Auth, line number 248

file Model/Ion_auth_model, method `change_password`

**Comment by benedmunds** [comment]
You should be using changePassword() with CI4, see https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/4/Controllers/Auth.php#L250

If that is what you're using, what issue are you seeing?

**Comment by Daniel-Monroy** [comment]
Thank you for your answer, the problem is https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/d485dfe97d9b6a9bf98e8ec6f5b0851ac3813b7e/Controllers/Auth.php#L248
and 
The method: 
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/d485dfe97d9b6a9bf98e8ec6f5b0851ac3813b7e/Models/IonAuthModel.php#L555

**Comment by benedmunds** [comment]
Can you describe the issue you’re seeing and what you’ve tried to troubleshoot it so far?

**Comment by Daniel-Monroy** [comment]
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/d485dfe97d9b6a9bf98e8ec6f5b0851ac3813b7e/Controllers/Auth.php#L248

For this

Apparently, CI4 no longer supports `$this->session->user_data('identity')`  instead is `$this->session->get('identity')`

**Comment by Daniel-Monroy** [comment]
For this 

https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/d485dfe97d9b6a9bf98e8ec6f5b0851ac3813b7e/Models/IonAuthModel.php#L555


![Captura de pantalla de 2020-02-27 18-38-53](https://user-images.githubusercontent.com/45611570/75499715-76b5a580-5990-11ea-97a3-a191fa8a92d2.png)

This is the solution that I propose: 

public function changePassword(string $identity, string $old, string $new): bool
	{
		$this->triggerEvents('pre_change_password');

		$this->triggerEvents('extra_where');

		$builder = $this->db->table($this->tables['users']);
		$query   = $builder
					   ->select('id, password')
					   ->where($this->identityColumn, $identity)
					   ->limit(1)
					   ->get()->getResult();

		if (empty($query))
		{
			$this->triggerEvents(['post_change_password', 'post_change_password_unsuccessful']);
			$this->setError('IonAuth.password_change_unsuccessful');
			return false;
		}

		$user = $query[0];

		if ($this->verifyPassword($old, $user->password, $identity))
		{
			$result = $this->setPasswordDb($identity, $new);

			if ($result)
			{
				$this->triggerEvents(['post_change_password', 'post_change_password_successful']);
				$this->setMessage('IonAuth.password_change_successful');
			}
			else
			{
				$this->triggerEvents(['post_change_password', 'post_change_password_unsuccessful']);
				$this->setError('IonAuth.password_change_unsuccessful');
			}

			return $result;
		}

		$this->setError('IonAuth.password_change_unsuccessful');
		return false;
	}

**Comment by benedmunds** [comment]
Ah gotcha! That makes sense.  Thanks for all the info here.

Are you game for submitting a PR (https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) to fix this? If not that’s fine, I can patch it.

**Comment by Daniel-Monroy** [comment]
Good morning, I have a branch with the solution but:

> remote: Permission to benedmunds/CodeIgniter-Ion-Auth.git denied to danielMonroy96.
> fatal: unable to access 'https://github.com/benedmunds/CodeIgniter-Ion-Auth.git/': The requested URL returned error: 403

**Comment by benedmunds** [comment]
Awesome!  So check that link I posted above.  You’ll need to fork the repo, push to your feature branch, then submit a PR with that.
