### ISSUE TITLE
$activationCode = $this->ionAuthModel->activation_code; 

### ISSUE THREAD

**Issue by mauguzun** [benedmunds/CodeIgniter-Ion-Auth#1406]
**This Github Issue section is meant to track bugs with the library itself**
Please post generic support issues to the CodeIgniter forums or StackOverflow.
Hi im not sure but maby need change 

$activationCode = $this->ionAuthModel->activationCode; 
**Libraries/IonAuht.php  line 255 in v4** 
other wise Undefined property: IonAuth\\Models\\IonAuthModel::$activation_code

**Comment by benedmunds** [comment]
Fixed with https://github.com/benedmunds/CodeIgniter-Ion-Auth/commit/2f134c5abc8e5b72fb32da01475c114fc3e96d0a

Thanks!
