### ISSUE TITLE
Error installing using composer

### ISSUE THREAD

**Issue by matheuspelegrino** [benedmunds/CodeIgniter-Ion-Auth#1409]
**Which branch are you using?**
4 

**What CodeIgniter version are you using?**
v4

**What PHP version are you using?**
PHP 7.4.2

**Describe the bug**
![Error](https://user-images.githubusercontent.com/45601574/75988662-aef93e80-5ed0-11ea-8cb3-7eb53dd1c3f2.jpg)

**To Reproduce**
1. Installing appstarter via composer as per the documentation ci4
2. Installing ionauth via composer as the file installing.md
3. Added routes according to ion auth docs
4. When accessing ion_auth routes see errors

Using the installation of ion auth by adding it to the root this problem does not occur

**Comment by bvrignaud** [comment]
Can you update your composer (`composer update`) please and test if it's ok ?
I just fix somes bugs on v4 branch.

**Comment by matheuspelegrino** [comment]
Everything is OK. Closing the topic. Thanks @bvrignaud
