### ISSUE TITLE
Missing Bcrypt Library file in download zip 

### ISSUE THREAD

**Issue by ghost** [benedmunds/CodeIgniter-Ion-Auth#1413]
**Which branch are you using?** : Branch 3

**What CodeIgniter version are you using?**
v3

**What PHP version are you using?**
PHP 7.2

Description of Bug:
------------------
I downloaded the zip file and installation instruction states that there should be a Bcrypt.php file in the Library folder. This is missing.

**Comment by benedmunds** [comment]
There's no longer a Bcrypt.php file since we're using the native PHP password hashing now.  I'll update the docs. Thanks!

**Comment by benedmunds** [comment]
Actually, it looks like the docs have been updated.  Where are you seeing this?

**Comment by ghost** [comment]
Hi,
Thank you for your reply. I found it in the tutorial link https://avenir.ro/authentication-system-with-ion-auth-and-ci3/lets-install-ion-auth-library/. It looks like it was done in 2016. Where can i get the latest tutorial? Sorry to ask you this but i am unable to find the right one.

**Comment by benedmunds** [comment]
@avenirer hey! any interest in updating your tutorial?

**Comment by benedmunds** [comment]
@murugapan the readme.md and installing.md are the best ways to get started atm

**Comment by ghost** [comment]
Hi benedmunds
Thank you for help. I will be updating the tutorial after i complete the testing. There are some errors in it.
