### ISSUE TITLE
Can't set username on registration

### ISSUE THREAD

**Issue by Max-02** [benedmunds/CodeIgniter-Ion-Auth#1414]
Hello
I just stated using ion auth so I got the newest version installed.
I am using the newest version of code igniter 3 and php 7.3.

In the Ion_auth_model.php register function is this on line 846:

$data = [
	$this->identity_column => $identity,
	'username' => $identity,
	'password' => $password,
	'email' => $email,
	'ip_address' => $ip_address,
	'created_on' => time(),
	'active' => ($manual_activation === FALSE ? 1 : 0)
];

Why do you set the username to the identity. So you cant set your username free. The username must be the identity. I want to set the email as the identity. In this case the username is the same as the email. 

I deleted this line of code: 'username' => $identity, and the bug was gone.

I may misunderstand the code, then I'm sorry. In any case, I would appreciate an answer.
Kind regards Max Klebe

**Comment by benedmunds** [comment]
Pass in the email address as the username or identity in the register() call and it should work fine.  Identity is the name of the variable that’s passed in.

**Comment by Max-02** [comment]
Yes, sorry if i get it wrong but i want an email as the key and a username that everyone can choose and the username should not be equal to the email.
I call the function like this: 

$password = $this->input->post("pass");
$email = $this->input->post("email");
$additional_data = array(
   'username' => $this->input->post("username"),
    'ID_Fachrichtung' => $this->input->post("specialization"),
 );
$this->ion_auth->register($email, $password, $email, $additional_data);

The config line:
$config['identity'] = 'email'; 

If I do this, the username is the same as the email.

**Comment by benedmunds** [comment]
Ah ok. So for that pass the parameters like you are but pass the username under additional data on a subsequent update call. I think that will work, I’ve never seen someone want a username if it’s not the identify PK before actually...

**Comment by Max-02** [comment]
Yes that shoud work.
This is your example of the register funciton on http://benedmunds.com/ion_auth/

$username = 'benedmunds';
$password = '12345678';
$email = 'ben.edmunds@gmail.com';
$additional_data = array(
      'first_name' => 'Ben',
       'last_name' => 'Edmunds',
 );
$group = array('1'); // Sets user to admin.
$this->ion_auth->register($username, $password, $email, $additional_data, $group);

But on stadard configuration and if you use the parameters right, the call of the register function should look like that:

$additional_data = array(
       'username' => $username,
      'first_name' => 'Ben',
       'last_name' => 'Edmunds',
 );
$this->ion_auth->register($email, $password, $email, $additional_data, $group);

And there we got the problem again.
But if you delete this line 'username' => $identity of the register funciton all is working fine.
I dont understand the purpose of this line. Bescause if somewane want to identify over the username he can change the config and the code is working fine  without this line.

**Comment by benedmunds** [comment]
Yea I get you’re point here, the username field in the DB probably should have been named “identity” from the start but it wasn’t and keeping the BC means not changing it.

Most people use either the username as the PK or the email as the PK (and don’t use username at all). I’ve never seen someone use email as the PK but still have a username.  So it’s a bit of an edge case here.

If you want to submit a PR that solves your use case but also retain BC, I’d be happy to review and consider it.  Thanks!

**Comment by Max-02** [comment]
Just opened a PR
