### ISSUE TITLE
can't not login

### ISSUE THREAD

**Issue by kylincodelab** [benedmunds/CodeIgniter-Ion-Auth#1419]
**Which branch are you using?**
2/3/4 (branch used should match CodeIgniter version)
3
**What commit hash are you on?**
Attempt updating to the latest commit on your branch.

**What CodeIgniter version are you using?**
v2/v3/v4
v3
**What PHP version are you using?**
PHP 5.4/5.6/5.7/7.0/etc
7.0
**Post your Ion Auth config below**
```
Config goes here
```

**Describe the bug**

**To Reproduce**
1. i rebuild the server 
2.cpoy all the website files to new dir
3.i login the website,but always found the http header :`refresh: 0;url=https://***.** `

**Expected behavior**
I think the bug should be at `/application/controllers/Auth.php`
but find nothing.....

**Comment by kylincodelab** [comment]
request:

:```
authority: **.**
:method: GET
:path: /auth/login
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: zh-CN,zh;q=0.9
cache-control: max-age=0
cookie: session=l3qq9hu4a92hs9llpq755sl2bl6e2rgd
referer: https://**.**/auth/login
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

```

response:

:authority: **.**
:method: GET
:path: /auth/login
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: zh-CN,zh;q=0.9
cache-control: max-age=0
cookie: session=l3qq9hu4a92hs9llpq755sl2bl6e2rgd
referer: https://**.**/auth/login
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**Comment by JamesShaver** [comment]
The login method takes a POST request, and you're using GET here.
