### ISSUE TITLE
If flashdata is set to identity than the user is shown as logged in

### ISSUE THREAD

**Issue by b3wii** [benedmunds/CodeIgniter-Ion-Auth#1420]
@benedmunds What do you think of this code?

```
if($this->session->flashdata('identity') === $this->session->userdata('identity')){
	throw new Exception("Don't set flashdata identity!");
}
```

Because if flashdata is set to identity than user is falsely detected as logged in:

//reset flashdata & userdata

```
$this->session->set_userdata('identity', $somevalue);

var_dump($this->session->flashdata('identity')); => null
var_dump($this->session->userdata('identity')); => $somevalue
```

//reset flashdata & userdata

```
$this->session->set_flashdata('identity', $somevalue);

var_dump($this->session->flashdata('identity')); => $somevalue
var_dump($this->session->userdata('identity')); => $somevalue

$this->ion_auth->logged_in() => true
```

**Comment by benedmunds** [comment]
How would this get set?  Are you worried that a developer would set that in the application code?

**Comment by b3wii** [comment]
Yes, if you set flashdata before redirect and check after redirect for example in contructor if user is logged in. I found this because i worked on a project that didnt use the newest version where Ion_auth.php logged_in() returns this:

`return (bool) $this->ci->session->userdata($identity)`

But it could still happen in the current version if set_flashdata('identity') is used.

**Comment by benedmunds** [comment]
Ah that makes sense. I’m cool with this check, send a PR whenever you get a chance please.
