### ISSUE TITLE
 Area accessible only to the administrator

### ISSUE THREAD

**Issue by Marcolino92** [benedmunds/CodeIgniter-Ion-Auth#1422]
I don't want to be wrong, but I think there is a bug.
If an UNLOGGED user tries to access a page visible only to the administrator, he shows an error, as he tries to find the user ID. Instead it works, if the user is logged in.

**TypeError
Argument 1 passed to App\Models\IonAuthModel::getUsersGroups() must be of the type integer, null given, called in /home/mhd-01/www.scriptlowcost.com/htdocs/script/app/Models/IonAuthModel.php on line 1568**

```
1520      * Get all groups a user is part of
1521      *
1522      * @param integer $id If a user id is not passed the id of the currently logged in user will be used
1523      *
1524      * @return \CodeIgniter\Database\ResultInterface
1525      * @author Ben Edmunds
1526      */
1527     public function getUsersGroups(int $id=0)
1528     {
1529         $this->triggerEvents('get_users_group');
1530 
1531         // if no id was passed use the current users id
1532         $id || $id = $this->session->get('user_id');
1533 
1534         $builder = $this->db->table($this->tables['users_groups']);
```

**Comment by benedmunds** [comment]
Hey, let me recap to make sure I understand.

Are you saying that you can get any users groups even if you aren't an admin?

**Comment by Marcolino92** [comment]
No. If a visitor (user not logged in) accesses a page restrictive to ADMIN only, it shows the error written above.

```
if(!$this->ionAuth->isAdmin()){
      redirect()->to('login');
}
```

If instead, the user is logged in, it works.

**Comment by benedmunds** [comment]
Ok cool.  So I think that is correct but we should probably stop the user from seeing a link to that page at all if they aren't logged in.

**Comment by benedmunds** [comment]
That or change the type hint to accept null and then throw a custom error. What do you think?

**Comment by Marcolino92** [comment]
It would be ideal to redirect to the login page

**Comment by Marcolino92** [comment]
How can I solve this?

**Comment by benedmunds** [comment]
@Marcolino92 actually, are you seeing this on the index page or the edit_user page?

**Comment by benedmunds** [comment]
Both of the getUsersGroups() calls are behind an admin check in the example controller.  Can you post your controller code that's generating this error as well please.

**Comment by Marcolino92** [comment]
I simply cloned the Auth controller.

```
namespace app\Controllers;

/**
 * Class Auth
 *
 * @property Ion_auth|Ion_auth_model $ion_auth      The ION Auth spark
 * @package  CodeIgniter-Ion-Auth
 * @author   Ben Edmunds <ben.edmunds@gmail.com>
 * @author   Benoit VRIGNAUD <benoit.vrignaud@zaclys.net>
 * @license  https://opensource.org/licenses/MIT	MIT License
 */
class Admin extends \App\Controllers\Auth {

	/**
	 *
	 * @var array
	 */
	public $data = [];

	/**
	 * Configuration
	 *
	 * @var \IonAuth\Config\IonAuth
	 */
	protected $configIonAuth;

	/**
	 * Constructor
	 *
	 * @return void
	 */
	public function __construct(){
		helper(['form', 'url', 'database', 'session']);
		$this->configIonAuth = config('IonAuth');
        $this->config = config('App');
	}
    
    /**
	 * Redirect if needed, otherwise display the user list
	 *
	 * @return string|\CodeIgniter\HTTP\RedirectResponse
	 */
	public function index(){
        
        $data = [
            'title' => 'Admin',
            'validation' => \Config\Services::validation(),
            'auth' => new \App\Libraries\IonAuth(),
            'session' => \Config\Services::session(),

        ];
        
        if(!$data['auth']->isAdmin()){
            redirect()->to('login');
        }

        echo view('themes/partial/header', $data);
        echo view('themes/admin/index', $data);
        echo view('themes/partial/footer');
	}
    
}
```

**Comment by benedmunds** [comment]
Are you not getting in to that not isAdmin if or is the redirect not working?

**Comment by Marcolino92** [comment]
If a visitor enters the page with only admin restriction, it shows that error. If, on the other hand, the user logged in tries to access the page, it works.

The problem lies in the fact that the function must necessarily recognize a user ID, otherwise an error. It would take something that if the user is not logged in redirects to the login page.

**Comment by Marcolino92** [comment]
Okay, I solved it
`public function getUsersGroups($id=false)`

and added return that I had forgotten to the redirect function

```
if(!$data['auth']->isAdmin()){
            return redirect()->to('login');
        }
```

**Comment by benedmunds** [comment]
Oh sorry I see.  Try changing 
`        if(!$data['auth']->isAdmin()){’
To 
`        if(!$data[‘auth’]->isLoggedIn() || !$data['auth']->isAdmin()){ `

**Comment by benedmunds** [comment]
Ok awesome 🎉
