### ISSUE TITLE
is there any package available for social auth?? 

### ISSUE THREAD

**Issue by jualahmed** [benedmunds/CodeIgniter-Ion-Auth#1423]
i am using CodeIgniter-Ion-Auth to authorize my application. now i want to user social auth like facebook,google .... is there any package available for make the easy?

**Comment by benedmunds** [comment]
There's an outdated branch that uses socialize here:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/tree/social

This was based off v2 so is a bit old now.  You might be able to use it as inspiration for an updated version though.

If you get this working I'd love to work with you to make an extension to Ion Auth for this.

**Comment by bvrignaud** [comment]
You can have look to : [https://github.com/bvrignaud/ci-fb-ion-auth](https://github.com/bvrignaud/ci-fb-ion-auth).
