### ISSUE TITLE
Class 'IonAuth\Libraries\IonAuth' not found

### ISSUE THREAD

**Issue by maaaom** [benedmunds/CodeIgniter-Ion-Auth#1426]
I am trying to install IonAuth to CI4

I have coped full folder to App/ThirdParty folder, I want the IonAuth files to be there.

Then in my controller trying to call this library, but I got error "Class 'IonAuth\Libraries\IonAuth' not found".

In controller:

$ionAuth = new \IonAuth\Libraries\IonAuth();

**Comment by maaaom** [comment]
I have put this in Config/Autoload.php

$classmap = [
                    'IonAuth' => ROOTPATH . 'ThirdParty/IonAuth',
                ];

but still error coming

**Comment by bvrignaud** [comment]
Why don't you use composer ?

**Comment by maaaom** [comment]
How I can make composer put folder in ThirdParty/IonAuth

**Comment by bvrignaud** [comment]
You don't.
Leave composer to install php libraries in the vendor folder.
It's the same for CodeIgniter and any php libraries.

Please use Composer, it's the good way.

**Comment by maaaom** [comment]
But in vendor folder, to many folders, can be only vendor/IonAuth?

**Comment by bvrignaud** [comment]
This is not a problem. This is the "role" of the vendor folder. Each libraries install in this folder is required others libraries.
Forget the ThirdParty folder. I don't think it will be use.

Sorry for my English.

**Comment by maaaom** [comment]
I agree with you, I will not use ThirdParty folder, but in vendor folder I need IonAuth folder be in vendor root folder.

**Comment by bvrignaud** [comment]
You must have this : ROOT_FOLDER/vendor/benedmunds/codeigniter-ion-auth

**Comment by maaaom** [comment]
can not bet ROOT_FOLDER/vendor/IonAuth ??

**Comment by bvrignaud** [comment]
Maybe, but I'm not a composer ninja :-)
Keep simple, use standard !

**Comment by maaaom** [comment]
Thanks, last question .. how I can make privileges and roles for users and groups in IonAuth?

**Comment by bvrignaud** [comment]
You can find the documentation here "vendor/benedmunds/codeigniter-ion-auth/userguide/index.html".
You can test user role  in each controller or method.
I think the best way will be in the routes config file but I haven't test it and I think that some requirements missing. Note that this library (for CI4) is recent as CI4.

Look at : [https://docs.laminas.dev/laminas-permissions-acl/](https://docs.laminas.dev/laminas-permissions-acl/) or [https://github.com/lonnieezell/myth-auth](https://github.com/lonnieezell/myth-auth).

Please,use CodeIgniter forum for this kind of question.

**Comment by kabeza** [comment]
> Why don't you use composer ?

Hi @bvrignaud 

There are some devs that are not familiar to Composer. I'm one of them.

One of the reasons I try to avoid it is that when I set .dev file to "development", it got installed 37 additional packages in the vendor folder ... I just needed IonAuth!

Besides that... What should we do with vendor folder and all those packages after I finish developing the App? I guess I don't need to deliver those 37 packages in the production version

Thanks and sorry 4 the OT

**Comment by bvrignaud** [comment]
I am convinced that today, you have to use composing in all (or almost) new developments.

**Comment by bvrignaud** [comment]
I am convinced that today, you have to use composing in all (or almost) php developments.

If you doesn't want install dev packages, you have to install dependencies with : `composer install --no-dev`

When you deliver your app, you can use composer to install your dependencies on your server.
Connect to your server with ssh, go to your application directory, and just run `composer install --no-dev`.

Hope this can help you.

**Comment by kabeza** [comment]
> When you deliver your app, you can use composer to install your dependencies on your server.
> Connect to your server with ssh, go to your application directory, and just run `composer install --no-dev`.
> 
> Hope this can help you.

Great. Hope my shared hosting provider will have it
Thanks for the tip

**Comment by coderix44** [comment]
Hi, i installed CI4 SETUP & added respective files from this folder

$ git clone https://github.com/benedmunds/CodeIgniter-Ion-Auth.git
my-project$ cd CodeIgniter-Ion-Auth
CodeIgniter-Ion-Auth$ git checkout 4

on running the application i got 

Error
Class 'IonAuth\Libraries\IonAuth' not found

plz help

**Comment by bvrignaud** [comment]
Have you  add this in your Config/Autoload.php (https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/4/INSTALLING.md):
```php
'IonAuth' => ROOTPATH . 'CodeIgniter-Ion-Auth',
```

Like for everybody, the best way to use a php library is to install it with composer.

**Comment by coderix44** [comment]
I tried using this command, not working. ion_4 is my application name which is in c://wamp64/www
$psr4 = [
			'App'         => APPPATH,                // To ensure filters, etc still found,
			APP_NAMESPACE => APPPATH,                // For custom namespace
			'Config'      => APPPATH . 'Config',
			'IonAuth' => ROOTPATH . 'ion_4',
		];

	
		$classmap = [
		   'IonAuth' => ROOTPATH . 'ion_4',
		];





Also i tried using composer to download, its asking me some auth token to enter. 

C:\wamp64\www>composer require benedmunds/CodeIgniter-Ion-Auth:4.x.dev
./composer.json has been updated
Loading composer repositories with package information
GitHub API limit (0 calls/hr) is exhausted, could not fetch https://api.github.com/repos/benedmunds/CodeIgniter-Ion-Auth/contents/composer.json?ref=2a868d1b3f4eb00966089bd03dfa5af226cefa70. Create a GitHub OAuth token to go over the API rate limit. You can also wait until ? for the rate limit to reset.

Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+CoderixPC1+2020-06-27+0356
to retrieve a token. It will be stored in "C:/Users/Coderix PC-1/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):


PLz help
