### ISSUE TITLE
Implementing RBAC for ion_auth codeigniter

### ISSUE THREAD

**Issue by prince-adeshina** [benedmunds/CodeIgniter-Ion-Auth#1429]
Hi,
I am using ion_auth library for one of my web app projects. I find the library very useful and appreciate it.

I have settled everything and the system works well. But what i want to do is that i would like to implement RBAC model to manage the web app users access. I found the concept of group in ion_auth very interesting but i still can not achieve what i want to do. User is in a role, and permission is set for role. 

1- Right now i can add user to role(group) but i can not set permission to group(role). Do you have an idea of how to achieve this stuff ??

2- I found some RBAC library(like ezrbac) with codeigniter but i found them difficult to implement and some of them are not working. And may be you have a way to do that with ion_auth. So instead of looking for another library i will use ion_auth to do my work. If no, can you help me with how i can achieve RBAC with codeigniter based on your experience ?

Thank you so much in advance.

**Comment by benedmunds** [comment]
Hey, thanks for using the library!

Roles and groups are a pretty similar concept.  Users can have multiple groups and then you verify the role access with in group checks.  You will probably want to abstract that a bit based on how you’re setting it up across your site.

You might want to check this project to see if it would help as well:
https://github.com/weblogics/Codeigniter-Ion-Auth-ACL
