### ISSUE TITLE
Error in installation instructions for Codeigniter 4 Relational DB Setup

### ISSUE THREAD

**Issue by crysaro** [benedmunds/CodeIgniter-Ion-Auth#1433]
**Which branch are you using?**
4

**What CodeIgniter version are you using?**
v4

**What PHP version are you using?**
PHP 7.3.2

**Describe the bug**
In the instructions on https://github.com/bvrignaud/CodeIgniter-Ion-Auth/blob/4/INSTALLING.md, "Relational DB Setup"
When I issued the command:
`php spark migrate:latest -n IonAuth`
I get an error "Command not found"
but when i remove the ':latest' it works
php spark migrate: -n IonAuth

**Comment by benedmunds** [comment]
Ah good catch.  Can you send a PR?

**Comment by cseoneohs** [comment]
Hello, same thing for me...

**Comment by benedmunds** [comment]
Fixed with https://github.com/benedmunds/CodeIgniter-Ion-Auth/commit/4f8516d28ec8a26b35538507bc34b821728a5b40

Thanks!
