### ISSUE TITLE
Configuration Issue when you execute the migration

### ISSUE THREAD

**Issue by jcollin** [benedmunds/CodeIgniter-Ion-Auth#1436]
**Which branch are you using?**
4

**What CodeIgniter version are you using?**
v4

**What PHP version are you using?**
PHP 7.3.16

**Describe the bug**
Php spark migrate command don't use the personal App Config of IonAuth (App/Config) but only your default Config :(

**Comment by benedmunds** [comment]
Thanks, merged the PR!
