### ISSUE TITLE
Blank CI 4 with IonAuth, redirections, etc.

### ISSUE THREAD

**Issue by kabeza** [benedmunds/CodeIgniter-Ion-Auth#1440]
Hi Ben
I've followed the install guide along with CI 4.0.3
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/4/INSTALLING.md

When I modify the default Home controller, with this code

```
<?php namespace App\Controllers;

class Home extends BaseController
{
	public function __construct()
	{
		$this->ionAuth = new \IonAuth\Libraries\IonAuth();
	}

	public function index()
	{
        if(!$this->ionAuth->loggedIn()){       	
        	return redirect('auth/login');
        }
        else {
			return view('welcome_message');
        }
	}

	//--------------------------------------------------------------------

}

```

The login works, I see the form, I fill the fields but when clicking submit, I get redirected to http://localhost
The line doing that is
143 from IonAuth/Controllers/Auth.php

`				return redirect()->to('/');
`

My Routes.php contains this

`$routes->get('/', 'Home::index');`

Shouldn't I be redirected to Home/index instead http://localhost ?

No matter If I change that line to 

`return redirect()->route('/');`

I'm still being redirected to http://localhost
I've set .env to development, etc. but see no errors...

Thanks

**Comment by benedmunds** [comment]
If you want to use named routes, you can update that redirect to:
`return redirect()->route('Home::index');`

**Comment by kabeza** [comment]
> If you want to use named routes, you can update that redirect to:
> `return redirect()->route('Home::index');`

Hi again. Redirecting that way throws an exception

It is something strange with the redirect function. 
Maybe its my environment or browser

Solved it by replacing the redirect line in 
\IonAuth\Controllers\Auth\login 
with:

`return redirect()->route('dash');`

And creating that route in Routes.php 

`$routes->get('/dash', 'Home::dashboard');`

Thanks

**Comment by benedmunds** [comment]
Ah cool.  Glad it's solved!
