### ISSUE TITLE
'IonAuth\Models\stdClass' not found in IonAuthModel::setHook()

### ISSUE THREAD

**Issue by salalex** [benedmunds/CodeIgniter-Ion-Auth#1452]
**Which branch are you using?**
4

**What commit hash are you on?**
Latest

**What CodeIgniter version are you using?**
v4.0.3

**What PHP version are you using?**
PHP 7.2.11

**Post your Ion Auth config below**
```
<?php namespace Config;

class IonAuth extends \IonAuth\Config\IonAuth
{
    // set your specific config
    public $siteTitle               = 'UMDL Monitor';       // Site Title, example.com
    public $identity                = 'username';
    // public $adminEmail               = 'admin@example.com'; // Admin Email, admin@example.com
    // public $emailTemplates           = 'App\\Views\\auth\\email\\';
    // ...
}

```

**Describe the bug**
When calling setHook() from a controller, I get a "'IonAuth\Models\stdClass' not found" error:
![sethook-error](https://user-images.githubusercontent.com/7436475/84865809-1cdd0680-b079-11ea-973a-bbaf44e7cd35.PNG)

**To Reproduce**
1. Create a controller which extends \IonAuth\Controllers\Auth
2. Add a public static function hook_func() {};
3. Call, e.g.  $this->ionAuth->setHook("logout", "logout_hook",  get_class($this), "hook_func");
4. See the error

**Expected behavior**
I would expect the hook to be installed without errors.

**Comment**
I think the problem is a missing '\\' before "stdClass" on line 2257 of Models/IonAuthModel.php; adding it fixes the problem. If you think so, I can create a pull request.

**Comment by benedmunds** [comment]
This is a great error report, thank you for this.  I agree that the missing backslash is the issue here.  If you want to send a PR I'll be happy to merge it.  Thanks!!

**Comment by salalex** [comment]
PR done. Thank you

**Comment by benedmunds** [comment]
Merged, thank you!
