### ISSUE TITLE
Login possible with inactive users?

### ISSUE THREAD

**Issue by flow8282** [benedmunds/CodeIgniter-Ion-Auth#1454]
I just deactivated a user and expected that a login should not be possible anymore. But the login is still possible.
I took a short look at the source and it seems the 'active' field is not taken into account in the login function.

Is this a bug or do i misunderstand this feature?

**Comment by benedmunds** [comment]
What branch are you on?

For v3, active status is checked here:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/models/Ion_auth_model.php#L930

**Comment by flow8282** [comment]
Hi Ben,
thanks for you quick reply.
I'm on branch 4. The issue was an type safe comaprison which has already been fixed.
Sorry for wasting your time and many thanks for your great authentication system!!

**Comment by benedmunds** [comment]
Ah no problem, glad it was fixed :D
