### ISSUE TITLE
getUserByPasswordResetCode - invalid reset code

### ISSUE THREAD

**Issue by practiceryan** [benedmunds/CodeIgniter-Ion-Auth#1455]
I am using the password reset code through 'forgottenPasswordCheck' .

I've traced my particular issue to getUserByPasswordResetCode. The user is found, however the verifyPassword is returning false.

```
public function getUserByForgottenPasswordCode(string $userCode)
	{
		// Retrieve the token object from the code
		$token = $this->retrieveSelectorValidatorCouple($userCode);

       //related to a different problem, which was resolved by a previous resolved issue
        if ($token === FALSE) {
            return FALSE;
        }
       //end related problem

		// Retrieve the user according to this selector
		$user = $this->where('forgotten_password_selector', $token->selector)->users()->row();

		if ($user)
		{
			// Check the hash against the validator
			if ($this->verifyPassword($token->validator, $user->forgotten_password_code))
			{
				return $user;
			}
                        //My beautiful flag.
			echo 'Error cause by verify password in model';
		}

		return false;
	}
```

**Comment by benedmunds** [comment]
Any progress troubleshooting this yet?

I'll attempt to reproduce.  What is your PHP version, CI version, and can you post your Ion Auth config?  Thanks!

**Comment by aiflu** [comment]
Same here. I found `password_verify($password, $hashPasswordDb);` in IonAuthModel.php, and tested directly with the value of `$token->validator` and `$user->forgotten_password_code` which were generated by `$token = $this->generateSelectorValidatorCouple(20, 80);` in `public function forgottenPassword(string $identity)`. The return value is false.
I thought that something is wrong with the encryption.


CI 4.0.3, php7.2, Config `class IonAuth extends \IonAuth\Config\IonAuth` with the default config of hash

```
    public $hashMethod          = 'bcrypt';  // bcrypt or argon2
    public $bcryptDefaultCost   = 10;        // Set cost according to your server benchmark - but no lower than 10 (default PHP value)
    public $bcryptAdminCost     = 12;        // Cost for user in admin group
    public $argon2DefaultParams = [
        'memory_cost' => 1 << 12, // 4MB
        'time_cost'   => 2,
        'threads'     => 2,
    ];
    public $argon2AdminParams   = [
        'memory_cost' => 1 << 14, // 16MB
        'time_cost'   => 4,
        'threads'     => 2,
    ];
```

Thx a lot.

**Comment by aiflu** [comment]
I've the same problem here.
After debugging the `$this->ion_auth->generateSelectorValidatorCouple(20, 80);`. The problem is the length of field forgotten_password_code in mysql. Because the length of validatorHashed is 60.
Juste set it to char 255 solved the problem for me.

**Comment by benedmunds** [comment]
@aiflu thanks for the follow up!  Could you send a PR with that change?

**Comment by aiflu** [comment]
There is no changes in the IonAuth.
Its the usage mysql of @practiceryan maybe has an error. He should check the length of all fields for char 255 in his DB. If not, the validator will be cut off in the field.

**Comment by practiceryan** [comment]
Sorry, i've been struggling with a seperate Django issue. I will set this to closed as that is probably the issue.

If it isnt i shall reopen and nag further
