### ISSUE TITLE
Argument 1 passed to IonAuth\Models\IonAuthModel::getUsersGroups() must be of the type integer, null given

### ISSUE THREAD

**Issue by aiflu** [benedmunds/CodeIgniter-Ion-Auth#1456]
When i called `public function inGroup($checkGroup, int $id=0, bool $checkAll=false): bool`, i get this error. After tracing and testing the code in IonAuthModel, i found `$id || $id = $this->session->get('user_id');` may set $id = NULL. 

So when it arrives at `$usersGroups = $this->getUsersGroups($id)->getResult();`, with the definition `public function getUsersGroups(int $id=0)`, the parameter shouldn't be NULL. And error.

I thought `public function getUsersGroups(int $id=0)` should be changed to `public function getUsersGroups(?int $id=0)` or change the `$id || $id = $this->session->get('user_id');` to set 0 when $id is NULL.

Thx

**Comment by benedmunds** [comment]
So it shouldn’t be null by here but it shouldn’t default to zero either right?  Should we throw an exception earlier to this if the user isn’t passed or logged in?

**Comment by aiflu** [comment]
@benedmunds 
Yes, the default zero makes false while passing $id || ...
I don't agree to throw an exception. Because I use $ionAuth->loggedIn() && $ionAuth->inGroup($group) to check if user is logged in and in the right group. So the function could be used without login. If we throw an exception, we should use try catch for each calling of inGroup() ?

Maybe we can check and set $id to 0 just after `$id || $id = $this->session->get('user_id');` by `$id = $id>0? $id : 0`.

**Comment by benedmunds** [comment]
Is loggedIn() returning true? The inGroup() call shouldn't be evaluated if loggedIn() returns false in that example...

**Comment by aiflu** [comment]
@benedmunds You're right. Weird, i can't reproduce the error. Maybe i made some mistakes in my code and corrected it while in the dev.
I close the issue. I'll reopen it, if necessary.
Thx.
