### ISSUE TITLE
Update Ion 2 to Ion3 Authentication instructions

### ISSUE THREAD

**Issue by marinbale2377** [benedmunds/CodeIgniter-Ion-Auth#1461]
Hello, great piece of work, been using it for a while in my Codeigniter 3 projects
I migrated my previous Ion2 to Ion3 today. Everything went pretty smooth except that I also have to replace the {base_dir}/application/controllers/Auth.php with the newer version in the package too. 

I think is worth to mention in the update instruction.
Thanks again for your work here!

**Comment by benedmunds** [comment]
Thanks!

Great point, would you mind sending a PR to add that to the guide?

**Comment by marinbale2377** [comment]
Sure thing, the Upgrade instructions should say something like this:

**Upgrading**

1. Download the latest version: https://github.com/benedmunds/CodeIgniter-Ion-Auth/zipball/3
2. Overwrite "{CI_base_dir}/application/third_party/libraries/**ion_auth.php**" and "{CI_base_dir}/application/third_party/models/**ion_auth_model.php**" with the newer versions.
3. Overwrite "{CI_base_dir}/application/controllers/**Auth.php**" with the newer version.
4. Overwrite "{CI_base_dir}/application/third_party/language/*" with the news versions.
4. Check "config/ion_auth.php" for evolution.

Upgrading from Ion Auth 2? Check the UPGRADING.md file in the package.

**Comment by benedmunds** [comment]
I updated it to reflect this.  Thank you!
