### ISSUE TITLE
Session Destroy if Public IP Change

### ISSUE THREAD

**Issue by arquizade** [benedmunds/CodeIgniter-Ion-Auth#1466]
**This Github Issue section is meant to track bugs with the library itself**
Please post generic support issues to the CodeIgniter forums or StackOverflow.
I have a project using CI3 i setup all the session expiration in 1 day. But my main issue is every time the machine change IP it will automatically logout or session destroy; for reference the machine is connected to a 4G connection router so the public IP change time-to-time. I hope you can help me a way that will not automatically logout. Thank you.

**Comment by benedmunds** [comment]
Hey,

This isn’t an Ion Auth specific issue but a CI session issue so you might have better luck on the CI forums.

One idea to try is to hard code remember me to always be set and see if that would solve it.
