### ISSUE TITLE
Codeigniter 4 ion Auth remember me not working

### ISSUE THREAD

**Issue by shoyshai** [benedmunds/CodeIgniter-Ion-Auth#1472]
remember me not working in codeigniter ioun auth 4

**Comment by benedmunds** [comment]
@abitme is working on this here: https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/1475#pullrequestreview-489675304

**Comment by shahid1579** [comment]
@benedmunds  
$this->load->library('bcrypt',$rounds);
From where this library is loading ?
As i am getting this Error "Unable to load the requested class: Bcrypt"

**Comment by benedmunds** [comment]
@shahid1579 are you using v4?

**Comment by shahid1579** [comment]
@benedmunds  V3 
But that was resolve as some Ion_auth files were mixed with old and new because of hectic sublime Text editor

**Comment by benedmunds** [comment]
Closing this due to age.  Please reopen if you're still experiencing issues here.
