### ISSUE TITLE
Ion Auth Forgot Password email

### ISSUE THREAD

**Issue by Keshangit** [benedmunds/CodeIgniter-Ion-Auth#1483]
I'm trying to install Ion_auth it's working fine. But forgot password email not sending. "Password Reset Email Sent" massage is showing. but there is no email receiving. I followed https://avenir.ro/authentication-system-with-ion-auth-and-ci3/lets-install-ion-auth-library/  this tutorial.

**Comment by benedmunds** [comment]
It's likely something with your email config.  I recommend creating a controller/method that uses the email class to send a test email with debugger information.  Use that to troubleshoot to find the correct config.  Then Ion Auth emails should work.
