### ISSUE TITLE
activation_code error on auth/create_user

### ISSUE THREAD

**Issue by rjvillanueva89** [benedmunds/CodeIgniter-Ion-Auth#1486]
**Which branch are you using?**
4

**What commit hash are you on?**
fa5caafe3476af8f168e8595a8fb4ca7cd0cd7ce

**What CodeIgniter version are you using?**
v4 (4.0.3)

**What PHP version are you using?**
PHP 7.4.9

**Post your Ion Auth config below**
```
public $useCiEmail = true;
public $emailActivation = true;
public $manualActivation = true;
```

**Describe the bug**
after submitting to auth/create_user function I got a 500 internal error on Libraries/IonAuth.php line 255

after debugging I saw that:
instead of: 
$this->ionAuthModel->activation_code

it should be: 
$this->ionAuthModel->activationCode

**Comment by bvrignaud** [comment]
You're right.
Can you make a PR please ?

**Comment by rjvillanueva89** [comment]
Sorry about that, this issue seems to have been fixed already.
