### ISSUE TITLE
Migration file does not work with argon2

### ISSUE THREAD

**Issue by ageir** [benedmunds/CodeIgniter-Ion-Auth#1495]
**Which branch are you using?**
Codeigniter 4

**What commit hash are you on?**
b5ab91268177d58bd0c30dde3cd11c71f6db26a6

**What CodeIgniter version are you using?**
v4

**What PHP version are you using?**
PHP 7.4

**Describe the bug**

Migration is not working with argon2.
20181211100537_install_ion_auth.php

The password column is too small. I tried hashing argon2 and it is 95 characters.
Login fails if using the migration file. Is 95 the correct length I should have in the database for argon 2? or can it be larger?

From the migration file:
`			'password' => [
				'type'       => 'VARCHAR',
				'constraint' => '80',
			],
`

**Comment by benedmunds** [comment]
I just pushed a fix for this with 4d671a26bc507dc49f08e1e069d3e94e88d5f637
