### ISSUE TITLE
Verify if the user is ON LINE

### ISSUE THREAD

**Issue by jaiasoftware** [benedmunds/CodeIgniter-Ion-Auth#1499]
Hi Ed!

My aplication need the user logegd in only once, but, in ION-AUTH i don't see anywhere for this, can you help me with any sugestion, please?

**Comment by benedmunds** [comment]
That isn't supported currently.  To do this in your app you'd need to track sessions and then kill any other active sessions for that user when they log in.  

You could check past issues for ideas on how to accomplish this, here one:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/issues/947
