### ISSUE TITLE
Controllers\Auth Line: 583 $this->data['message'] = $this->validation->getErrors() ? .....

### ISSUE THREAD

**Issue by moutlou** [benedmunds/CodeIgniter-Ion-Auth#1508]
PLease fix it to return empty string. When there aren't erros it returning a string with length = 134. We need preg_match or trim to check if is empty or not.
Otherwise you can add a variable like me

$this->data['hasErrors'] = $this->validation->getErrors() ? true : false ;

Thank you for this great library Ben.

**Comment by benedmunds** [comment]
Hey, the Validation library is a part of CI, not Ion Auth.

**Comment by moutlou** [comment]
But the variable $message is yours Ben. You are creating this var in the $data. İ didnt check but it musnt have 134 spaces , İ think.


Web Developer & Software Engineer


Kimden: Ben Edmunds ***@***.***>Gönderildi: 2 Nisan 2021 Cuma 02:35Kime: benedmunds/CodeIgniter-Ion-AuthBilgi: Moutlou; AuthorKonu: Re: [benedmunds/CodeIgniter-Ion-Auth] Controllers\Auth Line: 583 $this->data['message'] = $this->validation->getErrors() ? ..... (#1508)
Hey, the Validation library is a part of CI, not Ion Auth.

**Comment by benedmunds** [comment]
Sorry, I'm not quite following.  Is this as issue with what validation->getErrors() is returning into $data['message']?  Which version of Ion Auth and CI are you using?

**Comment by moutlou** [comment]
Ben, when there aren’t errors it not returning an empty string but a string with 134 spaces.

**Comment by benedmunds** [comment]
Which version of Ion Auth and CI are you using?

**Comment by moutlou** [comment]
I’m using Codeigniter 4  and IonAuth 4

 

 

I’m using it with extending your base class like this

class Authentication extends \IonAuth\Controllers\Auth

 

without any implementation into mt main class

**Comment by benedmunds** [comment]
validation->getErrors() should return as array, not a string...  See the CI source here:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Validation/Validation.php#L741

If you have an error are you getting an array back?  Which commit hash or specific version of CI are you using?

**Comment by moutlou** [comment]
Hello Ben,

The variable $message with var_dump($message) showed [string(139) “ “] ….

So, I found the problem. The variable $message contains the debug string as hex an it not showing anything.

 

The debug string is :

“

 

”

**Comment by benedmunds** [comment]
So it is an empty array? Is there an issue with that?

**Comment by moutlou** [comment]
No all are ok now Ben

**Comment by benedmunds** [comment]
Ok cool. Closing this issue then, thanks!
