### ISSUE TITLE
Hello How can solve this problem? Please Help me.

### ISSUE THREAD

**Issue by RaghuGlobytex24** [benedmunds/CodeIgniter-Ion-Auth#1517]
Hello How can solve this problem? Please Help me.
An uncaught Exception was encountered
Type: RuntimeException

Message: Unable to locate the model you have specified: Login_model

Filename: /var/www/html/abc/system/core/Loader.php

Line Number: 348

Backtrace:

File: /var/www/html/abc/application/controllers/Main.php
Line: 11
Function: __construct

File: /var/www/html/abc/index.php
Line: 315
Function: require_once

_Originally posted by @debasism2014 in https://github.com/benedmunds/CodeIgniter-Ion-Auth/issues/892#issuecomment-492995446_

**Comment by benedmunds** [comment]
Ion Auth doesn't have a Login_model file.  For general CodeIgniter support please post on the CI Forums or StackOverflow.
