### ISSUE TITLE
The requested URL was not found on this server.(Debian)

### ISSUE THREAD

**Issue by paranpul** [benedmunds/CodeIgniter-Ion-Auth#1525]
Linux

$cat /proc/version
Linux version 4.19.0-14-cloud-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.171-2 (2021-01-30)

$apache2 -v 
Server version: Apache/2.4.38 (Debian)
Server built:   2020-08-25T20:08:29

$php -v
PHP 8.0.3 (cli) (built: Mar  5 2021 08:38:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies

$mysql --version
mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Test Codeigniter:  v4.1.2 & v4.1.3

==================================
In my Linux Server
https://my_domain/auth

Not Found
The requested URL was not found on this server.
Apache/2.4.38 (Debian) Server at my_domain Port 443

In my Windows Test Server
http://localhost/auth/login

Login
Please login with your email/username and password below.
Email/Username: 
Password: 
Remember Me: 
Forgot your password?

===================================
Is there a way to fix the above not working issue?
And it works good on Windows.
Of course the installed Apache, PHP, database and codeigniter are the same for Windows and Linux.

![Ion-Auth-Linux-Err](https://user-images.githubusercontent.com/61884831/120935669-d80b0f00-c6d1-11eb-8359-2b01982402f0.png)
![Ion-Auth-Windows-OK](https://user-images.githubusercontent.com/61884831/120935670-d8a3a580-c6d1-11eb-88fc-858dcc57b9ff.png)

**Comment by benedmunds** [comment]
This is an issue with your environment, related more to  web server or CodeIgniter setup than an Ion Auth issue.

I'd recommend asking on the CI Forums or StackOverflow.
