### ISSUE TITLE
please solution

### ISSUE THREAD

**Issue by ichalnfi** [benedmunds/CodeIgniter-Ion-Auth#1527]
Message: Unable to locate the model you have specified: User_model

Filename: /home/u1362025/public_html/absen.nusaflyinginternational.com/system/core/Loader.php

Line Number: 348

Backtrace:

File: /home/u1362025/public_html/absen.nusaflyinginternational.com/application/controllers/User.php
Line: 10
Function: model

File: /home/u1362025/public_html/absen.nusaflyinginternational.com/index.php
Line: 315
Function: require_once

**Comment by benedmunds** [comment]
Ion Auth doesn't have a User_model.  Please post generic CI support questions to either the CI forums or StackOverflow.  Take care!
