### ISSUE TITLE
Using different email template for normal user and admin

### ISSUE THREAD

**Issue by federicovilla** [benedmunds/CodeIgniter-Ion-Auth#1534]
Using Codeigniter 3 here.
In my project I have a section reserved to admin users and a public login area for the registered normal user.
If the registered users (normal or admin ) use the forgot password funnction, they receive the same email with the same link to create a new password; I'm wondering if I set different email template/reset password link for different users.
In the config file I just see  one variable for that.
Thanks a lot for any feedback

**Comment by benedmunds** [comment]
In the config you can set `use_ci_email` to false, then do the email sending logic in your controller.
