### ISSUE TITLE
Argument 2 passed to IonAuth\Models\IonAuthModel::verifyPassword() must be of the type string, null given, called in /vendor/benedmunds/codeigniter-ion-auth/Models/IonAuthModel.php on line 764

### ISSUE THREAD

**Issue by simbu2dev** [benedmunds/CodeIgniter-Ion-Auth#1535]
**Which branch are you using?**
4 

**What commit hash are you on?**
Attempt updating to the latest commit on your branch.

**What CodeIgniter version are you using?**
v4

**What PHP version are you using?**
PHP 7.4.3

**Post your Ion Auth config below**
```
Config goes here
```

**Describe the bug**
Argument 2 passed to IonAuth\Models\IonAuthModel::verifyPassword() must be of the type string, null given, called in /vendor/benedmunds/codeigniter-ion-auth/Models/IonAuthModel.php on line 764

**To Reproduce**
1. Go to forgot password page and send a reset password link via email
2. Click on the Reset Password link from an email
3. Reset the password
4. Click the same reset link after reset password success

**Expected behavior**
It should give us an error template like 'link expired, generate new reset password link, already password reset done'...etc. But it throws TypeError

**Comment by benedmunds** [comment]
I just pushed a fix for this:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/commit/88e28e1570d377e9350b011be01de66e2d5505ca

Let me know if this fixes it for you as well please.


Thanks!

**Comment by simbu2dev** [comment]
> I just pushed a fix for this:
> [88e28e1](https://github.com/benedmunds/CodeIgniter-Ion-Auth/commit/88e28e1570d377e9350b011be01de66e2d5505ca)
> 
> Let me know if this fixes it for you as well please.
> 
> Thanks!

Yes, It works now and Thanks @benedmunds

**Comment by benedmunds** [comment]
Awesome, thanks for reporting it!
