### ISSUE TITLE
help for functionality triggers 

### ISSUE THREAD

**Issue by junglaCODE** [benedmunds/CodeIgniter-Ion-Auth#1536]
this question is for ci4

I have doubts in the use of triggers, example to register a user : `$this->ionAuthModel->triggerEvents('pre_account_creation')`

does nothing. and out there I see that there are some others who do the same.

I'd like to see if you could explain how it works

Thanks

**Comment by benedmunds** [comment]
Hey,

Are you saying that a few of them in particular aren’t working or that triggers/hooks aren’t working at all?

Here’s a good article on using them with CI3 (CI4 usage will be similar):
http://oldblog.codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth

**Comment by junglaCODE** [comment]
great. 


I am trying to dock this great library to be a service, also to adapt it a little more to the vision of ci4


thanks, for the information.

**Comment by benedmunds** [comment]
Sounds good, take care!
