### ISSUE TITLE
An uncaught Exception was encountered

### ISSUE THREAD

**Issue by Amchege** [benedmunds/CodeIgniter-Ion-Auth#1539]
**This Github Issue section is meant to track bugs with the library itself**
Please post generic support issues to the CodeIgniter forums or StackOverflow.
Type: Error

Message: Class 'Front_Controller' not found

Filename: /home/alphate1/pwani.alphatecdesigns.co.ke/application/controllers/Welcome.php

Line Number: 5

Backtrace:

File: /home/alphate1/pwani.alphatecdesigns.co.ke/index.php
Line: 307
Function: require_once

**Comment by avenirer** [comment]
This is not related to Ion auth. Try some stackexchange. :)
