### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by ghost** [benedmunds/CodeIgniter-Ion-Auth#1547]
I think the documentation needs to be updated, Please update immediately because I followed the documentation there are some that don't work,,Such as the logged_in function,,Why can't I,,, it works when I use loggedIn()

**Comment by datamweb** [comment]
Hi,Please [download ](https://github.com/benedmunds/CodeIgniter-Ion-Auth/zipball/4) and use its userguide. This is for version CI4.x .

**Comment by datamweb** [comment]
> I think the documentation needs to be updated, Please update immediately because I followed the documentation there are some that don't work,,Such as the logged_in function,,Why can't I,,, it works when I use loggedIn()

Hi,Please [download ](https://github.com/benedmunds/CodeIgniter-Ion-Auth/zipball/4) and use its userguide. This is for version CI4.x .

**Comment by avenirer** [comment]
Here's what. Asking for something to be done "immediately" is not helping anyone. It's open source what you are using here. Everyone does his/her best to help, without getting anything in return, but the ocasional "thanks". In this community we expect that if someone is using the code, he/she also has the good sense of helping out, either by fixing bugs, or by helping with documentation, or even by promoting the code in articles. :)

**Comment by benedmunds** [comment]
Closing this since it looks like you were using the v3 docs with v4 code.  Feel free to submit a PR if you find any issues in the v4 docs.

**Comment by ghost** [comment]
thanks

**Comment by ghost** [comment]
I want to ask, the forgottenPassword() and forgottenPasswordCheck() functions don't reset the password, the forgottenPassword() function only sends an email to reset the password, and the forgottenPassword() function checks the code, Means I need to make my own to update users' passwords?

**Comment by benedmunds** [comment]
Hey. The forgottenPassword method sets the hash for that but the user needs to set their actual new password.

You can see an example of this workflow in the included controller:

forgot_password:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/4/Controllers/Auth.php#L271

->

reset_password:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/4/Controllers/Auth.php#L351
