### ISSUE TITLE
Help me, how to call auth controller

### ISSUE THREAD

**Issue by youhunt** [benedmunds/CodeIgniter-Ion-Auth#1550]
Hi, Please help me how to solve my problem
I have do this installation
1. Download the latest version: https://github.com/benedmunds/CodeIgniter-Ion-Auth/zipball/3
2. Copy the files from this package to the correspoding folder in your application folder. For example, copy Ion_auth/config/ion_auth.php to system/application/config/ion_auth.php.
3. Run the appropriate SQL file from the /sql directory.

But when I try to go to http://localhost/ci3/auth, I got this error

Object not found!
The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the [webmaster]

Thanks and regards

Yohan Dedik Irawan

**Comment by youhunt** [comment]
But when I try to go to http://localhost/ci3/index.php/auth, it's redirect to http://localhost/ci3/auth/login.
But it's no error when manually I go to http://localhost/ci3/index.php/auth/login
Any advise or suggestion?

**Comment by benedmunds** [comment]
So index.php URLs work but direct URLs don’t?  That sounds like an issue with the URL rewriting on your server.

Does this work for routes outside of Auth?

**Comment by youhunt** [comment]
It's solved by URL rewriting by create .htaccess file. Thanks
