### ISSUE TITLE
install with composer problem

### ISSUE THREAD

**Issue by nemanjagmitric72** [benedmunds/CodeIgniter-Ion-Auth#1551]
I have a problem installing IonAuth with composer. 
When i run comand "composer require benedmunds/CodeIgniter-Ion-Auth:4.x-dev" i have error:  "./composer.json has been updated
Installation failed, reverting ./composer.json and ./composer.lock to their original content.
[RuntimeException]
  require.benedmunds/CodeIgniter-Ion-Auth is invalid, it should not contain uppercase characters. Please use benedmunds/codeigniter-ion-auth instead.  "
Can you help me whit this problem?

**Comment by benedmunds** [comment]
This has been fixed
