### ISSUE TITLE
Requires 'Remember Me' to be checked in order to log in.

### ISSUE THREAD

**Issue by zer01ne** [benedmunds/CodeIgniter-Ion-Auth#156]
Using the default username and password, (admin@admin.com / password), Ion Auth will not keep me logged in unless I check the 'Remember Me' checkbox.  I have tried multiple times, but get the same results.  I do not get a displayed error, just recycles to base_url.  However, if I check the 'Remember Me' button, then it keeps me logged in.

**Comment by ar27111994** [comment]
Still having this issue. Please help. @benedmunds @caseyh

**Comment by ar27111994** [comment]
Ok just figured it out. Its an ongoing issue with codeigniter sessions and PHP 7.1 and hasn't been fixed yet AFAIK.

**Comment by benedmunds** [comment]
2 is correct.  Merged the PR, thanks so much!
