### ISSUE TITLE
Description of getUsersGroups() method is incorrect

### ISSUE THREAD

**Issue by dgvirtual** [benedmunds/CodeIgniter-Ion-Auth#1562]
The Userguide to the version 4 describes usage of function getUsersGroups():

`$user_groups = $this->ionAuth->getUsersGroups($user->id)->result();`

the last method in the chain should actually be `getResult()`

**Comment by benedmunds** [comment]
Thanks for reporting!  Would you be interested in submitting a PR for this?

**Comment by benedmunds** [comment]
PR merged.  Thank you!
