### ISSUE TITLE
Force user change password

### ISSUE THREAD

**Issue by marcelod** [benedmunds/CodeIgniter-Ion-Auth#1573]
Hello, do you know if there is something to force the user to change the password every month, for example, and not be able to use the last 3 passwords?

**Comment by benedmunds** [comment]
I'm not aware of any existing solution for this.  To implement this you'd need to add a table storing the previous 3 password hashes as well as the update time for each, then check against that at next login or via a cronjob.

**Comment by marcelod** [comment]
Yes that's what I'm creating but doing in user login I check. Thanks
