### ISSUE TITLE
IonAuth - Codeigniter 4 - not working in php 8.2

### ISSUE THREAD

**Issue by AdascaliteiMarian** [benedmunds/CodeIgniter-Ion-Auth#1579]
Hi, I opened this because I found a while ago some comments about it and I can't seem to find the section anymore.
I want to know when is there gonna be an update for it or if it's gonna happen.

Thank you !

**Comment by benedmunds** [comment]
Hey,

What errors are you seeing in 8.2? Just dynamic property errors? Anything else?

Would you be interested in sending a PR to fix the dynamic properties?

**Comment by rafaelppaulucci** [comment]
Same here.. 

@benedmunds did you make a test with 8.2?
In PHP 8.1 everything works like a charm.

Thank you!

**Comment by datamweb** [comment]
@benedmunds I checked there is no problem with PHP 8.2.6 and CI 4.4.3.

![Screenshot 2023-11-15 194801](https://github.com/benedmunds/CodeIgniter-Ion-Auth/assets/9530214/8c919ae5-2932-4e91-b89b-f9f1e95073b7)

![Screenshot 2023-11-15 195137](https://github.com/benedmunds/CodeIgniter-Ion-Auth/assets/9530214/f4cd2b3c-3590-4b22-90c7-703a0c4cdae6)


```console
P:\Bug\ion\ionphp82>php  -v
PHP 8.2.6 (cli) (built: May  9 2023 16:02:16) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.6, Copyright (c), by Zend Technologies
    with Xdebug v3.2.2, Copyright (c) 2002-2023, by Derick Rethans

P:\Bug\ion\ionphp82>
```

**Comment by benedmunds** [comment]
Thanks @datamweb !
