### ISSUE TITLE
No 3.x releases - why?

### ISSUE THREAD

**Issue by dont-panic-42** [benedmunds/CodeIgniter-Ion-Auth#1583]
Hello,

Thank you for Ion Auth.

I'm working on a project still using CodeIgniter 3, and using Ion Auth 2.x.  While checking for updates I noticed that there is a 3.x branch of Ion Auth for CodeIgniter 3, but there is no 3.x release listed:

https://github.com/benedmunds/CodeIgniter-Ion-Auth/tags

Is that because 3.x was never stable enough for a release?  Is 3.x safe to use?

Thank you

**Comment by benedmunds** [comment]
Hey v3 is stable and good to use.   I just switched to a @latest release model there so didn’t cut releases.
