### ISSUE TITLE
$this->ion_auth->user() returns Ion_Auth_Model

### ISSUE THREAD

**Issue by gregmax17** [benedmunds/CodeIgniter-Ion-Auth#184]
This code explains it: 

[code]
public function user($id = NULL)
    {
        $this->trigger_events('user');

```
    //if no id was passed use the current users id
    $id || $id = $this->session->userdata('user_id');

    $this->limit(1);
    $this->where($this->tables['users'].'.id', $id);

    $this->users();

    return $this;
}
```

[/code]

Shouldn't it return something like:

[code]
return $this->response->row();
[/code]

Of course then, it still doesn't return the 'group' and 'group_description' the user belongs in as it states in the docs.

**Comment by waitaamon** [comment]
how can i get all members in a group?
