### ISSUE TITLE
function to verify password

### ISSUE THREAD

**Issue by rabu81** [benedmunds/CodeIgniter-Ion-Auth#233]
hi,

it would be nice with a method, to verify password.

e.g. i want to have a form, where a user can change password - but I want the original password to be verified, before I process and update the password on the user.

this it how it's done right now:

$id = 12;
$data = array(
    'password' => '123456789',
);               );
$this->ion_auth->update($id, $data)

would be nice, if I could verify before, by doing a call something like this:

$id = 12;
$originalPassword = $this->input->post('original_password');
$this->ion_auth->verify($id, $originalPassword)

I hope it make sense :)
- Rasmus

**Comment by ajaysahu93** [comment]
Hi, can you please help? As i load and call the verify() method, it throws an error saying "Undefined method Ion_auth::verify() called". Also i searched and couldnt find the verify method inside third_party\ion_auth\libraries\Ion_auth.php. 

Here is my authentication code:
Model:
function validate()
	{
		$un=$this->input->post('username');
		$pw=$this->input->post('password');

		$this->load->library('ion_auth');
		$this->ion_auth->verify($un, $pw);
		if ($this->ion_auth->hash_password_db($un, $pw) == TRUE)
		{
			$this->db->where('username', $un);
			$query=$this->db->get('users');
			foreach($query->result() as $rows)
			{
				$results[]= array(
					'first_name' => $rows->first_name,
					'phone' 		=> $rows->phone,
					'total_points' => $rows->total_points,
					);
			}

			return $results;
		}
			
		else return false;

**Comment by benedmunds** [comment]
@ajaysahu93 you dont need the verify() call, just delete that line and hash_password_db will handle it.
