### ISSUE TITLE
Modular branch of IonAuth library

### ISSUE THREAD

**Issue by sepehr** [benedmunds/CodeIgniter-Ion-Auth#257]
Is there any chance to maintain a modular branch of IonAuth library that works with Modular Extensions out of the box in the main repository?  
I'm currently maintaining it at [sepehr/ci-mongodb-ionauth-module](https://github.com/sepehr/ci-mongodb-ionauth-module), but it's hard to always keep it up to date with this upstream repo.

**Comment by taragurung** [comment]
Am really looking for the ion_auth library embedded in HMVC modules  Or the way to handle it

**Comment by absmugz** [comment]
Hi I am trying to have ion_auth library embedded in HMVC modules Or the way to handle it ? How do I go about this ?

**Comment by sepehr** [comment]
@absmugz, @taragurung: Here's an outdated IonAuth repo that can get you inspired how to make a HMVC module out of IonAuth:  
https://github.com/sepehr/ci-mongodb-ionauth-module

That's the best I can do for now :disappointed:

**Comment by taragurung** [comment]
@absmugz I have made it completely ready and using it in my project will send you soon cheers

**Comment by gregsidberry** [comment]
Optional: Update Controller as mentioned 

Update the naming in 3 locations, changing auth/ to module_name/auth/ 

Model -> BCRYPT library
Controller->redirects, find / replace: redirect('auth/ -> redirect('module_name/auth/
views-> links

ref: 
http://dmitriykravchuk.co.za/blog/2015/10/30/codeigniter-3-hmvc-ion-auth/
