### ISSUE TITLE
change password

### ISSUE THREAD

**Issue by 3ncor3** [benedmunds/CodeIgniter-Ion-Auth#277]
Hello,

I think you missed the `change_password()` functions in Ion_auth.php library file. 

But the model is there at line 525 `change_password($identity, $old, $new)`.

To counter this, I copy below functions from old Ion_auth library (v1 or something) and Its work!

``` /**
     * Change password.
     *
     * @return void
     * @author Mathew
     **/
    public function change_password($identity, $old, $new)
    {
        if ($this->ion_auth_model->change_password($identity, $old, $new))
        {
            $this->set_message('password_change_successful');
            return TRUE;
        }

        $this->set_error('password_change_unsuccessful');
        return FALSE;
    }
```

but can someone from Ion_auth team fix this issue? I hate when I found I need to repeating doing this. And also please write `change_password()` in documentation page, It's seems you missed that too.

Thx

**Comment by gpdas1** [comment]
Ben is great! It is there. Create a Hyperlink 'Change password' with href='auth/change_password'
