### ISSUE TITLE
users() exhausing php memory

### ISSUE THREAD

**Issue by taberrr** [benedmunds/CodeIgniter-Ion-Auth#291]
Hi, I have a db with about 135k users and when I try to use `$this->ion_auth->users()` I'm hitting PHP's memory limit (currently set to ~85mb). I can hit the table directly with an offset/limit, but was wondering if you'd consider adding a limit/offset parameter to the method?

**Comment by rameshchoudary** [comment]
how to redirect user to user's dashboard and admin to admin's dashboard

**Comment by benedmunds** [comment]
I don't understand your question.  What have you tried?
