### ISSUE TITLE
Unable to load the requested file: auth/login.php

### ISSUE THREAD

**Issue by perepost** [benedmunds/CodeIgniter-Ion-Auth#31]
Hi, I'm a noob on object oriented php and CI so I decided to try this one to get me started.
I'm trying CodeIgniter_1.7.2 with benedmunds-CodeIgniter-Ion-Auth-b15a45f.zip
CI install went fine, did the DB stuff and copied Ion-Auth files to respective directorys.

Now when I try: http://mytestserver/codeigniter/index.php/auth/login
I get: An Error Was Encountered
Unable to load the requested file: auth/login.php

Any clues of where I got it wrong?
Permissions seems fine.

**Comment by mfsi-avisheks** [comment]
I am sorry but I face the same issue :(. what made it fixed?

**Comment by benedmunds** [comment]
It was a path issue if I remember correctly.
