### ISSUE TITLE
forgotten password complete mail

### ISSUE THREAD

**Issue by danielschweiger** [benedmunds/CodeIgniter-Ion-Auth#353]
the password reset mail with the link to the reset page works, but I get no complete mail. I cant find the place where this is finaly send ...

shouldn't this mail be send somewhere like here in the controller:

//reset password - final step for forgotten password
    public function reset_password($code = NULL)
    {

....

$change = $this->ion_auth->reset_password($identity, $this->input->post('new'));

if($change) {

.... // send the complete mail?

With basic setup I dont get this mail, all other mails work ...

**Comment by Bhavinshah5111** [comment]
ion auth forgot password mail send but  not received in mail account.please help me .
how can i solve this ?

**Comment by benedmunds** [comment]
The best thing to do is just to create a test controller method that sends an email to work out the proper email settings.

**Comment by Bhavinshah5111** [comment]
problem in config file.but now it works ...sorry for disturbing ...thanks a lot...

**Comment by benedmunds** [comment]
What was the correct answer? for future users.

**Comment by Bhavinshah5111** [comment]
sir i made one email file and changing some security in gmail...
in my email config file 
<?php
 $config["mailtype"] = "html";
$config["protocol"] = "smtp";
$config["smtp_host"] = "ssl://smtp.googlemail.com";
$config["smtp_user"] = "xxxx@gmail.com";
$config["smtp_pass"] = "xxxx";
$config["smtp_port"] = 465;
$config["crlf"] = "\r\n";
$config["newline"] = "\r\n";
?>
suggest to made config file for email

**Comment by pudyasto** [comment]
Hey sir, I've successfully using reset password and using method forgotten_password_complete.
my question : 
how to change new password with some numbers 

like : 
Your password has been reset to: Yp9p68377WPUFv3xa1oClu

![2016-12-14 1](https://cloud.githubusercontent.com/assets/7855552/21188373/cbbd487c-c24d-11e6-9a66-252ee4f76ae9.png)

Thanks a lot ...
