### ISSUE TITLE
Problems with Undefined Property: Controller::$_cache_user_in_group

### ISSUE THREAD

**Issue by smokinjoe** [benedmunds/CodeIgniter-Ion-Auth#365]
Ben: Please disregard the email!  Not sure why I didn't think of using Github first.

I'm looking to upgrade our Ion Auth.  However, after bringing in the new files I'm running into these errors:

```
12/11/12 4:58:48.232 PM Joe: PHP-ERROR Severity: Notice  --> Undefined property: Home::$_cache_user_in_group /application/libraries/Ion_auth.php 121
12/11/12 4:58:48.232 PM Joe: PHP-ERROR Severity: Notice  --> Indirect modification of overloaded property Ion_auth::$_cache_user_in_group has no effect /application/libraries/Ion_auth.php 74
```

I'm trying to debug this but frankly, I have NO idea where to even begin looking to resolve this.  I'm not quite understanding what is going on and why this is occurring.

The only thing that I've been able to determine, is that this issue is stemming from _cache_user_in_group.. I think.

I commented line 74 in the Ion_auth.php library:
     `#$this->_cache_user_in_group =& $this->ion_auth_model->_cache_user_in_group;`

And I've been able to fill out and POST through the login form.  As I travel amongst pages, I get these errors:

```
12/11/12 5:01:08.004 PM Joe: PHP-ERROR Severity: Notice  --> Undefined property: Admin::$_cache_user_in_group /application/libraries/Ion_auth.php 121
12/11/12 5:01:08.006 PM Joe  PHP-ERROR Severity: Notice  --> Undefined property: Admin::$_cache_user_in_group /application/libraries/Ion_auth.php 121
12/11/12 5:01:08.006 PM Joe  PHP-ERROR Severity: Notice  --> Indirect modification of overloaded property Ion_auth::$_cache_user_in_group has no effect /application/libraries/Ion_auth.php 463
```

Well, hopefully that's a decent amount of info to help.  Please let me know if you need anymore info!

**Comment by paulcanning** [comment]
I'm also getting this error, and I am only loading the library in the autoload.php file. Is there anything else I can do to stop this error appearing?
