### ISSUE TITLE
Expired sessions not deleting fully and crashing.

### ISSUE THREAD

**Issue by Kebie** [benedmunds/CodeIgniter-Ion-Auth#392]
If I leave my project in my browser open for awhile the set_session() function in the model will start crashing.

A PHP Error was encountered
Severity: Notice
Message: Undefined property: stdClass::$username
Filename: models/ion_auth_model.php
Line Number: 1592

A PHP Error was encountered
Severity: Notice
Message: Undefined property: stdClass::$last_login
Filename: models/ion_auth_model.php
Line Number: 1595

All I am doing is calling $this->ion_auth->is_admin() in my controller. I am using a MAMP setup and CHROME. Is there something weird going on with session settings somewhere that I have to look into? If I delete all my localhost cookies and refresh it works fine again.

Anyone else experience this error? I tried searching.

Anyways awesome library, saved me lots of time.

**Comment by chrismackie28** [comment]
I'm getting the same issue but all works as expected in a live environment (heroku) so this seems like a mamp issue.
