### ISSUE TITLE
users() method returns objects where "id" is ambiguous

### ISSUE THREAD

**Issue by jamieburchell** [benedmunds/CodeIgniter-Ion-Auth#402]
When using the `users()` method and passing in a group ID the following SQL is generated:

```
SELECT DISTINCT *
FROM (`users`)
INNER JOIN `users_groups` ON `users_groups`.`user_m_id`=`users`.`id`
WHERE `users_groups`.`group_m_id` IN (1)
```

This means that when looping through the results, $user->id is actually the primary key of the `users_groups` table, rather than the user's ID.

**Comment by zawaruddin** [comment]
i'm using sql server and try to get a user by user() function and i get error "Ambiguous column name 'id' "

I think there is an error on line 1400 in ion_auth_model
$this->order_by('id', 'desc');    

so I tried to change it
$this->order_by($this->tables['users'].'.id', 'desc');

**Comment by benedmunds** [comment]
Can you send a PR?
