### ISSUE TITLE
 Redirect occuring on local environment but not production site

### ISSUE THREAD

**Issue by kc1** [benedmunds/CodeIgniter-Ion-Auth#465]
Hi Ben and everyone, 

I'm using Ion_auth with codeigniter. I have the following:

```
if ($this->form_validation->run() == true && $this->ion_auth->register($username, $password, $email, $additional_data))
    {
        //check to see if we are creating the user
        $this->session->set_flashdata('message', 'PLEASE CHECK EMAIL');
        redirect("auth", 'refresh');
```

I've tried: redirect("auth/login", 'refresh');, redirect("auth/index", 'refresh'); as well

This works fine with expected redirection to the 'auth' controller in my wamp development environment. But  I just get a blank screen on the remote website.

Any ideas on what to do next?

Thank you in advance,

Bill

**Comment by jollysprings** [comment]
Hello sir, You really doing a nice job with these Internet security. I use one of your services (the Ion Auth). I worked perfectly on my development server but when uploaded to my production server. I refuse to authenticate and when the correct login details is supplied; it tries login but throws user back to the login page. what do i do. i use code igniter 2.1.
 thanks in anticipation.
jollysprings

**Comment by benedmunds** [comment]
Make sure you're using the same PHP version on both and that you have bcrypt on the production server.

**Comment by jollysprings** [comment]
Thank you Sir for taking out your time to respond to my issues with Ion auth.
The issue still persist. My development server is php version 5.4.4. while that of my production is php version 5.4.4.1. A there is not bcrypt on both servers but Mcrypt is what i have enabled on both servers. 
It only shows form validation errors and not any other errors. when the right login details is provided, it will only flash the url of the admin panel to be access but will automatically return me to the login page again. I have been on this issue for more than a day now.Thank you in advance for any assistance
jollysprings      On Tuesday, 9 June 2015, 22:24, Ben Edmunds <notifications@github.com> wrote:
   

 Make sure you're using the same PHP version on both and that you have bcrypt on the production server.—
