### ISSUE TITLE
Can't change email address?

### ISSUE THREAD

**Issue by dodyagung** [benedmunds/CodeIgniter-Ion-Auth#474]
Hello, I'm new to this CI-Ion-Auth.

I still learning about this library. I also make a project that require user management, and I use this for my library.

I have a question, can I change the email address of user? (or is it possible?)
I have tried to change the email field in the database, and it's didn't work (couldn't login, maybe the email was required for encrypting password).

**Comment by antonradev** [comment]
@dodyagung  Did you implement changing the Email of the user? Could you share with me? How to check if it is not the email of some other user?
Thank you very much in advance!
