### ISSUE TITLE
Switching between username/email as identity

### ISSUE THREAD

**Issue by nathanpitman** [benedmunds/CodeIgniter-Ion-Auth#510]
I have a project where I would like to allow users to log-in with a username in one part of the app and have other users elsewhere in the app log-in with email address - I'm guessing that this might be as simple as switching the config var on the fly before I call register or log-in etc

I wondered if this was something that had been attempted by anyone else before and whether there are any immediate pitfalls I should be aware of...

**Comment by paulcanning** [comment]
I have tried this implementation and it's not working for me.

Code:

if($username):
                $forgotten = $this->ion_auth->forgotten_password($username);
            else:
                $this->ion_auth_model->identity_column = 'email';
                $forgotten = $this->ion_auth->forgotten_password($email);
            endif;

When trying to use an email, I just get an error saying "Unable to Reset Password"

**Comment by paulcanning** [comment]
I fixed the problem, by modifying Ion_auth.php, line 144

$identifier = $this->ion_auth_model->identity_column; // new line
$user = $this->where($identifier, $identity)->users()->row();  // changed

**Comment by benedmunds** [comment]
You're reference doesn't seem to match the current codebase.  Can you send a PR against current 2 branch?

**Comment by paulcanning** [comment]
Hmm, I'll have the check what version I'm using, it's been a while! 

Can you provide the reference code from the current codebase just so I can see the difference? 

I'll try do a PR in work tomorrow

**Comment by benedmunds** [comment]
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/libraries/Ion_auth.php#L144

That is line 144 in the current library

**Comment by paulcanning** [comment]
Looks  like I need line 140?

**Comment by benedmunds** [comment]
I dont see a query using username.  Maybe it was fixed since you last updated your local?

**Comment by paulcanning** [comment]
The issue was that it was using the configuration file no matter what. My code replaced the config with what ever the model was set too, meaning it could be overriden easily

**Comment by benedmunds** [comment]
Ah right. Ok. Send a PR when you get a chance and I'll be happy to merge it.

**Comment by warisaajkal** [comment]
Hi, Sir, I'm a learner of PHP I'm using first time Ion Auth user system

Please add username field on create user form if a new user register where put a username and how to check it new user username not exist in database.

Thanks

**Comment by benedmunds** [comment]
The controller is a example. Feel free to modify as needed.

**Comment by warisaajkal** [comment]
Thanks @benedmunds
