### ISSUE TITLE
Unable to Send Activation Email

### ISSUE THREAD

**Issue by wasconet** [benedmunds/CodeIgniter-Ion-Auth#538]
I have read almost everything online about getting email activation to work but its just not working for me.
1. have $config['email_activation'] = TRUE;
2. $config['use_ci_email'] = TRUE; 
3. $config['email_config'] = array(
             'protocol' => 'smtp',
             'smtp_host' => 'ssl://smtp.googlemail.com',
             'smtp_port' => 465,
             'smtp_user' => '*****_@gmail.com',
             'smtp_pass' => '**_**********', 
             'mailtype' => 'html',
             'charset' => 'iso-8859-1',
             'wordwrap' => TRUE
   );

I have tried sending email using native php mail() and it works, i tried codeigniter's mail and it works but i am getting "Unable to Send Activation Email" after registration using ion_auth

I created a file email.php in my config folder and still i am getting the "Unable to Send Activation Email" but even weirder on some controller i get this error when i have the email.php file

"Message: Cannot modify header information - headers already sent by (output started at /home/xxxxxxxx/public_html/application/config/email.php:1)"

Thanks Ben

**Comment by muditmehrotra** [comment]
Hi Ben,

I am new to ion_auth. I have done user registration successfully but I also need to send activation email to user and when user click that link his account need to be activate. My client wants to send activation email by using the mandrill.com. So my query is how I can do this? Also i have try to send activation email by configuring the config/ion_auth file by adding following code for gmail:

$config['email_activation']           = TRUE;               // Email Activation for registration
$config['manual_activation']          = FALSE;  

$config['use_ci_email'] = TRUE; // Send Email using the builtin CI email class, if false it will return the code and the identity
$config['email_config'] = array(
	'mailtype' => 'html', 'protocol' => 'smtp', 'smtp_host' => 'ssl://smtp.googlemail.com', 'smtp_port' => 465 , 'smtp_timeout'=>'30', 'smtp_user' => '******@gmail.com', 'smtp_pass' => '******', 'charset' => 'utf-8', 'newline' => '\r\n',
);


My view code is : 

<script type="text/javascript">

    $().ready(function() {
        $("#regForm").validate({
            rules: 
            {
                firstName: "required",
                lastName: "required",
                email: 
                {
                    required: true,
                    email: true
                },
                password: 
                {
                    required: true,
                    minlength: 5
                },
                confirmpassword: 
                {
                    required: true,
                    minlength: 5,
                    equalTo: "#password"
                }
            },
            messages: 
            {
                firstName: "First Name Required",
                lastName: "Last Name required",
                email: "Please enter a valid email address",
                password: 
                {
                    required: "Please provide a password",
                    minlength: "Your password must be at least 5 characters long"
                },
                confirmpassword: 
                {
                    required: "Please provide a password confirmation",
                    minlength: "Your password must be at least 5 characters long",
                    equalTo: "Please enter the same password as above"
                }
            },
            submitHandler: function(form) 
            {
				alert('Submit handler');
              $.ajax({
                type: "POST",
                url: "<?php echo base_url(); ?>customer/create",
                data: $(form).serialize(),
                timeout: 3000,
                success: function(data) {
                    Display_Load();
                    if(data == 'done')
                    {
                        alert('record saved');
                        setTimeout(Hide_Load(), 5000);
                    }
                    else if(data == 'no')
                    {
                        alert('not saved');
                        setTimeout(Hide_Load(), 5000);
                    }
                    else
                    {
                        alert(data);
                        setTimeout(Hide_Load(), 5000);
                    }
                }
              });
              return false;
            }


        });
        
    });
    
    function Display_Load()
    {
     $("#loading").fadeIn(1000,0);
     $("#loading").html("<img src='<?php echo base_url(); ?>resources/images/ajax-loader.gif' /> Loding please wait for a while...");
    }
    function Hide_Load()
    {
     $("#loading").fadeOut('slow');
    }

</script>


<div class="row">
                    <div class="col-md-7 col-md-offset-1">

                        <div class="well">
                            <?php $attributes = array('id' => 'regForm'); echo form_open('', $attributes); ?>
                            	
                                    <div class="form-group">
                                        <input class="form-control input-large" name="firstName" id="firstName" value="<?php echo set_value('firstName'); ?>" placeholder="First Name" type="text" autofocus />
            
                                    </div>
                                    <div class="form-group">
                                        <input class="form-control input-large" name="lastName" id="lastName" value="<?php echo set_value('lastName'); ?>" placeholder="Last Name" type="text" />
                                       
                                    </div>
                                
                                <div class="form-group">
                                <input class="form-control" name="email" id="email" value="<?php echo set_value('email'); ?>" placeholder="Your Email" type="email" />
                                <div style="color:#ff0000; font-weight:bold; font-size:12px;"><?php echo form_error('email'); ?></div>
                                </div>
                                <div class="form-group">
                                <input  type="password" class="form-control" name="password" id="password" placeholder="Password" />
                                <div style="color:#ff0000; font-weight:bold; font-size:12px;"><?php echo form_error('password'); ?></div>
                                </div>
                                <div class="form-group">
                                <input type="password" class="form-control" name="confirmpassword" id="confirmpassword" placeholder="Confirm Password" />
                                <div style="color:#ff0000; font-weight:bold; font-size:12px;"><?php echo form_error('confirmpassword'); ?></div>
                                </div>
                               <div class="form-group">
                                <div id="loading" style="color:#a94442; font-weight:bold;"></div>
                                <button class="btn btn-primary btn-block" type="submit">
                                    Sign up</button>
                               </div>
                            </form>
                        </div>

                    </div>

                </div>

My Controller Code is : 

public function create()
	{
		$this->form_validation->set_rules('email', 'Email', 'required|is_unique[gab_users.email]|trim|xss_clean');
		$this->form_validation->set_rules('firstName', 'First Name', 'required');
		$this->form_validation->set_rules('lastName', 'Last Name', 'required');
		$this->form_validation->set_rules('password', 'Password', 'required|min_length[5]|max_length[8]|matches[confirmpassword]');
		$this->form_validation->set_rules('confirmpassword', 'Password Confirmation', 'required|min_length[5]|max_length[8]');

		if($this->form_validation->run() === FALSE)
		{
			die("no");
		}
		else
		{
			$username = $this->input->post('email');
			$firstName = $this->input->post('firstName');
			$lastName = $this->input->post('lastName');
			$email = $this->input->post('email');
			$password = $this->input->post('password');
			
			$additional_data = array("first_name"=>$firstName, "last_name"=>$lastName);
			
			$group = array('2');
			$this->ion_auth->register($username, $password, $email, $additional_data, $group);
			die("done");
		}
		
	}


I have autoload the ion_auth, email libraries

Please, help me about this HOW I CAN SEND ACTIVATION EMAIL USING THE MANDRILL.COM AFTER USER REGISTRATION AND GOT VALIDATE THE ACCOUNT OF THE USER. 

LOOKING FORWARD TO HEAR FROM YOU.

THANKS

**Comment by benedmunds** [comment]
Setup a test controller method using those email settings and debug from there to find the correct email settings.

**Comment by Salman937** [comment]
Forgot password form is not send email, it's showing Unable to Reset Password.what is the problem

**Comment by avenirer** [comment]
please do tell me @Salman-Iqbal : are you trying to use Gmail to send emails from your CodeIgniter? Does it work to send mails from your CI app?

**Comment by Salman937** [comment]
Yes i am using Gmail to send emails from codeigniter , I want to send email from local server.

**Comment by avenirer** [comment]
Ok. Then most likely the problem is with the way you've set up the email library. Try to send an email from a test controller. I bet it won't work.

**Comment by Salman937** [comment]
Thanks for your replay, My code is now working @avenirer

**Comment by Salman937** [comment]
Can we add more data in ion auth session. @benedmunds @avenirer

**Comment by avenirer** [comment]
You can add whatever you like. It is after all your session... :)

**Comment by Salman937** [comment]
thanks @avenirer

**Comment by Salman937** [comment]
how to add new data in ion auth session.

**Comment by avenirer** [comment]
This is a question that is too broad. What do you mean by "how to add new data in ion auth session."? Don't you understand how to work with sessions or don't you understand how sessions work? For this there is the CI documentation.

**Comment by Salman937** [comment]
ok
