### ISSUE TITLE
Extending Ion Auth

### ISSUE THREAD

**Issue by nathanpitman** [benedmunds/CodeIgniter-Ion-Auth#574]
Hi ya, I'm wanting to extend the Ion Auth model with some of my own custom code specific to the project we're using it within.

What's best practice for something like this and is there a way to force that to autoload whenever the ion_auth library is loaded?

**Comment by joejean** [comment]
@benedmunds Would this approach also work if I want to attach some custom methods to the user object? For example, in the template, I want to be able to do something like `ion_auth.user.has_active_subscription()`? etc. If not, what would be the best way to do that. Thanks so much :)

**Comment by benedmunds** [comment]
@joejean The way I usually do that is by just making a new user model and extend the ion auth model if needed.
