### ISSUE TITLE
Multi-factor authentication

### ISSUE THREAD

**Issue by Venefilyn** [benedmunds/CodeIgniter-Ion-Auth#575]
Been roughly setting up a 2-step authentication for Ion-Auth (with the help of PHPGangsta's GoogleAuthenticator git) to be implemented in a school project website.
https://github.com/SpyTec/CodeIgniter-Ion-Auth/tree/2-step-auth

Currently only checks if user has gauth (Google Authentication) activated and gives a token login view if that is the case. Upon entering the correct TOTP token +-1 min it will log you in.

Still much to be done, but is this something you'd see getting pulled into the main repo at some point? And so far, is it setup securely with logging in?

**Comment by xiarahman** [comment]
Did anything happened to this integration?

**Comment by Venefilyn** [comment]
@xiarahman nothing came out of it, I didn't have time to redesign it at the time. After the rewrite/redesign of this repo it became even more difficult to do
