### ISSUE TITLE
Added multi-factor authentication with TOTP

### ISSUE THREAD

**Issue by Venefilyn** [benedmunds/CodeIgniter-Ion-Auth#594]
Over at https://github.com/SpyTec/CodeIgniter-Ion-Auth/tree/2-step-auth I've added 
multi-factor authentication with TOTP, RFC 6238, http://tools.ietf.org/html/rfc6238.
Taken a TOTP library from Michael Kliewe, PHPGangsta, https://github.com/PHPGangsta/GoogleAuthenticator

The extension includes
- Second-step login with TOTP
- Generation of TOTP secret key
- Backup codes generation
- Customizable config for OTP

To securely login on the second-step login there is a one-time generated token that much match with the submission. The user can login with the TOTP tokens or the backup codes the user has gotten after enabling OTP.

When editing a user there's a tickbox for adding OTP. This then brings you to /view/auth/otp_activation.php that will display a QR-code for the secret key and display it in plain text below, on top of that it will also show the backup_codes. If the user unticks the OTP from settings (from it being ticked in the first place) it will delete the users OTP from database. Recommended to only allow this after successful TOTP authentication.

It works with any app that follows RFC 6238, although the QR-code is generated to fit apps that follows Google Authenticator's way. Works great with both Authy and Google Authenticator.

The QR code can show issuer, name, digits and time-period. But it always shows the secret key. Issuer, name, digits, time-period and QR-code size takes from config unless something is specified. The name part is who the secret key belongs to, issuer is who the secret key is used for. The digits and time-period parameters isn't in use with any OTP libraries as far as I know, so they're completely useless at the moment.

As it is now it's pretty much done when it comes to TOTP (does not include HOTP) and authentication. So any interest in this going into it's own branch as is or is there anything missing?

Edit: Should be added that it's not setup with MongoDB model.

**Comment by sykosoft** [comment]
@SpyTec @benedmunds I know this has been closed for over 6 months. With that said, I reviewed the fork, and while it's slightly behind the master, I think it's (relatively) trivial to bring the fork up to date. Would you (Ben) re-consider merging this into the mainline? Two factor is becoming a lot more important for a lot of people. The work SpyTec has done here is great. (and licensing from the original PHPGansta code seems compatible).

If there's no hope of merging into mainline, I'll probably (preferably with SpyTec's help) continue to maintain the OTP fork.

**Comment by SpyTec** [comment]
Hey @sykosoft! I've not been updating my fork as much as I'd hope to. But since Ion Auth 2 is supposed to be simple and light I'd think that a rework of my fork to be more of a modular approach to the main repo rather than attaching itself directly to the core as it does now

**Comment by sykosoft** [comment]
@SpyTec I'm in agreement. @benedmunds What is the preferential way for extension of ion_auth?

**Comment by benedmunds** [comment]
The best way would be by using hooks:

http://codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth
