### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by tikky** [benedmunds/CodeIgniter-Ion-Auth#604]
Hello,

I have codeigniter set to polish language.
Where in ION AUTH I can change the default language for polish?

**Comment by tikky** [comment]
Long time ago I've asked for a help with polish language.
Today I found possible problem.

If you will take a look for example at italian tranlsation we have two files:
- auth_lang.php
- ion_auth_lang.php
and both are tranlsated to italian.

In Polish language folder we have also two files, but
auth_lang.php - it is on original - english version
ion_auth_lang.php - it is a polish version

So my question is: auth_lang.php - shouldn't be also translated to Polish?
If yes I can do it.

**Comment by benedmunds** [comment]
Yes it does need to be translated.
