### ISSUE TITLE
Error Number: 1452  Cannot add or update a child row: a foreign key constraint fails

### ISSUE THREAD

**Issue by satyajit98300** [benedmunds/CodeIgniter-Ion-Auth#615]
Its showing error.
Error Number: 1452

Cannot add or update a child row: a foreign key constraint fails (`trydoc`.`users_groups`, CONSTRAINT `fk_users_groups_groups1` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION)

INSERT INTO `users_groups` (`group_id`, `user_id`) VALUES (0, 7)

Filename: C:\EasyPHP-DevServe\data\localweb\trydocpro\system\database\DB_driver.php

Line Number: 330

need help.

**Comment by jitupatel7687** [comment]
A Database Error Occurred

Error Number: 1452

Cannot add or update a child row: a foreign key constraint fails (`fbuddyco_jobsite`.`users_groups`, CONSTRAINT `fk_users_groups_groups1` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION)

INSERT INTO `users_groups` (`group_id`, `user_id`) VALUES (0, 82)

Filename: /home/fbuddyco/public_html/job/models/ion_auth_model.php

Line Number: 1393

**Comment by jitupatel7687** [comment]
please tell me

**Comment by jitupatel7687** [comment]
This my code 


$additional_data = array(
				'first_name' => $this->input->post('first_name'),
				'last_name' => $this->input->post('last_name'),
				'address1' => $this->input->post('address'),
				'phone' => $this->input->post('phone'),
				'gender' => $this->input->post('gender')
				);

			if (!$this->ion_auth->email_check($email)){
				$group = array('3');
				$this->ion_auth->register($username, $password, $email, $additional_data, $group);
				//give error when inserting data complete
				redirect('candidate/registration_complete');
			}else{
				$data['error'] = "Email already exists";
				$this->load->view("candidate_registration",$data);
			}

**Comment by benedmunds** [comment]
Does that group exist?  Try using the group name.

**Comment by jitupatel7687** [comment]
yes group exist.  allready try group name

**Comment by benedmunds** [comment]
Try changing the 3 in the array to be an integer instead of a string. It shouldn't matter since PHP should type cast it but it's worth a try

**Comment by Lerp** [comment]
I am having same error.  I tried changing to INT but no go.

Would there be an issue if I just change the array argument to be just a string?

cheers :)

**Comment by avenirer** [comment]
is it "groupid" or "group_id" inside your table?

**Comment by Lerp** [comment]
hi there, it is group_id in the users_groups table

Going to double check the config and send another update here soon

cheers, Lerp

**Comment by Lerp** [comment]
I have adjusted the config as indicated and it is now inserting properly into the users_groups table

cheers & thanks, Lerp :)

**Comment by azhardev631** [comment]
Cannot add or update a child row: a foreign key constraint fails 
in seeding

**Comment by azhardev631** [comment]
Cannot add or update a child row: a foreign key constraint fails  in codeigniter 4


<?php

namespace App\Database\Seeds;
use App\Models\UserModel;
use App\Models\BlogModel;
use App\Models\CommentModel;
use CodeIgniter\Database\Seeder;

class CommonSeeder extends Seeder
{
    public function run()
    {
        $user = new UserModel;
        $blog = new BlogModel;
        $comment = new CommentModel;


        $users= [1,2,3,4,5,6];
        $faker = \Faker\Factory::create();
        for($i=0; $i<10;$i++){ 
        $user->save([
            "name"=> $faker->name,
            "email"=>$faker->email,
            "password"=>$faker->password
        ]);
        $blog->save([
            "message"=>$faker->text,
            "created_by"=>$faker->randomElement($array = array ($users))
        ]);
        $comment->save([
            "comment"=>$faker->text,
            "user_id"=>$faker->randomNumber,
            "blog_id"=>$faker->randomNumber
        ]);
        
        }
    }
}

**Comment by benedmunds** [comment]
Which FK constraint is failing? The group id?  Does that group exist?
