### ISSUE TITLE
Default group

### ISSUE THREAD

**Issue by 18209018** [benedmunds/CodeIgniter-Ion-Auth#619]
Is there any ways to prevent adding the default group when register? I don't need default group in my app and not specify it in config. Because of that, when I register a user, it always error when come to the add default group code, this block:

//add to default group if not already set
$default_group = $this->where('name', $this->config->item('default_group', 'ion_auth'))->group()->row();
if ((isset($default_group->id) && empty($groups)) || (!empty($groups) && !in_array($default_group->id, $groups))){
    $this->add_to_group($default_group->id, $id);
}

My app basically consist 3 account, admin, teacher, and student so there is no default group for user. Each group must be defined when registering the account.

**Comment by jitupatel7687** [comment]
i have 3 user (1= admin,2=candidate,3=recuriter) 
i default set in ion_auth.php  
$config['default_group']   = 'candidate'; 

This code for register recuriter
$username = 'benedmunds5';
		$password = '12345678';
		$email = 'jitupatels768a7@gmail.com';
		$additional_data = array(
								'first_name' => 'Ben',
								'last_name' => 'Edmunds',
								);
		$group = array('3'); //

		$this->ion_auth->register($username, $password, $email, $additional_data, $group);

registration successfully  but  i check in user_groups table in group_id it show 2 and 3 in user id 
means registration complete both candidate or recuriter

i want to only insert group 3  how to pevent dafault default_group when pass group 3

please tell me

**Comment by benedmunds** [comment]
You can't.  You could change the groups after the registration to remove it.

**Comment by jitupatel7687** [comment]
every recruiter user register his info 
i will delete default user group in user_groups table 
right

**Comment by jitupatel7687** [comment]
after registration

**Comment by jitupatel7687** [comment]
i comment this line 

//$this->add_to_group($default_group->id, $id);
line numner 925

ion_auth_model.php  it working fine
