### ISSUE TITLE
You must use the "set" method to update an entry

### ISSUE THREAD

**Issue by sparky672** [benedmunds/CodeIgniter-Ion-Auth#642]
I'm still in development and Ion Auth was last updated last year.   While testing today, I discovered the following error when using the "edit user" function.

So I followed your "upgrade" directions...

http://benedmunds.com/ion_auth/#upgrade
1.  Download the latest version: http://github.com/benedmunds/CodeIgniter-Ion-Auth/zipball/2
2.  Overwrite `libraries/ion_auth.php` and `models/ion_auth_model.php` with the new versions.

However, I'm still getting this error: 

> A Database Error Occurred
> You must use the "set" method to update an entry.
> Filename: models/ion_auth_model.php
> Line Number: 1588

Do I need to reinstall all Ion Auth files from scratch?  I love Ion Auth, but I really hate trying to keep it up to date.

**Comment by PedroRuizHidalgo** [comment]
I get error 500 when wrap the edit user's form as follow
`//$this->_render_page('auth/edit_user', $this->data,TRUE);
		$this->load->view(			
			'inc/main',
			$this->authview->inject(
				lang('edituser_edituser'),
				lang('edituser_title'),
				$this->_render_page('auth/edit_user', $this->data,TRUE),
				array(
					array(base_url(),lang('home_home')),
					array(base_url('index.php/auth/edit_user/'.$id),lang('edituser_edituser'),TRUE)
				) //ends breadcrumbs
			) // ends inject
		); //ends load view`

any idea?

**Comment by PedroRuizHidalgo** [comment]
I get error 500 when wrap the edit user's form as follow
`
       //$this->_render_page('auth/edit_user', $this->data,TRUE);
	$this->load->view(			
			'inc/main',
			$this->authview->inject(
				lang('edituser_edituser'),
				lang('edituser_title'),
				$this->_render_page('auth/edit_user', $this->data,TRUE),
				array(
					array(base_url(),lang('home_home')),
					array(base_url('index.php/auth/edit_user/'.$id),lang('edituser_edituser'),TRUE)
				) // this ends breadcrumbs
			) // this ends inject
		); // this ends load view
`

**Comment by sparky672** [comment]
> I get error 500 when wrap the edit user's form as follow

@PedroRuizHidalgo, your question has absolutely nothing to do with the issue I started here.  It would make sense for you to start your own issue.

**Comment by ghost** [comment]
@sparky672 it is ok yet

**Comment by sparky672** [comment]
@PedroRuizHidalgo, why do you keep hijacking this 2-year old thread?
