### ISSUE TITLE
how to display a page based on the user login group?

### ISSUE THREAD

**Issue by meyhantra** [benedmunds/CodeIgniter-Ion-Auth#655]
I have a group admin, operator, and user. I want to access the admin group administrator, operator access to the operator on the CodeIgniter controller. whether it can be done on ion_auth?

**Comment by hassanshaik82** [comment]
hi 
i want to restrict access for a particular admin to all group instead of his register group,pleas help regarding this issue.

**Comment by avenirer** [comment]
@hassanshaik82 this is like using the right hand to get rid of an itch on the left part of your head.

**Comment by hassanshaik82** [comment]
hi 
i want separate admin for each group,how its possibe

**Comment by avenirer** [comment]
@hassanshaik82 the simple fact that you admit that there is an "each group" gives you the answer. I simply don't follow your logic in this endeavor of yours.

**Comment by hassanshaik82** [comment]
Nothing but the particular admin able to manage users in that group,is there any reference for that,
iam a newbie for this

**Comment by hassanshaik82** [comment]
I'll discuss little more:
Under one Domain/website:
we are trying to create 5 Groups - where every Group is working on a different Project.
For Every group there is a Project Manager and a team of 10 each working under him on that particular project.
We are trying to see that every group will discuss/Raise Task and complete their tasks within the group and other group members has nothing to do with every other group.
where every one has to login through only one ; LOGIN (which is on the home page)
and by validating the user : they have push into their group only.
I- think you can understand more now, please help us to get some solutions.

**Comment by avenirer** [comment]
What you are doing here is not raising an issue, but asking for someone to work for free on your (or someone else's) project. Please do have the common sense of asking and paying a programmer to do this for you and stop using Github for these type of problems. There was a time when Github was just for those who knew what they're doing...

**Comment by Tjoosten** [comment]
+1 @avenirer

**Comment by Djumaiddy** [comment]
after so many times searching how can redirect the groups, i now find a solution. thanks so much Mr Ben and all of you guys.
thank you so much
