### ISSUE TITLE
After installing ion auth with CI 2.2.0 it show a db error

### ISSUE THREAD

**Issue by smshahinulislam** [benedmunds/CodeIgniter-Ion-Auth#659]
I installed CI 2.2.0 and add ion auth to it. In when I try to login it shows following error.

Unknown column 'email' in 'field list'

SELECT `email`, `username`, `email`, `id`, `password`, `active`, `last_login` FROM (`users`) WHERE `email` = 'admin@admin.com' ORDER BY `id` desc LIMIT 1

**Comment by vschaefer** [comment]
Hello,

I have a similar Problem and CI shows the following error: 

Error Number: 1054

Unknown column 'password' in 'field list'

SELECT `email`, `username`, `email`, `password`, `id`, `active`, `last_login` FROM (`users`) WHERE `email` = 'admin@admin.com' ORDER BY `id` desc LIMIT 1



The database looks correct. Does anyone have an idea what is wrong?
Thanks a lot.
