### ISSUE TITLE
Undefined property: Message::$load (Library: Message) Call to a member function config() on a non-object

### ISSUE THREAD

**Issue by ghost** [benedmunds/CodeIgniter-Ion-Auth#665]
Hi there!

I'm experiencing some difficulties with a newly created library which Is associated with a controller called "messaging" with class name "Messaging", the controller works fine and I load the library "Message" class "Message" in the constructor. 

class Messaging extends CI_Controller {

```
public function __construct()
{
    parent::__construct();

    $this->load->database();

    $this->load->helper("form");

    $this->load->library('ion_auth');
    $this->load->library("form_validation");
    $this->load->library("message"); // this is the new library.

    $this->lang->load('auth');
    $this->lang->load('email');
    $this->load->helper('language');

    $this->form_validation->set_error_delimiters($this->config->item('error_start_delimiter', 'ion_auth'), $this->config->item('error_end_delimiter', 'ion_auth'));
}
```

Of course the Auth controller and ion_auth library are working fine for me but the error I'm getting on calling the controller method -> "Messaging/contact_us" is that the loading of external resources in the library are falling whenever $this->load-> is used for.

The page displays:

A PHP Error was encountered

Severity: Notice

Message: Undefined property: Message::$load

Filename: libraries/Message.php

Line Number: 26

Fatal error: Call to a member function config() on a non-object in /home/michael93/public_html/application/libraries/Message.php on line 26

And this applies for loading, after doing some research I introduced a $CI =& get_instance(); in my constructor of my library and so if I replace all $this-> with $CI then no error occurs and the page redirects but with no error messages and I'm assuming it's because I was accessing the instance rather than $this although I'm not sure.

Here's how my constructor looks 

public function __construct()
    {
        $CI =& get_instance();

```
    $this->load->config('ion_auth', TRUE);
    $CI->load->library('email');
    $CI->lang->load('ion_auth');
    $CI->load->helper('cookie');
    $CI->load->helper('language');
    $CI->load->helper('url');
```

I've left $this->load just to show the difference but I would appreciate knowing what the correct approach to this is? 

Thank you very much :) All the purpose of the library is for handling processing and sending emails.

Thank you,

Michael

**Comment by lalithsagar03** [comment]
Severity: Notice

Message: Undefined property: REST_Controller::$load

can anyone help me to resolve?
Controller:-
<?php

defined('BASEPATH') OR exit('No direct script access allowed');
// This can be removed if you use __autoload() in config.php OR use Modular Extensions

// require APPPATH . '/libraries/REST_Controller.php';
require_once("application/libraries/REST_Controller.php");
require_once("application/libraries/Format.php");

class Api extends REST_Controller {

    function __construct() {
        parent::__construct();
        // $this->load->helper(array('form', 'url', 'firebase_notify'));
        $this->load->helper(array('form', 'url'));
        $this->load->library('form_validation');
        $this->load->helper('security');
        $this->load->library('tank_auth');
        $this->load->library('session');
        $this->load->library('REST_Controller');
        $this->lang->load('tank_auth');
        $this->load->helper('email');
        $this->load->helper('string');
        $this->lang->load('rest_controller');
        $this->load->model('common_model');
        define('STATUS', 'addstatus');
        define('MESSAGE', 'addmsg');
        $this->load->helper(array('url', 'language'));
        date_default_timezone_set('UTC');
        $this->ci = & get_instance();
    }

library:-<?php

// namespace Restserver\Libraries;
// use CI_Controller;
// use Exception;
// use stdClass;

defined('BASEPATH') OR exit('No direct script access allowed');


class REST_Controller extends CI_Controller {
}

**Comment by benedmunds** [comment]
Are you using Ion Auth? I see Tank Auth in here.

**Comment by lalithsagar03** [comment]
I'm using tankauth

**Comment by benedmunds** [comment]
These GH issues are for issues with Ion Auth.  Maybe try asking in the tank auth issue tracker.

Probably better to ask in the CodeIgniter forums or StackOverflow though.  This is probably due to using the REST_Controller.  You might need to grab the I superglobal and load using that instead of using $this.  Something like:

```
$ci =& get_instance();
$ci->load->helper(array('form', 'url', 'firebase_notify')); 
//etc
```

**Comment by lalithsagar03** [comment]
Yeah,Thank you so much for the response.I will do it.
