### ISSUE TITLE
Login identity set_value

### ISSUE THREAD

**Issue by adamdanielperry** [benedmunds/CodeIgniter-Ion-Auth#699]
On login, 
Identity input is being set to $this->form_validation->set_value('identity') so that you don't have to retype the email if the password is incorrect,
But the input is never being set due to the redirect if the login was un-successful, so this surely becomes useless?

I have had to set before the redirect:
$this->session->set_flashdata('identity', $this->input->get_post('identity'));
redirect('login', 'refresh');

And then use:
$this->data['identity'] = array('name' => 'identity',
	'id' => 'identity',
	'type' => 'text',
	'value' => $this->session->flashdata('identity'),
);

This isn't a huge issue, but just wondering if i'm missing something obvious?

**Comment by benedmunds** [comment]
Thats a fine way to do it.
