### ISSUE TITLE
unexpected ':' in libraries/Ion_auth.php on line 65

### ISSUE THREAD

**Issue by ghermans** [benedmunds/CodeIgniter-Ion-Auth#700]
public function __construct()
	{
		 $this->load->config('ion_auth', TRUE);
	 	 $this->load->library(array('email'));
		  $this->lang->load('ion_auth');

changed  $this->load->helper(array('cookie', 'language','url')): 
to             $this->load->helper(array('cookie', 'language','url'));

**Comment by benedmunds** [comment]
Thanks! Fixed.
