### ISSUE TITLE
PostgreSQL GROUP BY statement issue

### ISSUE THREAD

**Issue by Slamoth** [benedmunds/CodeIgniter-Ion-Auth#703]
Tried to add a user using postgres db and hit a problem.

ERROR: column "users.id" must appear in the GROUP BY clause or be used in an aggregate function LINE 4: ORDER BY "id" ASC ^
SELECT COUNT(*) AS "numrows" FROM "users" WHERE "email" = 'nada.nada@nada.com' ORDER BY "id" ASC LIMIT 1
Filename: /var/www/html/models/ion_auth_model.php
Line Number: 734

So,
PostgreSQL/Oracle/SQL Server require you to either specify each column not wrapped in aggregate functions in the group by.

**Comment by Slamoth** [comment]
Maybe
$this->db->distinct()->select('id')->where('email', $email);
$query = $this->db->get('users');
return $query->num_rows() > 0;

also same thing applies to all *_check functions as well !!!

**Comment by benedmunds** [comment]
Can you send a PR to fix this?

**Comment by benedmunds** [comment]
Bump?

**Comment by ronaldaraujo** [comment]
I inserted the "-> group by (" id ")" in lines 709 and 733 of the ion_auth_model.php file and it worked perfectly.

**Comment by benedmunds** [comment]
Could you send a PR?

**Comment by benedmunds** [comment]
Thanks!
