### ISSUE TITLE
No group set (even default) on new registration.

### ISSUE THREAD

**Issue by similar75** [benedmunds/CodeIgniter-Ion-Auth#704]
Hello,

First - great work. ;)
And the problem - no group set in new registrations, default or even i set it as fifth param (as array) in $this->ion_auth->register().

A quick fix for me (cant find this broke anything):

Starting at row 893 in ion_auth_model.php:

//check if the default set in config exists in database
$query = $this->db->get_where('groups',array('name' => $this->config->item('default_group', 'ion_auth')),1)->row();		
if( !isset($query->id) && empty($groups) ) 
{......

**Comment by benedmunds** [comment]
Can you send a PR so I can review?

**Comment by similar75** [comment]
Done - #705
