### ISSUE TITLE
Login trouble

### ISSUE THREAD

**Issue by Micky87** [benedmunds/CodeIgniter-Ion-Auth#706]
Hi,  I'm sorry for the inconvenience but I can not solve a problem with your ion_auth , I tried all  I can.

This is my code

    $input=$this->input->post(LOGIN_ID,true);
    $user_data=json_decode($input, TRUE);
    $result=$this->ion_auth->login($user_data['nickname'], $user_data['password']);
    return $result;

$user_data contains correct values

I saw that $result is always false, so i opened the database and the same password had different values for different users, so i think there is an error in registration

     $input=$this->input->post(REGISTRATION_INPUT,true);
     $registration_data=json_decode($input, TRUE);
     $username=$registration_data['nickname'];
     $password=$registration_data['password'];
     $email=$password=$registration_data['email'];
     $additional_data=array('first_name'=>$registration_data['name'],'last_name'=>$registration_data['surname']);
     $result=$this->ion_auth->register($username, $password, $email, $additional_data) ;

 In config file i set

    $config['identity'] = 'username';

And I set also username as index im my MYSQL table 
users(id,ip_address,username,password, salt, email,...)

I don't really know what to do, thanks for attention

**Comment by Micky87** [comment]
I solved there were problems with json

**Comment by Tjoosten** [comment]
Glad to hear that @Micky87
