### ISSUE TITLE
Function for change email

### ISSUE THREAD

**Issue by Ajtak** [benedmunds/CodeIgniter-Ion-Auth#708]
Hello.
 I need advice on how to add a function to change the email. What where you need to add? I suppose that in the controller and model. Could you please help me with this function? thank you

**Comment by similar75** [comment]
You can use update() function like this:

$this->ion_auth->update($id,array("email" => "new@email.com"));

.. i think.

**Comment by benedmunds** [comment]
You can use the update user method that's available in the library. You'd just need to add the controller method and view.

-Ben Edmunds

**Comment by antonradev** [comment]
@Ajtak Did you implement changing the Email of the user? Could you share with me? How to check if it is not the email of some other user?
Thank you very much in advance!
