### ISSUE TITLE
$this->tables always empty. (CI3)

### ISSUE THREAD

**Issue by srpurdy** [benedmunds/CodeIgniter-Ion-Auth#713]
Hi,

When I try to login I get this error below. This is a base CI3 install.
<pre>
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE = 'dfsdf' ORDER BY `id` DESC LIMIT 1' at line 2

SELECT `username`, `email`, `id`, `password`, `active`, `last_login` WHERE = 'dfsdf' ORDER BY `id` DESC LIMIT 1

Filename: models/Ion_auth_model.php

Line Number: 989
</pre>

Looking into it. none of the $this->tables or $this->identity are being set. They are empty.

My autoload file is like this below.
<pre>
$autoload['libraries'] = array('ion_auth', 'database');
$autoload['drivers'] = array('session');
$autoload['helper'] = array('url', 'form');
$autoload['config'] = array('website_config', 'ion_auth');
$autoload['language'] = array('ion_auth');
</pre>

While I can access pages like /auth/login, when I submit the form with data in the login wither it's the default admin login, or a random non existing login. Same result. 

Something I am missing? Why is the configuration variables not being passed in the model?

**Comment by benedmunds** [comment]
Remove ion_auth from the config autoload.  It's loaded by the library.

**Comment by srpurdy** [comment]
That worked! thanks :)
