### ISSUE TITLE
problem IonAuh on Ubuntu

### ISSUE THREAD

**Issue by gabrielpasv** [benedmunds/CodeIgniter-Ion-Auth#714]
Hi, sorry bothering but I would like to know if you could help to solve my issue. I have a developing server running ubuntu and I started a CI project there. I have add ion_auth to my project just fine, but when I try to test it using the ion login view I cannot login with user admin@admin.com and "password"  it doesn' t work. Strange because it did work on windows.

The only difference I did for ubuntu is that I had to change some database settings.
Here is how my db config looks like:

$db['default']['hostname'] = '192.168.56.101';
$db['default']['username'] = 'root';
$db['default']['password'] = 'portal';
$db['default']['database'] = 'ionauth';
$db['default']['dbdriver'] = 'mysql';
$db['default']['dbprefix'] = '';
$db['default']['pconnect'] = TRUE;
$db['default']['db_debug'] = FALSE;
$db['default']['cache_on'] = FALSE;
$db['default']['cachedir'] = '';
$db['default']['char_set'] = 'utf8';
$db['default']['dbcollat'] = 'utf8_general_ci';
$db['default']['swap_pre'] = '';
$db['default']['autoinit'] = TRUE;
$db['default']['stricton'] = FALSE;

on windows was the same, except that db_debug was set to TRUE

When I tried to login I see an sql error shows up really fast and then it redirect back to login page.

The error was something related to this:
mysql_escape_string() this function is deprecated use mysql_real_escape_string() instead

I hope you can help me, thanks

**Comment by m82amjaduk** [comment]
Have you used migration to add database ??

**Comment by m82amjaduk** [comment]
Have you used migration to add database table and data??

**Comment by gabrielpasv** [comment]
Hi, thanks for your help. No I am not using migration, in fact my database only have the ion auth tables

**Comment by gabrielpasv** [comment]
Something is wrong with mysql, because I changed it to postgresql and it worked just fine

**Comment by gabrielpasv** [comment]
Hi Benedmunds, 

Sorry bothering once again. I know you closed this. However the issue still. It does not work with mysql

can you please help me? 

Thanks

**Comment by benedmunds** [comment]
First I would recommend trying it with straight SQL thats provided in the library.  Maybe its an issue in the migrations?

**Comment by gabrielpasv** [comment]
I am not using CI migration. I just create the database as it is on the sql script you provided for mysql.

I will try to run the straight SQL. Do you know where I can find it ?

**Comment by benedmunds** [comment]
Oh I thought you had said that you were using migrations...  So check you're logs and see what the exact error is. Also check to see what the error level is: deprecated, warning, etc

**Comment by gabrielpasv** [comment]
this is the error



A PHP Error was encountered

Severity: 8192

Message: mysql_escape_string(): This function is deprecated; use mysql_real_escape_string() instead.

Filename: mysqli/mysqli_driver.php

Line Number: 320

**Comment by gabrielpasv** [comment]
nevermind I was able to make it work. It was permission problems

**Comment by benedmunds** [comment]
Yea so you need to either update CI, use PDO or just dont report deprecated warnings.  error_reporting(E_ALL ^ E_DEPRECATED);
