### ISSUE TITLE
application with 2 kind of users in different tables, is it possible?

### ISSUE THREAD

**Issue by gabrielpasv** [benedmunds/CodeIgniter-Ion-Auth#717]
Hi Benedmunds, it's me again sorry bothering....

My web application will have 2 kind of users, "Customers" and "Vendors"  and I want to have 2 tables to store them in the database. How can I change ion Auth to work on this ? Should I have 2 config files ?

tables for Customers:
C_groups
C_logins_attempts
C_users
C_users_groups

tables for Vendrs
V_groups
V_logins_attempts
V_users
V_users_groups

Let me know, thanks

**Comment by benedmunds** [comment]
You should just have a group for each.  They are all users.
