### ISSUE TITLE
codeigniter 3 integration with ion-auth error

### ISSUE THREAD

**Issue by michaelstokes** [benedmunds/CodeIgniter-Ion-Auth#731]
Hi all,

I'd really appreciate your help please. 

Running codeigniter v3 with ion-auth I am getting the following error in the browser:

A PHP Error was encountered

Severity: Warning

Message: mkdir(): Invalid path

Filename: drivers/Session_files_driver.php

Line Number: 117

Backtrace:

File: /Users/michaelstokes/Sites/new/application/libraries/Ion_auth.php
Line: 74
Function: driver

File: /Users/michaelstokes/Sites/new/application/controllers/Auth.php
Line: 9
Function: library

File: /Users/michaelstokes/Sites/new/index.php
Line: 292
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /Users/michaelstokes/Sites/new/system/core/Exceptions.php:272)

Filename: core/Common.php

Line Number: 565

Backtrace:

An uncaught Exception was encountered

Type: Exception

Message: Session: Configured save path '' is not a directory, doesn't exist or cannot be created.

Filename: /Users/michaelstokes/Sites/new/system/libraries/Session/drivers/Session_files_driver.php

Line Number: 119

Backtrace:

File: /Users/michaelstokes/Sites/new/application/libraries/Ion_auth.php
Line: 74
Function: driver

File: /Users/michaelstokes/Sites/new/application/controllers/Auth.php
Line: 9
Function: library

File: /Users/michaelstokes/Sites/new/index.php
Line: 292
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: fopen(3beccd1d7effac4a8beb232338f2a092768cc101): failed to open stream: Permission denied

Filename: drivers/Session_files_driver.php

Line Number: 156

Backtrace:

I've set the Base url and am not using .htaccess :) Thank you!

**Comment by benedmunds** [comment]
Are you using the latest CI3 from GH? There were some reason session fixes.

**Comment by michaelstokes** [comment]
?Hello,


Yes Codeigniter v3 from GitHub.



________________________________

**Comment by benedmunds** [comment]
what commit are you on?

**Comment by avenirer** [comment]
I guess the problem is that you've set in the config.php a variable named $config['sess_save_path']. That variable should point to an existing folder and in your case it doesn't.
