### ISSUE TITLE
Issue while logging out using ion-auth Version: 2.5.2

### ISSUE THREAD

**Issue by jogee31** [benedmunds/CodeIgniter-Ion-Auth#737]
Hi, 

I am facing problem when i'm being log out from my application.
Actually the situation is, i'm using ion auth for two application. So if i'm running my both application at the same time, and i'm being log out from one, then it's logging me out form other one also.

So Please help me to fix it. Waiting for response.

**Comment by benedmunds** [comment]
I'm sure its a session issue.  You might need to modify the CI session library to do what you want using a MY_Log class.
