### ISSUE TITLE
Multiple Update Using An Array Of IDs

### ISSUE THREAD

**Issue by ronpsp** [benedmunds/CodeIgniter-Ion-Auth#738]
Will there be a future update wherein the `update()` function can accept an array of user IDs? Because currently, looping through an entire array of user IDs and updating them one by one using `update()` uses a lot of resource.

(Yes I know, I can just update the database myself using custom logic. But maybe you have plans for integrating it directly :p )

Thanks!

**Comment by benedmunds** [comment]
No I'm not. I consider v2 feature compete.

If you send a PR I'll seriously consider it though. Thanks!

**Comment by ronpsp** [comment]
Alright, thanks man!
