### ISSUE TITLE
Creating a group blank page

### ISSUE THREAD

**Issue by dspstudio** [benedmunds/CodeIgniter-Ion-Auth#739]
Hello,

If i try to create a group with an existing name i don't receive any error just a blank page. While i searched in the code i found that it sets an error and returns false.
Best regards

**Comment by avenirer** [comment]
Well... it is supposed to do that. It's normal to halt the creation of group if a group with that name already exists. You can at any time output the error if the group wasn't created: `$this->ion_auth->errors()`
