### ISSUE TITLE
Email not sending

### ISSUE THREAD

**Issue by xxRockOnxx** [benedmunds/CodeIgniter-Ion-Auth#742]
Hey, i have a problem, School project's deadline is getting nearer.

I can send message before without using your library... just using CodeIgniter's email class like this

private function verify_email_send()
    {
        //set email library configuration
        $config = Array(
        'protocol' => 'smtp',
        'smtp_host' => 'ssl://smtp.googlemail.com',
        'smtp_port' => 465,
        'smtp_user' => 'myaccount@gmail.com',
        'smtp_pass' => 'mypassword',
        );

        //load email library
        $this->load->library('email', $config);
        $this->email->set_newline("\r\n");
 

        $email = $this->session->userdata('$email');
        $activation_code = $this->activation_code;
        
        
        $this->email->set_mailtype('html');
        $this->email->from($this->config->item('bot_email'), 'Insanitees');
        $this->email->to('recipient@gmail.com');
        $this->email->subject('Please verify your email address');
        
        $message = '<html><body>';
        $message .= '<p> Thanks for registering on Insanitees! Please <strong><a href="'.base_url().'Insanitees_controller/activate_user/'.$activation_code.'">click here</a></strong> to verify your email address.</p>';
        $message .= '<p>Thank you!</p>';
        $message .= '<p>Insanitees Administrator</p>';
        $message .= '</body></html>';
        
        $this->email->message($message);
        $this->email->send();
    }

but now that i found your ion auth, everything is find it's just that sending email activation is not working. My users cant login without activting. Here's my Ion auth config file

$config['use_ci_email'] = TRUE; // Send Email using the builtin CI email class, if false it will return the code and the identity
$config['email_config'] = array(
	'mailtype' => 'html',
        'protocol' => 'smtp',
        'smtp_host' => 'ssl://smtp.gmail.com',
        'smtp_user' => 'myaccount@gmail.com', // actual values different
        'smtp_pass' => 'password',
        'smtp_port' => 465
);

I'm on a Localhost running Xampp. I really need to finish this. Thanks

**Comment by avenirer** [comment]
So what you're saying is that when you used CI's email, on XAMPP, it worked? Also, are the same credentials in both examples (user an password)?

**Comment by xxRockOnxx** [comment]
Yes they are the same. This frustrates me alot. I tried sending email in my previous controller this afternoon but now I cant receive anything again... I also tried uploading my project on a free web hosting site and it's still not working it would just show a blank page. It works when i used smtp2go but it only allows me 20 emails per day.

**Comment by benedmunds** [comment]
This isn't an Ion Auth issue, it's an issue with your email providers and/or email settings.  The best way to debug it is to create a test controller and make an email call there.  Work out the settings and errors there.  Once you have the settings that work copy them into the config.

**Comment by xxRockOnxx** [comment]
I got it fixed by adding newline... and the ssl too in smtp host i think?

$config['email_config'] = array(
	'mailtype' => 'html',
        'protocol' => 'smtp',
        'smtp_host' => 'ssl://smtp.gmail.com',
        'smtp_user' => 'yourusername@gmail.com', // actual values different
        'smtp_pass' => 'password',
        'smtp_port' => 465,
	'newline' => "\r\n",
        'charset' => 'utf-8'
);

Notice the DOUBLE QUOTE on the newline.

**Comment by pranid** [comment]
$config = array(
			'protocol' 	=> 'smtp' , 
			'smtp_host' => 'ssl://smtp.googlemail.com' , 
			'smtp_port' => 465 , 
			'smtp_user' => 'someone@gmail.com' ,
			'smtp_pass' => 'your password',
			'mailtype'	=> 'html', 
			'charset' 	=> 'utf-8', 
			'newline' 	=> "\r\n",  
			'wordwrap' 	=> TRUE 
			);
		
		// Load email library and passing configured values to email library
		$this->load->library('email',$config);
	

This one will help...
