### ISSUE TITLE
Change user table fields id,username,password field

### ISSUE THREAD

**Issue by nayeem-ice10** [benedmunds/CodeIgniter-Ion-Auth#743]
I have two questions:

1. Is there any way to configure user table fields(i.e. user_id instead of id) ? I am working on a project where my client provided me with database schema which i can not change.
2. There two separate modules in my project which uses different tables for authentication. How can i load different config file in different controllers.

**Comment by benedmunds** [comment]
1. No not without modifying core code.

2. You can use CIs loader to overwrite the config
