### ISSUE TITLE
REQUEST: Supergroup or group inheritance support

### ISSUE THREAD

**Issue by sykosoft** [benedmunds/CodeIgniter-Ion-Auth#747]
We have the need to have some sort of supergroup or group inheritance. Essentially, we use groups for individual permissions (of actions), and would like a specified group to encompass a set of these permissions (groups currently). The way we're doing it now is just adding a macro group (let's call it engineer) and using an in_group(array('engineer', 'specific_permission')) but would prefer that engineer inherited other groups.

Is such a thing reasonable?

(If we go the route of doing this ourselves, would it be merged? Would anyone else be willing to do it?)

Thanks in advance.

**Comment by sykosoft** [comment]
The reverse would also work:

"specific_permission" has users in the engineer, admin, consultant, etc groups.

**Comment by benedmunds** [comment]
It probably would not be merged.  What you really need is a full ACL.  If you wrote one as a separate project that used hooks to achieve this I would merge any PRs that are needed to make it play nicely (as long as it maintained BC) and would promote the hell out of it.
