### ISSUE TITLE
res=t_password instead of reset_password

### ISSUE THREAD

**Issue by ankur140290** [benedmunds/CodeIgniter-Ion-Auth#765]
I have latest Xampp, CodeIgniter, Ion Auth. After configuring everything, the email for reset password generated is something like this: "http://10.50.2.124/ticket/auth/res=t_password/3DLl2WtdlahMM-0.ANPhEea92d7449f7673e68d5" instead of "http://10.50.2.124/ticket/auth/reset_password/3DLl2WtdlahMM-0.ANPhEea92d7449f7673e68d5"
This results in the message "The URI you submitted has disallowed characters.".

![image](https://cloud.githubusercontent.com/assets/3341545/7158117/4be0f840-e394-11e4-80c2-2b2049fd82d7.png)

**Comment by benedmunds** [comment]
What link is in the email template?

**Comment by ankur140290** [comment]
C:\xampp\htdocs\ticket\application\views\auth\email\forgot_password.tpl.php
ie: application\views\auth\email\forgot_password.tpl.php (default one)
The only problem is that word "e" in URL gets converted to "=" in all the links generated by ion_auth.

**Comment by benedmunds** [comment]
My guess is that's it's some kind of encoding issue. Try replacing the file with a fresh pull from github.

If that doesn't work try on a Linux server.

**Comment by ankur140290** [comment]
I already have the latest pull from github. 
I don't have Linux server.

**Comment by antoniofalcetta** [comment]
I think you should change the file "application / config / config.php" in the $ config ['permitted_uri_chars'] = 'az 0-9 ~%.: _ \ -'; and will add the symbol = ex. $ config ['permitted_uri_chars'] = 'az 0-9 ~%.: _ \ - =';

**Comment by avenirer** [comment]
@antoniofalcetta how would this change the underlying problem?

**Comment by antoniofalcetta** [comment]
honestly I have not tried...

**Comment by benedmunds** [comment]
Bump. Any updates on this?

**Comment by ankur140290** [comment]
Permitted URI doesn't solve this. The issue is thet the link generated is wrong

**Comment by ankur140290** [comment]
To resolve the problem, I just made change as:
>$config['email_config'] = array(
>	'mailtype' => 'html',
 >       'crlf'      => "\r\n",
>);

in ion_auth.php (config folder)
