### ISSUE TITLE
Remember code starting with . (dot)

### ISSUE THREAD

**Issue by andrefrcastro** [benedmunds/CodeIgniter-Ion-Auth#767]
Hi,

Sometimes i came across some situations where the recover code starts with a . (dot), something like:

`https://url/login/recover/.zaytCturEnwbBwKFQ0UBwO15b7f25734cfb027aa`

When this happens, we get a 403 from apache, not even from Codeigniter.

I am aware that this is a web server config issue, since it is not even routed to the index.php as all Codeigniter requests, but i think it's better to fix this in the code other then patching the htaccess or the web server config.

Thanks.

**Comment by benedmunds** [comment]
I don't think I've ever had anyone else report this so I would recommend just fixing it in your server environment.  It's probably your rewrite rule.  Maybe matching the dot incorrectly when looking for .tld or something similar?

**Comment by dualhub** [comment]
I'm actually getting this as well using Nginx. Will check my virtual host config.

**Comment by benedmunds** [comment]
Thanks!

**Comment by dualhub** [comment]
Not elegant in any way, but adding this around line 797 of ion_auth_model.php fixed it for me:
 
`$key = str_replace('.', '4', $key);
`

It simply replaces dots with the number 4 (but this could be anything else).

**Comment by benedmunds** [comment]
Maybe base64_encode and decode the hash before/after?

**Comment by dualhub** [comment]
Hey Ben, 

I'm getting this problem with a dot contained within the forgotten password code with the latest version of Ion Auth. I see you've totally rewritten Ion_auth_model.php, so my little patch (above) cannot work on this occasion.

Any ideas?
