### ISSUE TITLE
Why do we need to call hash_password in the login method?

### ISSUE THREAD

**Issue by OlexandrPopov** [benedmunds/CodeIgniter-Ion-Auth#768]
I mean the following code snippet:

```
//Hash something anyway, just to take up time
$this->hash_password($password);
```
You can find it at lines 996 and 1039 of the Ion_auth_model.php

**Comment by avenirer** [comment]
Because the password is hashed...

**Comment by OlexandrPopov** [comment]
Are you seriously? Have you seen the code?

**Comment by benedmunds** [comment]
@OlexandrPopov yes seriously.  Of course he's seen the code.  Watch your tone.

We are comparing a hash value in the database, so we need to rehash the plaintext password in order to compare the hashes.

**Comment by OlexandrPopov** [comment]
I'm sorry. I did not mean to offend you.

**Comment by OlexandrPopov** [comment]
Please take a look on line 1039 of the ion_auth_model.php
I'm using Ion Auth 2(http://github.com/benedmunds/CodeIgniter-Ion-Auth/zipball/2)

**Comment by benedmunds** [comment]
That is so the time to process an invalid login in this error path doesn't differ from one that does run a hash for comparison.  This is to protect agains timing attacks, you can read more here: https://www.owasp.org/index.php/Covert_timing_channel

**Comment by OlexandrPopov** [comment]
Thank you.
