### ISSUE TITLE
"Account Deactivated" message after registration

### ISSUE THREAD

**Issue by xxRockOnxx** [benedmunds/CodeIgniter-Ion-Auth#769]
Everything is fine, but why put Account deactivated message right after the registration?
Users would get that negative vibe. I can fix it by setting my own message on a flashdata and use that instead. But I want to stick with ion auth messages. That's all.

**Comment by benedmunds** [comment]
What do you mean?  Please send a PR with your proposed changes.

**Comment by xxRockOnxx** [comment]
OK, so Email activation is required and set on the ion auth's config file.
Then if registration is successful, message arrays are set to a flashdata.
I then read the flashdata value and echo it to the view.
Well, i get two message "Email Activation Sent" and "Accound Deactivated".

What message I'm expecting is something like "Account Successfully Created" because having a message of "Account Deactivated" after registration may bring a negative vibe to a user.

Maybe I get "Account Deactivated" message right after a successful registration because Email Activation is required and the account is not yet activated... but right after the registration? It's not likely to be appropriate...

![sample](https://cloud.githubusercontent.com/assets/11251134/7270073/ccabdcac-e90b-11e4-92a2-1c67dcdd1e76.png)

**Comment by benedmunds** [comment]
I just pushed up a fix for this with 3cbb83580a91dffcf26fc8d62e223693bb259d40

Please give it a try.

**Comment by xxRockOnxx** [comment]
So updating would fix this? or should I add another method in my controller that are made already?

**Comment by benedmunds** [comment]
Updating the model and library files should fix this.

**Comment by xxRockOnxx** [comment]
Whoops sorry for stupid question i was about to delete it but you replied so fast hahaha. Thanks ben ;)
Though what i expected is "Account Created Successfully" But this one is fine. You may consider it.
