### ISSUE TITLE
is_admin || in_group not working together. Tried asking help at #codeigniter channel

### ISSUE THREAD

**Issue by xxRockOnxx** [benedmunds/CodeIgniter-Ion-Auth#773]
I'm checking if a user is admin or in group to perform an operation but using both in an if condition like

if(!$this->ion_auth->is_admin() || !$this->ion_auth->in_group($group))

does not work. I need to do a nested if as a workaround like

if(!$this->ion_auth->is_admin())
{
   if(!$this->ion_auth->in_group($group)
    {
    }
}

**Comment by benedmunds** [comment]
Change the controller as needed for your specific use case.
