### ISSUE TITLE
session data set at logout method in Codeigniter ver 3

### ISSUE THREAD

**Issue by Rafeethu** [benedmunds/CodeIgniter-Ion-Auth#774]
Hi,

i was using ion auth with ci ver 2.1 without any issue. once started using ci ver 3.0 with ion auth ver 2.5.2, i have noticed the when i logout, the "Logout successfully" message is not set.

did anyone faced this issue?

**Comment by avenirer** [comment]
I did too, but I simply assumed is because of my coding... I will take a closer look...

**Comment by Rafeethu** [comment]
any update on this? i tried debugging the code, but couldn't locate the problem :-(

**Comment by avenirer** [comment]
The "problem" is that the session is destroyed after logout (literally destroyed). So, just as the manual of CI 3 says (http://www.codeigniter.com/userguide3/libraries/sessions.html#destroying-a-session - view the Note), you can't regenerate the session during the same request. This means that the library can't create that flashdata after it destroys the session (I guess...)
