### ISSUE TITLE
Accessing native php session from within ion_auth

### ISSUE THREAD

**Issue by jaymal** [benedmunds/CodeIgniter-Ion-Auth#775]
How do i access native php session variables values set outside of ion_auth within an application that uses ion_auth?
Thanks

**Comment by avenirer** [comment]
with $_SESSION['']? Or is it a trick question?

**Comment by jaymal** [comment]
Yes with  $_SESSION['']..it keeps returning an empty array within the ion_auth page

**Comment by benedmunds** [comment]
That's because Ion Auth uses CI sessions.  Just access them via $this->session->item().

**Comment by avenirer** [comment]
@benedmunds : I guess @jaymal was reffering to values set outside ion_auth. That is what is strange about this (and absolutely impossible in my opinion, exactly because Ion Auth works with CI sessions).

**Comment by benedmunds** [comment]
Ah.  No idea how you would do that.  You could use CI DB sessions I guess, then pull those sessions from the DB outside of CI.
