### ISSUE TITLE
Impersonating users

### ISSUE THREAD

**Issue by NemanjaK** [benedmunds/CodeIgniter-Ion-Auth#776]
Hey everyone,

I've started using Ion Auth recently and I must say it's a great increment to CodeIgniter community. There's a feature I occasionally stumble upon working on my projects and that's the option for admins to impersonate a user (login with user credentials without knowing the credentials itself). I've failed to find an easy way to do this with Ion Auth but I'd be more than happy to contribute with this feature. 

Reason I'm opening this issue is to get feedback would such an option represent increment in value of Ion Auth or not?

**Comment by benedmunds** [comment]
Ion Auth does not support this directly.  To accomplish this you would need to manually set session data.

**Comment by pkMyt1** [comment]
Wouldn't that type of login be a huge security risk?

**Comment by benedmunds** [comment]
It could be if implemented incorrectly.

**Comment by NemanjaK** [comment]
@pkMyt1 as Ben said - it should be carefully considered and thoroughly tested but it's something clients usually require as a feature.

@benedmunds yes I know it's currently not supported so I just wanted to check if I implement it would it be even taken into consideration as a contribution to Ion Auth? I'd be more then happy to fork and do it on my own and afterward check with the rest of the community.

**Comment by benedmunds** [comment]
I've only seen a couple requests for this over the years so I would rather just leave it up to those few users to implement rather than include it and it be used improperly by other users.
