### ISSUE TITLE
Credentials Checking function

### ISSUE THREAD

**Issue by sahanDissanayake** [benedmunds/CodeIgniter-Ion-Auth#777]
Hi @benedmunds 

I know that there is a ion-auth->user() function, My question is is there another function where I can see if the currently logged in user in logged in with proper credentials ?

Because some users could pass in a user id as a session variable or cookie and get access if I do not check the credentials,,

Any thoughts would be much appreciated. 

Cheers

**Comment by sahanDissanayake** [comment]
My end goal is to have policy, so that every admin request will go through something similar to 
```javascript 
$this -> ion_auth -> is_reallly_loggedin()
``

Which will check the session or cookies and the id against the DB and return true or false

**Comment by benedmunds** [comment]
Yes, check the group the user is assigned to.

**Comment by sahanDissanayake** [comment]
@benedmunds it just seems like in_group() just uses the session.userid

https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3cbb83580a91dffcf26fc8d62e223693bb259d40/libraries/Ion_auth.php#L476

Not a real like full DB check or anything for authentication,, Please correct me if I'm wrong,

Im just worried users might just change the cookie / session userid and have access to do bad stuff on my website,

**Comment by benedmunds** [comment]
Ah right.  I recommend using Db sessions to mitigate that.

**Comment by sahanDissanayake** [comment]
How do I do that may I ask please ?

Should the answer be here ? http://www.codeigniter.com/user_guide/libraries/sessions.html?highlight=session

So is there anything that I could use from ion_auth when im building this functionality ?

Thanks so much

**Comment by avenirer** [comment]
if you set your CI framework to use database to store the session the ion auth library will automatically use that type of session. This way you make sure that no one can at any time change the user id by cookie. Either way, CI3 doesn't use cookie sessions anymore, every session data is saved on the server. The only thing that is stored on the computer is the session id (http://www.codeigniter.com/user_guide/libraries/sessions.html?highlight=session#how-do-sessions-work). If you're using CI 2.x you can encrypt the session by setting an encryption key in the config.php of your application.

**Comment by sahanDissanayake** [comment]
thanks @avenirer , Im using CI V3 of Codeigniter,

I will give this a shot :+1:

**Comment by benedmunds** [comment]
Closing, please open if the issue remains.

**Comment by sahanDissanayake** [comment]
Cheers Ben, I will do, I think now I know how the ION Auth works, So all good
