### ISSUE TITLE
Error when using array for groups

### ISSUE THREAD

**Issue by dollardad** [benedmunds/CodeIgniter-Ion-Auth#78]
Small problem, first the function $this->ion_auth->is_group($group) should be in_group().  I think I remember seeing this elsewhere.  However a problem exists if you pass an array of groups.

Currently is_group returns in_array($check_group, $groups) which won't work if check_group is an array.

Solution:
Add condition to check if $check_groups is an array and if it is then walk through the array checking for a match.
    public function in_group($check_group)
    {
        $this->ci->ion_auth_model->trigger_events('is_group');

```
    $users_groups = $this->ci->ion_auth_model->get_users_groups();
    $groups = array();
    foreach ($users_groups as $group)
    {
        $groups[] = $group->name;
    }
    $permission = false;
    if(is_array($check_group)) {
        foreach($check_group as $key => $value){
            if(in_array($value, $groups)) {
                $permission = true;
            }
        }
    } else {
        if(in_array($check_group, $groups)) {
            $permission = true;
        }
    }
    return $permission;
}
```

Otherwise love your work

**Comment by varun8255** [comment]
can i use the soft key delete using ion auth.which we use in my model

**Comment by benedmunds** [comment]
You would need to write hooks for that

**Comment by varun8255** [comment]
$this->data['deleted'] = $this->ion_auth_model->set_hook('post_set_soft_key_delete', 'restrict_deleted_soft', $this, 'index', '');
and i have created a function inside ion auth model as soft_key_delete which triggers events 
$this->trigger_events('post_set_soft_key_delete'); i cant get the output.... is there any mistakes in the above snippet..........

thanks

**Comment by varun8255** [comment]
since i lack experience in codeigniter framework and ion auth ...any help would be appreciated
