### ISSUE TITLE
Username field

### ISSUE THREAD

**Issue by tikky** [benedmunds/CodeIgniter-Ion-Auth#780]
Hello,

In database with have a field "username" however when I am adding a user in form is no option to specify the username.
Could you add a form field login, to allow user to specify the login (username) - different then the name / surname?

**Comment by avenirer** [comment]
Your english didn't help me understand your issue... But in any case, you can add whatever you want to the controller or view, as those are not really a part of the library, but only an example of usage.

**Comment by tikky** [comment]
So once again:

In Auth.php we have a function "function create_user()" and one of line is:
[$username = strtolower($this->input->post('first_name')) . ' ' . strtolower($this->input->post('last_name'));](https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/controllers/auth.php#L439)

Could we change this behavior, and allow user to specific (choose) an username when creating new user (instead of automatic creation based on name + last_name)

Hope that is clear.

**Comment by avenirer** [comment]
My answer stands. You can change the controller anyway you want to. You can even create your own controller and views. To create a user using the library, you simply do a: `$this->ion_auth->register($username, $password, $email, $additional_data, $group)`, with whatever information you get from your forms.
