### ISSUE TITLE
I dont see where some functions are used

### ISSUE THREAD

**Issue by sahanDissanayake** [benedmunds/CodeIgniter-Ion-Auth#781]
@benedmunds  

These functions does not seem to be used anywhere
I think I'm missing something 

https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/models/ion_auth_model.php#L2241

https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/models/ion_auth_model.php#L2163

**Comment by benedmunds** [comment]
They aren't used by the library internally or the example controller, but they are public and accessible through the public API to the library in case they are needed for an implementation.
