### ISSUE TITLE
CodeIgniter failing when ion_auth->login() remember parameter is set to true

### ISSUE THREAD

**Issue by BunnyR** [benedmunds/CodeIgniter-Ion-Auth#783]
When I set the remember parameter to true in the ion auth login method I get the following error:

A PHP Error was encountered
Severity: Notice
Message: Array to string conversion
Filename: core/Input.php
Line Number: 404

The CodeIgniter line referred to is as follows: setcookie($prefix.$name, $value, $expire, $path, $domain, $secure, $httponly).

The code in my controller causing the issue is: $this->ion_auth->login($email, $password, true).

As soon as I alter the remember parameter to false, as below, I do not get the error:
$this->ion_auth->login($email, $password, false).

I've poked around in the Ion_auth method but I can't figure out what's going wrong here. Any help would be appreciated.

I'm using CI 3.0.0 and PHP Version 5.4.29.

Thanks!

**Comment by avenirer** [comment]
Make sure you have the latest version of CodeIgniter. Also make sure you have the latest version of Ion Auth. There shouldn't be errors inside the core files. Also, make a habit to mention the file name, and the line number where you think the error is.

**Comment by BunnyR** [comment]
I've re-done the CodeIgniter upgrade process and upgraded Ion Auth again and it looks like the issue has disappeared. I must have missed a certain peice of the upgrade the first time round.
