### ISSUE TITLE
Could not find the language line "create_user_validation_phone_label"

### ISSUE THREAD

**Issue by emilebourquin** [benedmunds/CodeIgniter-Ion-Auth#784]
Now that the phone number field is one input instead of three, create_user is throwing 'Could not find the language line "create_user_validation_phone_label"' errors.

The solution is to add:

`$lang['create_user_validation_phone_label']            = 'Phone';`

and remove:

`$lang['create_user_validation_phone1_label']           = 'First Part of Phone';
$lang['create_user_validation_phone2_label']           = 'Second Part of Phone';
$lang['create_user_validation_phone3_label']           = 'Third Part of Phone';`

from auth_lang.php .

The same needs to happen in the edit_user section of auth_lang.php .

Thanks again for the great software, Ben, it's a huge help.

**Comment by benedmunds** [comment]
Could you send a PR for this please?  Thanks!
