### ISSUE TITLE
Fatal error when trying to access Model from an Ion Auth view

### ISSUE THREAD

**Issue by sparky672** [benedmunds/CodeIgniter-Ion-Auth#790]
Strange thing happening here.

I have a custom template system that I use.  All CI views use my template and it's been working fine until now.

    $history = $this->products_model->get_user_orders($ion->user()->row()->id);

Gives this error:

>  Fatal error:  Call to a member function get_user_orders() on a non-object

There's nothing wrong with that line.  It works on all other CI views.  It's only giving this error when I try to load an Ion Auth page.   The Ion Auth Controller was modified as follows to use my custom template...

    function _render_page($view, $data=null, $render=false)
    {
		$this->viewdata = (empty($data)) ? $this->data: $data;

		$view_html = $this->template->load('default', $view, $this->viewdata);

		if (!$render) return $view_html;
    }

Why can't I call my Model from within an Ion Auth view?

**Comment by benedmunds** [comment]
I'm sure it has something to do with the way you're loading it.  

Are you loading that model in the proper controller?  Try autoloading it.

Also you really shouldn't call models directly from views.

**Comment by sparky672** [comment]
>  Are you loading that model in the proper controller? Try autoloading it.

No problems or errors when I use any other Controller.

>  Also you really shouldn't call models directly from views.

I know.  However, I'm simply trying to set a flag that is accessible in all views globally.  I'm going to put more thought into this part.  Regardless, if I can call that model directly when I use that template elsewhere, why can't I call it from an Ion Auth view?

**Comment by benedmunds** [comment]
Try autoloading the model and see if the issue goes away.  This would denote that it's a loading issue.

**Comment by sparky672** [comment]
YES.  Stupid me.  Completely forgot that I'm only loading the model from my own Controller and not via the Ion Auth Controller.  Sorry for wasting your time with my nonsense.  LOL.

**Comment by benedmunds** [comment]
No problem!

**Comment by sparky672** [comment]
FYI for future readers:   I removed the call to the Model from my View.  I'm now calling my Model from my custom Template library class instead and setting a data variable for the View.
