### ISSUE TITLE
Login with Username or Email

### ISSUE THREAD

**Issue by iamthestreets** [benedmunds/CodeIgniter-Ion-Auth#792]
Hi,

I am trying to setup the login to be by either username or login, but I do not see a way to set it up this way. In the config file I can only choose one. Can you help me with this setup?

**Comment by avenirer** [comment]
In the config file you do have $config['identity'] and you can either put "username" or "email" as values.

**Comment by iamthestreets** [comment]
Thanks for the reply.

I want the ability to set both and let the user decide when loggin in if they want to log in with Username or Email. Make sense?

**Comment by benedmunds** [comment]
The library doesnt support this.  In the past I have accomplished this by dynamically changing the identitiy config item and just trying a login() call for each identity.

**Comment by iamthestreets** [comment]
Ok, thanks for the reply!
