### ISSUE TITLE
Login is not working

### ISSUE THREAD

**Issue by raushan896** [benedmunds/CodeIgniter-Ion-Auth#795]
When i am entering email as admin@admin.com and password as password its giving:

Incorrect Login
Please login with your email and password below.

While everything seems correct. Unable to find what's wrong!

**Comment by benedmunds** [comment]
Did you setup the database along with the seed data?

**Comment by raushan896** [comment]
Yes i did

**Comment by raushan896** [comment]
yes i did. I sent my code to your email. Could you please check
out....whats wrong in it!!

**Comment by raushan896** [comment]
Problem solved...
Actually, i was not using upgraded files.
Overwriting "libraries/ion_auth.php" and "models/ion_auth_model.php" with the new versions solved it.
Well...thanks :)
