### ISSUE TITLE
No email send out

### ISSUE THREAD

**Issue by sonicwong** [benedmunds/CodeIgniter-Ion-Auth#796]
No email send out after submit in "forget password" page.
It return "Password Reset Email Sent".

I can't found any email code like this:

$this->load->library('email');
$this->email->from('your@example.com', 'Your Name');
$this->email->to('someone@example.com'); 
$this->email->subject('Email Test');
$this->email->message('Testing the email class.');	
$this->email->send();

Is it already include email function or I need to add myself ?

**Comment by benedmunds** [comment]
It's in the library.

You should create a test controller to work out your email config.
