### ISSUE TITLE
Logout not working correct.

### ISSUE THREAD

**Issue by pink-squirrel** [benedmunds/CodeIgniter-Ion-Auth#798]
Hi Ben,

I found an error in the logout process.

The user isn't logged out direct after the function call. 

    log_message('error', 'Before - USER ID: ' . $this->ion_auth->get_user_id());
    $this->ion_auth->logout();
    log_message('error', 'After - USER ID: ' . $this->ion_auth->get_user_id());

Results in:

    Before - USER ID: 19
    After - USER ID: 19

In my mind this is a bug. Or can you explain it?

Thanks! Oliver

**Comment by benedmunds** [comment]
It's just due to the way the session library works. They'll be logged out on the next page load.

**Comment by pink-squirrel** [comment]
Wow, thanks for your fast reply. It didn't make sense for me but I see the bug is not in your plugin.

Thanks for this great plugin.  :-)
