### ISSUE TITLE
Get user data inside of another controller

### ISSUE THREAD

**Issue by iamthestreets** [benedmunds/CodeIgniter-Ion-Auth#799]
Hi,

I have created a controller and I would like to get some user data in this controller to pass to one of my views.

First I load the library:
`$this->load->library('ion_auth');`

Then i try doing:
`$user_data = $this->ion_auth->user()->row();`
`$data['user_email'] = $user->email;`
`$this->load->view('templates/frontend/front_header', $data);`
Then in my view I try doing this:
`echo $user_email`

But I keep getting this error:
`Message: Undefined index: user_email`

Can you help me with using the `user()` Get a user?

**Comment by avenirer** [comment]
Well... nothing is more precious than the span attention. You stored something in $user_data, but you want to access the email from $user->email...

**Comment by iamthestreets** [comment]
Even if I correct it to:
`$data['user_email'] = $user_data->email;`

it does not work. Same error.
