### ISSUE TITLE
error Undefined property

### ISSUE THREAD

**Issue by OriTheMan** [benedmunds/CodeIgniter-Ion-Auth#800]
Hi,
i followed the steps in the documentation, and installed the ion-auth.
i'm using CI 3, and receive the following error:

```
A PHP Error was encountered

Severity: Notice

Message: Undefined property: Dashboard::$ion_auth_model

Filename: libraries/Ion_auth.php

Line Number: 125

Backtrace:

File: xxx/public_html/xxx/application/libraries/Ion_auth.php
Line: 125
Function: _error_handler

File: xxx/public_html/xxx/application/libraries/Ion_auth.php
Line: 71
Function: __get

File: xxx/public_html/xxx/index.php
Line: 292
Function: require_once

```

**Comment by benedmunds** [comment]
How are you loading the library?

-Ben Edmunds

**Comment by OriTheMan** [comment]
yes.

**Comment by OriTheMan** [comment]
when i use autoload i receive this error
```
$autoload['libraries'] = array('database', 'ion_auth', 'session');
```

**Comment by avenirer** [comment]
Make sure, the file name for the ion_auth model starts with capital letter: Ion_auth_model.php

**Comment by OriTheMan** [comment]
its already capital letter

**Comment by OriTheMan** [comment]
no idea why its happened?

**Comment by benedmunds** [comment]
I'm not sure, never seen that.  Can you ensure all the files are there?

**Comment by OriTheMan** [comment]
found the problem.
in ion_auth library you should replace any  `$this->ion_auth_model` with `$this->Ion_auth_model`

**Comment by avenirer** [comment]
that is a weird solution...

**Comment by OriTheMan** [comment]
yeah... but it's works!

**Comment by Tjoosten** [comment]
Maybe we can apply this fix as a temporarily fix. So we can do some further investigation?

**Comment by benedmunds** [comment]
I dont think that'll account for CI 2?

**Comment by nrshoukhin** [comment]
May be you are checking the log in before loading the parent constructor from in your controller.

**Comment by vitor-defenx** [comment]
Hello, got the same issue working with CI 3.1.9 and HMVC from Wirez...
playing around for almost a week trying to get it sorted out.

Plot Twist: just found the solution or my case, Controller Auth must extend MX_Controller, the rest of bugfix is easy.

**Comment by PedroRuiz** [comment]
Same problem here. Finally I forgot parent::__construct() in MY_Controller.
