### ISSUE TITLE
Migration is based on a deprecated schema

### ISSUE THREAD

**Issue by orionstar** [benedmunds/CodeIgniter-Ion-Auth#804]
In the SQL dump and in the migration default data for example the ip address  is varchar but at the creation of the field, the type is varbinary...

**Comment by benedmunds** [comment]
Please send a PR

**Comment by Tjoosten** [comment]
@benedmunds i Will take care pfff It tomorrow

**Comment by Tjoosten** [comment]
@benedmunds This issue can be closed. Because this issue fix has been merged.

**Comment by orionstar** [comment]
@Tjoosten You missed the bottom VARBINARY ;)

**Comment by Tjoosten** [comment]
@orionstar Brace for impact another fix is coming out! PS can you point the file plz?

**Comment by orionstar** [comment]
@Tjoosten migrations/001_install_ion_auth.php::214

**Comment by Tjoosten** [comment]
Ok i will send a PR in 30 minutes! Alright?

**Comment by orionstar** [comment]
Thank you. It's not urgent or stg like that... I thought I will fix it int the next few weeks when I have spare time, but you overtake me. :)

**Comment by Tjoosten** [comment]
@orionstar the PR is up now.

**Comment by benedmunds** [comment]
Merged
