### ISSUE TITLE
failure importing ion_auth

### ISSUE THREAD

**Issue by alindima** [benedmunds/CodeIgniter-Ion-Auth#806]
I have written an application in CodeIgniter 3 which uses Ion_auth.I have developed it locally on windows but then i deployed the app on a live linux server.
My app imports the ion_auth library in the controller's constructor but nothing is displayed but a blank screen.
When i comment out the library's import,everything works fine
Please help

**Comment by avenirer** [comment]
Make sure the file names start with uppercase.

**Comment by alindima** [comment]
They do start with uppercase characters.I have properly capitalized the files based on the docs,but still it doesn't work..

**Comment by benedmunds** [comment]
What error are you seeing in your logs?

**Comment by alindima** [comment]
It's ok.It was the bcrypt's fault since it isn't supported in php 5.2 and my host was running php 5.2.
I have moved my app to another server and it works fine
