### ISSUE TITLE
logout() does not work on CI 3.x

### ISSUE THREAD

**Issue by sigmoidal** [benedmunds/CodeIgniter-Ion-Auth#807]
The logout function in libraries/Ion_auth.php does not work properly in CI 3.x because on line 387, the associative array notation of unset_userdata is used, but this is deprecated:

```
$this->session->unset_userdata( array($identity => '', 'id' => '', 'user_id' => '') );
```

For CI 3.x this should be changed to:
```
$this->session->unset_userdata( array($identity, 'id', 'user_id') );
```

In addition, the userdata functions have been deprecated and therefore it would be nice to update the code for CI3.x eventually.

thanks.

**Comment by benedmunds** [comment]
Could you send a PR please?

**Comment by sigmoidal** [comment]
This was also submitted as a PR some days ago.
