### ISSUE TITLE
logged_in does not use correct field

### ISSUE THREAD

**Issue by sigmoidal** [benedmunds/CodeIgniter-Ion-Auth#808]
The logged_in() function logs out a user exclusively based on the 'identity' field, but does not take into account that this may not be the field used to identify the user. This has to be changed  so that the it is read from the configuration file, as set by the user:

```
public function logged_in()
{
	$this->ion_auth_model->trigger_events('logged_in');
	$identity = $this->config->item('identity', 'ion_auth');
	return (bool) $this->session->userdata($identity);
}
```

**Comment by benedmunds** [comment]
Could you send a PR please?

**Comment by Tjoosten** [comment]
Maybe if @sigmoidal can explain more what needs to be changed can i make a pr for this?

**Comment by sigmoidal** [comment]
I have already done that, but didn't reply here, my bad. Tim thank you for offering to help. I think ben has already merged it in.

**Comment by Tjoosten** [comment]
@sigmoidal @benedmunds can someone investigate this? So we can be sure if this issue can be closed or not?

**Comment by sigmoidal** [comment]
I just looked at the code and it is merged in already, so I would close the issue.

**Comment by Tjoosten** [comment]
Alright? Anyway thx for reporting!
