### ISSUE TITLE
CI 3 & Ion Auth

### ISSUE THREAD

**Issue by Philwn** [benedmunds/CodeIgniter-Ion-Auth#810]
Hi,
Ive created an app using Codeigniter 3 and ion auth. Locally everything was fine and I could login and create users etc. Once uploaded from local to live environment when logging in the page just seems to refresh, no errors given but not logged in.

**Comment by Philwn** [comment]
It would appear it doesnt even run form validation, it just refreshes the page

**Comment by benedmunds** [comment]
Make sure the capitalization of the files are correct.

**Comment by Philwn** [comment]
I appreciate your time to answer, I narrowed it down and it wasn't an Ion Auth issue. as no forms would submit. Turns out my server was set to non www but my config had www therefore redirecting to non www would loose post data. very frustrated with myself! Thank you for a great library.
