### ISSUE TITLE
Get Username based on groups

### ISSUE THREAD

**Issue by wpthemes786** [benedmunds/CodeIgniter-Ion-Auth#811]
Hello.

I want to get username,  first name and last name from users table and join table with groups table where group name is doctor. I am in admin view i just print the the doctors list in my admin view. its difficult to retreive because i have only admin id. so i have to ask you that how to get the username based on group assign.

**Comment by ghermans** [comment]
i don’t think there is a default function  in ion_auth , however you could add a custom query in models/ion_auth_model.php

**Comment by avenirer** [comment]
Doesn't ```$users = $this->ion_auth->users()->result();``` work? (http://benedmunds.com/ion_auth/#users)

**Comment by ghermans** [comment]
Indeed the answer from @avenirer  should be the solution
