### ISSUE TITLE
How to get user id after registration ?

### ISSUE THREAD

**Issue by absmugz** [benedmunds/CodeIgniter-Ion-Auth#822]
Hi all,

I am trying to get the user id just after registration, here is my code, so the data inserts onto the ion-auth user table but I need to get the id because its a multistep form and need to save the id in other tables. 

$username = $this->input->post('username');
$password = $this->input->post('password');
$email = $this->input->post('your_email');
		$additional_data = array(
								'first_name' => $this->input->post('first_name'),
								'last_name' => $this->input->post('surname'),
								);
//$group = array('1'); // Sets user to admin. No need for array('1', '2') as user is always set to member by default

$this->ion_auth->register($username, $password, $email, $additional_data);

$user = $this->ion_auth->user()->row();
		

var_dump($user->id);die();

Its gives me NULL when I try this but the the user has been saved in the database.

**Comment by avenirer** [comment]
Try this: $id = $this->ion_auth->register($username, $password, $email, $additional_data);

**Comment by absmugz** [comment]
Thank you for the quick answer, I tried this 
$id = $this->ion_auth->register($username, $password, $email, $additional_data);

var_dump($id);die();

this is what I get bool(false) 

What I need is to get the id of the user that has just been inserted into the database.

**Comment by avenirer** [comment]
And yet the user is inserted into the table?

**Comment by avenirer** [comment]
You didn't pass the group to the register() method
$id = $this->ion_auth->register($username, $password, $email, $additional_data,$group);

**Comment by absmugz** [comment]
Hi I pass the group to the register() method
$id = $this->ion_auth->register($username, $password, $email, $additional_data,$group);

Because it says $group = array('1'); // Sets user to admin. No need for array('1', '2') as user is always set to member by default
so I thought if I commented it out the user will be created as a member by default. However I tried your code
 $username = $this->input->post('username');
$password = $this->input->post('password');
$email = $this->input->post('your_email');
		$additional_data = array(
								'first_name' => $this->input->post('first_name'),
								'last_name' => $this->input->post('surname'),
								);
$group = array('2'); // Sets user to admin. No need for array('1', '2') as user is always set to member by default

$this->ion_auth->register($username, $password, $email, $additional_data, $group);

$id = $this->ion_auth->register($username, $password, $email, $additional_data, $group);

var_dump($id);die();

Still got bool(false)

**Comment by avenirer** [comment]
Well... it should have returned the id of the new user. Try this:

```php
if ($this->ion_auth->register($username, $password, $email, $additional_data, $group))
{
	$messages = $this->ion_auth->messages();
	echo $messages;
}
else
{
	$errors = $this->ion_auth->errors();
	echo $errors;
}
```

And see what errors it gives you.

**Comment by absmugz** [comment]
Hi, thank you for the quick response :
After your awesome code, I get string(35) "

Account Successfully Created
" 
How do I get the user id ?

**Comment by avenirer** [comment]
This could be due to the fact that maybe you don't have an autoincrement primary key in your database "users" table?

**Comment by absmugz** [comment]
I used the default users table which you get when you download ion-auth :)

**Comment by avenirer** [comment]
Well... From what I see in your schema, you are not right...
```
CREATE TABLE `users` (
`id` int(11) unsigned NOT NULL,
  `ip_address` varchar(15) NOT NULL,
  `username` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `salt` varchar(255) DEFAULT NULL,
  `email` varchar(100) NOT NULL,
  `activation_code` varchar(40) DEFAULT NULL,
  `forgotten_password_code` varchar(40) DEFAULT NULL,
  `forgotten_password_time` int(11) unsigned DEFAULT NULL,
  `remember_code` varchar(40) DEFAULT NULL,
  `created_on` int(11) unsigned NOT NULL,
  `last_login` int(11) unsigned DEFAULT NULL,
  `active` tinyint(1) unsigned DEFAULT NULL,
  `first_name` varchar(50) DEFAULT NULL,
  `last_name` varchar(50) DEFAULT NULL,
  `company` varchar(100) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=11 ;
```
As you can see 'id' is not auto-incremented...

**Comment by absmugz** [comment]
I just used the following and still get the issue :
DROP TABLE IF EXISTS `groups`;

#
# Table structure for table 'groups'
#

CREATE TABLE `groups` (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(20) NOT NULL,
  `description` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Dumping data for table 'groups'
#

INSERT INTO `groups` (`id`, `name`, `description`) VALUES
     (1,'admin','Administrator'),
     (2,'members','General User');



DROP TABLE IF EXISTS `users`;

#
# Table structure for table 'users'
#

CREATE TABLE `users` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ip_address` varchar(15) NOT NULL,
  `username` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `salt` varchar(255) DEFAULT NULL,
  `email` varchar(100) NOT NULL,
  `activation_code` varchar(40) DEFAULT NULL,
  `forgotten_password_code` varchar(40) DEFAULT NULL,
  `forgotten_password_time` int(11) unsigned DEFAULT NULL,
  `remember_code` varchar(40) DEFAULT NULL,
  `created_on` int(11) unsigned NOT NULL,
  `last_login` int(11) unsigned DEFAULT NULL,
  `active` tinyint(1) unsigned DEFAULT NULL,
  `first_name` varchar(50) DEFAULT NULL,
  `last_name` varchar(50) DEFAULT NULL,
  `company` varchar(100) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


#
# Dumping data for table 'users'
#

INSERT INTO `users` (`id`, `ip_address`, `username`, `password`, `salt`, `email`, `activation_code`, `forgotten_password_code`, `created_on`, `last_login`, `active`, `first_name`, `last_name`, `company`, `phone`) VALUES
     ('1','127.0.0.1','administrator','$2a$07$SeBknntpZror9uyftVopmu61qg0ms8Qv1yV6FG.kQOSM.9QhmTo36','','admin@admin.com','',NULL,'1268889823','1268889823','1', 'Admin','istrator','ADMIN','0');


DROP TABLE IF EXISTS `users_groups`;

#
# Table structure for table 'users_groups'
#

CREATE TABLE `users_groups` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL,
  `group_id` mediumint(8) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_users_groups_users1_idx` (`user_id`),
  KEY `fk_users_groups_groups1_idx` (`group_id`),
  CONSTRAINT `uc_users_groups` UNIQUE (`user_id`, `group_id`),
  CONSTRAINT `fk_users_groups_users1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_groups_groups1` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `users_groups` (`id`, `user_id`, `group_id`) VALUES
     (1,1,1),
     (2,1,2);


DROP TABLE IF EXISTS `login_attempts`;

#
# Table structure for table 'login_attempts'
#

CREATE TABLE `login_attempts` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ip_address` varchar(15) NOT NULL,
  `login` varchar(100) NOT NULL,
  `time` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by absmugz** [comment]
if ($this->ion_auth->register($username, $password, $email, $additional_data, $group))
{
    $messages = $this->ion_auth->messages();
    $user = $this->ion_auth->user()->row();
    $user_id = $user->id;
    //echo $messages;
    //var_dump($messages);die();
    var_dump($user_id);die();
}
else
{
    $errors = $this->ion_auth->errors();
    //echo $errors;
     var_dump($errors);die();
}

Getting null error

**Comment by avenirer** [comment]
What do you mean by "null error"? What is happening there it's weird, as the register() method should have returned your id if you had the table set up correctly. I will test the library tonight to see if indeed works or not.

**Comment by absmugz** [comment]
I am really struggling with ion auth and I think my issue is misunderstood, so I will describe what I am trying to do again :

I have a custom registration form which inserts the user into the ion_auth user table, this part works using the following code -
$username = $this->input->post('username');
$password = $this->input->post('password');
$email = $this->input->post('your_email');
		$additional_data = array(
								'first_name' => $this->input->post('first_name'),
								'last_name' => $this->input->post('surname'),
								);
$group = array('2'); // Sets user to admin. No need for array('1', '2') as user is always set to member by default

//$this->ion_auth->register($username, $password, $email, $additional_data, $group);

if ($this->ion_auth->register($username, $password, $email, $additional_data, $group))
{
    $messages = $this->ion_auth->messages();
    //$user = $this->ion_auth->user()->row();
	$id = $this->ion_auth->user()->row();
    //$user_id = $user->id;
                       
                      
    //echo $messages;
    //var_dump($messages);die();
    //var_dump($user_id);die();
    var_dump($messages);
    var_dump($id);die();
}
else
{
    $errors = $this->ion_auth->errors();
    //echo $errors;
     var_dump($errors);die();
}

The above works perfectly. On insert I would like to return the user id of the user that has just been created but its just not working is it because I am not logged in as a admin user ? Please help me man, I am really stuck, its the same issue from last week still. finally it returns 1 for :

$user = $this->ion_auth->user()->row();
$user_id = $user->id;

If I am logged in as admin but I want to return the just inserted id or user so I can store it in other tables when I am not logged in and registering as a new user it is returning NULL.

**Comment by benedmunds** [comment]
This will give you the user id on registration:


    $id = $this->ion_auth->register($username, $password, $email, $additional_data, $group);

    if ($id)
    {

**Comment by SylTi** [comment]
https://github.com/benedmunds/CodeIgniter-Ion-Auth/issues/744
This is still not working. register always return false.

**Comment by benedmunds** [comment]
Then you have another issue.  What does 

$errors = $this->ion_auth->errors();
var_dump($errors);die();

give you?

**Comment by SylTi** [comment]
Thanks ! I'm still new using your lib ! 
`Unable to Send Activation Email`

**Comment by benedmunds** [comment]
Make sure to update your email config for what you're using.

**Comment by srok** [comment]
The "unable to send activation email" error shoud not prevent the method to return the Id as the user is in fact created.

**Comment by benedmunds** [comment]
@srok I wouldn't be against rolling back a transaction if it fails but definitely wouldn't want it to proceed as normal.

**Comment by enfrte** [comment]
Just had this issue. Thanks to this thread, I got it sorted. I tend not to set up my mail early in dev, but found it a bit odd that you needed the registration email to send correctly in order receive the registration id, considering how the user row is stored in the database regardless.
