### ISSUE TITLE
Query Build Like Plus in Groups not working

### ISSUE THREAD

**Issue by danielslim** [benedmunds/CodeIgniter-Ion-Auth#823]
I'm new with CI so please correct me if i'm wrong... Using the users query like with all groups work fine but combine with groups yields all records. 
 
This works ok
$this->ion_auth->offset($offset)->limit($config['per_page'])->like(array('first_name'=>$search_term))->like(array('last_name'=>$search_term))->users()->result();

This doesn't work - would show all result
$this->ion_auth->offset($offset)->limit($config['per_page'])->like(array('first_name'=>$search_term))->like(array('last_name'=>$search_term))->users('admin','manager')->result();

The solution is using like query on where clause. 
$this->ion_auth->offset($offset)->limit($config['per_page'])->where("(users.first_name LIKE '%".$this->db->escape_like_str($search_term)."%' OR users.last_name LIKE '%".$this->db->escape_like_str($search_term)."%' )")->users(array('admin','manager'))->result();

**Comment by avenirer** [comment]
Why do you complicate yourself? Why not use a User_model and do whatever you want with the records?

**Comment by benedmunds** [comment]
@avenirer's solution is the correct path.  Ion Auth supports basic querying but not all the abilities of the DB object.
