### ISSUE TITLE
Field 'username' doesn't have a default value

### ISSUE THREAD

**Issue by victorcl** [benedmunds/CodeIgniter-Ion-Auth#831]
Hi.
I am getting Field 'username' doesn't have a default value when trying to create a user with $this->ion_auth->register()
What I have found out is that on ion_auth_model.php line 918 
		$data = array(
		    $this->identity_column   => $identity,		    
		    'password'   => $password,
		    'email'      => $email,
		    'ip_address' => $ip_address,
		    'created_on' => time(),
		    'active'     => ($manual_activation === false ? 1 : 0)
		);
$this->identity_column is equal to "email" but email is already there and then username is never passed to the insert , even do is passed on ->register($username,... so the query aways fails.

I dont know if I am doing something wrong or this is a bug.
Thanks.

**Comment by avenirer** [comment]
I don't understand. What column did you use as identity column in the configuration file? If you used email as identity column what are you doing with "username"?

**Comment by spreaderman** [comment]
I have the same error. 

Using Mysql 5.6.13, PHP and when submitting http://localhost:8000/auth/create_user I get the following error:

+++
Error Number: 1364

Field 'username' doesn't have a default value

INSERT INTO users (first_name, last_name, company, phone, email, password, ip_address, created_on, active) VALUES ('Tom', 'Harry', 'My Company', '298098092384', 'tharry@example.com', 'snip', '::1', 1439092920, 1)

Filename: /Users/snip/Dropbox/webserver/snip/models/ion_auth_model.php

Line Number: 938
+++

The ion_auth.php contains the following:

$config['identity'] = 'email'; // You can use any unique column in your table as identity column. The values in this column, alongside password, will be used for login purposes

Error log in codeignitor is:

+++
DEBUG - 2015-08-09 13:13:00 --> Ion_auth class already loaded. Second attempt ignored.
DEBUG - 2015-08-09 13:13:00 --> Form_validation class already loaded. Second attempt ignored.
DEBUG - 2015-08-09 13:13:00 --> Language file loaded: language/english/auth_lang.php
DEBUG - 2015-08-09 13:13:00 --> Language file loaded: language/english/form_validation_lang.php
DEBUG - 2015-08-09 13:13:00 --> DB Transaction Failure
ERROR - 2015-08-09 13:13:00 --> Query error: Field 'username' doesn't have a default value
DEBUG - 2015-08-09 13:13:00 --> Language file loaded: language/english/db_lang.php
+++

Pleased to hear.

What there something changed from older (workable) versions here?

**Comment by Tjoosten** [comment]
Hmm maybe the fault occurs in the database scheme?

**Comment by spreaderman** [comment]
Tjoosten, wondering if you could elaborate a bit more.  All the necessary fields are in the DB.

**Comment by goose-za** [comment]
Hi Guys. 

I managed to find a workaround for this particular issue. I altered the users table and set the username field's default value to NULL. I then created a BEFORE INSERT trigger on the user table that sets the username field to a calculated value (in this case LOWER(CONCAT(NEW.last_name, LEFT(NEW.first_name,1)));)

I hope that this helps someone.

**Comment by victorcl** [comment]
avernier by default ion_auth has $config['identity'] = 'email' so this is causing the problem because on the register queries in the model it uses this object (the one below), so 'email' property is duplicated and since USERNAME has NOT NULL and since is never passed, then it fails, the solucion would be to set $config['identity'] = 'username'; by default.

$data = array(
$this->identity_column => $identity,
'password' => $password,
'email' => $email,
'ip_address' => $ip_address,
'created_on' => time(),
'active' => ($manual_activation === false ? 1 : 0)
);

**Comment by avenirer** [comment]
@victorcl but wouldn't it be better if the username is NULL by default? Because your solution would be only a bypass of the problem and not a solution.

**Comment by prashantnirgun** [comment]
/* ion_auth_module.php add the following line at line no 908 */
  'username'	 => $additional_data['first_name'].".".$additional_data['last_name'],

**Comment by avenirer** [comment]
"..._module..."? where?

**Comment by prashantnirgun** [comment]
File Path : application/models/ion_auth_module.php
username Field required a value I am providing a value by just concating first name & Last Name

**Comment by avenirer** [comment]
the question remains... "module"?

**Comment by prashantnirgun** [comment]
Ohh I am very sorry avenirer please read it as model not module I will correct the comment
