### ISSUE TITLE
Get all users in a group

### ISSUE THREAD

**Issue by waitaamon** [benedmunds/CodeIgniter-Ion-Auth#833]
how can i get all users in a certain group?

**Comment by avenirer** [comment]
Did you by any change managed to read the manual? Especially this part: http://benedmunds.com/ion_auth/#users ?

**Comment by Tjoosten** [comment]
@benedmunds this seems like a personal help request. @avenirer helped the guy out. So maybe we can close this issue

**Comment by benedmunds** [comment]
Agreed.
