### ISSUE TITLE
Maintain login on iOS Safari

### ISSUE THREAD

**Issue by mikegraham00** [benedmunds/CodeIgniter-Ion-Auth#840]
Not sure if this is the right place to ask this question, but I've searched high and low for the answer everywhere else with no success.

Building a web-based application that will be accessed through a QR code scanner. If user scans a code and is not logged in, they are prompted to login. This works fine. However, if they scan another code it opens a new Safari browser tab/window and they are asked to login again. Is there any way that you know of to maintain the Ion Auth login cookie across multiple mobile Safari windows?

**Comment by benedmunds** [comment]
You'd probably be best to ask on StackOverflow or the CodeIgniter forums about how to persist the CI session.  It's not Ion Auth specific but related to the CI session and cookie handling.
