### ISSUE TITLE
register() Function Does Not Apply Username

### ISSUE THREAD

**Issue by GazmanDevelopment** [benedmunds/CodeIgniter-Ion-Auth#843]
When running the register function, the Username field is left blank.  I have confirmed the variable used does actually store the username by dumping it just prior to using it.  All other fields are added without issue.  

Running:
Ubuntu 14.04.2 LTS
Apache 2.4.7
PHP: Version 5.5.9-1ubuntu4.11
```
// Load the information from the POST request
$first_name = $this->input->post('first_name');
$last_name = $this->input->post('last_name');
$username = $this->input->post('user_name');
$email = $this->input->post('user_email');
$level = $this->input->post('user_level');
$password = $this->input->post('new_password');
$password_check = $this->input->post('check_password');

// Setup additional information ready to be added to the database
$group = array($level); 
$additional_data = array(
	'first_name' 	=> $first_name,
	'last_name' 	=> $last_name);

// Add the new user to the database
$user_id = $this->ion_auth->register($username, $password, $email, $additional_data, $group);```

**Comment by benedmunds** [comment]
Whats the output the dump?

What the DB query output?

**Comment by Siente** [comment]
In my opinion Line 908 in Ion_auth_model.php should be changed from
$this->identity_column   => $identity,
to
'username'   => $identity,

**Comment by avenirer** [comment]
@benedmunds the problem, in my opinion is with the fact that the controller doesn't enforce the filling of the username and allows the users to let it unfilled. So, we either
- make sure that, if "username" field is set as the identity column, to let the library try to create a username by uniting first name with last name... or...
- we enforce the filling of a username field in the register form.

It's your choice, and depending on this, with your approval, I will try to change the library, and/or model.

**Comment by benedmunds** [comment]
I'd say we just add validation to enforce it.  If there is a form field it should be required. and then in userland people can have different implementations of the library.

**Comment by GazmanDevelopment** [comment]
Hi Ben, My apologies for not responding earlier - I've been down with a cold.  I can get you the information, but I like your last suggestion.

**Comment by russ-ab** [comment]
@Siente worked like a charm!

**Comment by Noushid** [comment]
How to Change `users.password` TO `**user.xx_password`**
