### ISSUE TITLE
Still logged in after closing browser - Codeigniter or Ion Auth issue?

### ISSUE THREAD

**Issue by dualhub** [benedmunds/CodeIgniter-Ion-Auth#844]
Hi Ben,

Sorry if this isn't anything to do with Ion Auth, but I'm struggling with what appears to be the default behaviour of either CI or Ion Auth in that when a browser is closed down and reopened, the user remains logged in. 

I've set $config['remember_users'] to FALSE in the Ion Auth config but it doesn't appear to make any difference. 

Is continuing to be logged in normal behaviour for web apps these days? Worried about users not clicking 'log out' when on a public computer.

Cheers

Jim

**Comment by avenirer** [comment]
Could you tell us the version of the CodeIgniter?

**Comment by dualhub** [comment]
@avenirer It is Codeigniter 3.0

**Comment by soundiver** [comment]
Hello I have same problem...

**Comment by benedmunds** [comment]
This is an issue with the CI session config, see thread here: http://stackoverflow.com/questions/14359806/why-codeignitor-does-not-finish-the-session-after-closing-the-browser

**Comment by avenirer** [comment]
Could you show us the configuration for your sessions?

**Comment by soundiver** [comment]
Thank you for your answers. I tried to add $config['sess_expire_on_close']  = TRUE; but doesn't work for me. Maybe is a problem of cofiguration my local wamp server?

My configuration for sessions (before add <i>sess_expire_on_close</i>):
$config['sess_driver'] = 'database';
$config['sess_save_path'] = 'ci_sessions';
$config['sess_cookie_name'] = 'ciapp_session';
$config['sess_expiration'] = 7200;
//$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;

**Comment by soundiver** [comment]
Now I've modified this row:

$config['sess_expiration'] = 0;  /* before was 7200 */

And now if I close the browser, the session is killed and If I reopen  I'm not logged
