### ISSUE TITLE
I dont think this one work.

### ISSUE THREAD

**Issue by aa6my** [benedmunds/CodeIgniter-Ion-Auth#846]
$group = array('3'); 
$this->ion_auth->register($username, $password, $email, $additional_data, $group);

Even you try to register this user in group 3. But ion model will make it 2. Depends on what u set in ion_auth config. So i assume this ion_auth cannot register base on group more than 2.

Group.
1. admin
2. moderator
3. user

**Comment by avenirer** [comment]
It works in my tests...
