### ISSUE TITLE
Issue with codeignitor 3.0.0

### ISSUE THREAD

**Issue by manojmaurya** [benedmunds/CodeIgniter-Ion-Auth#848]
Thanks for your Auth library, it's made coding fast & easy for me.

I made an application with codeignitor 3.0 with Ion-Auth library. It was working fine on my local xampp server. But now i moved to godaddy shared hosting server it is showing me message:
-----------------------------------------------
A PHP Error was encountered
Severity: Warning
Message: mkdir() [function.mkdir]: No such file or directory
Filename: drivers/Session_files_driver.php
Line Number: 117
-------------------------------------------

I have made following changes on godaddy server:
Ion-Auth Library:
controller/auth.php -----> controller/Auth.php
model/ion_auth_model.php  ---->  model/Ion_auth_model.php

config/Config.php
$config['index_page'] = 'index.php';
$config['uri_protocol']	= 'QUERY_STRING';

And also add .htaccess file:
----------------------------------
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php?/$1 [L]
----------------------------------

You can check here error message --> http://demo.websiteadda.in/index.php?auth

Am i doing anything wrong because i cehcked everything seems fine? Please help me to resolve this issue.

Thanks & Regards
Manoj

**Comment by avenirer** [comment]
make sure the sessions directory (or the directory that you've set up in the config of your CI3 for keeping the sessions) is writable.

**Comment by manojmaurya** [comment]
Thankyou Avenirer, I tried yesterday same soultion but i didn't get success but today i did same thing again according to your answer and it is working now :). You are lucky for me.
Thankyou again.

Regards
Manoj
