### ISSUE TITLE
Custom logout message not showing up

### ISSUE THREAD

**Issue by Urastor** [benedmunds/CodeIgniter-Ion-Auth#849]
Hey Ho,

if I want to show a custom logout message after calling the logout method of IonAuth, the flashdata, which is stored in the session, disappeared.

Probably it's because the logout methods regenerates the session, but I call the session-method afterwards:

```php
public function logout()
{
    $this->ion_auth->logout();
        
    $this->session->set_flashdata('message', $this->ion_auth->messages());
    redirect(base_url('admin/login'));
}
```

**Comment by benedmunds** [comment]
yea, sessions dont commit until the next refresh in CI.  Might be best to add a URL var for passing that.
