### ISSUE TITLE
Help Me : A Database Error Occurred

### ISSUE THREAD

**Issue by MyHPPY** [benedmunds/CodeIgniter-Ion-Auth#850]
I'am beginner use CodeIgniter Ion Auth in Codeigniter 3. And my problem to access http://localhost/ion

> Error Number: 1064

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `id` = '8d7db3ee05bdc9c149c2c8004c06dc4c3574434c'' at line 2

> SELECT `data` WHERE `id` = '8d7db3ee05bdc9c149c2c8004c06dc4c3574434c'

> Filename: libraries/Session/drivers/Session_database_driver.php

> Line Number: 160

Please help me

**Comment by avenirer** [comment]
I think this is actually a problem coming from the configuration of the CodeIgniter and not from IonAuth. Did you set the sessions correctly?

**Comment by MyHPPY** [comment]
Where I configuration session of the CodeIgniter?

**Comment by avenirer** [comment]
This is an entirely other subject...

**Comment by MyHPPY** [comment]
Please help me.
I do not know the location of faults

**Comment by ghermans** [comment]
You can find your solution by reading the manual!  http://www.codeigniter.com/user_guide/libraries/sessions.html

**Comment by MyHPPY** [comment]
My configuration in config.php
```php
$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'login_attempts';
```

**Comment by avenirer** [comment]
you are still not reading the manual...

**Comment by Tjoosten** [comment]
RTFM

**Comment by heaversm** [comment]
Way to scare off yet another much needed female programmer guys. If everything was solved by reading the manual we would have no need for the "issues" section of github.

**Comment by benedmunds** [comment]
@MyHPPY it would be better if you could ask these type of questions on the CodeIgniter Forums or StackOverflow since this is mainly meant for issues with the library and not general development questions.

Thanks and best of luck finding help!

**Comment by avenirer** [comment]
Don't worry, @MyHPPY we still love you and if you ever need help with this particular library we will gladly help. It's ok now @heaversm ?

**Comment by heaversm** [comment]
Yes!
