### ISSUE TITLE
Implementing Like Clause inside ion auth model

### ISSUE THREAD

**Issue by Brostin08** [benedmunds/CodeIgniter-Ion-Auth#851]
I want to display in a view a list of groups with name having  the string 'section' followed by any characters. So I am modifying a replicated function of group() inside ion_auth_model like this:
```
public function groupfilter($pattern = NULL)
	{
		$this->trigger_events('group');

		if (isset($pattern))
		{
		$this->where($this->tables['groups'].'.name', $IDONTKNOWWHATTOPUTHERE);
		$this->like(NULL,$pattern);
		
			
		}

		return $this->groups();
	}
```
I echoed that query and resulted to:

SELECT * FROM `groups` WHERE `name` IS NULL

It seems that the LIKE clause isn't hooking up with the query...
How would I produced the desired output?

**Comment by benedmunds** [comment]
I think you want this:


public function groupfilter($pattern = NULL)
    {
        $this->trigger_events('group');

        if (isset($pattern))
        {
	        $this->like($this->tables['groups'].'.name', $pattern);
        }

        return $this->groups();
    }

**Comment by Brostin08** [comment]
Using the above code gives this query:
```
SELECT * FROM `groups` 
```

Controller:
```
public function index()
  {
    $this->data['page_title'] = 'Groups';
   // $this->data['groups'] = $this->ion_auth->groups()->result();
    $this->data['groupsections'] = $this->ion_auth->groupfilterbyname('%section%')->result();
    $this->data['query'] =  $this->db->last_query();
    $this->render('admin/Groups/list_groups_view');
  }
```
 View:
```
            <div class="col-lg-12" style="margin-top: 10px;">
              <?php
              if(!empty($groupsections))
              {
                echo '<table class="table table-hover table-bordered table-condensed">';
                foreach($groupsections as $group)
                {
                  echo '<tr>';
                  echo '<td>'.$group->name.'</td><td>'.$group->description.'</td><td>'.anchor('admin/Groups/edit/'.$group->id,'<span class="glyphicon glyphicon-pencil"></span>');
                  if(!in_array($group->name, array('admin','members'))) echo ' '.anchor('admin/Groups/delete/'.$group->id,'<span class="glyphicon glyphicon-remove"></span>');
                  echo '</td>';
                  echo '</tr>';
                }
                echo '</table>';
              }
            ?>
            </div>
            <div class="col-lg-12" style="margin-top: 10px;">
              <?php
              echo $query;
            ?>
            </div>
```

**Comment by avenirer** [comment]
You have here ```$this->data['groupsections'] = $this->ion_auth->groupfilterbyname('%section%')->result();```, but I think you should have this: ```$this->data['groupsections'] = $this->ion_auth->groupfilterbyname('section')->result();```, although I am not sure this will resolve your problem.

**Comment by Brostin08** [comment]
Hi Avenir,

I have tried but your proposed solution hasn't resolved the problem.

I think the function like() isn't hooking up with the query. Maybe a problem with the trigger_events() function?

other SQL Clauses are hooking up (e.g order_by() , limit()) correctly. Maybe we could reopen this issue?

**Comment by avenirer** [comment]
Hello @Brostin08, I don't know if this solves it, but could you try to change some lines into your ion_auth_model.php? I am reffering to the lines 1330-1338. Change from this:

```php
if (isset($this->_ion_like) && !empty($this->_ion_like))
{
	foreach ($this->_ion_like as $like)
	{
		$this->db->or_like($like);
	}
	$this->_ion_like = array();
}
```
...to this:
```php
if (isset($this->_ion_like) && !empty($this->_ion_like))
{
	$i = 1;
	foreach ($this->_ion_like as $like)
	{
		if($i==1)
		{
			$this->db->or_like($like);
		}
		else
		{
			$this->db->or_like($like);
		}
		$i++;
	}
	$this->_ion_like = array();
}
```
I am sorry, but there is no way I can test this...

**Comment by Brostin08** [comment]
I'm sorry avenir it is not working.

However,I used this:

    $this->db->like($this->tables['groups'].'.name', $pattern);

directly in the groupfilterbyname() function, and it works, the string $pattern should not have '%' or '_' characters to ensure the query will not break.

Is there any bad effects to this?

OT:  Thank you Avenir for your codeigniter tutorials, serves as my project's skeleton! And Ben for the auth system, very simple to use!
