### ISSUE TITLE
Hook -> calling a method from a separate library

### ISSUE THREAD

**Issue by digitaloutback** [benedmunds/CodeIgniter-Ion-Auth#852]
An example hook I am trying to do that will use a method from another class. How can I get this working?

```
$this->ion_auth->set_hook('post_login_successful', 'hook_name', $this->language, 'process_user_language', array());
```

**Comment by benedmunds** [comment]
Here's a good tutorial on using hooks in Ion Auth http://codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth

**Comment by digitaloutback** [comment]
Thanks.. but I have seen this article, but it doesn't advise what to put in class/method if for example i am using a function from a different class.

**Comment by benedmunds** [comment]
Post the code surrounding this set_hook call and also the class you're calling from the hook.
