### ISSUE TITLE
Ion-Auth Codeigniter 3 compatibillity - No login or password reset.

### ISSUE THREAD

**Issue by howzit** [benedmunds/CodeIgniter-Ion-Auth#853]
Hi, I am very interested in configuring and adapting Ion-Auth to work with my system.
I am busy updating a procedural system into Codeigniter 3

 and followed the instructions very carefully but found errors and cannot get it to work.
It seems, when loading domain.com/auth/login it simply do not log in?
I even tried to reset the Admin password, got the email, but when clicking on the link and entering the two new passwords fields, i get only the following error: An Error Was Encountered
This form post did not pass our security checks.

I spent hours trying to figure this out but no joy.

I read up somewhere someone was mentioning to disable the $config['csrf_protection'] in the app and enable it in the CI config.php file and even description on how and where to do it.
My problem is that these descriptions actually are either outdated due to Ion-Auth updates or I am missing the point as the line they referring to, is changed or different from the explanation.

I am including my config/ion_auth.php and controller/Auth.php files for reference in case I missed anything? ---> Ok was trying but for some reason cannot attach the files in txt or docx?!

**Comment by avenirer** [comment]
Well... we can't help if we don't know what the error is, can we? can we see the error? or something?... anything?...

**Comment by abuzubair** [comment]
The same problem occur with me....

**Comment by avenirer** [comment]
That is very helpful to know @abuzubair... and the "...." will really help us understand where the error is.
