### ISSUE TITLE
how to get inserted id of last registered member

### ISSUE THREAD

**Issue by xensor** [benedmunds/CodeIgniter-Ion-Auth#855]
[code]
public function user_profile( $groups = array() )
	{

		$this->db->insert('user_profile',$groups);
	}

[/code]

i am trying to make a model function that will populate the user_profile table with the id of the registered member when they register. 

the user_profile table contains the user details like (display,first, last, age, location) i have it set up to get the details just need ot know how to get the inserted_id of the registered member. 

i am not sure if this: $this->db->insert_id() will work or not

**Comment by Brostin08** [comment]
Hi. I have this similar issue where I need to get the id of the newly registered user (if that is how you want it done).

Ion-auth will return the id of the registered user in this function:

````
$id= $this->ion_auth->register($username, $password, $email, $additional_data, $group_ids);
````
