### ISSUE TITLE
user($id) by company

### ISSUE THREAD

**Issue by lostlian** [benedmunds/CodeIgniter-Ion-Auth#856]
Hi,

Im trying to get a user but i want to make sure only brings it if it is in the current company. I was seeing that there is an event called extra_where in users() but i couldnt find any function called extra_where. 

Where can i add or customize this in users() without modifing the model

```php
$this->trigger_events('extra_where');

		// run each where that was passed
		if (isset($this->_ion_where) && !empty($this->_ion_where))
		{
			foreach ($this->_ion_where as $where)
			{
				$this->db->where($where);
			}

			$this->_ion_where = array();
		}
```

**Comment by benedmunds** [comment]
Something like this should do it:

     $users = $this->ion_auth->where('company_id', $company_id)->users()->result();

**Comment by lostlian** [comment]
Thanks, I finally did this solutions but for this to work needed column 'company' id to exist in the users table. At the it was the best solution. Thanks a lot
