### ISSUE TITLE
Changing hash_method, will users need to reset passwords?

### ISSUE THREAD

**Issue by paulcanning** [benedmunds/CodeIgniter-Ion-Auth#857]
I am looking to change the hash_method from SHA1 to BCRYPT for increased security.

However, I already have a few users in my database.

If I go and change the hash_method, will the users be able to log in as usual, or will they need to do a password reset in order to have a BCRYPT password generated?

**Comment by benedmunds** [comment]
Hey Paul,

If you did this they would need to do a password reset.  You could also write a script to programmatically trigger the reset for everyone.

**Comment by paulcanning** [comment]
How do you trigger a global reset? Would be much appreciated!

**Comment by benedmunds** [comment]
You would just write a script that queries all the users, then loops through them and calls password reset for each one so they would receive the email.

**Comment by netsenior** [comment]
does it apply for the inverse situation? I mean changing from BCRYPT to SHA1 ... the development server php version is >5.3 while the production server is 5.2...

**Comment by benedmunds** [comment]
Yes, although I definitely wouldnt recommend downgrading to SHA1.
