### ISSUE TITLE
Carry over session data through remembered logins

### ISSUE THREAD

**Issue by russ-ab** [benedmunds/CodeIgniter-Ion-Auth#858]
There's a way to carry over all data from the old session when a "login_remembered_user()" is executed?

**Comment by benedmunds** [comment]
Im not sure what you mean.  Explain your use case more please.

**Comment by russ-ab** [comment]
If I:
```php
set_userdata('test_data', 'bla bla bla')
``` 
It will persist to the session until the cookie expires.

When the cookie expires the library will do the verification to "login_remembered_user()" if pass, it will create a new session using the data:


```php
//Ion_auth_model.php 1721
$session_data = array(
     'identity'     => $user->{$this->identity_column},
    $this->identity_column    => $user->{$this->identity_column},
    'email'    => $user->email,
    'user_id'    => $user->id, //everyone likes to overwrite id so we'll use user_id
    'old_last_login'    => $user->last_login
);

$this->session->set_userdata($session_data);
```
What about the 'test_data'? There's a way to retrieve from that session (old)?

**Comment by benedmunds** [comment]
If you saved the information to the user's record or another related table you could this repopulate the session with the data.  This will be a slight performance hit though.
