### ISSUE TITLE
login attempts question

### ISSUE THREAD

**Issue by nplaviola** [benedmunds/CodeIgniter-Ion-Auth#859]
I have the following configurations set:
$config['track_login_attempts']       = TRUE;              
$config['track_login_ip_address']     = TRUE;
$config['maximum_login_attempts']     = 5;  
$config['lockout_time']               = 600;  

It works fine in my application, recording the user identity and ip address, and clearing them away once the user logs in. However, if an attempt to login is made with multiple user names, upon a successful login none of the previous attempted user identity rows are deleted. This leads the function get_attempts_num() to report back >0  even after a successful login. I assume because it's checking for ip addresses and not also the user identity. It also restricts the number of login tries to 5 - the number of other existing user identities in the login attempts table.

I suppose then my question is, why not clear away all attempts made from a certain ip address upon the successful login by any user on that ip address?

**Comment by benedmunds** [comment]
Actually it seems that the better solution would be to update get_attempts_num to check identity as well.  Thoughts?

**Comment by nplaviola** [comment]
Yeah, that makes more sense. You'd still have a record of those other attempts which could be useful.

**Comment by nplaviola** [comment]
It works beautifully now, thanks.

**Comment by benedmunds** [comment]
Can you send a PR with that change?  That'd be helpful to others as well.

**Comment by nplaviola** [comment]
Yep, here you go! https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/860

**Comment by benedmunds** [comment]
Merged.  Thank you!

**Comment by avenirer** [comment]
So... now, if I want to break a co-worker's pass I try to login 4 times, I log my username and then I try again. Cool :)

**Comment by benedmunds** [comment]
Not sure I follow @avenirer ?  It's updated to match against IP and Username now where previously it was inconsistently only matching against IP in one part of the logic.

**Comment by danielslim** [comment]
I get what @avenirer is saying. co-workers in the same network likely to have same IP, so if the login fail limit is 5, then i can use co-worker username try for 4 times, clearing IP failed attempt count by using my username, then try the co-worker login repeat it util i crack it? 

But since clean_login_attempts doesn't clear all IP address, it only reset ip + login so you can't just reset all failed IP with a successful login... otherwise it would be security issue.

**Comment by benedmunds** [comment]
Agreed.  This was an issue previously but isn't anymore.

You agree @avenirer ?

**Comment by avenirer** [comment]
Yes. It is a good idea. :+1:

**Comment by nplaviola** [comment]
One thing I'd like to add:

If a user reaches their max login attempts, say 5, and they wait until after the lockout time has passed, they will only have 1 attempt to login again before being locked out. This is because the function `is_time_locked_out($identity)` looks at the last login attempt time AND checks if the max login attempts have been exceeded.
```php
public function is_time_locked_out($identity) {

		return $this->is_max_login_attempts_exceeded($identity) && $this->get_last_attempt_time($identity) > time() - $this->config->item('lockout_time', 'ion_auth');
	}
```
Since the previous attempts were never cleared by a successful login, they get counted against the user when they attempt to login again.

Is this the intended behavior?

**Comment by benedmunds** [comment]
Hmm yes I believe it should clear that.  Thoughts? @danielslim and @avenirer

**Comment by avenirer** [comment]
@nplaviola Actually, they are not locked out, they can only try again after waiting the number of seconds mentioned in the configuration file. That means that after the maximum number of failed logins the user has to wait 600 seconds between the next tries.

**Comment by avenirer** [comment]
Suppose we have exceeded max login attempts ($this->is_max_login_attempts_exceeded($identity) = TRUE), less than a minute ago. If we try to login in less than 600 seconds again ($this->get_last_attempt_time($identity) > time() - $this->config->item('lockout_time', 'ion_auth') = FALSE), a FALSE will be returned, which means you are not allowed to login unless you wait 600 seconds before last attempted login.

**Comment by nplaviola** [comment]
@avenirer Okay, that makes sense. That setup will work for me, I just wasn't sure if a user's attempts were meant to be reset or not after the lockout period expired.
