### ISSUE TITLE
Social login

### ISSUE THREAD

**Issue by ramigb** [benedmunds/CodeIgniter-Ion-Auth#861]
Is there a way to be able to login without password? this will be used internally by the application when a callback from the provider is sent! so if the provider user id and name match the one in the database the user is logged in, i'm using HybridAuth to take care of this.

**Comment by benedmunds** [comment]
There's not a built in way to do that.  In the past I've used the oauth token or similar but you'll definitely have to code a work around

**Comment by ramigb** [comment]
@benedmunds thank you for the quick reply and thank you for the great library, i hope this feature gets implements in any future releases, i will extend the lib and see what i can do.
