### ISSUE TITLE
Default group not set in register() when groups are specified

### ISSUE THREAD

**Issue by komirad** [benedmunds/CodeIgniter-Ion-Auth#862]
According to documentation http://benedmunds.com/ion_auth/ on the register() method

> $group = array('1'); // Sets user to admin. No need for array('1', '2') as user is **always set to member by default**

This not reflected in the code on ion_auth_model.php

> 		// add in groups array if it doesn't exits and stop adding into default group if default group ids are set
>
> 		if( isset($default_group->id) && empty($groups) )
> 		{
> 			$groups[] = $default_group->id;
> 		}
> 
> 		if (!empty($groups))
> 		{
> 			// add to groups
> 			foreach ($groups as $group)
> 			{
> 				$this->add_to_group($group, $id);
> 			}
> 		}

**Comment by benedmunds** [comment]
I believe this was changed at some point.  Would you mind sending a PR for the documentation to update this?

**Comment by avenirer** [comment]
@benedmunds Actually I think there is something wrong somewhere else, as in the userguide html (on Github) that part is not in there, but only on the site where the documentation is found.

**Comment by benedmunds** [comment]
This was out of sync with the live site.  I just updated it, thanks!
