### ISSUE TITLE
Unexpected characters in controllers/auth.php

### ISSUE THREAD

**Issue by semihcosu** [benedmunds/CodeIgniter-Ion-Auth#865]
I've had an error message about this when I was trying to reset my password. This bit of the code was causing it (between lines 480-486) :

            $this->data['identity'] = array(
                'name'  => 'identity',
                'id'    => 'identity',
                'type'  => 'text',
                'value' => $this->form_validation->set_value('identity
                '),
            );

**Comment by avenirer** [comment]
what error message was that?

**Comment by semihcosu** [comment]
I didn't note the error before I fixed it because it looked obvious in here, and also the error was pointing the same line:

    $this->data['identity'] = array(
            'name'  => 'identity',
            'id'    => 'identity',
            'type'  => 'text',
            'value' => $this->form_validation->set_value('identity
            '),
           --^                                                  --^
        );

But it was something like `Parse error: syntax error, unexpected ')', expecting '=' in ...\auth.php on line 538` (I've added some more codes at the start of auth.php, that's why line numbers don't match. But it was pointing exactly the same line)

**Comment by pawelkg** [comment]
Unclosed quotation marks and brackets at line 484 in controllers/auth.php.
I don't have editor right now to fix it.

**Comment by benedmunds** [comment]
Fixed, thanks!
