### ISSUE TITLE
Reset Password Question

### ISSUE THREAD

**Issue by iamthestreets** [benedmunds/CodeIgniter-Ion-Auth#867]
Hi,

I am a little confused at what this `$this->ion_auth->reset_password` is calling in the Auth controller. To me it seems that it is calling a `reset_password` function in the ion_auth library, but the `reset_password` function does not exist in the ion_auth library and only the model ion_auth_model.

So what is this actually calling the library or model?  If it is actually calling the model how? shouldn't it look like this: `$this->ion_auth_model->reset_password`.

Thanks!

**Comment by benedmunds** [comment]
The library passes any calls made it methods that dont exist in it to the model.  This allows us to override methods as needed.
