### ISSUE TITLE
trigger_events and set_hook confusion

### ISSUE THREAD

**Issue by iamthestreets** [benedmunds/CodeIgniter-Ion-Auth#868]
Are either of these two functions actually being used or called anywhere? Based on what I can see these are not currently being used anywhere. I have read and tried to understand what they are doing, but can't seem to understand it.

If they are being used can you explain how? The documentation is not helpful as it does not relate to the code that ion auth is displaying.

**Comment by benedmunds** [comment]
Jeff has a great blog post on using hooks here:
http://codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth

**Comment by iamthestreets** [comment]
Thanks, but this article does not explain how you are using it. I don't see any hooks being set so I just want to know how they are being used in ion auth. For example is this being used `$this->trigger_events('pre_change_password');`? If yes, what is it actually doing?

**Comment by benedmunds** [comment]
That sets a trigger, which can then be hooked into.  Ion Auth isn't using that trigger directly but if you setup a hook into it that hook will then be triggered.  Make sense?

**Comment by iamthestreets** [comment]
ooohh got it. I feel like an idiot now lol. Thanks for the clarification.
