### ISSUE TITLE
No syncronisation between github and manual

### ISSUE THREAD

**Issue by avenirer** [benedmunds/CodeIgniter-Ion-Auth#869]
The index.html of the user guide on github is still not syncronised with the user guide from here: http://benedmunds.com/ion_auth/

How is this syncronisation done?

**Comment by benedmunds** [comment]
I just manually copy section over when I see a PR.  The code is slightly different to get it to work within my site.  If you can point out whats wrong I'll update it.

**Comment by avenirer** [comment]
@benedmunds for example the create_user() method doesn't appear on the website. Also in the login() method we've changed "Username" to "Identity"... These are the things I noticed that made me write the issue.

**Comment by benedmunds** [comment]
Updated.  Thanks dude!
