### ISSUE TITLE
forgotten password complete email

### ISSUE THREAD

**Issue by iamthestreets** [benedmunds/CodeIgniter-Ion-Auth#872]
Hi,

I noticed there is a function in the `Ion_auth` library called `forgotten_password_complete`, but it does not seem to be used. Also, if it were to be used it would not work unless I'm missing something. The function requires the forgot password code to passed `public function forgotten_password_complete($code)` , but the code is removed once the password has been reset.

So I guess my first question is does the `forgotten_password_complete` function get used?
If no would i need to completely rewrite it since the forgot password is being removed before I can call it?

**Comment by avenirer** [comment]
Indeed it seems that that function is no longer used. Maybe it was used in the passed and now it's kept for compatibility reasons @benedmunds ? Shouldn't we delete it? But what do you mean @iamthestreets  by "I need to completely rewrite it"? Do you need to do something special after someone resets the password?

**Comment by iamthestreets** [comment]
I want to send an email letting the user know their password has been changed. There could be many reasons why you should do this, the most important is to make sure they are aware of the change just incase it wasn't them. 

What I mean by rewriting is the current `forgotten_password_complete` function requires you to pass the forgotten password code to the function to trigger the email to be sent, but by the time the change is complete to code no longer exists. Also, it is designed to send the actual password in an email which should not be done for security reasons. 

If I have to rewrite it myself I am ok with that I just want to make sure I'm not missing something and I would also suggest to delete it if it is no longer used or rewrite it.

Thanks!

**Comment by benedmunds** [comment]
Yea it's not used anymore but older versions did so kept it for BC.

@iamthestreets you'd probably be best using a hook for this: http://codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth

**Comment by iamthestreets** [comment]
I somewhat understand the hooks and trigger events, but i still don't see the benefit of using it. I also don't know how it would work for me in this case. When/where do I set the hook? In the Auth `reset_password()` function? Also, as I mentioned before the code needs to be passed to the `forgotten_password_complete()` function so correct me if i'm wrong, but this function will not work if I want to wait for the reset to be completed because the code will be removed.

Can you help with an example?

**Comment by benedmunds** [comment]
You'd be best just writing a completely new function for sending that confirmation email, then call it after activation (via a hook) to send the email.
