### ISSUE TITLE
(int) problem in model when user_id colum is bigint

### ISSUE THREAD

**Issue by skobeo** [benedmunds/CodeIgniter-Ion-Auth#875]
in add_to_group function in model, using (int)$user_id failed when user_id column is big int. Removed (int) is ok.
Seems to be same in remove_from_group function.

Message is Duplicate key in users_groups cause php (int) is limited to 2147483647

**Comment by benedmunds** [comment]
PHP doesn't support bigints, so it's probably casting it to a float.  This should be fine.  Would you mind sending a PR to change the (int) to (float) and test your use case please?

**Comment by pawelkg** [comment]
Integer in 64bit system will have different range. We need to put number to DB, so why not do something like this: $this->join['groups'] => $group_id + 0 ?

**Comment by benedmunds** [comment]
Not sure why that would be a better solution.  Can you explain?

**Comment by pawelkg** [comment]
Well, I think there's no. It's just another way to solve this. We are going to have int when it's available, and float otherwise.

**Comment by benedmunds** [comment]
This has been updated to use floats.
