### ISSUE TITLE
Avenir ion auth tutorial and modifications for members only access

### ISSUE THREAD

**Issue by absmugz** [benedmunds/CodeIgniter-Ion-Auth#876]
I followed Avenir tutorial on hoe to run ion auth on the following link :

http://avenir.ro/authentication-system-with-ion-auth-and-ci3/lets-install-ion-auth-library/

All the code I created is on the following repo : 

https://github.com/absmugz/ion_auth_installation

I then did my own modifications to create in my_controller a Members_Controller, please look what I have done in home controller, members controller and Members_Controller in my_controller, it all works but is this the right way to code this ?

What I achieved and wanted is : 
1.Have a admin area only - this is achieved with Auth_Controller and the tutorial in My_controller. This is the cms part for admin users only
2.The tricky part, Have a home page where all members can access but when they try to access other pages they have to log in, the home controller extends the CI_controller but the rest of the members only pages extend Members_Controller.

**Comment by avenirer** [comment]
Please. This has nothing to do with Ion Auth. Do not post such issues on this github repo.

**Comment by benedmunds** [comment]
@absmugz I'd recommend posting this on StackOverflow or the CodeIgniter forums.  This area is meant for issues with the library itself.  Thanks!
