### ISSUE TITLE
Setting "Remember Me" bypasses additional logic checks

### ISSUE THREAD

**Issue by paulcanning** [benedmunds/CodeIgniter-Ion-Auth#877]
For my user login, I have to do a lot of additional logic checks, as a user can belong to a "company" which in turn belongs to an "organisation".

All 3 have an active boolean flag.

The user flag is handled by ion_auth, but the company and organisation flags, I am handling myself.

To check, I am first actually logging the user in (if they are active) and then checking the other flags.

If one of the flags is set to inactive, I am logging the user out, setting some flashdata and then redirecting them, using "redirect(location, refresh)".

This works fine, unless the "Remember Me" flag is set.

If the flag is set to 1, to remember the user, my additional checks are ignored and the user can log in, despite the company they belong to being inactive.

So, how can I fix this? Is it an ion_auth bug, working as intended or what?

Should I be using custom callbacks somehow? (Not sure how in this case, as I need to log the user in, to get their ID to cross reference which company they belong to, to check if it is active)

**Comment by avenirer** [comment]
I think whenever you change something to the user like those flags, you can delete the "remember_code" from the users table. This way the remember me won't work anymore...

**Comment by benedmunds** [comment]
You could also use the pre_remember_user hook to check before it runs.

**Comment by paulcanning** [comment]
Hey Ben, how exactly would I use that hook? Do I need to do something before or after I call the logout method?

**Comment by benedmunds** [comment]
Here's a good tutorial on using hooks:

http://codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth

**Comment by paulcanning** [comment]
If I need to unset the "Remember Me" flag, should it not be post_remember_me maybe? So I can remove it after it sets, for a specific condition like I have above?

**Comment by benedmunds** [comment]
This is the logic that checks for a valid remember session, so a pre is what you want.
