### ISSUE TITLE
Using a third party email service like Postmark

### ISSUE THREAD

**Issue by nathanpitman** [benedmunds/CodeIgniter-Ion-Auth#878]
Is there currently any way to have Ion Auth route it's email via a third party email service like Postmark, or plans to implement such a feature?

**Comment by benedmunds** [comment]
You can create a MY_Email class to overwrite the default CodeIgniter Email class

**Comment by nathanpitman** [comment]
Why didn't I think if that. Wood. Trees. Head. Desk. 

Thanks Ben! :D
