### ISSUE TITLE
Cookies identity and remember_me not create on chrome and opera

### ISSUE THREAD

**Issue by sergecodd** [benedmunds/CodeIgniter-Ion-Auth#880]
Hi 
I use the Ion-Auth on CodeIgniter 2.2 
When users login the identity and remember_me cookies are no create for Chrome and Opera Browsers. 
But every thing is good with Firefox browser 
How can i over comme this probleme ? 
Thanks

**Comment by benedmunds** [comment]
This must be an issue with the CI class, please post on the CI forums.

**Comment by sergecodd** [comment]
Hi to all thanks the problem was with the CI config file 
This is the configaration that solve the problem : 
$config['sess_cookie_name']		= 'cisession';  // no space or special caracter


$config['cookie_prefix']	= "";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;
