### ISSUE TITLE
failed reset password when change identity type

### ISSUE THREAD

**Issue by dexterns88** [benedmunds/CodeIgniter-Ion-Auth#881]
When change $config['identity']  to use username 
$config['identity'] = 'username';

Reset password doesn't work , after submit form got message "The Identity field is required".

**Comment by benedmunds** [comment]
Might need a little more help troubleshooting.  Are you passing the username on the reset pass form?

**Comment by dexterns88** [comment]
yes , but they return error " The Identity field is required."

In 'form_validation' you checking email or identity field , but every time field name is 'email', We need to create form field name according to selected authentication type same as when validating form.

```php
if ($this->config->item('identity', 'ion_auth') != 'email') {
      $this->form_validation->set_rules('identity', $this->lang->line('forgot_password_identity_label'), 'required');
} else {
      $this->form_validation->set_rules('email', $this->lang->line('forgot_password_validation_email_label'), 'required|valid_email');
}

if ($this->form_validation->run() == false) {
      // setup the input
      $this->data['email'] = array('name' => 'email',
        'id' => 'email',
        'class' => 'form-control'
);
```

**Comment by dexterns88** [comment]
I made some change in controller forgot_password(), and after this change everything work fine when change auth type to username.

```php
 if ($this->form_validation->run() == false) {
      // setup the input
     // Create field depending on type of authentication
      if ($this->config->item('identity', 'ion_auth') != 'email') {
        $this->data['email'] = array('name' => 'identity',
          'id' => 'identity',
          'class' => 'form-control'
        );
      } else {
        $this->data['email'] = array('name' => 'email',
          'id' => 'email',
          'class' => 'form-control'
        );
      }

// rest of code 
```

```php
} else {
      $identity_column = $this->config->item('identity', 'ion_auth');
      
     // same here
      if ($this->config->item('identity', 'ion_auth') != 'email') {
        $identity = $this->ion_auth->where($identity_column, $this->input->post('identity'))->users()->row();
      } else {
        $identity = $this->ion_auth->where($identity_column, $this->input->post('email'))->users()->row();
      }
//rest of code

```

**Comment by dexterns88** [comment]
This issue is in Ion Auth 2

**Comment by benedmunds** [comment]
Can you send a PR with the change?

**Comment by dexterns88** [comment]
This is my changed forgot_password() function ,


```php
function forgot_password()
  {
    // setting validation rules by checking wheather identity is username or email
    if ($this->config->item('identity', 'ion_auth') != 'email') {
      $this->form_validation->set_rules('identity', $this->lang->line('forgot_password_identity_label'), 'required');
    } else {
      $this->form_validation->set_rules('email', $this->lang->line('forgot_password_validation_email_label'), 'required|valid_email');
    }

    if ($this->form_validation->run() == false) {
      // setup the input

      if ($this->config->item('identity', 'ion_auth') != 'email') {
        $this->data['email'] = array('name' => 'identity',
          'id' => 'identity',
          'class' => 'form-control'
        );
      } else {
        $this->data['email'] = array('name' => 'email',
          'id' => 'email',
          'class' => 'form-control'
        );
      }

      if ($this->config->item('identity', 'ion_auth') != 'email') {
        $this->data['identity_label'] = $this->lang->line('forgot_password_identity_label');
      } else {
        $this->data['identity_label'] = $this->lang->line('forgot_password_email_identity_label');
      }

      // set any errors and display the form
      $this->data['message'] = (validation_errors()) ? validation_errors() : $this->session->flashdata('message');

      $this->_render_page('auth/forgot_password', $this->data);
    } else {
      $identity_column = $this->config->item('identity', 'ion_auth');

      if ($this->config->item('identity', 'ion_auth') != 'email') {
        $identity = $this->ion_auth->where($identity_column, $this->input->post('identity'))->users()->row();
      } else {
        $identity = $this->ion_auth->where($identity_column, $this->input->post('email'))->users()->row();
      }

      if (empty($identity)) {
        if ($this->config->item('identity', 'ion_auth') != 'email') {
          $this->ion_auth->set_error('forgot_password_identity_not_found');
        } else {
          $this->ion_auth->set_error('forgot_password_email_not_found');
        }

        $this->session->set_flashdata('message', $this->ion_auth->errors());
        redirect("auth/forgot_password", 'refresh');
      }

      // run the forgotten password method to email an activation code to the user
      $forgotten = $this->ion_auth->forgotten_password($identity->{$this->config->item('identity', 'ion_auth')});

      if ($forgotten) {
        // if there were no errors
        $this->session->set_flashdata('message', $this->ion_auth->messages());
        redirect("auth/login", 'refresh'); //we should display a confirmation page here instead of the login page
      } else {
        $this->session->set_flashdata('message', $this->ion_auth->errors());
        redirect("auth/forgot_password", 'refresh');
      }
    }
  }

```

**Comment by Mblockmus13** [comment]
function forgot_password()
  {
    // setting validation rules by checking wheather identity is username or email
    if ($this->config->item('identity', 'ion_auth') != 'email') {
      $this->form_validation->set_rules('identity', $this->lang->line('forgot_password_identity_label'), 'required');
    } else {
      $this->form_validation->set_rules('email', $this->lang->line('forgot_password_validation_email_label'), 'required|valid_email');
    }

    if ($this->form_validation->run() == false) {
      // setup the input

      if ($this->config->item('identity', 'ion_auth') != 'email') {
        $this->data['email'] = array('name' => 'identity',
          'id' => 'identity',
          'class' => 'form-control'
        );
      } else {
        $this->data['email'] = array('name' => 'email',
          'id' => 'email',
          'class' => 'form-control'
        );
      }

      if ($this->config->item('identity', 'ion_auth') != 'email') {
        $this->data['identity_label'] = $this->lang->line('forgot_password_identity_label');
      } else {
        $this->data['identity_label'] = $this->lang->line('forgot_password_email_identity_label');
      }

      // set any errors and display the form
      $this->data['message'] = (validation_errors()) ? validation_errors() : $this->session->flashdata('message');

      $this->_render_page('auth/forgot_password', $this->data);
    } else {
      $identity_column = $this->config->item('identity', 'ion_auth');

      if ($this->config->item('identity', 'ion_auth') != 'email') {
        $identity = $this->ion_auth->where($identity_column, $this->input->post('identity'))->users()->row();
      } else {
        $identity = $this->ion_auth->where($identity_column, $this->input->post('email'))->users()->row();
      }

      if (empty($identity)) {
        if ($this->config->item('identity', 'ion_auth') != 'email') {
          $this->ion_auth->set_error('forgot_password_identity_not_found');
        } else {
          $this->ion_auth->set_error('forgot_password_email_not_found');
        }

        $this->session->set_flashdata('message', $this->ion_auth->errors());
        redirect("auth/forgot_password", 'refresh');
      }

      // run the forgotten password method to email an activation code to the user
      $forgotten = $this->ion_auth->forgotten_password($identity->{$this->config->item('identity', 'ion_auth')});

      if ($forgotten) {
        // if there were  few errors
        $this->session->set_flashdata('message', $this->ion_auth->messages());
        redirect("auth/login", 'refresh'); //we should display a confirmation page here instead of the login page
      } else {
        $this->session->set_flashdata('message', $this->ion_auth->errors());
        redirect("auth/forgot_password", 'refresh');
      Prompt ("Resolved")

**Comment by lloricode** [comment]
omg sorry i did not seen this. issue
i send  PR for this
#1033 

@dexterns88 , I just modify the ion_auth. check my PR, hmm maybe some one can also enhance the idea.

**Comment by benedmunds** [comment]
I don't believe there is an issue here. We can continue discussion under the PR

**Comment by lloricode** [comment]
@benedmunds ok sir, i will reopen my PR later after my modification again (if i succeed)
