### ISSUE TITLE
Email Delivery

### ISSUE THREAD

**Issue by Majimazuri** [benedmunds/CodeIgniter-Ion-Auth#886]
HI Ben;
Congrats for a good work of Iron Auth;
I have installed iron auth but when resenting password the email set but not delivered; other email outside the Iron auth are delivered well; but I don't know why those of Iron auth are not delivered; please help me because I am  a bit new-bye.

Thanks!

**Comment by benedmunds** [comment]
Make sure you don't have conflicting email config settings in your email config and ion auth config.
And make sure that config matches what you're sending other emails with.

**Comment by Majimazuri** [comment]
Thanks; but I did not get you because my codeigniter instillation it is new; no any customization; 
what config are supposed to be cheeked? 
Thanks again;

**Comment by Majimazuri** [comment]
Oh!
Thanks; now I i have got the solution; I have changed iron_auth.php in config; 
$config['use_ci_email'] = FALSE;
To......TRUE
Thank you again;
