### ISSUE TITLE
Error when calling logout

### ISSUE THREAD

**Issue by sillexo** [benedmunds/CodeIgniter-Ion-Auth#891]
A PHP Error was encountered
Severity: Notice
Message: Array to string conversion
Filename: core/Input.php
Line Number: 410

Codeigniter 3.0

**Comment by benedmunds** [comment]
Is this using a clean Ion Auth install?  and what action did you take to cause this?

**Comment by avenirer** [comment]
Being inside the core directory, and Input.php, this doesn't seem to be related to Ion Auth, but to the way you've set up the controller.

**Comment by sillexo** [comment]
public function logout()
        {
            if ($this->logged_in)
            {
                $this->ion_auth->logout();
                $this->input->set_cookie(array('PHPSESSID' => ''));
            }
            redirect($this->site_url, 'refresh');
        }

**Comment by benedmunds** [comment]
You're using this CI method improperly.  See the docs here: https://codeigniter.com/user_guide/libraries/input.html#using-post-get-cookie-or-server-data

Closing since this isnt an Ion Auth issue.
