### ISSUE TITLE
What to do Next?

### ISSUE THREAD

**Issue by Mblockmus13** [benedmunds/CodeIgniter-Ion-Auth#895]
I need to know what to work on next.

**Comment by Mblockmus13** [comment]
I need to know what to work on.

**Comment by benedmunds** [comment]
Why are you working on anything?  Whats the goal?

**Comment by Mblockmus13** [comment]
i dunno i want to work on something

**Comment by benedmunds** [comment]
Sorry, CI2 is a stable project.  No need for changes.

**Comment by Mblockmus13** [comment]
ok

**Comment by Mblockmus13** [comment]
sorry
