### ISSUE TITLE
Unable to load ion_auth_model.php

### ISSUE THREAD

**Issue by neilfm** [benedmunds/CodeIgniter-Ion-Auth#897]
The ion_auth_model must be Ion_auth_model (ucfirst) in order to work with PHP7.

**Comment by avenirer** [comment]
Actually it has nothing to do with PHP7. This is how CodeIgniter 3 works. Also this is mentioned in the installation instructions of this library.

**Comment by pawelkg** [comment]
In my opinion, since CI 2.x is no longer in development (nor security fix), file names should be as CI 3.x requires. Of course, a note about how to obtain backward compatibility should appear.

**Comment by avenirer** [comment]
Eh... As I remember there is no problem if you capitalize the file names in CI2

**Comment by pawelkg** [comment]
Then what's the problem, to set file names ucfirst, to be compatible with both CI3 and CI2?

**Comment by claide** [comment]
in codeigniter.php file, ucfirst function is being used in the variable $class which requires that the controllers have the first letter capitalized.

`$class = ucfirst ($ RTR-> class); //line 254 and 258`

I noticed this issue while moving files to webserver. But it works smoothly when working in local machine.

**Comment by filjoseph1989** [comment]
Download the latest update and then just copy the Ion_auth_model to the model directory
