### ISSUE TITLE
What is PHP5 Magic?

### ISSUE THREAD

**Issue by Abubaker87** [benedmunds/CodeIgniter-Ion-Auth#899]
Dear Ben.. You say that never use ion_auth_model->method().. Then how should it be called? What do you mean by PHP5 magic?

**Comment by avenirer** [comment]
I guess he is referring to the fact that the model is accessed through the library. If you look inside the library files (lines 95-100) you will see that everything that is called inside the library is verified if it exists inside the ion auth model.

**Comment by antanova** [comment]
If you have a method on the model you want to call, say `ion_auth_model->method()`, then call it as if it was defined on the library, so `ion_auth->method()`. This then uses [a PHP magic method](http://php.net/manual/en/language.oop5.magic.php) (specifically, the `__call` method in the ion_auth.php library file) to make it work.
