### ISSUE TITLE
Moving from mySql to oracle 

### ISSUE THREAD

**Issue by soundiver** [benedmunds/CodeIgniter-Ion-Auth#900]
Hello, I have WAMP in local (MySql) and Ion-Auth works great!

But I moved to Oracle.

In Oracle schemas I have created Uppercase tables (CI_SESSIONS, USERS)
 and fields (EMAIL, etc..) and now I have many issues with case sensitive query. If i understand, all tables and fields in Ion-Auth are in lowercase...

How can I solve?

I'm trying to modify directly the code in Ion-Auth and CI core files (Session_database_driver.php, etc.) but i fear to be wrong 

Thank You

**Comment by benedmunds** [comment]
I'e never used Oracle.  Can you not just set the table names to capitalized?  If not, you'd change this in the ion auth config file.

**Comment by Tjoosten** [comment]
I think there is no support for Oracle @benedmunds
