### ISSUE TITLE
Ion auth hmvc and restful api and phonegap

### ISSUE THREAD

**Issue by absmugz** [benedmunds/CodeIgniter-Ion-Auth#901]
Hi fellow devs, compliments of the season to you all, wish everyone a fantastic dev year.

I want to include ion auth as a module following the hmvc pattern then I want to be able to use the restful api with ion auth and be able to login from a phonegap app, can anyone please guide me through how go about this ?

**Comment by avenirer** [comment]
Just... wow...

**Comment by absmugz** [comment]
I am not asking for code, I am just looking for a brief and precise guideline as I am still intermediate

**Comment by Tjoosten** [comment]
@avenirer is this a code request or is it just me?

**Comment by absmugz** [comment]
Hi all,

So I sat and thought about this carefully then tried some code, I was thinking about it the wrong way, I thought the easiest wat to get phonegap to work with ion auth is to implement jquery mobile with ion auth then do the user form in jquery mobile and submit it using ajax to use or access members area using ion auth. I will post code later today to help anyone also struggling with this

**Comment by absmugz** [comment]
Hi all,

Below is what I had to do to get ion auth to work with phonegap. ajax and jquery mobile, maybe some one is struggling with this : 

Ajax jquery mobile form : 
`
<form id="callAjaxForm" class="ui-body ui-body-a ui-corner-all" data-ajax="false" method="post" action="">
                <fieldset>
                    <div data-role="fieldcontain">
                        <label for="username">Enter your username:</label>
                        <input type="text" value="" name="identity" id="identity"/>
                    </div>                                  
                    <div data-role="fieldcontain">                                      
                        <label for="password">Enter your password:</label>
                        <input type="password" value="" name="password" id="password"/> 
                    </div>
                    <input type="submit" data-theme="b" name="submit" id="submit" value="Submit">
                </fieldset>
            </form> 
            
            <div id="notification"></div>  
 `
Ajax code : 
`$("#submit").click(function(event) {
event.preventDefault();
var user_name = $("input#identity").val();
var password = $("input#password").val();
//console.log('this is before ajax' . user_name + password);
jQuery.ajax({
type: "POST",
url: "http://myapi.dev/Members/login",
data: {identity: user_name, password: password},
success: function(data) {
//console.log(response);
alert(data);
$('#notification').html(data);
$.mobile.changePage($("#about"), null, true, true);
}
});
});`
