### ISSUE TITLE
Log in without password

### ISSUE THREAD

**Issue by antanova** [benedmunds/CodeIgniter-Ion-Auth#902]
I'm looking to add the ability to ['sign in with LinkedIn'](https://developer.linkedin.com/docs/signin-with-linkedin) to an app that currently uses Ion Auth. Users who sign in via Linked in will not have any password; is there a way for me to programmatically register/log a user in without one?

**Comment by benedmunds** [comment]
You'd want to store the oauth key and use that for authentication.  You'd need to modify or extend Ion Auth to add that ability.

**Comment by antanova** [comment]
I think what I'll do is get the user's ID from LinkedIn and use that as their username (identity) and then manually call `ion_auth->set_session` for them, so no need to deal with passwords.

Thanks.
