### ISSUE TITLE
AJAX calls to app breaks csrf because it uses flashdata

### ISSUE THREAD

**Issue by komirad** [benedmunds/CodeIgniter-Ion-Auth#904]
In the auth controller, flashdata is used for csrfkey and csrfvalue -> https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/controllers/auth.php

Problem with this is if any AJAX calls are made to Codeigniter after the key/value is generated, the flashdata is lost and csrf fails.

Is there a better way to handle this other than doing a "keep_flashdata()" on every AJAX call?

Note some AJAX calls are unrelated to auth/ion_auth, and are for things such as notifications. So applying a keep_flashdata() on such unrelated functions seems like an inelegant solution.

Can we use something else for the csrf code?

**Comment by avenirer** [comment]
@komirad Hello. The controllers are put in there only as an example. You are not forced to use them. So, if you want to use other controllers, go ahead. You can even use the framework's CSRF. Don't let them stop you :)
