### ISSUE TITLE
Logout error Warning

### ISSUE THREAD

**Issue by mdsirdiu** [benedmunds/CodeIgniter-Ion-Auth#906]
When logout

A PHP Error was encountered

Severity: Warning

Message: session_regenerate_id(): Cannot regenerate session id - session is not active

Filename: Session/Session.php

Line Number: 625

Backtrace:

File: E:\xampp\htdocs\etender\application\libraries\Ion_auth.php
Line: 417
Function: sess_regenerate

File: E:\xampp\htdocs\etender\application\controllers\Auth.php
Line: 75
Function: logout

File: E:\xampp\htdocs\etender\index.php
Line: 292
Function: require_once

**Comment by avenirer** [comment]
Well... "session is not active"... Did you load the session library correctly?

**Comment by mdsirdiu** [comment]
session in auto load
$autoload['libraries'] = array('session', 'database');

**Comment by avenirer** [comment]
you need to set up the session, not only to "autoload" it. http://www.codeigniter.com/user_guide/libraries/sessions.html#session-drivers

**Comment by mdsirdiu** [comment]
What I have to set up ? could you explain me please ?

**Comment by avenirer** [comment]
In Codeigniter manual is explained pretty straightforward, depending on what driver you are using (file, database, etc.). If you are planing to use database for sessions I could point you to one of my tutorials: http://avenir.ro/authentication-system-with-ion-auth-and-ci3/lets-install-ion-auth-library/

**Comment by mdsirdiu** [comment]
I have setup session like bellow. But but warning showing still now. Should any change for fix the error warning. please tell me.

$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

**Comment by avenirer** [comment]
You have no path for your session files:
```php
$config['sess_save_path'] = NULL;
```
If you have time, please do read the CodeIgniter manual which is a very good reference for the framework.

**Comment by mdsirdiu** [comment]
Thank you so much brother. I'm trying again.

**Comment by creanium** [comment]
This is actually an error introduced in PHP 7, caused by destroying the session, then trying to regenerate a destroyed session. 

http://stackoverflow.com/questions/34661205/sessions-in-codeigniter-with-php7

**Comment by agung-wete** [comment]
issue confirmed. We need add : session_start() before creating new session
```php
		// Destroy the session
		$this->session->sess_destroy();
		session_start(); 
		//Recreate the session
		if (substr(CI_VERSION, 0, 1) == '2')
		{
			$this->session->sess_create();
		}
		else
		{
			$this->session->sess_regenerate(TRUE);
		}

**Comment by avenirer** [comment]
Actually, if the problem you report is related to PHP7 (and yet I am not convinced...) then the problem is related to the framework and not the library. What @mdsirdiu reported was actually related to the fact that the session was not set properly. @benedmunds do you have any opinion about that "error introduced in PHP7"?

**Comment by mdsirdiu** [comment]
Problem solved by following @agung-wete comment. Thank you every body for support me

**Comment by agung-wete** [comment]
@avenirer its PHP7 + CI 3 issue

@mdsirdiu, CI 2 havent use $_SESSION, so correct code would be :
```php
        // Destroy the session
        $this->session->sess_destroy();
        
        //Recreate the session
        if (substr(CI_VERSION, 0, 1) == '2')
        {
            $this->session->sess_create();
        }
        else
        {
            session_start(); 
            $this->session->sess_regenerate(TRUE);
        }

**Comment by mdsirdiu** [comment]
@agung-wete
Will it make any error if use PHP VERSION < 7

**Comment by benedmunds** [comment]
Does this cause any regression errors under PHP 5 or 6?

**Comment by agung-wete** [comment]
@benedmunds maybe this link helps : https://fossies.org/diffs/php/5.6.16_vs_7.0.0/ext/session/tests/session_regenerate_id_error.phpt-diff.html

**Comment by benedmunds** [comment]
I agree with that @agung-wete 

Can you send a PR?

**Comment by Latief-Anwar** [comment]
same problem, and thank to @mdsirdiu, @agung-wete, @avenirer

**Comment by baldisbadder** [comment]
The additional session_start as suggested by agun_wete solved the problem for me. Thank you!

**Comment by gsuresh2u** [comment]
@agung-wete  Thanks it worked for me too
