### ISSUE TITLE
Codeigniter 3.0 ion_auth.php missing 

### ISSUE THREAD

**Issue by nehil** [benedmunds/CodeIgniter-Ion-Auth#907]
I chaged Everyting as per Instruction required in Installation. 
Though it runs perfectly on XAMPP, on Uploading it on live server I get Error 
```The configuration file ion_auth.php does not exist.```

What can the issue?

**Comment by avenirer** [comment]
Allow me to put this stupid question...: does the configuration file ion_auth.php exist inside application/config directory on your live server?
