### ISSUE TITLE
Automatic logout when browser closes ...

### ISSUE THREAD

**Issue by jdriesen** [benedmunds/CodeIgniter-Ion-Auth#909]
Hi Ben,

How can I 'force' a logout when the browser (or the tab with the application) closes ?

Thanks in advance for your reply,

Johnny

**Comment by avenirer** [comment]
You could do that using the configuration file config.php: $config['sess_expiration'] = 0;
Also on tab close, you can use javascript onbeforeunload() (...I think...)

**Comment by jdriesen** [comment]
Yep, solved Adrian.
Thanks mate !

Grtz,
Johnny

**Comment by Tjoosten** [comment]
@jdriesen can you close the issue then please?

**Comment by smartnetguru** [comment]
@jdriesen can you please explain or share code on how you solved the problem.
Thanks.
