### ISSUE TITLE
set_hook private function

### ISSUE THREAD

**Issue by FraOre** [benedmunds/CodeIgniter-Ion-Auth#910]
Hi, I setted a hook to save the log of the user login/logout
$this->ion_auth->set_hook('post_login_unsuccessful', 'login_unsuccess_log', $this, 'user_accesslog', array(0));
$this->ion_auth->set_hook('post_login_successful', 'login_success_log', $this, 'user_accesslog', array(1));
$this->ion_auth->set_hook('logout', 'logout_success_log', $this, 'user_accesslog', array(2));

the function is  
function user_accesslog($status)
  {
    $data = array(
      'ip_address' => $this->input->ip_address(),
      'timestamp' => time(),
      'session_id' => $this->session->userdata('identity'),
      'user_id' => $this->session->userdata('user_id'),
      'status' => $status
    );

```
$this->accesslog->insert($data);
```

  }

the problem is that i cannot set the user_accesslog function private... If i did it the hook doesent works...

Can someone help me?

Thanks

**Comment by avenirer** [comment]
Where did you insert the function? I'm not sure but I think you must insert it inside the ion_auth model.

**Comment by benedmunds** [comment]
No it shouldn't be in the model. But is the only issue that you want to make it private?

**Comment by FraOre** [comment]
Yes i want make the function private. Because if it remains public can be trigged by url www.site.com/user/user_accesslog...

**Comment by benedmunds** [comment]
Start the name of it with an underscore or use a class method instead of s controller method
