### ISSUE TITLE
Ion_Auth and GitHub auth

### ISSUE THREAD

**Issue by arizona2014** [benedmunds/CodeIgniter-Ion-Auth#911]
I've implemented successfully Ion_Auth on my site and frankly it works pretty good. Now I would love to give to my users the possibility to login with GitHub. 

Does someone tried this before ? And if so how one can manage the communication between GitHub and Ion_Auth to send well the authentication variables and states.

**Comment by benedmunds** [comment]
I'm not aware of it but it's worth seeing if anyone comments that they have.

**Comment by Reconix** [comment]
http://hybridauth.sourceforge.net

Pretty sure I seen the two(Ion Auth & Hybrid Auth) merged somewhere here on github.

**Comment by benedmunds** [comment]
Ah yes!  It hasn't been updated in awhile and I don't know if it supports Github but it would be a great starting place even if it doesnt work.  It's located here https://github.com/benedmunds/CodeIgniter-Ion-Auth/tree/social
