### ISSUE TITLE
hostname converted to IP

### ISSUE THREAD

**Issue by prashantnirgun** [benedmunds/CodeIgniter-Ion-Auth#913]
Hi

Let me first say thanks for developing such a wonderful library. Since I am new to the library please help me I am facing one problem. movement I entered userID and pwd it convert my hostname into ip
it become http://127.0.1.1/admin/dashboard it should be dev.local/admin/dashboard.

Now the biggest problem is I am on localhost and created few virtual host for development purpose. 
here is login function below. If you spear some time and give me hint It will be a great help for me. 
Thanks in Advance
function login()
	{
		$this->data['title'] = "Login";

		//validate form input
		$this->form_validation->set_rules('identity', 'Identity', 'required');
		$this->form_validation->set_rules('password', 'Password', 'required');

		if ($this->form_validation->run() == true)
		{
			// check to see if the user is logging in
			// check for "remember me"
			$remember = (bool) $this->input->post('remember');

			if ($this->ion_auth->login($this->input->post('identity'), $this->input->post('password'), $remember))
			{
				//if the login is successful
				//redirect them back to the home page
				$this->session->set_flashdata('message', $this->ion_auth->messages());
				//redirect('dashboard', 'refresh');
				redirect('/admin/dashboard');
				echo 'go to dashbaord';
			}
			else
			{
				// if the login was un-successful
				// redirect them back to the login page
				$this->session->set_flashdata('message', $this->ion_auth->errors());				
				redirect('auth/login', 'refresh'); // use redirects instead of loading views for compatibility with MY_Controller libraries
				
			}
		}
		else
		{
			// the user is not logging in so display the login page
			// set the flash data error message if there is one
			$this->data['message'] = (validation_errors()) ? validation_errors() : $this->session->flashdata('message');

			$this->data['identity'] = array('name' => 'identity',
				'id'    => 'identity',
				'type'  => 'text',
				'value' => $this->form_validation->set_value('identity'),
			);
			$this->data['password'] = array('name' => 'password',
				'id'   => 'password',
				'type' => 'password',
			);

			//$this->_render_page('auth/login', $this->data);
			$this->_render_page('login', $this->data);

		}
	}

**Comment by prashantnirgun** [comment]
Sorry I didn't give complete information My Os is Ubuntu 15, WebServer apache2 and I created virualhost name dev.local I am using in Codeigniter 3. Is it because of I config/database.php

$db['default'] = array(
	'dsn'	=> '',
	'hostname' => 'localhost',

But I tried to put hostname as dev.local but it fails to connect.

**Comment by prashantnirgun** [comment]
I try to debug the code using crome and found Resources Tab has option Cookies, localstorage, session Storage  which previously showing dev.local and movement we submit the form it is showing 127.0.1.1

**Comment by avenirer** [comment]
This is not an issue related to the Ion Auth library. @benedmunds please close it.

**Comment by benedmunds** [comment]
Agreed. Please ask for help with general development topics on the CI forums

**Comment by prashantnirgun** [comment]
Issue resolved added following line in config.ini
$config['base_url'] = 'http://dev.local';
