### ISSUE TITLE
creating https over http on localhost 

### ISSUE THREAD

**Issue by prashantnirgun** [benedmunds/CodeIgniter-Ion-Auth#914]
Hi

if i tried to login using url localhost/ci/index.php/users/auth/login it redirect to 
https://localhost/ci/index.php/users/auth/login I removed .htaccess file. How to redirect it to http 
my $config['base_url'] = 'http://localhost/ci'; Anybody knows how to fix this ?

problem area is if the images, jquery and other resources are not loaded everything gets failed because browser console shows the following error.

Mixed Content: The page at 'https://localhost/ci/index.php/users/auth/login' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://localhost/ci/index.php/users/auth/login'. This endpoint should be made available over a secure connection.

**Comment by benedmunds** [comment]
Please post this on the CI forums or stackoverflow as it's not an issue with the library
