### ISSUE TITLE
Admin can deactivate but can't activate without sending the activation code.

### ISSUE THREAD

**Issue by Ihabafia** [benedmunds/CodeIgniter-Ion-Auth#915]
Hi,

I can deactivate the account as an admin, but the code creates an activation code. while if I am the admin and would like to re-activate the code I can't do it because the mySql query is looking for:

SELECT `email` FROM `users` WHERE `activation_code` = '' AND `id` = '2' ORDER BY `id` DESC LIMIT 1

which means I can't re-activate it.

I think the code needs to be changed by having the code that way on ion_auth_model.php:

if(!$this->ion_auth->is_admin())
	$this->db->where('activation_code', $code);

$query = $this->db->select($this->identity_column)
                  ->where('id', $id)
                  ->limit(1)
   		  ->order_by('id', 'desc')
                  ->get($this->tables['users']);

**Comment by benedmunds** [comment]
You just pass the ID as the first param to the activate method:

    ->activate(**$id**, $code)
