### ISSUE TITLE
How to have the admin be the only one to activate members after registration

### ISSUE THREAD

**Issue by absmugz** [benedmunds/CodeIgniter-Ion-Auth#916]
Hi fellow devs,

How do I get admin be the only one to activate members after registration. So when the user registers they get a message that they will get an email once activated by the admin.

**Comment by avenirer** [comment]
"Issues" is not on github to teach the users how to think or program. :)

**Comment by absmugz** [comment]
All I had to do was change the $config['manual_activation'] to TRUE @ Avenir sometimes it would be nice to point people in the right direction :)

**Comment by avenirer** [comment]
Actually that wasn't the answer. You wanted the admin to be the only one to activate members after registration. If you set that to true the users will be able to activate the account by simply clicking on the activation link they receive in mail.

**Comment by avenirer** [comment]
@absmugz does that send an email to users?

**Comment by absmugz** [comment]
Hey Aveniner,  sorry for the late response mate ☺ at the moment I have email activation set to false but what I plan to do is extend ion auth so that when the admin activates the user manually ther user get a email notification that tjey have been approved ☺

**Comment by avenirer** [comment]
Try using the Ion Auth hooks for that, namely the post_activate_successful. That hook is triggered in line 498 of ion_auth_model.
