### ISSUE TITLE
Email activation of member account directing to forgot password even though account is activated.

### ISSUE THREAD

**Issue by olliefalle** [benedmunds/CodeIgniter-Ion-Auth#918]
Hi,

I am using the email activation for my members, however i seem to have an issue.

The activation email is received by the user but when they click on the link it is redirecting them to the forgot login page and the unable to activate error message is shown. However, the account is being activated as it should.

I'm not sure why it's failing the $activation condition in the activate function.

Any suggestions?

Thanks

**Comment by avenirer** [comment]
Could you show us the activation controller method?

**Comment by olliefalle** [comment]
Here is what's being used to activate the user:

`// activate the user
	function activate($id, $code=false)
	{
		if ($code !== false)
		{
			$activation = $this->ion_auth->activate($id, $code);
		}
		else if ($this->ion_auth->is_admin())
		{
			$activation = $this->ion_auth->activate($id);
		}

		if ($activation)
		{
			// redirect them to the auth page
			$this->session->set_flashdata('message', $this->ion_auth->messages());
			redirect("login", 'refresh');
		}
		else
		{
			// redirect them to the forgot password page
			$this->session->set_flashdata('othermessage', $this->ion_auth->errors());
			redirect("members/forgot_password", 'refresh');
		}
	}`

**Comment by avenirer** [comment]
I guess that when you are testing you are already logged in as administrator on that particular browser, and that is what is happening.

**Comment by avenirer** [comment]
Do you have both $config['email_activation'] and $config['manual_activation'] set to TRUE?

**Comment by olliefalle** [comment]
Hi avenirer,

Manual activation is set to false and email activation set to true.

I also tested on a different browser without being logged in as a admin user but still i keep getting directed to the forgot password page.

Running out of ideas!!!

**Comment by olliefalle** [comment]
I think i have found the issue. 

I created a MY_controller to put the site in maintenance mode which was still turned on.

When i turned this off, i was able to get the correct activation message.

Will run some more tests and confirm.

Thanks
