### ISSUE TITLE
Login issue for admin and user

### ISSUE THREAD

**Issue by rajoriya654** [benedmunds/CodeIgniter-Ion-Auth#919]
http://www.awesomescreenshot.com/image/1025355/9f61a8b7b9ad561440bc129b468e6e9a
http://www.awesomescreenshot.com/image/1025356/60d6cad5f4cc31f286f7e2c46983923b

I m using the ion-auth with this https://github.com/waifung0207/ci_bootstrap_3

Now i m greeting totally stuck when i login form front-end and then set in url admin, it automatically takes me at the admin userpanel without login in the admin panel. 

Please help me for this... if you want to see the code files, please tell me i can share with you!

But please help me,  to sort out for this problem.

**Comment by benedmunds** [comment]
You would be best posting this to the CI forums or StackOverflow since this issues section is for problems with the library itself.
