### ISSUE TITLE
Get user by identifier?

### ISSUE THREAD

**Issue by adarshdec23** [benedmunds/CodeIgniter-Ion-Auth#920]
I checked the documentation, but was not able to find a method that allowed me to find a user (get their id / user object) by the unique identifier? Is this feature missing, or am I missing something very obvious?

**Comment by benedmunds** [comment]
It's the user() method, documented here: http://benedmunds.com/ion_auth/#user

Usage:
    $id = 1;
    $user = $this->ion_auth->user($id);

**Comment by adarshdec23** [comment]
That is if you know the user id. Say I only know the username and want to get user info.

**Comment by avenirer** [comment]
This feature is "missing". An alternate solution would be for you to create a User model. This way you can do whatever you want with the table data.

**Comment by benedmunds** [comment]
No it's not missing but it's a bit more complicated:
`
    $user = $this->ion_auth->where('first_name', 'John')->users()->row();
`
