### ISSUE TITLE
Feature request login using Mobile Number

### ISSUE THREAD

**Issue by prashantnirgun** [benedmunds/CodeIgniter-Ion-Auth#928]
I found many website offer login using Email / User Name / Mobile Number in our case we need to declared our Identity column. Is there any why where I can use both or add on Mobile number as Identity Column. 

I need this feature It will be a great help if anybody guide about how do I do this ? It will be a great help for me.

**Comment by avenirer** [comment]
you can only have one identity column... whatever its name is... even "mobile". if you want to make sure the username and email is also unique you can do that inside the register controller, where you validate the input fields by using the unique[] rule.

**Comment by Ema4rl** [comment]
@prashantnirgun I've once extended Ion Auth for Email / User Name / Mobile Number login on one of my projects. You'll have to dig in the library, extend it, then use your extended version.
<br>
_-> I'll look for the project's files and send it to you if you're interested_
