### ISSUE TITLE
register() never writes 'username' into DB 

### ISSUE THREAD

**Issue by aaliseyko** [benedmunds/CodeIgniter-Ion-Auth#929]
register() method never write 'username' into DB if:
$config['identity']  = 'email'. 

Ion_auth_model.php
line: 908
		$data = array(
		    $this->identity_column   => $identity,
		    'password'   => $password,
		    'email'      => $email,
		    'ip_address' => $ip_address,
		    'created_on' => time(),
		    'active'     => ($manual_activation === false ? 1 : 0)
		);

at this point  $this->identity_column is set as 'email', so 'username' data can't be sent to DB 'users' table

**Comment by avenirer** [comment]
You are absolutely right. You can add the username by using the additional data parameter, I think.

**Comment by aaliseyko** [comment]
sure, but why just not simply write 'username' as 'username' and use 'identity' param for login process or smthg like this?

**Comment by avenirer** [comment]
i don't understand your question...
