### ISSUE TITLE
Auto Redirect Ion Auth

### ISSUE THREAD

**Issue by Mifan168** [benedmunds/CodeIgniter-Ion-Auth#930]
I use codeigniter 3.0.5 and ion_auth

why when i'm using in config.php header `_<?php` it can be auto redirect but doesn't work with `<?php` ?
*`_` = blank space

**Comment by avenirer** [comment]
Not that it has any connection with the library, could you be more clear than this?

**Comment by benedmunds** [comment]
Closing since this isn't related to Ion Auth.

Please report general programming questions on the CI Forums or StackOverflow.
