### ISSUE TITLE
Performance Issues returning users from large users table

### ISSUE THREAD

**Issue by nathanpitman** [benedmunds/CodeIgniter-Ion-Auth#932]
I'm running into some big issues when returning a limited set of users from a large Ion Auth users table. I have ~500,000 users and most of those belong to a particular user group. When I query the database for these users using Ion Auth functions (even paginated to 50 at a time) the resulting query is taking upwards of 10 seconds to execute.

```
SELECT DISTINCT `users`.*, FROM_UNIXTIME(users.last_login) AS f_last_login
FROM (`users`)
INNER JOIN `users_groups` ON `users_groups`.`user_id`=`users`.`id`
WHERE `users_groups`.`group_id` IN (5)
ORDER BY `id` desc
LIMIT 50
```

I'm guessing the crux of the issue is the join on the users_groups table. Do you have any advice on how I can improve this? I don't really want to abandon Ion Auth. :/

**Comment by nathanpitman** [comment]
Incidentally, if you flip the query that Ion Auth generates on it's head... you can return the same result set in ms...

```
SELECT `users`.*, FROM_UNIXTIME(users.last_login) AS f_last_login FROM (`users_groups`)
JOIN `users` ON `users`.`id`=`users_groups`.`user_id`
WHERE `users_groups`.`group_id`=5
GROUP BY users_groups.user_id
ORDER BY `user_id` desc
LIMIT 50
```

**Comment by benedmunds** [comment]
Interesting. Do you see a simple way to get Ion Auth to generate this query using the DB class?  Or did you have to use SQL statements to get CI to do this?

**Comment by nathanpitman** [comment]
This seems to mostly replicate the query using CI active record... I need to take a look at the Ion Auth class though and see whether it's possible to implement...

```
$this->db->select("users.*, FROM_UNIXTIME(users.last_login) AS f_last_login", FALSE);
$this->db->join('users', 'users.id=users_groups.user_id');
$this->db->where_in('users_groups.group_id', $group_id);
$this->db->group_by('users_groups.user_id');
$this->db->get('users_groups')->result();
```

**Comment by avenirer** [comment]
did you add an index key on the group_id field in users?

**Comment by avenirer** [comment]
Actually I think there should not be an id in users_groups table. The unique key shoul actually be a combination between group_id and user_id. This should speed up the query...

**Comment by nathanpitman** [comment]
My users_groups table is as per the install SQL: https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/sql/ion_auth.sql#L66-L76

I'll give your suggestion a try though...

**Comment by nathanpitman** [comment]
Well I tried that, unfortunately it made little difference. The query is still taking 10+ seconds to run.

![screen shot 2016-03-30 at 11 55 30](https://cloud.githubusercontent.com/assets/694545/14139970/56b16208-f66e-11e5-8cc7-c10e399e0078.png)

Here's an EXPLAIN on that query:

![screen shot 2016-03-30 at 11 56 11](https://cloud.githubusercontent.com/assets/694545/14139992/72b2061a-f66e-11e5-878e-976e941ffd8d.png)

**Comment by nathanpitman** [comment]
Any further thoughts all? :)

**Comment by nathanpitman** [comment]
@avenirer sorry for the late response but just to let you know that in some cases removing the ID column from the users_groups table has reduced my queries from ~5secs to ~50ms. :D

I still have some work to do but getting there!

**Comment by benedmunds** [comment]
Hey, if you want to submit a Pr for this I'd be happy to consider it
