### ISSUE TITLE
Login not succesfull

### ISSUE THREAD

**Issue by mytrix-technology** [benedmunds/CodeIgniter-Ion-Auth#937]
After trying to use CodeIgniter Ion Auth turns to login did not work due to this condition $ this-> ion_auth-> login ($ identity, $ password, $ remember) return value bool (false).
I investigate to the use of ion_auth turns to decrypt the password on the condition $ this-> bcrypt-> verify ($ password, $ hash_password_db-> password) on the model ion_auth_model.php restore value bool (false).

Could help to resolve this case ???

thank you

**Comment by Tjoosten** [comment]
Can u give me the function?

**Comment by benedmunds** [comment]
@mytrix-technology what version of PHP are you using?

**Comment by mytrix-technology** [comment]
@benedmunds : my PHP version is 5.4.45.
@Tjoosten : my function is like this modul. I only same the name attribute and id attribute at form.

**Comment by cssandoval** [comment]
Hi all,
I faced the same problem some minutes ago.... I was usin sha1 as the hash method. Using this method I got the same error "Login not successful". I checked the ion_auth_model.php and saw that I was not reaching this part:

```
        `if ($query->num_rows() === 1)
    {
        $user = $query->row();

        $password = $this->hash_password_db($user->id, $password);

        if ($password === TRUE)
        {
            if ($user->active == 0)
            {
                $this->trigger_events('post_login_unsuccessful');
                $this->set_error('login_unsuccessful_not_active');

                return FALSE;
            }

            $this->set_session($user);

            $this->update_last_login($user->id);

            $this->clear_login_attempts($identity);

            if ($remember && $this->config->item('remember_users', 'ion_auth'))
            {
                $this->remember_user($user->id);
            }

            $this->trigger_events(array('post_login', 'post_login_successful'));
            $this->set_message('login_successful');

            return TRUE;
        }
    }`
```

it seems that something about sha1 didn't work for my with my current configuration, so I changed to bcrypt and now is working fine.
