### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by chuck-savino** [benedmunds/CodeIgniter-Ion-Auth#938]
I noticed this code in the Ion_auth_model delete_user method:

// if user does not exist in database then it returns FALSE else removes the user from groups
		if ($this->db->affected_rows() == 0)
		{
		    return FALSE;
		}

However, my expereince with CI 3.06 is that on deletes, $this->db->affected_rows() returns -1 for fail and 1 for success. It only returns affected rows count for inserts or updates, not deletes.

**Comment by benedmunds** [comment]
From a quick bit of research it looks like this may be driver specific...  So we should probably just check for truthy or not...

Thoughts?

**Comment by avenirer** [comment]
From CI manual: "In MySQL “DELETE FROM TABLE” returns 0 affected rows. The database class has a small hack that allows it to return the correct number of affected rows. By default this hack is enabled but it can be turned off in the database driver file." (https://codeigniter.com/user_guide/database/helpers.html)

**Comment by avenirer** [comment]
Hmm... You seem to be right... Looking at the mysql_driver.php inside system it seems that it is using mysql protocol... which is deprecated:

```php
	protected function _escape_str($str)
	{
		return mysql_real_escape_string($str, $this->conn_id);
	}

	// --------------------------------------------------------------------

	/**
	 * Affected Rows
	 *
	 * @return	int
	 */
	public function affected_rows()
	{
		return mysql_affected_rows($this->conn_id);
	}

	// --------------------------------------------------------------------

	/**
	 * Insert ID
	 *
	 * @return	int
	 */
	public function insert_id()
	{
		return mysql_insert_id($this->conn_id);
	}
```

**Comment by benedmunds** [comment]
Yea and Postgres just returns 0 or the number: http://php.net/manual/en/function.pg-affected-rows.php

Actually this might need some testing but the current logic, ==0, should match -1 or 0 right since its a double equals.  If I'm not incorrect -1 should evaluate to 0...

**Comment by benedmunds** [comment]
Nvmd, it does not
``
    Ben@ayr ~/htdocs> cat test.php
<?php

var_dump(-1 == 0);

var_dump(0 == 0);

var_dump(1 == 0);
Ben@ayr ~/htdocs> php test.php
bool(false)
bool(true)
bool(false)

**Comment by benedmunds** [comment]
So this would probably be best, thoughts?

```
Ben@ayr ~/htdocs> cat test.php
<?php

var_dump(-1 <= 0);

var_dump(0 <= 0);

var_dump(1 <= 0);
Ben@ayr ~/htdocs> php test.php
bool(true)
bool(true)
bool(false)
```

**Comment by avenirer** [comment]
http://php.net/manual/en/mysqli.affected-rows.php "-1 indicates that the query returned an error.".

**Comment by avenirer** [comment]
It won't hurt to change it to <=0

**Comment by benedmunds** [comment]
After reviewing the logic more I think what we have now is what we want really.  @chuck-savino can you confirm that you were actually getting an error from the current logic?

**Comment by chuck-savino** [comment]
I agree it does appear to be driver specific That is what is frustrating
because the whole point of the framework is to abstract out the need to
worry about which driver is being used by the app. Given that we have to
deal with it...

Since anything other than 0 would resolve to true, I would go with when <=
0 then execute the failed condition.

Regards,

Chuck

Regards,

Chuck

IT Consultant
(o) 972-429-9374
www.csavino.com

**Comment by benedmunds** [comment]
@chuck-savino  This should fix it.  Let me know if it handles it for you and close this issue if it does please.  Thanks!!!

https://github.com/benedmunds/CodeIgniter-Ion-Auth/commit/edfd398d1050eff5ffc7d85405252f06070854c0

**Comment by chuck-savino** [comment]
I am currently waiting for a tech to get my Internet fixed. Will try it
when I  get back online. Thx.
