### ISSUE TITLE
Remember me created cookie disappear when loging out.

### ISSUE THREAD

**Issue by Wmas** [benedmunds/CodeIgniter-Ion-Auth#943]
Hi Ben,

I am using your script for a while now, but today I was asked to activate the 'Remember me option' which I did.
Done! I thought. Unfortunately the user could still not be remembered.
After spending a few hours looking up for the problem I found a strange issue.

When I try to log in my self I will clearly see in my console (firebug on FF) that the the cookies will be created correctly and they are also there when I search for the cookies in the browser.

Strangely when I logout the cookies disappears (also have checked in the browser cookies list) and are not available anymore when I try to login again.

I don't know anymore what to do.

I will appreciate your help

Cheers 

Franco

**Comment by benedmunds** [comment]
Does this happen when navigating to /logout or when you close the browser tab/window?

**Comment by Wmas** [comment]
Thanks for your reply.
I was just looking if the $expire value while setting the cookie is having a value at all.

Anyway this happen when I logout.

**Comment by benedmunds** [comment]
What is the expire on the cookie?

**Comment by Wmas** [comment]
I was just busy to look at this:

$config['user_expire']                = 864000;  //10 days

**Comment by Wmas** [comment]
Hi Ben,

In the logout method the cookie will be deleted by default (why is that?):
```
// delete the remember me cookies if they exist
if (get_cookie($this->config->item('identity_cookie_name', 'ion_auth')))
{
	delete_cookie($this->config->item('identity_cookie_name', 'ion_auth'));
}
if (get_cookie($this->config->item('remember_cookie_name', 'ion_auth')))
{
	delete_cookie($this->config->item('remember_cookie_name', 'ion_auth'));
}
```

That seems to be be reason why it will disappear when the user logout, don't you think?

**Comment by benedmunds** [comment]
Ah yea, I see what you're doing now.  This isn't actually a bug but a different expectation.

The Remember Me functionality is to automatically log the user back in if they leave the site and their session expires.  So you can come back 2 days later and as long as you still have the cookie you'll be automatically logged back in.

If the user explicitly logs out it means they no longer want to be logged in so they are both logged out and their remember me cookie is deleted.

**Comment by Wmas** [comment]
I understand. I have a multiuser application so I would like to give them the possibility to remember their credentials when they are logging out. So the very next time they wish to login again than the cookie is till there (in my case remembered for 10 days).

I don't know if I could comment those deleting lines, or maybe  better twith a conditional approach:

if in the user table the `remember_code` filed is NULL delete the cookies if any else keep the cookies in place.

**Comment by benedmunds** [comment]
what do you mean by a "multiuser application"? 

I don't think you should do this... but if you must then just wrap that delete code in an if based on user input.

**Comment by Wmas** [comment]
My application can be accessed by many users. Every user has his own space in it.
When someone want to leave than he/she clicks on 'Logout'.

If some user want to use the 'remember me' option in the actual situation wont work because the cookies will be deleted by default.

My idea was to keep track of the user table field 'remember_code'.

if($remember_code == NULL){
if (get_cookie($this->config->item('identity_cookie_name', 'ion_auth')))
{
    delete_cookie($this->config->item('identity_cookie_name', 'ion_auth'));
}
if (get_cookie($this->config->item('remember_cookie_name', 'ion_auth')))
{
    delete_cookie($this->config->item('remember_cookie_name', 'ion_auth'));
}
}

**Comment by benedmunds** [comment]
So people are sharing a computer?

**Comment by Wmas** [comment]
It can be, but is not the case. I have read also the other issues where they are talking also about almost the same. This case is much more simple.
The logout function deletes the created (remember me) cookies once the user is logging out.

If the logged in user wants to be remembered the 'remember_code' field in the user table will be filled in, so we do not want to delete the cookies for this user.

I suggest, in order to avoid this to implement a conditional statement in the logout method.

**Comment by benedmunds** [comment]
Maybe I'm just not following....

As a user:
You select Remember Me on login and it will be saved client side until deleted.  This allows you to navigate away from the site, come back, and still be logged in.

If you click to logout you are logged out completely, session, remember me, everything. Because you want to logout.

**Comment by Wmas** [comment]
I am sorry Ben if I can not clearly explain what I mean.
I understand everything you say and your logic is to keep someone logged in.

My goal is an other one.

The user makes an account.
The user login and choose to be remembered
This for many users (and also mine users) means:
"Ok, now I will be remembered, so next time I will come here again (using my computer of course) I don't have to fill all (or parts of) my credentials in. The credentials are filled in for me."

**Comment by benedmunds** [comment]
ohhhh you mean like just auto populating the email field on the login form?

**Comment by Wmas** [comment]
Yes!

**Comment by Wmas** [comment]
But for this the cookies must not be deleted, that's why i suggest the conditional deleting of the cookies

**Comment by benedmunds** [comment]
Gotcha.  

In your controller, on login create a new cookie for the email address.  If the email address cookie exists, then pre-fill the value of the form field on load.

Please dont do this for passwords, any solution would be terribly insecure.

**Comment by Wmas** [comment]
In this way if someone (me) wants to, can use the cookies to populate what ever he/she wants to

**Comment by benedmunds** [comment]
I wouldnt use the Ion Auth remember me cookie for that.  Let it remain for its intended use case.  But you can add new cookies and use them however you need to.

**Comment by Wmas** [comment]
What I am asking you is, if it is possible for you to, is to make the cookies be delete in a conditional way, as I suggested a few comments above.
Once the cookies are there is not so complicated to use them.

**Comment by benedmunds** [comment]
No.  I dont want to complicate the logic for an edge case.  The cookie does what it's intended to do.  If you need custom logic or new features feel free to implement them in your app.

**Comment by Wmas** [comment]
Ok Ben, that's clear. I will do that.
I want to thank you for your time and for the 'ion-auth'
Cheers and have a nice day

**Comment by benedmunds** [comment]
No worries!  Glad we finally got clear on what we were discussing haha.  Have fun!
