### ISSUE TITLE
[Question] Activate Method in Model

### ISSUE THREAD

**Issue by keithmclaughlin** [benedmunds/CodeIgniter-Ion-Auth#945]
Can I ask why the activate method in the model activates the user regardless of whether an activation_code is provided or not?

https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/models/Ion_auth_model.php#L452

**Comment by benedmunds** [comment]
I let the controller handle that.  There are times you might want to activate the user without that code.  For example, I've implemented sites before where the admin was able to activate users by clicking a button.
