### ISSUE TITLE
Simple 'email only' log-in

### ISSUE THREAD

**Issue by nathanpitman** [benedmunds/CodeIgniter-Ion-Auth#946]
I'm working on a project where we are using Ion Auth and want to offer a simple 'email address only' log-in as the log-in URL is unique for each account and users are (in this context) unlikely to want to use a password. The system does not store/reveal personal data so we have no concerns from that perspective. It simply provides access to content which is recorded as having been viewed by that user.

I would like to extend Ion Auth to offer a simple log-in method which does not use the password. What approach am I best of taking to do this... creating a model which extends the ion_auth model? Is there some other approach which might be preferable?

**Comment by benedmunds** [comment]
The easiest approach would probably be to just hard code a password for all these users and then pass that in in your controller so they never have to enter it.  That or maybe just make their password be their email address by default.

**Comment by nathanpitman** [comment]
Password as email address is a genius idea. Thanks Ben. :)
