### ISSUE TITLE
logout existing session if the same user logs in from a different client

### ISSUE THREAD

**Issue by pranjalrajput** [benedmunds/CodeIgniter-Ion-Auth#947]
Currently we are using ion auth with CI 2.2.5
We intend to allow only one login per user id per client.
So if a user is already logged in and he/she tries to login from a different client, the current session should expire.
How can we enable this feature?
Any pointers/hints would be greatly appreciated.
Thanks,

**Comment by nathanpitman** [comment]
Pretty sure the key here will be using the database to store session data and then check against that on log-in. You could prob kill any other sessions for the same client ID pre login using the Ion Auth hooks?

**Comment by pranjalrajput** [comment]
Thanks @nathanpitman.
Already using database to store session. We can add the hook as you suggested, but what should be the mechanism to kill other sessions. Which class or api method can we use? or should we manipulate the session table (like deleting a row or modifying any value)

**Comment by pranjalrajput** [comment]
Anybody ??
Please help ...

**Comment by avenirer** [comment]
@pranjalrajput Just before login in someone, you can simply call $this->ion_auth->logout();

**Comment by pranjalrajput** [comment]
@avenirer , we need to logout OTHER/EXISISTING sessions from the same user and retain the current session.
So for example if user-A logs in from machine-1 and then after few minutes logs in from machine-2 then the session at machine-1 should be invalidated/logged out/destroyed.

**Comment by avenirer** [comment]
IN THEORY (so no tested code)... You would have to create a field called session_id inside the users table. Also create a post_login_successful hook that will insert that session id if the user is logged in. Also create a logged_in hook that will check current session id with the session id inside the table. If the two are different, simply call the logout() method of the library.

**Comment by Ema4rl** [comment]
That was brilliant @avenirer !

**Comment by trungdq88** [comment]
> So for example if user-A logs in from machine-1 and then after few minutes logs in from machine-2 then the session at machine-1 should be invalidated/logged out/destroyed.

Really?? Why would we do that???

Let's say I have my Laptop and Tablet, I can't keep the login state from both devices?

Someone please give me some light.

**Comment by nullart** [comment]
The problem with @avenirer's solution is the config['sess_time_to_update']. Everytime a new session_id is generated, the user gets logged out.

**Comment by wrabit** [comment]
In theory, as you are storing user_id and unique identity in the session as well, you might be able to simply:

```
    $this->db->like('data', $user->email);
    $this->db->delete('ci_sessions');
```

**Comment by bthart** [comment]
digitaloutback, this may work, however, it doesn't seem that IonAuth stores any user information in the CIsessions table, so it would still require work to set this up. 

If people are interested to setup IonAuth so each user can only have one active session at any one time, they could copy the following code to the end of the IonAuth Model Login() function. This is based on a previous comment from avenirer. You should also add a currentsessionid to your users table in MySQL.

              $this->db->delete('ci_sessions', array('session_id' => $this->ion_auth->user()->row()->currentsessionid)); 
        
        
        $data = array(
               'currentsessionid' => $this->session->userdata('session_id')
               
            );

                  $this->db->where('id', $this->ion_auth->user()->row()->id);
                 $this->db->update('users', $data);

**Comment by ghost** [comment]
@bthart thank you. it work for me. in codeigniter 3, but ion auth no have session_id in userdata session, I used `session_id()` for get latest session id.

**Comment by chirag00757** [comment]
Anyone can help me how can I do this in codeigniter 3 without ion auth ? I am managing sessions using database and storing session_id in users table as well but having hard hard time to update regenerated session_id to user table and matching two sessions for authentication.

**Comment by AlokInsan** [comment]
Hi avenirer sir, 
                       Thanks for a brilliant answer in ion auth library.

**Comment by athul7447** [comment]
I have this issue please help me
