### ISSUE TITLE
Reset or changing current user password

### ISSUE THREAD

**Issue by claide** [benedmunds/CodeIgniter-Ion-Auth#953]
Hi to the maker of this great library. I have a question. Is there a way we can change or reset the user password. Like for example: Input old password then check if it matches then enter the new password something like that. I read the documentation but I can't find what I wanted to achieve. Thanks in advance!

Regards

**Comment by avenirer** [comment]
Well... this library can do so much. It can't teach you to think though...

**Comment by benedmunds** [comment]
Hey,

You'll need to implement this in your controller logic.  The supplied controller is just a me example, feel free to modify as needed.
