### ISSUE TITLE
Is LDAP authentication possible in ION_AUTH

### ISSUE THREAD

**Issue by praburaj06** [benedmunds/CodeIgniter-Ion-Auth#954]
Is it possible to enable LDAP authentication in ion-auth????

**Comment by benedmunds** [comment]
You could always add code to interface with LDAP but it's not built in.

**Comment by ramasofficial** [comment]
I make my ERP systems with LDAP, if you want i can upload my code here.

**Comment by pblaz1988** [comment]
here is quick and dirty hack to make LDAP work - you will need to install php-ldap, and replace the login function. classic log-in won't work anymore.
https://github.com/pblaz1988/Ion-Auth-LDAP-Module
