### ISSUE TITLE
Make a forum for ion auth. 

### ISSUE THREAD

**Issue by Tjoosten** [benedmunds/CodeIgniter-Ion-Auth#955]
Hi, 

I was wondering is there a possibility to make a forum or gitter for ion-auth. To seperate library bugs and user bugs?

**Comment by avenirer** [comment]
That would be a great idea 👍

**Comment by Tjoosten** [comment]
@benedmunds @avenirer i would like to set this up if you want

**Comment by benedmunds** [comment]
I'm fine with this. Just make it clear that it's community supported please

**Comment by Tjoosten** [comment]
@benedmunds can u make the room. Because i have no permission over the repo

**Comment by benedmunds** [comment]
Where are you trying to make the forum?

**Comment by Tjoosten** [comment]
gitter

**Comment by benedmunds** [comment]
Ha looks like I made one awhile back:

https://gitter.im/benedmunds/CodeIgniter-Ion-Auth
