### ISSUE TITLE
auth pages not working on production server

### ISSUE THREAD

**Issue by schester44** [benedmunds/CodeIgniter-Ion-Auth#957]
Hey Ben, awesome library, I appreciate everything you've done. I'm having a super weird issue where auth pages work fine on localhost but  are returning a 404 error page on my production server.

I have another CI instance set up on the same server so i'm pretty sure its not server config related and is project related. Have you come across anyone else that has experienced this issue before?

Here is the main config/config.php file and config/ion_auth.php file, maybe you can spot what i'm doing wrong? As far as I can tell, the database is set up as it should be. I'm pretty lost at this point. Any suggestions on what I should look for?

config.php: https://gist.github.com/schester44/a331ad871e2582c8cb0d6f4ac47c8d52
ion_auth.php: https://gist.github.com/schester44/e4e03de6661146cc549ffa9391f25ed7

**Comment by benedmunds** [comment]
Usually this is due to HTTP rewriting of index.php.  Make sure the proper .htaccess is in place, mod_rewrite is installed, and that Allow Override is in you apache settings for this.

**Comment by schester44** [comment]
Hey Ben, thanks for the response. Just to clarify, I already have another instance of CI running on this same server with ion_auth working just fine. Just to make sure my .htaccess was correct, I copy/pasta the .htaccess from the working site to the broken site and I was still unable to get it to work.

This is a single page application, fearing that was the issue, I disabled pretty much all functionality of the site and i'm still getting the 404 page. 

Do you think it could be database or config related? Should I reload the library and config files?

EDIT: Copied the config file from my other working site. Still a no go. I'm at a loss as to what could be causing this.

**Comment by benedmunds** [comment]
What if you add the index.php back in the config and your test URLs?

**Comment by schester44** [comment]
Adding the index.php results in the same results. Still getting a 404. I've made quite a few changes to the auth controller. I'll try reloading a default/untouched version and go from there.

**Comment by benedmunds** [comment]
Sorry for the inactivity here. Is this still an issue?
