### ISSUE TITLE
How to keep user logged in over multiple domains (not subdomain)

### ISSUE THREAD

**Issue by ynnr85** [benedmunds/CodeIgniter-Ion-Auth#959]
Hi,
I am writing a wildcard subdomain based app, and I can extend session login to all my subdomains, for example if you logged in in **mysite.com** I can use session in **subdomains.mysite.com.** But right now I am mapping domains to my own site so **mapping.com** point to **mysite.com**, but I can not make work session all over any mapping domains, so I need log in session in **mysite.com** can be expanded to **mapping.com**, the question is when I redirect after login in **mysite.com/login** logged_in() functions return false in **mapping.com/admin**, so do you have any idea how to make it works?

Best regards

**Comment by Tjoosten** [comment]
I think u need to look for a Oauth service based on CI!
