### ISSUE TITLE
Server Error.

### ISSUE THREAD

**Issue by gbrigens** [benedmunds/CodeIgniter-Ion-Auth#962]
I am getting this error when I try to launch application on a server. Local host its working fine without any issue.

A PHP Error was encountered

Severity: Compile Error

Message: Can't use method return value in write context

Filename: models/Ion_auth_model.php

Line Number: 2283

Backtrace:

**Comment by avenirer** [comment]
That line doesn't exist... the Ion_auth_model has (only) 2256 lines

**Comment by gbrigens** [comment]
What might be the issue? and how can I solve this?

**Comment by avenirer** [comment]
I told you what the issue is. What you can do is update the library to the latest version (replace the old files on your server with the files of the repository). But considering that you are reffering to a line in the code that doesn't exist, you must first make sure you know what you're doing...
