### ISSUE TITLE
Can not restore the databse, foreign key constraint fails

### ISSUE THREAD

**Issue by Wmas** [benedmunds/CodeIgniter-Ion-Auth#965]
# After making a database backup, I have tried to restore it but unfortunately I get this error:

A database error occoured.
Error Number: 1217
Cannot delete or update a parent row: a foreign key constraint fails
DROP TABLE IF EXISTS `groups`;
Filename: controllers/admin/Database.php
# Line Number: 346

Before I go to the 'groups' table and alter the constrains (probably making a mess of it), I would like to know if anyone knows how I can restore my database without having this problem.

Thank you

NOTE: sorry for the bold text, but I don't know why this is happening.

**Comment by benedmunds** [comment]
Is this still an issue for you or have you resolved it?

**Comment by Wmas** [comment]
Hi Ben tanks for your reply.

I have solved this.

Franco Magliozzi
franco@webline-studio.nl
