### ISSUE TITLE
How to change default session name in ion auth

### ISSUE THREAD

**Issue by mahethekiller** [benedmunds/CodeIgniter-Ion-Auth#967]
i am using codeigniter for two different project but they both are on same server in different directories,  and they both have separate login form  and different database but when i login on first project  and try to open other project, its already logged in their ,  so how can i make the other project ion auth use different session name so their is no such issue... please help

**Comment by avenirer** [comment]
you do it by setting a name of the session inside application/configuration/config.php

**Comment by mahethekiller** [comment]
yes i got it , thank you

**Comment by mahethekiller** [comment]
ex. for site1

$config['sess_cookie_name'] = 'site1_cookies';
$config['sess_table_name'] = 'site1_sessions';

for site2

$config['sess_cookie_name'] = 'site2_cookies';
$config['sess_table_name'] = 'site2_sessions';
