### ISSUE TITLE
Version numbering and how to echo version?

### ISSUE THREAD

**Issue by sparky672** [benedmunds/CodeIgniter-Ion-Auth#968]
Two questions:
1.  How can I `echo` my Ion Auth version number?  I'd like to put this on my application's Admin page.
2.  According to comments in `Ion_auth_model.php`, I have version 2.5.2.  This file's modification date is 3/23/15 and the comments say `Last Change: 3.22.13`.  However, as of today, the latest version of `Ion_auth_model.php` posted here on GitHub also shows version 2.5.2 within the comments and says `Last Change: 05-Jul-2016.13`  I assume the `.13` part is a typo... but if the file was last changed on 7/5/16, then why is the version number the same as mine from 3.22.13?  I'm not even sure mine is from 2013, since my file modification date is 3/23/15, which is closer to when I downloaded from here.  The change-log is also stuck on 3/22/13 in both files.  I don't know what I have, or if I should update.... very confusing.

**Comment by benedmunds** [comment]
There's no version numbers in the code.  Stopped doing those when I stopped using CI Spark.

**Comment by sparky672** [comment]
> There's no version numbers in the code.

But you still have a version number in the comment section.  

How do I know what I have installed?  Was it last updated on 3/22/13 or do I go by the file modification date of 3/23/15?

**Comment by benedmunds** [comment]
I'd recommend using the file mod dates

**Comment by sparky672** [comment]
> I'd recommend using the file mod dates

Thanks.

Then I respectfully suggest that the version number be removed from the comments.  I see [something called version 2.6.0 from 7/30/14](https://github.com/benedmunds/CodeIgniter-Ion-Auth/releases/tag/2.6.0) and it too shows `Version 2.5.2` in the comments.

**Comment by benedmunds** [comment]
Where do you see that?

**Comment by sparky672** [comment]
>  Where do you see that?

[`Ion_auth_model.php`, line 5](https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/models/Ion_auth_model.php#L5):

```
* Version: 2.5.2
```

---

Also see [line 17](https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/models/Ion_auth_model.php#L17):

```
* Last Change: 05-Jul-2016.13
```

I assume the `.13` at the end is a typo you'd want to know about.

**Comment by benedmunds** [comment]
This has been removed.  Thanks!
