### ISSUE TITLE
An uncaught Exception was encountered  Type: RuntimeException  Message: Unable to locate the model you have specified: CI_auth

### ISSUE THREAD

**Issue by desire1982** [benedmunds/CodeIgniter-Ion-Auth#971]
An uncaught Exception was encountered

Type: RuntimeException

Message: Unable to locate the model you have specified: CI_auth

Filename: C:\wamp\www\CodeIgniter\ci_reg\system\core\Loader.php

Line Number: 344

Backtrace:

File: C:\wamp\www\CodeIgniter\ci_reg\application\controllers\Welcome.php
Line: 8
Function: model

File: C:\wamp\www\CodeIgniter\ci_reg\index.php
Line: 315
Function: require_once

I am a beginner in codeigniter. My website shows me this error. I want help for my problem and see which file work. it is also a help to solve this problem in codeigniter, please show me this link.

**Comment by benedmunds** [comment]
Looks like you're trying to load CI_auth when you should be loading ion_auth.  Please post general CI questions in the CI Forums since this GH issues list is for bug reports in Ion Auth.
