### ISSUE TITLE
Is there any option for permissions managment ?

### ISSUE THREAD

**Issue by khalid-mahmood** [benedmunds/CodeIgniter-Ion-Auth#973]
is there any options for user level permissions control ?

**Comment by Tjoosten** [comment]
i think that Ion-auth does not support that. Maybe you can check it in the documentation

**Comment by ehabafia** [comment]
I do have a modified version that does this.  I need some time to prepare
it.

**Comment by benedmunds** [comment]
It does not have a built in acl
