### ISSUE TITLE
BCrypt

### ISSUE THREAD

**Issue by aldrinmagno** [benedmunds/CodeIgniter-Ion-Auth#975]
Hello,

I have an issue regarding the hashing algorithm that is being use, is it really BCrypt? 

When I dive into the codes of the system I saw that ion_auth uses PHP's crypt built in function to hash passwords. However, according to the PHP Manual 

> crypt() will return a hashed string using the standard Unix DES-based algorithm or alternative algorithms that may be available on the system.

Maybe I'm missing something here. Can anybody explain what hashing algorithm is being  used?

Fantastic software by the way. Keep up the great work.

Thanks,

**Comment by dmonizer** [comment]
http://php.net/crypt:

On systems where the crypt() function supports multiple hash types, the following constants are set to 0 or 1 depending on whether the given type is available:

CRYPT_BLOWFISH - Blowfish hashing with a salt as follows: "$2a$", "$2x$" or "$2y$", a two digit cost parameter, "$", and 22 characters from the alphabet "./0-9A-Za-z". 


Bcrypt.php:

 public function __construct($params=array('rounds'=>7, 'salt_prefix'=>'$2y$')) {
    if(CRYPT_BLOWFISH != 1) {
      throw new Exception("bcrypt not supported in this installation. See http://php.net/crypt");
    }
