### ISSUE TITLE
Multiple users tables

### ISSUE THREAD

**Issue by er-karim** [benedmunds/CodeIgniter-Ion-Auth#981]
Hi Ben, I have just started a new project on CodeIgniter and I really want to use your **Auth System**.

The problem is that I don't want to use **users** table and i'm not using one table only i'm using 3 tables so i don't how to add them to the configuration file so that I can use them as users table.

Is it possible ?

**Comment by benedmunds** [comment]
No thats not possible with the current setup.  You could either update Ion Auth to support that or write a database view to map the data.

**Comment by er-karim** [comment]
Anyway thanks for your reply 👍
