### ISSUE TITLE
Login issue password problem

### ISSUE THREAD

**Issue by er-karim** [benedmunds/CodeIgniter-Ion-Auth#982]
Hi Ben,

I have already installed Ion Auth and now i can access to login page and when i fill up the form with
- Email: admin@admin.com
- Password: password

I stay in the same page after looking at Ion_auth_model for the error from where it comes I found this
- $db_password                             = $2a$07$SeBknntpZror9uy06097f32d6c3c06583
- $hash_password_db->password = $2a$07$SeBknntpZror9uyftVopmu61qg0ms8Qv1yV6FG.kQOSM.9QhmTo36

So ($db_password == $hash_password_db->password) is FALSE and that's why I can't be logged in

**Comment by benedmunds** [comment]
The model code should be using 

```
$this->bcrypt->verify($password,$hash_password_db->password
```

https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/models/Ion_auth_model.php#L320

Ensure you are using bcrypt in your config for hashing method.

**Comment by er-karim** [comment]
Thank you a lot Ben for your help 👍
