### ISSUE TITLE
How to Change Password in Ion Auth ?

### ISSUE THREAD

**Issue by bilal-ahmed-dev** [benedmunds/CodeIgniter-Ion-Auth#984]
Hello,

I am using yours ion auth library and its wonderful.

I know i can change the password in admin side in users list.

In my scenario i have another controller which is for doctors only. 

And in doctors dashboard i want to provide change password option.

The issue is i am having issue that how i can change the password means which encryption you used and how you decrypt the password.

I want to just save the password in encrypted form not want to decrypt also, just want to save in database users table.

Kindly help me out in this issue.

Glad to hear from you soon. Thanks

Regards

**Comment by benedmunds** [comment]
You can copy the controller method and views used for changing passwords to make a new user accessible endpoint for the user to change their own password.  For setting the password, use Ion Auth.

**Comment by faizan481** [comment]
how to change default admin password from this repo?

### Default Login
Username: admin@admin.com
Password: password

**Comment by benedmunds** [comment]
You can call update() with a new password to change the password.
