### ISSUE TITLE
$identity checking for empty failed

### ISSUE THREAD

**Issue by zhuzhaodan** [benedmunds/CodeIgniter-Ion-Auth#985]
`
    public function identity_check($identity = '')
    {
        $this->trigger_events('identity_check');

```
    if (empty($identity))
    {
        return FALSE;
    }

    return $this->db->where($this->identity_column, $identity)
                    ->count_all_results($this->tables['users']) > 0;
}`
```

if $identity is empty, then return false then goes here

`if ($this->identity_check($identity))
        {
            $this->set_error('account_creation_duplicate_identity');
            return FALSE;
        }`

Then skiped the check for empty $identity, which results in $identity is empty in the database

**Comment by benedmunds** [comment]
Is Identity an empty string or maybe a null?

**Comment by zhuzhaodan** [comment]
Im using CI3, returns NULL

**Comment by benedmunds** [comment]
So should just typecast the identity to ensure it's a string

$identity = (string) $identity;

**Comment by zhuzhaodan** [comment]
`if (empty($identity))
    {
        return FALSE;
    }`

Return should be true to trigger the error

**Comment by zhuzhaodan** [comment]
It should be checked when using the form_validation in the controller, but in case someone missed that step, this last resort doesn't save them from an empty identity in database

**Comment by benedmunds** [comment]
The identity check isn't really meant to stop you from saving an empty identity, just to see if its a duplicate.  You really should handle that in your controller logic.

**Comment by zhuzhaodan** [comment]
Yes you are right, however ,the empty check just does nothing and should be removed I suppose

**Comment by benedmunds** [comment]
Slight performance boost.  No need to hit the DB if its empty.
