### ISSUE TITLE
Reset authorized user after change password?

### ISSUE THREAD

**Issue by epexa** [benedmunds/CodeIgniter-Ion-Auth#986]
How to reset all authorized users one login, after a password change.

Example.
The authorized account two users with a single login and password.
Account owner change password, as authentication reset another user?

**Comment by benedmunds** [comment]
Why would one user have two user records?

**Comment by epexa** [comment]
@benedmunds sorry for my bad english!
I mean, we have authorization under a single login, example admin@admin.com.
Next, you change password.
How to do I automatically logout after the you changed the password.

**In real life it is necessary in two situations. If two people are one administrator account. Or if someone has authorized under my account without my permission. I login to my account, change passwords, and it is necessary that all the other who is authorized under my username, need deauthorize. Maybe check every time current password with the session?**

**Comment by benedmunds** [comment]
That's not built into Ion Auth directly.  You would need to use DB stored sessions and then invalidate their session record.
