### ISSUE TITLE
Current working version

### ISSUE THREAD

**Issue by Indigo744** [benedmunds/CodeIgniter-Ion-Auth#987]
Hello,

I am using IonAuth for quite some time now: version 2.6.0 (from July 2014) with CI 2.
I plan to upgrade to CI 3 in the future.

From the official release 2.6.0 in July 2014, there seems to be quite some commit activites on the "2" branch. But you never made any new "official" version with a tag, nor explained what was the evolution. Why is that? Is there any breaking change?
And so, which version is considered to be fit for production?

Thanks a lot for your reply.

**Comment by benedmunds** [comment]
The "2" branch is the current working version and should work with CI 3, at least I'm not aware of any issues.

The 2 is simply to denote the version of Ion Auth and doesn't relate to the CI version.

**Comment by Indigo744** [comment]
Thanks for your reply.

I know that the "2" corresponds to version 2. However, my question was mainly regarding:
- why is there no "officiel" version, i.e. tagged one (2.6.0 was in 2014)?
- between the latest commit of "2" branch, and 2.6.0 tag, is there any breaking change? There is sadly no changelog...

Thanks a lot.

**Comment by benedmunds** [comment]
Ah, do to time constraints I dropped support of Spark, which in turn meant the version numbers have been dropped.   The HEAD of the 2 branch is basically always the current version and the git log contains the changes.  Also with something security related I feel like you should always use the most up to date version available.  I do strive to never introduce BC breaks into a major version.

**Comment by Indigo744** [comment]
Ok, I understand :)
I will upgrade ASAP then! 

Thanks a lot for your answers.

**Comment by benedmunds** [comment]
No problem!
