### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by Indigo744** [benedmunds/CodeIgniter-Ion-Auth#989]
Dear @benedmunds,

Do you think it would be possible to include a composer.json in order for this repo to be compatible with Composer?

Thanks.

**Comment by benedmunds** [comment]
Dont think that would be a good fit since it only works with CodeIgniter.

**Comment by Indigo744** [comment]
Mmmh, this is true.
However, it could be useful to keep the library up to date along with others.

**Comment by Indigo744** [comment]
I'm closing this point. I will use IonAuth in third_party folder and update it manually :)

**Comment by benedmunds** [comment]
Thanks!  Appreciate the feedback as well!

**Comment by Indigo744** [comment]
For information, I will use the former "sparks" approach in the third_party folder:

```
 -- application
    -- third_party
        -- ionauth
            -- [commit_id]
```

And using in autoload:
`$autoload['packages'] = array(APPPATH . 'third_party/ion_auth/0f9029f8e3ff877ad5882ef2e678d41b12524408');`

That way, I can track the current version installed.
