### ISSUE TITLE
Is it possible to active activation email without CSRF checks?

### ISSUE THREAD

**Issue by skydotint** [benedmunds/CodeIgniter-Ion-Auth#992]
Is it possible to active activation email without CSRF checks?

**Comment by benedmunds** [comment]
Why would you want to do that?

**Comment by skydotint** [comment]
I have a large project and I didn't concern about the CSRF checks when I started. So, I have used <form> tag directly instead of form_open(). And It seems now that we need form_open() function to use CSRF properly with the system. [May be I am wrong.]

**Comment by benedmunds** [comment]
You really should just update your code to use CSRF protection.  If you want to go without it though there's nothing in Ion Auth forcing you to use it, just modify the controller and view code as you require.

**Comment by gorankrgovic** [comment]
@skydotint as Ben said, you should use the form with CSRF protection, however if you do not want to use form helper you can add the token field in your view like this:

`<input type="hidden" name="<?php echo $this->security->get_csrf_token_name(); ?>" value="<?php echo $this->security->get_csrf_hash(); ?>">`

**Comment by lloricode** [comment]
this is what say @benedmunds to me,
#1034 

as i observe, its ok not to use CSRF in ion_auth, so you can use a CSRF of CI bult in, to every using form_open automatically generate a CSRF.
