### ISSUE TITLE
Send Email Activation

### ISSUE THREAD

**Issue by whatnowangga** [benedmunds/CodeIgniter-Ion-Auth#993]
Hello,
im really confuse for this case, i have lot searching in everywhere.
this is my setup email_config
$config['use_ci_email'] = true; // Send Email using the builtin CI email class, if false it will return the code and the identity
$config['email_config'] = array( 
    'protocol' => 'smtp', 
    'smtp_host' => 'ssl://blablabla', 
    'smtp_port' => 465, 
    'smtp_timeout'=>'30', 
    'smtp_user' => 'MyUserName', 
    'smtp_pass' => 'MyPassword', 
    'mailtype' => 'html', 
    'charset' => 'iso-8859-1', 
    'newline' => '\r\n'
    );
that cannot send email.
but
if i change that line to be a 
$config['email_config'] = 'file'
its work but this is a show of email 
[![ss.png](https://s12.postimg.org/udw4ttgv1/image.png)](https://postimg.org/image/a6ip1ijdl/)

**Comment by benedmunds** [comment]
Is there a difference in your email config file vs what is here?

**Comment by whatnowangga** [comment]
yes , if i change to $config['email_config'] = 'file' .
the email not sending html format

**Comment by benedmunds** [comment]
whats in your email config file?  config/email.php

**Comment by whatnowangga** [comment]
i didnt see any email.php in my application/config/ folder :/ @benedmunds

**Comment by benedmunds** [comment]
Ok that makes sense.  It seems that your email config is just wrong.  Are you sure the smtp info is correct?

**Comment by whatnowangga** [comment]
sure, i use this smtp in controller for test. it work @benedmunds

**Comment by benedmunds** [comment]
Try using the codeigniter email.php config file instead https://www.codeigniter.com/user_guide/libraries/email.html#setting-email-preferences-in-a-config-file  and see what you get

**Comment by whatnowangga** [comment]
<?php defined('BASEPATH') OR exit('No direct script access allowed.');
$config['useragent']        = 'CodeIgniter';  
$config['protocol']         = 'smtp'; 
$config['mailpath']         = '/usr/sbin/sendmail';
$config['smtp_host']        = 'ssl://asdfasdfasdfasdf';
$config['smtp_user']        = 'balblalba';
$config['smtp_pass']        = 'XXXXX';
$config['smtp_port']        = 25;
$config['smtp_timeout']     = 30;  
$config['smtp_debug']       = 0;  
$config['smtp_auto_tls']    = true;  
$config['smtp_conn_options'] = array();  
$config['wordwrap']         = true;
$config['wrapchars']        = 76;
$config['mailtype']         = 'html';  
$config['charset']          = null;
$config['validate']         = true;
$config['priority']         = 3;  
$config['crlf']             = "\r\n";  
$config['newline']          = "\r\n"; 
$config['bcc_batch_mode']   = false;
$config['bcc_batch_size']   = 200;

i write like that @benedmunds  cmiw
and what i should be write in ion_auth in config folder ??

**Comment by benedmunds** [comment]
@anggaand123 I wouldnt recommend posting your username and password on a public issue forum.  Maybe edit and just remove the password

**Comment by whatnowangga** [comment]
yes my false, i already edited @benedmunds

**Comment by benedmunds** [comment]
Are you sure that smtp_host is correct?  usually its an https:// address.

**Comment by whatnowangga** [comment]
if i use https:// address this is a massage
Message: fsockopen(): unable to connect to https://myhost:465 (Unable to find the socket transport "https"- blablablabla

**Comment by benedmunds** [comment]
What error are you getting with the ssl?

**Comment by whatnowangga** [comment]
"Unable to Send Activation Email"

**Comment by benedmunds** [comment]
What does print_debugger() return if you add it?

https://www.codeigniter.com/user_guide/libraries/email.html#CI_Email::print_debugger

**Comment by whatnowangga** [comment]
where i must add print_debugger ??
what i must to do with email.php in config folder.
and what i must write in ion_auth in config folder

**Comment by benedmunds** [comment]
In the Ion Auth library file here https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/libraries/Ion_auth.php#L379

**Comment by whatnowangga** [comment]
$this->ion_auth_model->trigger_events(array('post_account_creation', 'post_account_creation_unsuccessful', 'activation_email_unsuccessful'));
            $this->set_error('activation_email_unsuccessful');
            $this->email->print_debugger(array('headers'));
            return FALSE;

i adding print_debugger like that.
i still get Unable to Send Activation Email error

@benedmunds

**Comment by benedmunds** [comment]
Try replacing the register method with this https://gist.github.com/benedmunds/720fad25503227ec0993e7282410ba55

This adds several debug messages.  Let me know what you get from this.

**Comment by whatnowangga** [comment]
sometime i got this massge
220-srv15.niagahoster.com ESMTP Exim 4.87 #1 Tue, 25 Oct 2016 00:59:39 +0700 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail. 

is mean, my hosting problem ??

**Comment by benedmunds** [comment]
Yes looks like a problem with your SMTP provider.

**Comment by benedmunds** [comment]
I recommend SendGrid if you are looking for a new one.  Otherwise maybe contact your current provider to see what the issue is.
