### ISSUE TITLE
Error auto logout of Ione-Auth

### ISSUE THREAD

**Issue by bomden11** [benedmunds/CodeIgniter-Ion-Auth#997]
I cant set time for auto logout. In 1 day, i must login 2 3 times. How can i set time for it ? Make my login live long time

I edit 

$config['sess_expiration']      = 720000;

But it not effect. Please help me ! Thank

**Comment by benedmunds** [comment]
Try setting the $config['user_expire'] to 0 in the ion_auth config.

**Comment by bomden11** [comment]
$config['user_expire']                = 604800;               // How long to remember the user (seconds). Set to zero for no expiration

604800 ~ 7 days. It not effect. I dont want it never exp.

**Comment by benedmunds** [comment]
Try it at zero and see if it solves your problem first please.  

Also this may help http://stackoverflow.com/questions/6856960/codeigniter-session-expires-frequently
