### ISSUE TITLE
Edit and activate/deactivate issue

### ISSUE THREAD

**Issue by satrianivzla** [benedmunds/CodeIgniter-Ion-Auth#998]
Hi there

I have been downloaded code from here and testing it since a few days ago. 
Using it with CI 3.1.2 and Bootstrap 3.3.7
Then until today I only created 1 user as simple member beside default admin - member. Until that everything works fine:  Bootstrap integration, log in, log out, show data, I can see pages and content as admin, as a normal member and as visitor ...  normal behavior.

Playing now with the **admin** role. Logged as Admin, check user list, found 2 users and if I choose and try to edit the simple user member that I created and make it admin, it works but also changed all personal data less email from the original Admin user created by default. Then my 2 users have the same data less email info. 

And now other issue. Logged as **Admin**. if I try to active or deactivate another user, form took the admin id and data and even the question asked is if I want to deactivate Administrator account when I am trying as I said to  deactivate to another user ...  I check form action and hidden input and both are using $user->id; and I guess that this is not the correct variable. Data is mixed here.

**Comment by benedmunds** [comment]
Hey I'm not following this. Can you post screenshots or screencasts walking through the issues please.

**Comment by satrianivzla** [comment]
Hi thank u 4 quick answer.

Issue # 1:
I have 2 users: 1 admin and member as John Doe with admin@admin.com and 1 member only as  Jane Doe with jane@admin.com.
Logged as admin and try to change (using edit option) to Jane as admin, made change and save it and now I have both accounts with same data less email. Both names now are Jane, both last name now are Doe and one have as email admin@admin.com and the other have now jane@admin.com.

Issue # 2
Again logged as admin and try to deactivate to Jane's account. I have the form asking me if I want to deactivate to 'administrator' when it must ask if I want to  deactivate to 'Jane'. I saw that  form action and hidden input and both are using $user->id; it means that If I want to deactivate  to 'Jane' it must be $user->2 and I have $user->1.

**Comment by satrianivzla** [comment]
Hi Thank U 4 UR quick answer!
Here is what I am trying to explain before with screenshots as you asked.
**Issue # 1:**
I have 2 users: 1 admin as **John Doe** with **admin[@]admin.com** and 1 member only as **Jane Doe** with **jane[@]admin.com**. Of course that  I must be logged as admin to see panel like this 

![logged](https://cloud.githubusercontent.com/assets/7875387/20459774/70b17406-aea4-11e6-8e84-6002ba60a73b.jpg)

Then as I am logged as admin - not as Jane of course, go and try to change (using **edit** option) to **Jane** as **admin**, made change and save it and now when I check I have both accounts with same data less email. 

![logged2](https://cloud.githubusercontent.com/assets/7875387/20459772/70a4ddf4-aea4-11e6-89bb-ec28ae52d7d6.jpg)

 Both user's names now are **Jane**, both last name now are **Doe** and one account have as email **admin[@]admin.com** and the other have now **jane[@]admin.com**.

![logged3](https://cloud.githubusercontent.com/assets/7875387/20459773/70aa42f8-aea4-11e6-925f-8d8dcd866bf8.jpg)

This behavior is not normal I should be able to update data from any other user meanwhile I am logged as **Admin**.

Database before

![data1](https://cloud.githubusercontent.com/assets/7875387/20459809/cb8d3f58-aea5-11e6-99f1-7fed1c2fddd8.jpg)

Database after 

![data2](https://cloud.githubusercontent.com/assets/7875387/20459810/cb8efc6c-aea5-11e6-8e06-045540fed2ea.jpg)

**Comment by satrianivzla** [comment]
issue #2 
Again logged as admin and try to deactivate to Jane's account.

![desactivar](https://cloud.githubusercontent.com/assets/7875387/20459801/31061b44-aea5-11e6-8c9b-d285cb2a92c0.jpg)

 I have the form asking me if I want to deactivate to '**administrator**' when it must ask if I want to deactivate to '**Jane**'. I saw that form action and hidden input and both are using **$user->id;** it means that If I want to deactivate to 'Jane' it must be **$user->2** and the form took wrongly **$user->1** and also  takes wrongly username value $user->username as '**administrator**'  when should took value as '**Jane**'. 

![desactiva2](https://cloud.githubusercontent.com/assets/7875387/20459802/310ba3a2-aea5-11e6-9434-c314408c2056.jpg)

Again this behavior is not normal looks like took values from Adim session user logged and is not reading data from the index page when I choose the user that I want to  deactivate.

**Comment by benedmunds** [comment]
Ensure that you are passing the user's ID to ion_auth->update().  If you don't pass an ID it will default to the currently logged in user.

**Comment by satrianivzla** [comment]
Hi, thank you again.
I was able to detect that I was using the same variable twice and it was overwriting it, and it was the cause of this behavior.
